import { difference } from "./difference.js";
const actual0 = difference(20, 7);
if (actual0 !== 13) throw new Error("case 0");
console.log("ELMOS_OBSERVATION\tjson\t" + JSON.stringify({case_id: 0, value: actual0}));
const actual1 = difference(3, 8);
if (actual1 !== 0) throw new Error("case 1");
console.log("ELMOS_OBSERVATION\tjson\t" + JSON.stringify({case_id: 1, value: actual1}));
const actual2 = difference(4, 4);
if (actual2 !== 0) throw new Error("case 2");
console.log("ELMOS_OBSERVATION\tjson\t" + JSON.stringify({case_id: 2, value: actual2}));
