package io.elmos.evidence;

public enum EvidenceType {
    REPOSITORY_SNAPSHOT, TECHNOLOGY_FINGERPRINT, BASELINE_BUILD, BASELINE_TEST,
    DEPENDENCY_ANALYSIS, VULNERABILITY_SCAN, RECIPE_EXECUTION, AGENT_CHANGE,
    BUILD_RESULT, TEST_RESULT, API_COMPATIBILITY, DATABASE_COMPATIBILITY,
    SONAR_QUALITY_GATE, PERFORMANCE_RESULT, HUMAN_APPROVAL, PULL_REQUEST, ROLLBACK_PLAN
}

