// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    proposal: { type: Object, value: {} },
    disabled: { type: Boolean, value: false },
  },
  data: {},
  methods: {
    handleClickButton0(event) {
      this.triggerEvent("approve");
    },
    handleClickButton1(event) {
      this.triggerEvent("reject");
    },
    handleClickButton2(event) {
      this.triggerEvent("prepareScm");
    },
  },
});
