package io.elmos.lowering;

import io.elmos.uir.UirModels;

import java.nio.file.*;
import java.time.Clock;
import java.util.*;

import static io.elmos.lowering.LoweringModels.*;

/** Faithful-first orchestration. Compiler/AST backends are injected capabilities and missing backends fail closed. */
public final class MethodBodyLoweringService {
    private final TargetCapabilityMatrix capabilities;private final LoweringRuleRegistry rules;private final Map<String,TargetEmitter> emitters;private final Map<String,StaticValidator> validators;private final Clock clock;
    public MethodBodyLoweringService(TargetCapabilityMatrix capabilities,LoweringRuleRegistry rules,Map<String,TargetEmitter> emitters,Map<String,StaticValidator> validators,Clock clock){this.capabilities=Objects.requireNonNull(capabilities);this.rules=Objects.requireNonNull(rules);this.emitters=Map.copyOf(emitters);this.validators=Map.copyOf(validators);this.clock=Objects.requireNonNull(clock);}
    public RunResult lower(Request request){
        Path workspace=secure(request.workspace()),repository=workspace.resolve("target-repository");String language=request.skeleton().plan().profile().language(),version=request.skeleton().plan().profile().resolvedRuntimeVersion();
        List<CallablePlan> plans=new LoweringPlanner(capabilities,rules).plan(request);String configurationHash=LoweringIds.hash(List.of(request.profile(),request.budgets(),request.skeleton().plan().generationId(),rules.all()));String runId=LoweringIds.id("loweringrun",request.uir().manifest().uirRunId(),request.skeleton().manifest().targetRepositoryId(),configurationHash);
        Map<String,UirModels.Declaration> declarations=index(request.uir(),UirModels.Declaration.class,UirModels.Declaration::declarationId);Map<String,UirModels.Operation> operationIndex=index(request.uir(),UirModels.Operation.class,UirModels.Operation::operationId);
        TargetEmitter emitter=emitters.get(language);StaticValidator validator=validators.get(language);List<CallableResult> results=new ArrayList<>();int agentCount=0;
        for(CallablePlan plan:plans){
            List<UirModels.Operation> operations=plan.operationIds().stream().map(operationIndex::get).filter(Objects::nonNull).toList();
            if(!plan.escalationReasons().isEmpty()||emitter==null||validator==null){boolean agent=request.profile().allowAgentFallback()&&agentCount<request.budgets().maxAgentCalls();AgentPacket packet=agent?packet(plan,operations,request):null;if(agent)agentCount++;results.add(new CallableResult(plan.targetDeclarationId(),plan.moduleId(),agent?"agent-required":"manual-required",null,null,null,null,null,packet,backendDiagnostics(plan,emitter,validator)));continue;}
            try{
                Emission faithful=validateEmission(emitter.emit(new EmissionRequest(plan,declarations.get(plan.sourceDeclarationId()),operations,"faithful")),plan,"faithful",request.budgets());StaticValidation faithfulValidation=validator.validate(new ValidationRequest(plan,faithful,repository));
                if(!faithfulValidation.passed()){results.add(new CallableResult(plan.targetDeclarationId(),plan.moduleId(),"blocked",LoweringIds.hashText(faithful.body()),null,null,faithfulValidation,null,null,faithfulValidation.diagnostics()));continue;}
                Emission selected=faithful;StaticValidation idiomaticValidation=null;String idiomaticHash=null;
                if(request.profile().idiomaticLevel()>0&&!request.profile().fidelityMode().equals("strict")){Emission idiomatic=validateEmission(emitter.emit(new EmissionRequest(plan,declarations.get(plan.sourceDeclarationId()),operations,"idiomatic")),plan,"idiomatic",request.budgets());idiomaticValidation=validator.validate(new ValidationRequest(plan,idiomatic,repository));if(idiomaticValidation.passed()){selected=idiomatic;idiomaticHash=LoweringIds.hashText(idiomatic.body());}}
                Patch patch=new GeneratedRegionPatchManager().apply(repository,plan,selected,request.skeleton());results.add(new CallableResult(plan.targetDeclarationId(),plan.moduleId(),idiomaticHash==null?"verified-faithful":"verified",LoweringIds.hashText(faithful.body()),idiomaticHash,patch,faithfulValidation,idiomaticValidation,null,List.of()));
            }catch(RuntimeException error){results.add(new CallableResult(plan.targetDeclarationId(),plan.moduleId(),"blocked",null,null,null,null,null,null,List.of(error.getMessage()==null?error.getClass().getSimpleName():error.getMessage())));}
        }
        Coverage coverage=coverage(plans,results);Fidelity fidelity=fidelity(plans,results);ConformanceReport conformance=conformance(runId,plans,results,coverage,fidelity);List<Capability> targetCapabilities=capabilities.forTarget(language,version);RunManifest manifest=new RunManifest(runId,request.uir().manifest().uirRunId(),request.skeleton().manifest().targetRepositoryId(),request.skeleton().plan().profile().targetProfileId(),language,configurationHash,plans.stream().map(CallablePlan::callablePlanId).toList(),rules.all().stream().filter(rule->rule.targetLanguage().equals(language)).map(Rule::ruleId).toList(),targetCapabilities.stream().map(Capability::capabilityId).toList(),clock.instant());RunResult result=new RunResult(manifest,plans,results,conformance);new LoweringArtifactWriter().write(workspace,result,targetCapabilities,rules.all());return result;
    }
    private static Emission validateEmission(Emission emission,CallablePlan plan,String phase,Budgets budgets){if(emission==null||!emission.phase().equals(phase))throw new IllegalStateException("EMITTER_PHASE_MISMATCH");if(emission.body()==null||emission.body().isBlank()||emission.body().contains("MIGRATION_BODY_PENDING")||emission.body().contains("return null"))throw new IllegalStateException("EMITTER_INCOMPLETE_BODY");if(!new HashSet<>(emission.sourceOperationIds()).containsAll(plan.operationIds()))throw new IllegalStateException("EMITTER_SOURCE_MAP_GAP");long lines=emission.body().lines().count();if(lines>budgets.maxGeneratedLocPerPatch())throw new IllegalStateException("PATCH_LOC_BUDGET_EXCEEDED");return emission;}
    private static AgentPacket packet(CallablePlan plan,List<UirModels.Operation>operations,Request request){List<String>effects=operations.stream().flatMap(value->value.effectIds().stream()).distinct().sorted().toList();return new AgentPacket(LoweringIds.id("agent-task",plan.callablePlanId()),plan.targetDeclarationId(),plan.targetLanguage(),"faithful-port",plan.operationIds(),plan.typeMappings().stream().map(TypeMapping::sourceTypeId).toList(),effects,plan.openObligations(),List.of("public-signature-locked","evaluation-order-locked","effect-contract-locked","approved-dependencies-only","patch-only"),validationCommands(request.skeleton().plan().profile().language()),"structured-ast-patch",String.join(",",plan.escalationReasons()));}
    private static List<String> validationCommands(String language){return switch(language){case"java"->List.of("mvn test");case"python"->List.of("python -m compileall src","pyright");case"csharp"->List.of("dotnet build --no-restore");default->List.of("tsc --noEmit");};}
    private static List<String> backendDiagnostics(CallablePlan plan,TargetEmitter emitter,StaticValidator validator){List<String>values=new ArrayList<>(plan.escalationReasons());if(emitter==null)values.add("TARGET_AST_EMITTER_UNAVAILABLE:"+plan.targetLanguage());if(validator==null)values.add("TARGET_STATIC_VALIDATOR_UNAVAILABLE:"+plan.targetLanguage());return List.copyOf(values);}
    private static Coverage coverage(List<CallablePlan>plans,List<CallableResult>results){long total=plans.size(),generated=results.stream().filter(value->value.patch()!=null).count(),agent=results.stream().filter(value->value.agentPacket()!=null).count(),manual=results.stream().filter(value->value.status().equals("manual-required")).count(),opaque=plans.stream().filter(value->value.escalationReasons().stream().anyMatch(reason->reason.startsWith("opaque-operation"))).count(),validated=results.stream().filter(value->value.faithfulValidation()!=null&&value.faithfulValidation().passed()).count(),mapped=plans.stream().mapToLong(value->value.operations().size()).sum(),operations=plans.stream().mapToLong(value->value.operationIds().size()).sum();return new Coverage(rate(generated,total),rate(generated,total),rate(agent,total),rate(manual,total),rate(opaque,total),rate(validated,total),rate(mapped,operations),(int)Math.max(0,total-generated),0);}
    private static Fidelity fidelity(List<CallablePlan>plans,List<CallableResult>results){double verified=rate(results.stream().filter(value->value.patch()!=null).count(),plans.size()),typed=rate(plans.stream().filter(value->value.typeMappings().stream().allMatch(mapping->mapping.lossiness().equals("none"))).count(),plans.size());return new Fidelity(typed,verified,verified,verified,verified,verified,verified);}
    private static ConformanceReport conformance(String runId,List<CallablePlan>plans,List<CallableResult>results,Coverage coverage,Fidelity fidelity){List<String>open=plans.stream().flatMap(value->value.openObligations().stream()).distinct().sorted().toList(),blocking=new ArrayList<>();results.stream().filter(value->value.status().equals("blocked")||value.status().equals("manual-required")).forEach(value->blocking.addAll(value.diagnostics()));List<ModuleGate>gates=new ArrayList<>();for(String module:plans.stream().map(CallablePlan::moduleId).distinct().sorted().toList()){List<CallableResult>moduleResults=results.stream().filter(value->value.moduleId().equals(module)).toList();long total=moduleResults.size(),generated=moduleResults.stream().filter(value->value.patch()!=null).count(),verified=moduleResults.stream().filter(value->value.faithfulValidation()!=null&&value.faithfulValidation().passed()).count();double generation=rate(generated,total),validation=rate(verified,total);boolean hasBlock=moduleResults.stream().anyMatch(value->value.status().equals("blocked")||value.status().equals("manual-required"));String gate=generation>=.97&&validation>=.96&&!hasBlock?"L-D":generation>=.90&&validation>=.90&&!hasBlock?"L-C":generation>=.85&&validation>=.85?"L-B":generation>0?"L-A":"blocked";boolean next=Set.of("L-C","L-D").contains(gate);gates.add(new ModuleGate(module,gate,next,next,false,hasBlock?List.of("unresolved-or-unverified-callables"):List.of("behavioral-equivalence-not-yet-proven")));}
        boolean eligible=!gates.isEmpty()&&gates.stream().allMatch(ModuleGate::eligibleForDependencyMapping)&&blocking.isEmpty()&&open.isEmpty();return new ConformanceReport(5,eligible?"passed":"blocked",runId,gates,coverage,fidelity,List.copyOf(blocking),open,eligible);}
    private static Path secure(Path requested){try{Path path=requested.toAbsolutePath().normalize();if(Files.exists(path,LinkOption.NOFOLLOW_LINKS)&&Files.isSymbolicLink(path))throw new SecurityException("LOWERING_WORKSPACE_SYMLINK");Files.createDirectories(path);Path real=path.toRealPath(LinkOption.NOFOLLOW_LINKS);Path repo=real.resolve("target-repository");if(!Files.isDirectory(repo,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(repo))throw new IllegalStateException("TARGET_REPOSITORY_UNAVAILABLE");return real;}catch(java.io.IOException error){throw new IllegalArgumentException("LOWERING_WORKSPACE_UNAVAILABLE",error);}}
    private static double rate(long numerator,long denominator){return denominator==0?1:Math.min(1,Math.round(numerator*100000d/denominator)/100000d);}
    private static <T>List<T>payloads(UirModels.Dataset dataset,Class<T>type){return dataset.entities().stream().map(UirModels.Entity::payload).filter(type::isInstance).map(type::cast).toList();}
    private static <T>Map<String,T>index(UirModels.Dataset dataset,Class<T>type,java.util.function.Function<T,String>id){Map<String,T>result=new HashMap<>();for(T value:payloads(dataset,type))result.put(id.apply(value),value);return result;}
}
