CREATE TABLE IF NOT EXISTS book (
  book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_name VARCHAR(255),
  author VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  translator VARCHAR(255),
  press VARCHAR(255),
  series_name VARCHAR(255),
  isbn VARCHAR(32),
  press_time VARCHAR(64),
  version VARCHAR(64),
  shelf_time VARCHAR(64),
  category VARCHAR(128),
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  vip_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  school_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  activity VARCHAR(255),
  sales INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app_user (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(64),
  admire_field VARCHAR(512),
  expert_at VARCHAR(512),
  tag VARCHAR(512),
  know_from VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS rating (
  rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  rating DECIMAL(3,2) NOT NULL CHECK (rating >= 1 AND rating <= 5),
  rated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_rating_user FOREIGN KEY (user_id) REFERENCES app_user(user_id),
  CONSTRAINT fk_rating_book FOREIGN KEY (book_id) REFERENCES book(book_id),
  CONSTRAINT uq_rating_user_book UNIQUE (user_id, book_id)
);

CREATE INDEX IF NOT EXISTS idx_rating_user ON rating(user_id);
CREATE INDEX IF NOT EXISTS idx_rating_book ON rating(book_id);
