"""Exact, digest-bound registry for the 132 semantic-assurance Skills."""

from __future__ import annotations

import json
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from .canonical import digest_bytes, validate_identifier
from .contracts import CapabilityState, Operation

PACKAGE_ID = "elmos-semantic-assurance-expansion-skills-v1.0.0"
SOURCE_ARCHIVE_SHA256 = (
    "sha256:0e470c927bf2840214d0e11d04ff0dbf914385b55c68c36370a5209e61994f60"
)
SOURCE_MANIFEST_SHA256 = (
    "sha256:e0aae397b0a72afbcaef4e8e17474c4d67735327dbd67f9fd16c1897c7f56f40"
)
EXPECTED_SKILL_COUNT = 132
EXPECTED_EDGE_COUNT = 229
EXPECTED_INTERNAL_EDGE_COUNT = 227
EXPECTED_EXTERNAL_DEPENDENCIES = frozenset(
    {
        "elmos-multi-source-repository-discovery",
        "elmos-embedded-sql-routine-migrator",
    }
)
EXPECTED_BATCH_COUNTS = {
    "J": 16,
    "K": 14,
    "L": 16,
    "M": 18,
    "N": 16,
    "O": 14,
    "P": 12,
    "Q": 14,
    "R": 12,
}
COLLISION_ALIASES = {
    "elmos-proof-obligation-generator": (
        "elmos-semantic-assurance-proof-obligation-generator"
    ),
    "elmos-proof-cache-invalidation": (
        "elmos-semantic-assurance-proof-cache-invalidation"
    ),
}


class RegistryError(RuntimeError):
    pass


@dataclass(frozen=True, slots=True)
class SkillBinding:
    source_skill_id: str
    source_name: str
    installed_name: str
    batch: str
    layer: str
    risk: str
    description: str
    dependencies: tuple[str, ...]
    outputs: tuple[str, ...]
    handler_id: str
    operation: Operation
    capability_state: CapabilityState

    def to_dict(self) -> dict[str, Any]:
        return {
            "sourceSkillId": self.source_skill_id,
            "sourceName": self.source_name,
            "installedName": self.installed_name,
            "batch": self.batch,
            "layer": self.layer,
            "risk": self.risk,
            "description": self.description,
            "dependencies": list(self.dependencies),
            "outputs": list(self.outputs),
            "handlerId": self.handler_id,
            "operation": self.operation.value,
            "capabilityState": self.capability_state.value,
            # Runtime code is implemented locally; capabilityState records
            # whether the operation is bounded, adapter-backed, or external
            # evidence-gated.  Keep these dimensions distinct.
            "implementationState": "RUNTIME_CODE_COMPLETE",
            "externalEvidenceStatus": "NOT_RUN",
            "certificationStatus": "NOT_CERTIFIED",
        }


def _handler_id(name: str) -> str:
    return "execute_" + name.replace("-", "_")


class SkillRegistry:
    """Load and validate the repository-owned compiled contract.

    Runtime dispatch never reads source-package Markdown or executes package
    helpers.  The compiled contract is generated by the repository importer
    only after the pinned source manifest and dependency graph validate.
    """

    def __init__(self, contract_path: str | Path | None = None) -> None:
        if contract_path is None:
            repository_root = Path(__file__).resolve().parents[4]
            contract_path = (
                repository_root
                / "docs/semantic-assurance-expansion/compiled-contract.json"
            )
        path = Path(contract_path)
        if not path.is_file() or path.is_symlink():
            raise RegistryError(f"compiled contract is missing or unsafe: {path}")
        try:
            raw = path.read_bytes()
            document = json.loads(raw.decode("utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise RegistryError(f"compiled contract is unreadable: {exc}") from exc
        self.contract_digest = digest_bytes(raw)
        self._document = document
        self._bindings = self._validate(document)

    @property
    def count(self) -> int:
        return len(self._bindings)

    def get(self, source_name: str) -> SkillBinding:
        try:
            return self._bindings[source_name]
        except KeyError as exc:
            raise KeyError(f"unknown semantic-assurance Skill: {source_name}") from exc

    def list(self, batch: str | None = None) -> list[dict[str, Any]]:
        return [
            binding.to_dict()
            for binding in self._bindings.values()
            if batch is None or binding.batch == batch
        ]

    @property
    def package_blockers(self) -> tuple[dict[str, Any], ...]:
        blockers = self._document.get("packageBlockers", [])
        if not isinstance(blockers, list):
            raise RegistryError("compiled contract packageBlockers must be an array")
        return tuple(dict(item) for item in blockers if isinstance(item, dict))

    def _validate(self, document: Any) -> dict[str, SkillBinding]:
        if not isinstance(document, dict):
            raise RegistryError("compiled contract must be an object")
        if document.get("schemaVersion") != "elmos.semantic-assurance.compiled-contract/v1":
            raise RegistryError("compiled contract schema version mismatch")
        package = document.get("package")
        if not isinstance(package, dict):
            raise RegistryError("compiled contract package is missing")
        if package.get("id") != PACKAGE_ID:
            raise RegistryError("compiled contract package identity mismatch")
        if package.get("archiveSha256") != SOURCE_ARCHIVE_SHA256:
            raise RegistryError("compiled contract archive digest mismatch")
        if package.get("sourceManifestSha256") != SOURCE_MANIFEST_SHA256:
            raise RegistryError("compiled contract manifest digest mismatch")
        if package.get("sourceReadiness") != "not-run":
            raise RegistryError("compiled contract promoted source readiness")
        if package.get("externalEvidenceStatus") != "NOT_RUN":
            raise RegistryError("compiled contract promoted external evidence")
        if package.get("certificationStatus") != "NOT_CERTIFIED":
            raise RegistryError("compiled contract promoted certification")

        records = document.get("skills")
        if not isinstance(records, list) or len(records) != EXPECTED_SKILL_COUNT:
            raise RegistryError("compiled contract must contain exactly 132 Skills")
        bindings: dict[str, SkillBinding] = {}
        seen_ids: set[str] = set()
        seen_outputs: set[str] = set()
        batch_counts: dict[str, int] = defaultdict(int)
        for ordinal, record in enumerate(records, start=169):
            if not isinstance(record, dict):
                raise RegistryError("compiled contract Skill records must be objects")
            expected_id = f"ELMOS-POLY-{ordinal:03d}"
            if record.get("sourceSkillId") != expected_id or expected_id in seen_ids:
                raise RegistryError(f"compiled contract Skill ID drift at {expected_id}")
            source_id = expected_id
            source_name = validate_identifier(
                record.get("sourceName"), "compiledContract.sourceName"
            )
            if source_name in bindings:
                raise RegistryError(f"duplicate source Skill name: {source_name}")
            installed_name = validate_identifier(
                record.get("installedName"), "compiledContract.installedName"
            )
            expected_installed = COLLISION_ALIASES.get(source_name, source_name)
            if installed_name != expected_installed:
                raise RegistryError(f"installed alias drift for {source_name}")
            batch_value = record.get("batch")
            if not isinstance(batch_value, str):
                raise RegistryError(f"invalid batch for {source_name}")
            batch = batch_value
            if batch not in EXPECTED_BATCH_COUNTS:
                raise RegistryError(f"invalid batch for {source_name}")
            batch_counts[batch] += 1
            if record.get("risk") != "critical":
                raise RegistryError(f"risk was weakened for {source_name}")
            dependencies = record.get("dependencies")
            outputs = record.get("outputs")
            if not isinstance(dependencies, list) or any(
                not isinstance(item, str) for item in dependencies
            ):
                raise RegistryError(f"dependencies invalid for {source_name}")
            if len(set(dependencies)) != len(dependencies):
                raise RegistryError(f"duplicate dependencies for {source_name}")
            for dependency in dependencies:
                validate_identifier(
                    dependency, f"compiledContract.{source_name}.dependency"
                )
            if not isinstance(outputs, list) or len(outputs) != 3 or any(
                not isinstance(item, str) for item in outputs
            ):
                raise RegistryError(f"outputs invalid for {source_name}")
            expected_prefix = f"semantic-assurance/{source_name}/"
            for output in outputs:
                parsed_output = PurePosixPath(output)
                if (
                    not output.startswith(expected_prefix)
                    or parsed_output.is_absolute()
                    or ".." in parsed_output.parts
                    or "\\" in output
                    or output in seen_outputs
                ):
                    raise RegistryError(f"output scope drift for {source_name}")
                seen_outputs.add(output)
            handler_id = validate_identifier(
                record.get("handlerId"), "compiledContract.handlerId"
            )
            if handler_id != _handler_id(source_name):
                raise RegistryError(f"handler binding drift for {source_name}")
            try:
                operation = Operation(record.get("operation"))
                capability_state = CapabilityState(record.get("capabilityState"))
            except ValueError as exc:
                raise RegistryError(f"unsupported runtime binding for {source_name}") from exc
            description = record.get("description")
            layer = record.get("layer")
            if not isinstance(description, str) or len(description) < 20:
                raise RegistryError(f"description invalid for {source_name}")
            if not isinstance(layer, str) or not layer:
                raise RegistryError(f"layer invalid for {source_name}")
            bindings[source_name] = SkillBinding(
                source_skill_id=source_id,
                source_name=source_name,
                installed_name=installed_name,
                batch=batch,
                layer=layer,
                risk="critical",
                description=description,
                dependencies=tuple(dependencies),
                outputs=tuple(outputs),
                handler_id=handler_id,
                operation=operation,
                capability_state=capability_state,
            )
            seen_ids.add(source_id)
        if dict(batch_counts) != EXPECTED_BATCH_COUNTS:
            raise RegistryError("compiled contract batch counts drifted")
        self._validate_graph(bindings)
        return bindings

    @staticmethod
    def _validate_graph(bindings: dict[str, SkillBinding]) -> None:
        names = set(bindings)
        all_dependencies = [
            dependency
            for binding in bindings.values()
            for dependency in binding.dependencies
        ]
        if len(all_dependencies) != EXPECTED_EDGE_COUNT:
            raise RegistryError("compiled contract dependency edge count drifted")
        external = set(all_dependencies) - names
        if external != EXPECTED_EXTERNAL_DEPENDENCIES:
            raise RegistryError("compiled contract external dependency drift")
        internal_edges = [
            (dependency, binding.source_name)
            for binding in bindings.values()
            for dependency in binding.dependencies
            if dependency in names
        ]
        if len(internal_edges) != EXPECTED_INTERNAL_EDGE_COUNT:
            raise RegistryError("compiled contract internal edge count drifted")
        adjacency: dict[str, list[str]] = defaultdict(list)
        indegree = {name: 0 for name in names}
        for dependency, dependent in internal_edges:
            adjacency[dependency].append(dependent)
            indegree[dependent] += 1
        queue = deque(sorted(name for name, count in indegree.items() if count == 0))
        visited = 0
        while queue:
            current = queue.popleft()
            visited += 1
            for dependent in sorted(adjacency[current]):
                indegree[dependent] -= 1
                if indegree[dependent] == 0:
                    queue.append(dependent)
        if visited != len(names):
            raise RegistryError("compiled contract dependency graph contains a cycle")


__all__ = [
    "COLLISION_ALIASES",
    "EXPECTED_BATCH_COUNTS",
    "EXPECTED_EXTERNAL_DEPENDENCIES",
    "PACKAGE_ID",
    "SOURCE_ARCHIVE_SHA256",
    "SOURCE_MANIFEST_SHA256",
    "RegistryError",
    "SkillBinding",
    "SkillRegistry",
]
