"""Hand-verified, per-vendor DDL rendering for `certified-ddl-v1`.

Deliberately does NOT use sqlglot's built-in cross-dialect `.sql(dialect=...)`
generator for the final emission step. That generator is excellent for
parsing (see `parser.py`) but, empirically, its default cross-dialect output
for AUTO_INCREMENT/IDENTITY columns and BOOLEAN columns is wrong for several
pairs -- e.g. transpiling MySQL's `AUTO_INCREMENT` straight to Oracle leaves
the literal keyword `AUTO_INCREMENT` in the output, which Oracle's parser
rejects outright; transpiling SQL Server `IDENTITY(1,1)` to MySQL emits
`GENERATED BY DEFAULT AS IDENTITY (...)`, which is not valid MySQL syntax.
Both were reproduced and confirmed against sqlglot 30.14.0 before writing
this module. This module owns exactly those decisions instead, per dialect,
verified by the round-trip and (where possible) real-execution tests in
`tests/`.
"""
from __future__ import annotations

from .models import (
    CanonicalType,
    CanonicalTypeRef,
    CheckOperator,
    Dialect,
    DefaultKind,
    ColumnDefault,
    DialectError,
    ReferentialAction,
)

_CHECK_OPERATOR_SQL: dict[CheckOperator, str] = {
    CheckOperator.EQ: "=",
    CheckOperator.NE: "<>",
    CheckOperator.LT: "<",
    CheckOperator.LE: "<=",
    CheckOperator.GT: ">",
    CheckOperator.GE: ">=",
}

_REFERENTIAL_ACTION_SQL: dict[ReferentialAction, str] = {
    ReferentialAction.CASCADE: "CASCADE",
    ReferentialAction.SET_NULL: "SET NULL",
    ReferentialAction.RESTRICT: "RESTRICT",
    ReferentialAction.NO_ACTION: "NO ACTION",
}


def check_operator_sql(operator: CheckOperator) -> str:
    return _CHECK_OPERATOR_SQL[operator]


def referential_action_sql(action: ReferentialAction) -> str:
    return _REFERENTIAL_ACTION_SQL[action]


#: Hard, documented per-vendor ceilings for a *character* column length.
#: Exceeding one of these is a statement the target server rejects outright,
#: so certified-ddl-v1 fails closed on it rather than emitting DDL that only
#: sqlglot's grammar accepts.
#:
#:   postgres  varchar(n)   n <= 10485760
#:   mysql     VARCHAR(n)   n <= 65535 (further limited by the 65535-byte row
#:                          size; that one depends on the table's charset and
#:                          other columns, so it stays an execution-leg check)
#:   oracle    VARCHAR2(n CHAR)  n <= 4000 with the default MAX_STRING_SIZE
#:   tsql      NVARCHAR(n)  n <= 4000 (NVARCHAR is 2 bytes/char, so its limit
#:                          is half of VARCHAR's 8000; Unicode fidelity is
#:                          worth more than the extra range -- see below)
_MAX_VARCHAR_LENGTH: dict[Dialect, int] = {
    Dialect.POSTGRES: 10_485_760,
    Dialect.MYSQL: 65_535,
    Dialect.ORACLE: 4_000,
    Dialect.TSQL: 4_000,
}

#: Same, for fixed-length CHAR columns.
#:   postgres char(n) n <= 10485760 | mysql CHAR(n) n <= 255
#:   oracle CHAR(n CHAR) n <= 2000  | tsql NCHAR(n) n <= 4000
_MAX_CHAR_LENGTH: dict[Dialect, int] = {
    Dialect.POSTGRES: 10_485_760,
    Dialect.MYSQL: 255,
    Dialect.ORACLE: 2_000,
    Dialect.TSQL: 4_000,
}

#: Documented maximum DECIMAL/NUMERIC/NUMBER precision per vendor.
_MAX_DECIMAL_PRECISION: dict[Dialect, int] = {
    Dialect.POSTGRES: 1_000,
    Dialect.MYSQL: 65,
    Dialect.ORACLE: 38,
    Dialect.TSQL: 38,
}

#: Documented maximum DECIMAL scale per vendor (MySQL caps scale at 30
#: independently of precision; the others only require scale <= precision).
_MAX_DECIMAL_SCALE: dict[Dialect, int] = {Dialect.MYSQL: 30}


def _require_length(length: int, limit: int, dialect: Dialect, rendered: str) -> None:
    if length > limit:
        raise DialectError(
            "CERTIFIED_DDL_LENGTH_EXCEEDS_TARGET",
            f"length {length} exceeds the maximum {limit} that {dialect.value} accepts for "
            f"{rendered}; certified-ddl-v1 will not emit DDL the target server rejects",
        )


def render_type(type_ref: CanonicalTypeRef, dialect: Dialect) -> str:
    t = type_ref.canonical_type
    if t == CanonicalType.BOOLEAN:
        return {
            Dialect.POSTGRES: "BOOLEAN",
            Dialect.MYSQL: "BOOLEAN",
            Dialect.TSQL: "BIT",
            Dialect.ORACLE: "NUMBER(1)",
        }[dialect]
    if t == CanonicalType.INT16:
        return {
            Dialect.POSTGRES: "SMALLINT",
            Dialect.MYSQL: "SMALLINT",
            Dialect.TSQL: "SMALLINT",
            Dialect.ORACLE: "NUMBER(5)",
        }[dialect]
    if t == CanonicalType.INT32:
        return {
            Dialect.POSTGRES: "INTEGER",
            Dialect.MYSQL: "INT",
            Dialect.TSQL: "INT",
            Dialect.ORACLE: "NUMBER(10)",
        }[dialect]
    if t == CanonicalType.INT64:
        return {
            Dialect.POSTGRES: "BIGINT",
            Dialect.MYSQL: "BIGINT",
            Dialect.TSQL: "BIGINT",
            Dialect.ORACLE: "NUMBER(19)",
        }[dialect]
    if t == CanonicalType.DECIMAL:
        # precision is mandatory in the canonical model: an unparameterised
        # DECIMAL is arbitrary-precision and is rejected at parse time rather
        # than defaulted here (defaulting scale to 0 silently rounded every
        # fractional value away).
        assert type_ref.precision is not None  # parser enforces this
        precision = type_ref.precision
        scale = type_ref.scale if type_ref.scale is not None else 0
        limit = _MAX_DECIMAL_PRECISION[dialect]
        if precision > limit:
            raise DialectError(
                "CERTIFIED_DDL_PRECISION_EXCEEDS_TARGET",
                f"DECIMAL precision {precision} exceeds the maximum {limit} that "
                f"{dialect.value} accepts",
            )
        scale_limit = _MAX_DECIMAL_SCALE.get(dialect)
        if scale_limit is not None and scale > scale_limit:
            raise DialectError(
                "CERTIFIED_DDL_PRECISION_EXCEEDS_TARGET",
                f"DECIMAL scale {scale} exceeds the maximum {scale_limit} that "
                f"{dialect.value} accepts",
            )
        name = "NUMBER" if dialect == Dialect.ORACLE else ("NUMERIC" if dialect == Dialect.POSTGRES else "DECIMAL")
        return f"{name}({precision}, {scale})"
    if t == CanonicalType.CHAR:
        length = type_ref.length if type_ref.length is not None else 1
        _require_length(length, _MAX_CHAR_LENGTH[dialect], dialect, "CHAR")
        if dialect == Dialect.TSQL:
            # NCHAR, not CHAR: SQL Server's CHAR/VARCHAR are single-byte
            # code-page types, so routing a UTF-8 PostgreSQL/MySQL column into
            # CHAR silently replaces every character the server's collation
            # code page cannot represent with '?'.
            return f"NCHAR({length})"
        if dialect == Dialect.ORACLE:
            # Oracle's default length semantics is BYTE (NLS_LENGTH_SEMANTICS),
            # so a bare CHAR(50) holds 50 *bytes* -- as few as 12 characters in
            # AL32UTF8. Every other dialect in this profile counts characters,
            # so the CHAR qualifier is mandatory to keep the column the same
            # size after translation.
            return f"CHAR({length} CHAR)"
        return f"CHAR({length})"
    if t == CanonicalType.VARCHAR:
        # length is mandatory in the canonical model: an unbounded VARCHAR is
        # parsed as TEXT (PostgreSQL) or rejected (everything else) rather
        # than defaulted to 255, which truncated every longer value.
        assert type_ref.length is not None  # parser enforces this
        length = type_ref.length
        _require_length(length, _MAX_VARCHAR_LENGTH[dialect], dialect, "VARCHAR")
        if dialect == Dialect.TSQL:
            return f"NVARCHAR({length})"  # see the CHAR branch for why not VARCHAR
        if dialect == Dialect.ORACLE:
            return f"VARCHAR2({length} CHAR)"  # see the CHAR branch for why not a bare length
        return f"VARCHAR({length})"
    if t == CanonicalType.TEXT:
        return {
            Dialect.POSTGRES: "TEXT",
            # NOT plain TEXT: MySQL's TEXT holds 65,535 *bytes*, versus ~1 GB
            # for PostgreSQL's TEXT, 2 GB for NVARCHAR(MAX) and 4 GB for CLOB.
            # LONGTEXT is the only MySQL form that is not a silent truncation
            # of the other three.
            Dialect.MYSQL: "LONGTEXT",
            # NVARCHAR(MAX), not VARCHAR(MAX) -- same code-page reason as CHAR.
            Dialect.TSQL: "NVARCHAR(MAX)",
            Dialect.ORACLE: "CLOB",
        }[dialect]
    if t == CanonicalType.DATE:
        return "DATE"
    if t == CanonicalType.TIMESTAMP:
        return {
            Dialect.POSTGRES: "TIMESTAMP",
            # NOT MySQL's TIMESTAMP: that type is stored as UTC and converted
            # to the session time zone on every read, is limited to
            # 1970-01-01..2038-01-19, and (with the default
            # explicit_defaults_for_timestamp=OFF) silently acquires NOT NULL
            # DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP on the
            # first such column. DATETIME is the faithful equivalent of
            # PostgreSQL's `timestamp without time zone`, Oracle's TIMESTAMP
            # and SQL Server's DATETIME2.
            Dialect.MYSQL: "DATETIME",
            Dialect.TSQL: "DATETIME2",
            Dialect.ORACLE: "TIMESTAMP",
        }[dialect]
    raise DialectError("CERTIFIED_DDL_UNREACHABLE_TYPE", f"no renderer registered for {t}")  # pragma: no cover


def render_auto_increment_suffix(dialect: Dialect) -> str:
    """Text to append immediately after the rendered type when a column is
    `auto_increment`. Each dialect's real, native mechanism -- never a
    passthrough of another dialect's keyword."""
    return {
        Dialect.POSTGRES: " GENERATED BY DEFAULT AS IDENTITY",
        Dialect.MYSQL: " AUTO_INCREMENT",
        Dialect.TSQL: " IDENTITY(1,1)",
        # Oracle 12c+ (released 2013); certified-ddl-v1 does not target 11g or earlier.
        Dialect.ORACLE: " GENERATED BY DEFAULT AS IDENTITY",
    }[dialect]


def render_default(default: ColumnDefault, type_ref: CanonicalTypeRef, dialect: Dialect) -> str:
    if default.kind == DefaultKind.CURRENT_TIMESTAMP:
        # SYSDATETIME(), not GETDATE(): GETDATE() returns the legacy `datetime`
        # type -- 3.33 ms granularity, range 1753-9999 -- so it silently
        # truncates the sub-millisecond precision of the DATETIME2 column this
        # profile renders. SYSDATETIME() returns datetime2(7) and matches
        # CURRENT_TIMESTAMP on the other three dialects.
        return "SYSDATETIME()" if dialect == Dialect.TSQL else "CURRENT_TIMESTAMP"
    if default.kind == DefaultKind.NUMBER:
        assert default.literal is not None
        return default.literal
    if default.kind == DefaultKind.STRING:
        assert default.literal is not None
        escaped = default.literal.replace("'", "''")
        return f"'{escaped}'"
    if default.kind == DefaultKind.BOOLEAN:
        assert default.literal in ("true", "false")
        # Oracle/SQL Server render BOOLEAN as NUMBER(1)/BIT (see render_type):
        # neither dialect accepts a TRUE/FALSE literal against that column type.
        if dialect in (Dialect.ORACLE, Dialect.TSQL):
            return "1" if default.literal == "true" else "0"
        return "TRUE" if default.literal == "true" else "FALSE"
    raise DialectError("CERTIFIED_DDL_UNREACHABLE_DEFAULT", f"no renderer registered for {default.kind}")  # pragma: no cover


IDENTIFIER_PATTERN = r"[A-Za-z_][A-Za-z0-9_]{0,62}"
"""certified-ddl-v1 requires plain, unquoted identifiers only (see parser.py)
so this module never has to reproduce four different quoting characters
(double quotes for Postgres/Oracle, backticks for MySQL, brackets for T-SQL)
and their four different reserved-word lists. An identifier requiring
quoting is out of scope and must fail closed at parse time."""
