"""Hand-verified, per-vendor DDL rendering for `certified-ddl-v1`.

Deliberately does NOT use sqlglot's built-in cross-dialect `.sql(dialect=...)`
generator for the final emission step. That generator is excellent for
parsing (see `parser.py`) but, empirically, its default cross-dialect output
for AUTO_INCREMENT/IDENTITY columns and BOOLEAN columns is wrong for several
pairs -- e.g. transpiling MySQL's `AUTO_INCREMENT` straight to Oracle leaves
the literal keyword `AUTO_INCREMENT` in the output, which Oracle's parser
rejects outright; transpiling SQL Server `IDENTITY(1,1)` to MySQL emits
`GENERATED BY DEFAULT AS IDENTITY (...)`, which is not valid MySQL syntax.
Both were reproduced and confirmed against sqlglot 30.14.0 before writing
this module. This module owns exactly those decisions instead, per dialect,
verified by the round-trip and (where possible) real-execution tests in
`tests/`.
"""
from __future__ import annotations

from .models import (
    CanonicalType,
    CanonicalTypeRef,
    CheckOperator,
    Dialect,
    DefaultKind,
    ColumnDefault,
    DialectError,
    ReferentialAction,
)

_CHECK_OPERATOR_SQL: dict[CheckOperator, str] = {
    CheckOperator.EQ: "=",
    CheckOperator.NE: "<>",
    CheckOperator.LT: "<",
    CheckOperator.LE: "<=",
    CheckOperator.GT: ">",
    CheckOperator.GE: ">=",
}

_REFERENTIAL_ACTION_SQL: dict[ReferentialAction, str] = {
    ReferentialAction.CASCADE: "CASCADE",
    ReferentialAction.SET_NULL: "SET NULL",
    ReferentialAction.RESTRICT: "RESTRICT",
    ReferentialAction.NO_ACTION: "NO ACTION",
}


def check_operator_sql(operator: CheckOperator) -> str:
    return _CHECK_OPERATOR_SQL[operator]


def referential_action_sql(action: ReferentialAction) -> str:
    return _REFERENTIAL_ACTION_SQL[action]


#: Which referential actions each vendor's `references_clause` actually
#: accepts, per their documented grammar -- NOT per what sqlglot will parse.
#:
#: This table exists because sqlglot accepts `ON DELETE NO ACTION ON UPDATE
#: NO ACTION` for every dialect, so the syntax-validation leg cannot catch a
#: clause the real database rejects. Oracle in particular:
#:
#:   - has NO `ON UPDATE` clause at all;
#:   - accepts only `ON DELETE CASCADE` and `ON DELETE SET NULL`, with the
#:     omitted form carrying NO ACTION semantics;
#:   - has no RESTRICT.
#:
#: SQL Server has no RESTRICT either. MySQL (InnoDB) and PostgreSQL accept
#: all four of the canonical actions.
_ON_DELETE_SUPPORT: dict[Dialect, frozenset[ReferentialAction]] = {
    Dialect.POSTGRES: frozenset(ReferentialAction),
    Dialect.MYSQL: frozenset(ReferentialAction),
    Dialect.TSQL: frozenset({ReferentialAction.NO_ACTION, ReferentialAction.CASCADE, ReferentialAction.SET_NULL}),
    Dialect.ORACLE: frozenset({ReferentialAction.NO_ACTION, ReferentialAction.CASCADE, ReferentialAction.SET_NULL}),
}

_ON_UPDATE_SUPPORT: dict[Dialect, frozenset[ReferentialAction]] = {
    Dialect.POSTGRES: frozenset(ReferentialAction),
    Dialect.MYSQL: frozenset(ReferentialAction),
    Dialect.TSQL: frozenset({ReferentialAction.NO_ACTION, ReferentialAction.CASCADE, ReferentialAction.SET_NULL}),
    # Oracle has no ON UPDATE clause. Only the implicit default is reachable.
    Dialect.ORACLE: frozenset({ReferentialAction.NO_ACTION}),
}

#: Dialects where NO ACTION must be expressed by OMITTING the clause rather
#: than by spelling it out.
_OMIT_NO_ACTION = frozenset({Dialect.ORACLE})


def render_reference_actions(
    on_delete: ReferentialAction, on_update: ReferentialAction, dialect: Dialect
) -> str:
    """Render the ON DELETE / ON UPDATE tail of a REFERENCES clause.

    Returns the empty string when the target expresses both actions by
    omission. Raises `DialectError` -- fail closed -- when the target has no
    way to express the requested action, because the alternatives are all
    worse: emitting a clause the database rejects breaks the migration
    loudly, and silently downgrading (say RESTRICT to NO ACTION) changes
    when the constraint is checked without telling anyone.
    """
    for action, supported, clause in (
        (on_delete, _ON_DELETE_SUPPORT[dialect], "ON DELETE"),
        (on_update, _ON_UPDATE_SUPPORT[dialect], "ON UPDATE"),
    ):
        if action not in supported:
            detail = (
                f"{dialect.value} has no {clause} clause"
                if not supported - {ReferentialAction.NO_ACTION}
                else f"{dialect.value} does not accept {clause} {referential_action_sql(action)}"
            )
            raise DialectError(
                "CERTIFIED_DDL_UNREACHABLE_REFERENTIAL_ACTION",
                f"{detail}; certified-ddl-v1 refuses to downgrade it silently",
            )

    parts: list[str] = []
    omit_default = dialect in _OMIT_NO_ACTION
    if not (omit_default and on_delete is ReferentialAction.NO_ACTION):
        parts.append(f"ON DELETE {referential_action_sql(on_delete)}")
    if not (omit_default and on_update is ReferentialAction.NO_ACTION):
        parts.append(f"ON UPDATE {referential_action_sql(on_update)}")
    return " ".join(parts)


def render_type(type_ref: CanonicalTypeRef, dialect: Dialect) -> str:
    t = type_ref.canonical_type
    if t == CanonicalType.BOOLEAN:
        return {
            Dialect.POSTGRES: "BOOLEAN",
            Dialect.MYSQL: "BOOLEAN",
            Dialect.TSQL: "BIT",
            Dialect.ORACLE: "NUMBER(1)",
        }[dialect]
    if t == CanonicalType.INT16:
        return {
            Dialect.POSTGRES: "SMALLINT",
            Dialect.MYSQL: "SMALLINT",
            Dialect.TSQL: "SMALLINT",
            Dialect.ORACLE: "NUMBER(5)",
        }[dialect]
    if t == CanonicalType.INT32:
        return {
            Dialect.POSTGRES: "INTEGER",
            Dialect.MYSQL: "INT",
            Dialect.TSQL: "INT",
            Dialect.ORACLE: "NUMBER(10)",
        }[dialect]
    if t == CanonicalType.INT64:
        return {
            Dialect.POSTGRES: "BIGINT",
            Dialect.MYSQL: "BIGINT",
            Dialect.TSQL: "BIGINT",
            Dialect.ORACLE: "NUMBER(19)",
        }[dialect]
    if t == CanonicalType.DECIMAL:
        precision = type_ref.precision if type_ref.precision is not None else 18
        scale = type_ref.scale if type_ref.scale is not None else 0
        name = "NUMBER" if dialect == Dialect.ORACLE else ("NUMERIC" if dialect == Dialect.POSTGRES else "DECIMAL")
        return f"{name}({precision}, {scale})"
    if t == CanonicalType.CHAR:
        length = type_ref.length if type_ref.length is not None else 1
        return f"CHAR({length})"
    if t == CanonicalType.VARCHAR:
        length = type_ref.length if type_ref.length is not None else 255
        name = "VARCHAR2" if dialect == Dialect.ORACLE else "VARCHAR"
        return f"{name}({length})"
    if t == CanonicalType.TEXT:
        return {
            Dialect.POSTGRES: "TEXT",
            Dialect.MYSQL: "TEXT",
            Dialect.TSQL: "VARCHAR(MAX)",
            Dialect.ORACLE: "CLOB",
        }[dialect]
    if t == CanonicalType.DATE:
        return "DATE"
    if t == CanonicalType.TIMESTAMP:
        return {
            Dialect.POSTGRES: "TIMESTAMP",
            Dialect.MYSQL: "TIMESTAMP",
            Dialect.TSQL: "DATETIME2",
            Dialect.ORACLE: "TIMESTAMP",
        }[dialect]
    raise DialectError("CERTIFIED_DDL_UNREACHABLE_TYPE", f"no renderer registered for {t}")  # pragma: no cover


def render_auto_increment_suffix(dialect: Dialect) -> str:
    """Text to append immediately after the rendered type when a column is
    `auto_increment`. Each dialect's real, native mechanism -- never a
    passthrough of another dialect's keyword."""
    return {
        Dialect.POSTGRES: " GENERATED BY DEFAULT AS IDENTITY",
        Dialect.MYSQL: " AUTO_INCREMENT",
        Dialect.TSQL: " IDENTITY(1,1)",
        # Oracle 12c+ (released 2013); certified-ddl-v1 does not target 11g or earlier.
        Dialect.ORACLE: " GENERATED BY DEFAULT AS IDENTITY",
    }[dialect]


def render_default(default: ColumnDefault, type_ref: CanonicalTypeRef, dialect: Dialect) -> str:
    if default.kind == DefaultKind.CURRENT_TIMESTAMP:
        return "GETDATE()" if dialect == Dialect.TSQL else "CURRENT_TIMESTAMP"
    if default.kind == DefaultKind.NUMBER:
        assert default.literal is not None
        return default.literal
    if default.kind == DefaultKind.STRING:
        assert default.literal is not None
        escaped = default.literal.replace("'", "''")
        return f"'{escaped}'"
    if default.kind == DefaultKind.BOOLEAN:
        assert default.literal in ("true", "false")
        # Oracle/SQL Server render BOOLEAN as NUMBER(1)/BIT (see render_type):
        # neither dialect accepts a TRUE/FALSE literal against that column type.
        if dialect in (Dialect.ORACLE, Dialect.TSQL):
            return "1" if default.literal == "true" else "0"
        return "TRUE" if default.literal == "true" else "FALSE"
    raise DialectError("CERTIFIED_DDL_UNREACHABLE_DEFAULT", f"no renderer registered for {default.kind}")  # pragma: no cover


IDENTIFIER_PATTERN = r"[A-Za-z_][A-Za-z0-9_]{0,62}"
"""certified-ddl-v1 requires plain, unquoted identifiers only (see parser.py)
so this module never has to reproduce four different quoting characters
(double quotes for Postgres/Oracle, backticks for MySQL, brackets for T-SQL)
and their four different reserved-word lists. An identifier requiring
quoting is out of scope and must fail closed at parse time."""
