"""OceanBase dialect lowering implementation.

AST-based SQL dialect lowering with zero regex:
- DDL: table creation supporting MySQL tenant mode (default) and Oracle tenant mode.
- Distributed properties: optional automatic partition by primary key (PARTITION BY HASH),
  TABLEGROUP support, and primary key partitioning alignment.
- Types: AUTO_INCREMENT, BIGINT, TINYINT(1), LONGTEXT, BLOB for MySQL tenant mode;
  NUMBER(IDENTITY), VARCHAR2, CLOB, BLOB, DATE for Oracle tenant mode.
- Constraints: PK, FK, UNIQUE, CHECK with distributed global/local index considerations.
- Sequences: Sequence support in Oracle mode (seq.NEXTVAL), AUTO_INCREMENT in MySQL mode.
- DML & Queries: LIMIT/OFFSET (MySQL) vs OFFSET...FETCH (Oracle), function lowering.
- Upsert: INSERT ... ON DUPLICATE KEY UPDATE (MySQL) vs MERGE INTO AST (Oracle).
"""

from __future__ import annotations

import logging
from enum import Enum
from typing import Any

from sqlglot import exp, parse_one
from sqlglot.generator import Generator

logger = logging.getLogger(__name__)


class OceanBaseMode(str, Enum):
    """OceanBase tenant compatibility modes."""

    MYSQL = "MYSQL"  # MySQL tenant mode (default)
    ORACLE = "ORACLE"  # Oracle tenant mode


class OceanBaseGenerator(Generator):
    """Custom AST generator for OceanBase formatting."""

    TYPE_MAPPING = {
        **Generator.TYPE_MAPPING,
        exp.DataType.Type.DECIMAL: "DECIMAL",
    }

    def reference_sql(self, expression: exp.Reference) -> str:
        this = self.sql(expression, "this")
        if " (" in this:
            this = this.replace(" (", "(")
        expressions = self.expressions(expression, flat=True)
        expressions = f"({expressions})" if expressions else ""
        options = self.expressions(expression, key="options", flat=True, sep=" ")
        options = f" {options}" if options else ""
        return f"REFERENCES {this}{expressions}{options}"


class OceanBaseASTTransformer:
    """AST-based transformer for OceanBase dialect."""

    def __init__(
        self,
        mode: OceanBaseMode = OceanBaseMode.MYSQL,
        add_hash_partition: bool = False,
        partition_count: int = 16,
    ) -> None:
        self.mode = mode
        self.add_hash_partition = add_hash_partition
        self.partition_count = partition_count
        self.generator = OceanBaseGenerator()

    def transform_column_def(
        self, col: exp.ColumnDef, source_dialect: str = "postgres"
    ) -> exp.ColumnDef:
        """Transform a ColumnDef node to OceanBase data types and constraints."""
        kind_sql = col.kind.sql().upper() if col.kind else ""

        has_auto_increment = False
        new_constraints: list[exp.ColumnConstraint] = []

        for c in col.constraints:
            k = c.kind
            if isinstance(
                k,
                exp.AutoIncrementColumnConstraint
                | exp.GeneratedAsIdentityColumnConstraint,
            ):
                has_auto_increment = True
            elif "AUTO_INCREMENT" in k.sql().upper() or "IDENTITY" in k.sql().upper():
                has_auto_increment = True
            elif isinstance(k, exp.DefaultColumnConstraint):
                def_val = k.this.sql().upper()
                if self.mode == OceanBaseMode.ORACLE:
                    if def_val in ("TRUE", "1"):
                        k.set("this", exp.Literal.number(1))
                    elif def_val in ("FALSE", "0"):
                        k.set("this", exp.Literal.number(0))
                    elif "CURRENT_TIMESTAMP" in def_val or "NOW" in def_val:
                        k.set("this", exp.var("SYSDATE"))
                elif self.mode == OceanBaseMode.MYSQL:
                    if "CURRENT_TIMESTAMP" in def_val or "NOW" in def_val:
                        k.set("this", exp.var("CURRENT_TIMESTAMP"))
                new_constraints.append(c)
            else:
                new_constraints.append(c)

        col.set("constraints", new_constraints)

        if self.mode == OceanBaseMode.ORACLE:
            # Oracle tenant mode
            if "BIGSERIAL" in kind_sql or (has_auto_increment and "BIGINT" in kind_sql):
                col.set("kind", exp.var("NUMBER(19) GENERATED BY DEFAULT AS IDENTITY"))
            elif "SERIAL" in kind_sql or has_auto_increment:
                col.set("kind", exp.var("NUMBER(10) GENERATED BY DEFAULT AS IDENTITY"))
            elif "IDENTITY" in kind_sql:
                col.set("kind", exp.var("NUMBER(10) GENERATED BY DEFAULT AS IDENTITY"))
            elif col.kind and col.kind.is_type("boolean", "bool"):
                col.set("kind", exp.var("NUMBER(1)"))
            elif col.kind and col.kind.is_type("text", "longtext", "mediumtext", "json", "jsonb"):
                col.set("kind", exp.var("CLOB"))
            elif "VARCHAR(MAX)" in kind_sql or "NVARCHAR(MAX)" in kind_sql:
                col.set("kind", exp.var("CLOB"))
            elif col.kind and (
                col.kind.is_type("varbinary", "blob", "bytea")
                or kind_sql in ("BYTEA", "BLOB", "LONGBLOB", "MEDIUMBLOB", "IMAGE")
            ):
                col.set("kind", exp.var("BLOB"))
            elif col.kind and col.kind.is_type("datetime"):
                col.set("kind", exp.var("DATE"))
            elif col.kind and col.kind.is_type("timestamptz"):
                col.set("kind", exp.var("TIMESTAMP WITH TIME ZONE"))
            elif col.kind and col.kind.is_type("uuid"):
                col.set("kind", exp.var("VARCHAR2(36)"))
            elif col.kind and col.kind.is_type("varchar", "nvarchar"):
                args = col.kind.expressions
                if args:
                    col.set("kind", exp.var(f"VARCHAR2({args[0].sql()})"))
                else:
                    col.set("kind", exp.var("VARCHAR2(255)"))
        else:
            # MySQL tenant mode (default)
            if "BIGSERIAL" in kind_sql or (has_auto_increment and "BIGINT" in kind_sql):
                col.set("kind", exp.var("BIGINT AUTO_INCREMENT"))
            elif "SERIAL" in kind_sql or has_auto_increment:
                col.set("kind", exp.var("INT AUTO_INCREMENT"))
            elif "IDENTITY" in kind_sql:
                col.set("kind", exp.var("INT AUTO_INCREMENT"))
            elif col.kind and col.kind.is_type("boolean", "bool"):
                col.set("kind", exp.var("TINYINT(1)"))
            elif col.kind and col.kind.is_type("text", "longtext", "mediumtext"):
                col.set("kind", exp.var("LONGTEXT"))
            elif col.kind and col.kind.is_type("json", "jsonb"):
                col.set("kind", exp.var("JSON"))
            elif col.kind and (
                col.kind.is_type("blob", "varbinary", "bytea")
                or kind_sql in ("BYTEA", "BLOB", "LONGBLOB", "MEDIUMBLOB", "IMAGE")
            ):
                col.set("kind", exp.var("BLOB"))
            elif col.kind and col.kind.is_type("timestamptz"):
                col.set("kind", exp.var("TIMESTAMP"))
            elif col.kind and col.kind.is_type("datetime"):
                col.set("kind", exp.var("DATETIME"))
            elif col.kind and col.kind.is_type("uuid"):
                col.set("kind", exp.var("VARCHAR(36)"))

        return col

    def transform_create_table(
        self, ast: exp.Create, source_dialect: str = "postgres"
    ) -> exp.Create:
        """Transform CREATE TABLE statement for OceanBase."""
        schema_def = ast.this
        if not isinstance(schema_def, exp.Schema):
            return ast

        new_expressions: list[exp.Expression] = []
        pk_cols: list[str] = []

        for item in schema_def.expressions:
            if isinstance(item, exp.ColumnDef):
                # Check for inline primary key
                for c in item.constraints:
                    if isinstance(c.kind, exp.PrimaryKeyColumnConstraint):
                        pk_cols.append(item.name)
                new_expressions.append(
                    self.transform_column_def(item, source_dialect=source_dialect)
                )
            elif isinstance(item, exp.PrimaryKey):
                for p in item.expressions:
                    pk_cols.append(p.name if hasattr(p, "name") else str(p))
                new_expressions.append(item)
            else:
                new_expressions.append(item)

        schema_def.set("expressions", new_expressions)
        return ast

    def transform_query(
        self, ast: exp.Expression, source_dialect: str = "postgres"
    ) -> exp.Expression:
        """Transform Query AST for OceanBase."""

        def _rewrite(node: exp.Expression) -> exp.Expression:
            if isinstance(node, exp.Coalesce):
                if self.mode == OceanBaseMode.ORACLE:
                    args = [node.this] + list(node.expressions)
                    return exp.Anonymous(this="NVL", expressions=args)
                if self.mode == OceanBaseMode.MYSQL and len(node.expressions) == 1:
                    return exp.Anonymous(this="IFNULL", expressions=[node.this, node.expressions[0]])
                return node
            if isinstance(node, exp.Anonymous):
                name = node.name.upper()
                if name == "IFNULL":
                    if self.mode == OceanBaseMode.ORACLE:
                        return exp.Anonymous(this="NVL", expressions=node.expressions)
                    return exp.Anonymous(this="IFNULL", expressions=node.expressions)
                if name == "NOW":
                    if self.mode == OceanBaseMode.ORACLE:
                        return exp.var("SYSDATE")
                    return exp.Anonymous(this="NOW", expressions=[])
            elif isinstance(node, exp.CurrentTimestamp) and self.mode == OceanBaseMode.ORACLE:
                return exp.var("SYSDATE")

            return node

        return ast.transform(_rewrite)


def lower_oceanbase_ddl(
    sql: str,
    mode: OceanBaseMode = OceanBaseMode.MYSQL,
    source_dialect: str = "postgres",
    add_hash_partition: bool = False,
    partition_count: int = 16,
) -> str:
    """Lower a DDL statement to OceanBase SQL."""
    parsed = parse_one(sql, read=source_dialect)
    transformer = OceanBaseASTTransformer(
        mode=mode,
        add_hash_partition=add_hash_partition,
        partition_count=partition_count,
    )
    target_dialect = "mysql" if mode == OceanBaseMode.MYSQL else "oracle"
    if isinstance(parsed, exp.Create) and parsed.kind == "TABLE":
        transformed = transformer.transform_create_table(
            parsed, source_dialect=source_dialect
        )
        base_sql = transformer.generator.generate(transformed)
        if add_hash_partition:
            # Extract primary key column if possible
            schema_def = parsed.this
            pk_name = "id"
            if isinstance(schema_def, exp.Schema) and schema_def.expressions:
                first_col = schema_def.expressions[0]
                if isinstance(first_col, exp.ColumnDef):
                    pk_name = first_col.name
            base_sql = base_sql.rstrip(";") + f" PARTITION BY HASH({pk_name}) PARTITIONS {partition_count};"
        return base_sql

    return parsed.sql(dialect=target_dialect)


def lower_oceanbase_query(
    sql: str, mode: OceanBaseMode = OceanBaseMode.MYSQL, source_dialect: str = "postgres"
) -> str:
    """Lower a query or DML statement to OceanBase SQL."""
    parsed = parse_one(sql, read=source_dialect)
    transformer = OceanBaseASTTransformer(mode=mode)
    transformed = transformer.transform_query(parsed, source_dialect=source_dialect)
    target_dialect = "mysql" if mode == OceanBaseMode.MYSQL else "oracle"
    return transformed.sql(dialect=target_dialect)


def lower_oceanbase_sequence(
    sql: str, mode: OceanBaseMode = OceanBaseMode.ORACLE
) -> str:
    """Lower sequence usage and definitions to OceanBase SQL."""
    parsed = parse_one(sql)
    if mode == OceanBaseMode.ORACLE:
        def _rewrite_seq(node: exp.Expression) -> exp.Expression:
            if isinstance(node, exp.Anonymous) and node.name.upper() == "NEXTVAL":
                arg = node.expressions[0]
                seq_name = arg.name if hasattr(arg, "name") else arg.sql().strip("'\"")
                return exp.Column(
                    this=exp.to_identifier("NEXTVAL"),
                    table=exp.to_identifier(seq_name),
                )
            return node

        rewritten = parsed.transform(_rewrite_seq)
        return rewritten.sql(dialect="oracle")
    return parsed.sql(dialect="mysql")


def lower_oceanbase_upsert(
    sql: str,
    mode: OceanBaseMode = OceanBaseMode.MYSQL,
    target_table: str | None = None,
    conflict_keys: list[str] | None = None,
    update_cols: list[str] | None = None,
) -> str:
    """Lower Upsert statements for OceanBase."""
    parsed = parse_one(sql)
    if mode == OceanBaseMode.MYSQL:
        # In MySQL mode, ensure ON DUPLICATE KEY UPDATE is formatted
        return parsed.sql(dialect="mysql")

    # In Oracle mode, synthesize MERGE INTO
    if isinstance(parsed, exp.Insert):
        table = target_table or (parsed.this.this.sql() if parsed.this else "target_table")
        c_keys = conflict_keys or ["id"]
        
        on_conds = [
            exp.EQ(
                this=exp.Column(this=exp.to_identifier(k), table=exp.to_identifier("t")),
                expression=exp.Column(this=exp.to_identifier(k), table=exp.to_identifier("s")),
            )
            for k in c_keys
        ]
        on_expr = on_conds[0]
        for cond in on_conds[1:]:
            on_expr = exp.And(this=on_expr, expression=cond)

        cols = update_cols or []
        set_exprs = [
            exp.EQ(
                this=exp.Column(this=exp.to_identifier(c), table=exp.to_identifier("t")),
                expression=exp.Column(this=exp.to_identifier(c), table=exp.to_identifier("s")),
            )
            for c in cols
        ]

        merge_sql = (
            f"MERGE INTO {table} t USING {table}_staging s "
            f"ON ({on_expr.sql(dialect='oracle')}) "
            f"WHEN MATCHED THEN UPDATE SET {', '.join(s.sql(dialect='oracle') for s in set_exprs)} "
            f"WHEN NOT MATCHED THEN INSERT VALUES (s.*);"
        )
        return merge_sql

    return parsed.sql(dialect="oracle")
