"""Unit tests for OceanBase dialect lowerer."""

from __future__ import annotations

import pytest

from elmos_sql_dialect.chinadb import (
    OceanBaseMode,
    lower_chinadb_sql,
    lower_oceanbase_ddl,
    lower_oceanbase_query,
    lower_oceanbase_sequence,
    lower_oceanbase_upsert,
    lower_to_oceanbase,
    translate_to_oceanbase,
)


def test_oceanbase_mysql_mode_ddl_basic() -> None:
    source_sql = """
    CREATE TABLE users (
        id BIGSERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        is_active BOOLEAN DEFAULT TRUE,
        bio TEXT,
        metadata JSONB,
        avatar BYTEA,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );
    """
    lowered = lower_oceanbase_ddl(source_sql, mode=OceanBaseMode.MYSQL)
    assert "AUTO_INCREMENT" in lowered
    assert "TINYINT(1)" in lowered
    assert "LONGTEXT" in lowered
    assert "JSON" in lowered
    assert "BLOB" in lowered
    assert "PRIMARY KEY" in lowered


def test_oceanbase_mysql_mode_with_hash_partition() -> None:
    source_sql = """
    CREATE TABLE orders (
        id BIGINT PRIMARY KEY,
        order_no VARCHAR(64) NOT NULL
    );
    """
    lowered = lower_oceanbase_ddl(
        source_sql,
        mode=OceanBaseMode.MYSQL,
        add_hash_partition=True,
        partition_count=32,
    )
    assert "PARTITION BY HASH(id) PARTITIONS 32" in lowered


def test_oceanbase_oracle_mode_ddl_types() -> None:
    source_sql = """
    CREATE TABLE customers (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        is_vip BOOLEAN DEFAULT FALSE,
        notes TEXT,
        created_at DATETIME DEFAULT NOW()
    );
    """
    lowered = lower_oceanbase_ddl(source_sql, mode=OceanBaseMode.ORACLE)
    assert "NUMBER(10) GENERATED BY DEFAULT AS IDENTITY" in lowered
    assert "NUMBER(1)" in lowered
    assert "CLOB" in lowered
    assert "VARCHAR2" in lowered
    assert "DATE" in lowered or "TIMESTAMP" in lowered


def test_oceanbase_query_functions() -> None:
    # MySQL tenant mode
    q_mysql = "SELECT id, IFNULL(name, 'anon'), NOW() FROM users LIMIT 10;"
    lowered_mysql = lower_oceanbase_query(q_mysql, mode=OceanBaseMode.MYSQL)
    assert "IFNULL" in lowered_mysql
    assert "NOW()" in lowered_mysql or "CURRENT_TIMESTAMP" in lowered_mysql

    # Oracle tenant mode
    q_ora = "SELECT id, IFNULL(name, 'anon'), NOW() FROM users;"
    lowered_ora = lower_oceanbase_query(q_ora, mode=OceanBaseMode.ORACLE)
    assert "NVL" in lowered_ora
    assert "SYSDATE" in lowered_ora


def test_oceanbase_upsert() -> None:
    # MySQL mode
    upsert_mysql = "INSERT INTO users (id, name) VALUES (1, 'bob') ON DUPLICATE KEY UPDATE name = 'bob';"
    lowered_mysql = lower_oceanbase_upsert(upsert_mysql, mode=OceanBaseMode.MYSQL)
    assert "ON DUPLICATE KEY UPDATE" in lowered_mysql

    # Oracle mode MERGE INTO
    insert_ora = "INSERT INTO users (id, name) VALUES (1, 'bob');"
    merge_ora = lower_oceanbase_upsert(
        insert_ora,
        mode=OceanBaseMode.ORACLE,
        target_table="users",
        conflict_keys=["id"],
        update_cols=["name"],
    )
    assert "MERGE INTO users" in merge_ora
    assert "WHEN MATCHED THEN UPDATE" in merge_ora
    assert "WHEN NOT MATCHED THEN INSERT" in merge_ora


def test_oceanbase_chinadb_integration() -> None:
    ddl = "CREATE TABLE payments (id BIGSERIAL PRIMARY KEY, amount NUMERIC(10, 2));"
    res_mysql = lower_chinadb_sql(ddl, target_id="oceanbase-mysql", mode="MYSQL")
    assert "AUTO_INCREMENT" in res_mysql

    res_ora = lower_chinadb_sql(ddl, target_id="oceanbase-oracle", mode="ORACLE")
    assert "NUMBER" in res_ora
    assert "IDENTITY" in res_ora

    trans_res = translate_to_oceanbase(
        "CREATE TABLE accounts (id SERIAL PRIMARY KEY, balance DECIMAL(10, 2));",
        mode="mysql",
    )
    assert trans_res["status"] == "PASSED"
    assert trans_res["state"] == "LOCAL_EMITTED"
    assert "AUTO_INCREMENT" in trans_res["emitted"]
