"""Tests for Dameng (DM8) and openGauss dialect lowering and ChinaDB integration."""

from __future__ import annotations

import pytest

from elmos_sql_dialect.chinadb import (
    DM8_CAPABILITIES,
    OPENGAUSS_CAPABILITIES,
    chinadb_capabilities,
    lower_to_dm8,
    lower_to_opengauss,
    translate_chinadb_ddl,
    translate_to_dm8,
    translate_to_opengauss,
)
from elmos_sql_dialect.dm8_dialect import DM8DialectLowerer
from elmos_sql_dialect.models import ChinaDbDialect
from elmos_sql_dialect.opengauss_dialect import OpenGaussDialectLowerer, OpenGaussMode

# =============================================================================
# DM8 Lowering Tests
# =============================================================================


class TestDM8Lowering:
    """Tests for DM8DialectLowerer."""

    @pytest.fixture
    def lowerer(self) -> DM8DialectLowerer:
        return DM8DialectLowerer()

    def test_dm8_data_type_lowering(self, lowerer: DM8DialectLowerer) -> None:
        """Test PostgreSQL / MySQL / T-SQL data types mapped to DM8."""
        # Postgres serial types
        assert "BIGINT IDENTITY(1, 1)" in lowerer.lower_data_types("id BIGSERIAL PRIMARY KEY")
        assert "INT IDENTITY(1, 1)" in lowerer.lower_data_types("id SERIAL PRIMARY KEY")
        assert "IDENTITY(1, 1)" in lowerer.lower_data_types("id INT GENERATED ALWAYS AS IDENTITY")
        assert "IDENTITY(1, 1)" in lowerer.lower_data_types("id INT GENERATED BY DEFAULT AS IDENTITY")

        # MySQL AUTO_INCREMENT
        assert "IDENTITY(1, 1)" in lowerer.lower_data_types("id INT AUTO_INCREMENT PRIMARY KEY")

        # Boolean -> BIT
        assert "is_active BIT" in lowerer.lower_data_types("is_active BOOLEAN")
        assert "is_active BIT" in lowerer.lower_data_types("is_active BOOL")

        # Text -> CLOB
        assert "bio CLOB" in lowerer.lower_data_types("bio TEXT")
        assert "doc CLOB" in lowerer.lower_data_types("doc LONGTEXT")
        assert "doc CLOB" in lowerer.lower_data_types("doc MEDIUMTEXT")

        # Bytea / Blob -> BLOB
        assert "avatar BLOB" in lowerer.lower_data_types("avatar BYTEA")
        assert "data BLOB" in lowerer.lower_data_types("data LONGBLOB")

        # Timestamps and UUID
        assert "TIMESTAMP WITH TIME ZONE" in lowerer.lower_data_types("created_at TIMESTAMPTZ")
        assert "VARCHAR(36)" in lowerer.lower_data_types("token UUID")

        # JSON/JSONB -> CLOB
        assert "payload CLOB" in lowerer.lower_data_types("payload JSON")
        assert "payload CLOB" in lowerer.lower_data_types("payload JSONB")

    def test_dm8_constraints_lowering(self, lowerer: DM8DialectLowerer) -> None:
        """Test DM8 table constraints preservation."""
        ddl = (
            "CREATE TABLE order_items (\n"
            "  id SERIAL PRIMARY KEY,\n"
            "  order_id INT REFERENCES orders(id) ON DELETE CASCADE,\n"
            "  sku VARCHAR(50) NOT NULL,\n"
            "  quantity INT NOT NULL,\n"
            "  price NUMERIC(10, 2) NOT NULL,\n"
            "  CONSTRAINT uq_order_sku UNIQUE (order_id, sku),\n"
            "  CONSTRAINT chk_qty CHECK (quantity > 0)\n"
            ");"
        )
        lowered = lowerer.lower_ddl(ddl)
        assert "PRIMARY KEY" in lowered
        assert "REFERENCES orders(id) ON DELETE CASCADE" in lowered
        assert "UNIQUE (order_id, sku)" in lowered
        assert "CHECK (quantity > 0)" in lowered
        assert "INT IDENTITY(1, 1)" in lowered

    def test_dm8_sequence_lowering(self, lowerer: DM8DialectLowerer) -> None:
        """Test DM8 sequence creation and NEXTVAL semantics."""
        # Sequence creation
        seq_ddl = "CREATE SEQUENCE seq_orders START WITH 1 INCREMENT BY 1;"
        assert lowerer.lower_sequence(seq_ddl) == seq_ddl

        # nextval('seq_orders') -> seq_orders.NEXTVAL
        query = "SELECT nextval('seq_orders')"
        lowered = lowerer.lower_sequence(query)
        assert "seq_orders.NEXTVAL" in lowered

        # seq_orders.nextval -> seq_orders.NEXTVAL
        query2 = "SELECT seq_orders.nextval FROM DUAL"
        assert "seq_orders.NEXTVAL" in lowerer.lower_sequence(query2)

    def test_dm8_query_functions(self, lowerer: DM8DialectLowerer) -> None:
        """Test DM8 function lowering: NOW -> SYSDATE, IFNULL -> NVL, ILIKE, etc."""
        # NOW() -> SYSDATE, CURRENT_TIMESTAMP -> SYSTIMESTAMP
        assert "SYSDATE" in lowerer.lower_functions("SELECT NOW()")
        assert "SYSTIMESTAMP" in lowerer.lower_functions("SELECT CURRENT_TIMESTAMP")

        # IFNULL / ISNULL -> NVL
        assert "NVL(name, 'default')" in lowerer.lower_functions("SELECT IFNULL(name, 'default')")
        assert "NVL(name, 'default')" in lowerer.lower_functions("SELECT ISNULL(name, 'default')")

        # SUBSTRING -> SUBSTR
        assert "SUBSTR(name, 1, 5)" in lowerer.lower_functions("SELECT SUBSTRING(name FROM 1 FOR 5)")
        assert "SUBSTR(name, 1, 5)" in lowerer.lower_functions("SELECT SUBSTRING(name, 1, 5)")

        # UUID generators -> RAWTOHEX(SYS_GUID())
        assert "RAWTOHEX(SYS_GUID())" in lowerer.lower_functions("SELECT GEN_RANDOM_UUID()")
        assert "RAWTOHEX(SYS_GUID())" in lowerer.lower_functions("SELECT UUID()")
        assert "RAWTOHEX(SYS_GUID())" in lowerer.lower_functions("SELECT NEWID()")

        # ILIKE with default regex_like strategy
        res_default = lowerer.lower_functions("SELECT * FROM t WHERE name ILIKE '%test%'")
        assert "REGEXP_LIKE(name, '%test%', 'i')" in res_default

        # ILIKE with lower strategy
        lower_lowerer = DM8DialectLowerer(ilike_strategy="lower")
        res_lower = lower_lowerer.lower_functions("SELECT * FROM t WHERE name ILIKE '%test%'")
        assert "LOWER(name) LIKE LOWER('%test%')" in res_lower

    def test_dm8_limit_offset_and_dual(self, lowerer: DM8DialectLowerer) -> None:
        """Test LIMIT/OFFSET and FROM DUAL assurance."""
        # ANSI OFFSET ... FETCH ... -> LIMIT ... OFFSET ...
        q1 = "SELECT * FROM orders ORDER BY id OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY"
        assert "LIMIT 10 OFFSET 20" in lowerer.lower_limit_offset(q1)

        # MySQL LIMIT offset, count -> LIMIT count OFFSET offset
        q2 = "SELECT * FROM orders LIMIT 20, 10"
        assert "LIMIT 10 OFFSET 20" in lowerer.lower_limit_offset(q2)

        # T-SQL TOP n
        q3 = "SELECT TOP 10 id, name FROM users"
        assert "LIMIT 10" in lowerer.lower_limit_offset(q3)

        # FROM DUAL
        assert lowerer.ensure_dual_table("SELECT 1") == "SELECT 1 FROM DUAL"
        assert lowerer.ensure_dual_table("SELECT SYSDATE;") == "SELECT SYSDATE FROM DUAL;"
        assert lowerer.ensure_dual_table("SELECT * FROM users") == "SELECT * FROM users"

        # ROWNUM pagination wrapper
        paged = lowerer.wrap_with_rownum("SELECT id FROM orders", 10, 20)
        assert "ROWNUM <= 30" in paged
        assert "rnum > 20" in paged

    def test_dm8_upsert_mysql_on_duplicate(self, lowerer: DM8DialectLowerer) -> None:
        """Test MySQL ON DUPLICATE KEY UPDATE lowering to MERGE INTO."""
        mysql_sql = (
            "INSERT INTO accounts (id, balance, updated_at) "
            "VALUES (1001, 500.0, NOW()) "
            "ON DUPLICATE KEY UPDATE balance = 500.0, updated_at = NOW();"
        )
        merged = lowerer.lower_upsert(mysql_sql)
        assert merged.startswith("MERGE INTO accounts USING")
        assert "ON (accounts.id = src.id)" in merged
        assert "WHEN MATCHED THEN UPDATE SET" in merged
        assert "balance = 500.0" in merged
        assert "WHEN NOT MATCHED THEN INSERT" in merged

    def test_dm8_upsert_postgres_on_conflict_do_update(self, lowerer: DM8DialectLowerer) -> None:
        """Test PostgreSQL ON CONFLICT DO UPDATE lowering to MERGE INTO."""
        pg_sql = (
            "INSERT INTO products (sku, title, price) "
            "VALUES ('SKU-001', 'Keyboard', 99.99) "
            "ON CONFLICT (sku) DO UPDATE SET title = EXCLUDED.title, price = EXCLUDED.price;"
        )
        merged = lowerer.lower_upsert(pg_sql)
        assert merged.startswith("MERGE INTO products USING")
        assert "ON (products.sku = src.sku)" in merged
        assert "WHEN MATCHED THEN UPDATE SET title = src.title, price = src.price" in merged
        assert "WHEN NOT MATCHED THEN INSERT" in merged

    def test_dm8_upsert_postgres_on_conflict_do_nothing(self, lowerer: DM8DialectLowerer) -> None:
        """Test PostgreSQL ON CONFLICT DO NOTHING lowering to MERGE INTO."""
        pg_sql = (
            "INSERT INTO tags (id, name) VALUES (1, 'tech') "
            "ON CONFLICT (id) DO NOTHING;"
        )
        merged = lowerer.lower_upsert(pg_sql)
        assert merged.startswith("MERGE INTO tags USING")
        assert "ON (tags.id = src.id)" in merged
        assert "WHEN MATCHED" not in merged
        assert "WHEN NOT MATCHED THEN INSERT" in merged


# =============================================================================
# openGauss Lowering Tests
# =============================================================================


class TestOpenGaussLowering:
    """Tests for OpenGaussDialectLowerer."""

    @pytest.fixture
    def lowerer(self) -> OpenGaussDialectLowerer:
        return OpenGaussDialectLowerer()

    def test_opengauss_create_table_hash_distribution(self, lowerer: OpenGaussDialectLowerer) -> None:
        """Test openGauss table creation with DISTRIBUTE BY HASH and ORIENTATION."""
        # Table with single primary key
        ddl1 = "CREATE TABLE users (user_id INT PRIMARY KEY, username VARCHAR(50));"
        lowered1 = lowerer.lower_create_table(ddl1)
        assert "WITH (ORIENTATION = ROW)" in lowered1
        assert "DISTRIBUTE BY HASH(user_id)" in lowered1

        # Table without primary key -> uses first column
        ddl2 = "CREATE TABLE logs (msg TEXT, created_at TIMESTAMP);"
        lowered2 = lowerer.lower_create_table(ddl2)
        assert "DISTRIBUTE BY HASH(msg)" in lowered2

        # Explicit distribution column and COLUMN orientation
        ddl3 = "CREATE TABLE metrics (tenant_id VARCHAR(64), metric_val FLOAT);"
        lowered3 = lowerer.lower_create_table(
            ddl3,
            orientation="COLUMN",
            distribute_column="tenant_id",
        )
        assert "WITH (ORIENTATION = COLUMN)" in lowered3
        assert "DISTRIBUTE BY HASH(tenant_id)" in lowered3

    def test_opengauss_data_types(self, lowerer: OpenGaussDialectLowerer) -> None:
        """Test openGauss data type conversions from other engines."""
        # MySQL conversions
        assert "SERIAL" in lowerer.lower_data_types("id INT AUTO_INCREMENT PRIMARY KEY")
        assert "BIGSERIAL" in lowerer.lower_data_types("id BIGINT AUTO_INCREMENT PRIMARY KEY")
        assert "TEXT" in lowerer.lower_data_types("content LONGTEXT")
        assert "TIMESTAMP" in lowerer.lower_data_types("ts DATETIME")
        assert "SMALLINT" in lowerer.lower_data_types("flags TINYINT")

        # Oracle conversions
        assert "NUMERIC" in lowerer.lower_data_types("val NUMBER")
        assert "NUMERIC(10, 2)" in lowerer.lower_data_types("amount NUMBER(10, 2)")
        assert "VARCHAR(100)" in lowerer.lower_data_types("name VARCHAR2(100)")
        assert "TEXT" in lowerer.lower_data_types("doc CLOB")
        assert "BYTEA" in lowerer.lower_data_types("raw_data BLOB")

        # T-SQL conversions
        assert "UUID" in lowerer.lower_data_types("guid UNIQUEIDENTIFIER")
        assert "SERIAL" in lowerer.lower_data_types("id INT IDENTITY(1, 1)")

    def test_opengauss_modes(self) -> None:
        """Test openGauss compatibility modes: PG, A (Oracle), B (MySQL)."""
        # Mode PG (PostgreSQL)
        lowerer_pg = OpenGaussDialectLowerer(mode=OpenGaussMode.PG)
        q_pg = "SELECT IFNULL(col, 'def'), NOW() FROM t"
        lowered_pg = lowerer_pg.lower_query(q_pg)
        assert "COALESCE" in lowered_pg
        assert "CURRENT_TIMESTAMP" in lowered_pg

        # Mode B (MySQL)
        lowerer_b = OpenGaussDialectLowerer(mode=OpenGaussMode.B)
        q_b = "SELECT IFNULL(col, 'def'), NOW() FROM t LIMIT 10, 20"
        lowered_b = lowerer_b.lower_query(q_b)
        assert "LIMIT 20 OFFSET 10" in lowered_b

        # Mode A (Oracle)
        lowerer_a = OpenGaussDialectLowerer(mode=OpenGaussMode.A)
        q_a = "SELECT NVL(col, 'def') FROM t"
        assert "NVL" in lowerer_a.lower_query(q_a)

    def test_opengauss_routine_lowering(self, lowerer: OpenGaussDialectLowerer) -> None:
        """Test openGauss FUNCTION and PROCEDURE envelope lowering."""
        # Function without $$
        func_sql = (
            "CREATE OR REPLACE FUNCTION get_user_count(tenant VARCHAR)\n"
            "RETURNS INTEGER AS\n"
            "BEGIN\n"
            "  RETURN 42;\n"
            "END;\n"
        )
        lowered_func = lowerer.lower_routine(func_sql, routine_type="FUNCTION")
        assert "$$" in lowered_func
        assert "LANGUAGE plpgsql;" in lowered_func

        # Procedure
        proc_sql = (
            "CREATE OR REPLACE PROCEDURE purge_old_records(retention_days INT)\n"
            "AS\n"
            "BEGIN\n"
            "  DELETE FROM logs WHERE created_at < NOW() - retention_days;\n"
            "END;\n"
        )
        lowered_proc = lowerer.lower_routine(proc_sql, routine_type="PROCEDURE")
        assert "$$" in lowered_proc
        assert "LANGUAGE plpgsql;" in lowered_proc


# =============================================================================
# ChinaDB Integration Tests
# =============================================================================


class TestChinaDBIntegration:
    """Tests for chinadb.py DM8 and openGauss integration."""

    def test_translate_chinadb_ddl_dm8(self) -> None:
        """Test translate_chinadb_ddl for DM8."""
        ddl = "CREATE TABLE customers (id SERIAL PRIMARY KEY, is_vip BOOLEAN, notes TEXT);"
        translated = translate_chinadb_ddl(ddl, "postgres", "dm8", "native")
        assert "INT IDENTITY(1, 1)" in translated["emitted"]
        assert "BIT" in translated["emitted"]
        assert "CLOB" in translated["emitted"]

    def test_translate_chinadb_ddl_opengauss(self) -> None:
        """Test translate_chinadb_ddl for openGauss."""
        ddl = "CREATE TABLE customers (id SERIAL PRIMARY KEY, is_vip BOOLEAN, notes TEXT);"
        translated = translate_chinadb_ddl(ddl, "postgres", "opengauss", "native")
        assert "DISTRIBUTE BY HASH(id)" in translated["emitted"]
        assert "WITH (ORIENTATION = ROW)" in translated["emitted"]

    def test_convenience_functions(self) -> None:
        """Test translate_to_dm8, translate_to_opengauss, lower_to_dm8, lower_to_opengauss."""
        ddl = "CREATE TABLE items (id SERIAL PRIMARY KEY, descr TEXT);"

        # DDL convenience functions
        dm8_ddl = translate_to_dm8(ddl)
        assert "INT IDENTITY(1, 1)" in dm8_ddl["emitted"]
        assert "CLOB" in dm8_ddl["emitted"]

        og_ddl = translate_to_opengauss(ddl)
        assert "DISTRIBUTE BY HASH(id)" in og_ddl["emitted"]

        # Query convenience functions
        q = "SELECT IFNULL(a, b), NOW()"
        dm8_q = lower_to_dm8(q, kind="query")
        assert "NVL(a, b)" in dm8_q
        assert "SYSDATE" in dm8_q
        assert "FROM DUAL" in dm8_q

        og_q = lower_to_opengauss(q, kind="query", mode=OpenGaussMode.PG)
        assert "COALESCE(a, b)" in og_q

    def test_capabilities_and_models(self) -> None:
        """Test ChinaDbDialect enum and capability sets."""
        assert ChinaDbDialect.DM8.value == "dm8"
        assert ChinaDbDialect.OPENGAUSS.value == "opengauss"

        assert "MERGE_UPSERT" in DM8_CAPABILITIES
        assert "CLOB_TEXT" in DM8_CAPABILITIES
        assert "IDENTITY_COLUMNS" in DM8_CAPABILITIES
        assert "HASH_DISTRIBUTION" in OPENGAUSS_CAPABILITIES
        assert "COMPATIBILITY_MODES" in OPENGAUSS_CAPABILITIES
        assert "ROW_ORIENTATION" in OPENGAUSS_CAPABILITIES
        assert "COLUMN_ORIENTATION" in OPENGAUSS_CAPABILITIES
        assert "PLPGSQL_ROUTINES" in OPENGAUSS_CAPABILITIES

        caps = chinadb_capabilities()
        targets = {t["id"]: t for t in caps["targets"]}
        assert "dm8" in targets
        assert "opengauss" in targets
        assert targets["dm8"]["implementationStatus"] == "LOCAL_ADAPTER"
        assert targets["opengauss"]["implementationStatus"] == "LOCAL_ADAPTER"


# =============================================================================
# Adversarial & Zero-Regex AST Proof Tests
# =============================================================================


class TestAdversarialASTPreservation:
    """Rigorous tests proving AST transformation is zero-regex and keyword-safe."""

    def test_dm8_keyword_column_names_and_literals(self) -> None:
        """Verify column names containing keywords and string literals are NOT corrupted."""
        lowerer = DM8DialectLowerer()
        ddl = (
            "CREATE TABLE audit_logs (\n"
            "  id SERIAL PRIMARY KEY,\n"
            "  serial_number VARCHAR(100) NOT NULL,\n"
            "  text_content VARCHAR(255),\n"
            "  auto_increment_val VARCHAR(50),\n"
            "  is_active_bit INT DEFAULT 1,\n"
            "  clob_identifier VARCHAR(64)\n"
            ");"
        )
        lowered = lowerer.lower_ddl(ddl)
        assert "serial_number VARCHAR(100)" in lowered
        assert "text_content VARCHAR(255)" in lowered
        assert "auto_increment_val VARCHAR(50)" in lowered
        assert "is_active_bit INT" in lowered
        assert "clob_identifier VARCHAR(64)" in lowered

        # String literal protection: keywords in strings must remain untouched
        q = "SELECT * FROM t WHERE note = 'AUTO_INCREMENT failed for SERIAL text';"
        lowered_q = lowerer.lower_functions(q)
        assert "'AUTO_INCREMENT failed for SERIAL text'" in lowered_q

    def test_opengauss_keyword_column_names_and_literals(self) -> None:
        """Verify openGauss lowerer preserves keyword column names and string literals."""
        lowerer = OpenGaussDialectLowerer()
        ddl = (
            "CREATE TABLE sensor_data (\n"
            "  id INT AUTO_INCREMENT PRIMARY KEY,\n"
            "  serial_number VARCHAR(100),\n"
            "  text_payload VARCHAR(200),\n"
            "  blob_hash VARCHAR(64),\n"
            "  number_of_retries INT\n"
            ");"
        )
        lowered = lowerer.lower_ddl(ddl, source_dialect="mysql")
        assert "serial_number VARCHAR(100)" in lowered
        assert "text_payload VARCHAR(200)" in lowered
        assert "blob_hash VARCHAR(64)" in lowered
        assert "number_of_retries INT" in lowered
        assert "DISTRIBUTE BY HASH(id)" in lowered

        # String literal with SQL keywords
        q = "SELECT * FROM t WHERE status = 'CHECK NOW() AND SYSDATE: NVL(a, b)';"
        lowered_q = lowerer.lower_query(q, mode=OpenGaussMode.PG)
        assert "'CHECK NOW() AND SYSDATE: NVL(a, b)'" in lowered_q

