"""Real, executed (not just reviewed) tests for certified-ddl-v1.

Every direction pair among the four certified dialects is exercised at least
once with a realistic CREATE TABLE (types, NOT NULL, DEFAULT, PRIMARY KEY,
UNIQUE, FOREIGN KEY with ON DELETE/ON UPDATE, CHECK, and an AUTO_INCREMENT/
IDENTITY column -- the exact construct that a naive `sqlglot.transpile(...)`
call gets wrong for several of these pairs, see `dialects.py`'s docstring).
Negative cases prove certified-ddl-v1 fails closed for out-of-scope SQL
instead of silently mistranslating it.
"""
from __future__ import annotations

import itertools

import pytest

from elmos_sql_dialect.engine import translate_ddl
from elmos_sql_dialect.models import Dialect, RouteError

ALL_DIALECTS = [d.value for d in Dialect]
ALL_DIRECTION_PAIRS = [(s, t) for s, t in itertools.permutations(ALL_DIALECTS, 2)]

REALISTIC_DDL_BY_SOURCE = {
    "mysql": """
        CREATE TABLE customers (
            id INT AUTO_INCREMENT PRIMARY KEY,
            email VARCHAR(255) NOT NULL UNIQUE,
            balance DECIMAL(10,2) DEFAULT 0,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            org_id INT NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            CONSTRAINT fk_org FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT chk_balance CHECK (balance >= 0)
        )
    """,
    "postgres": """
        CREATE TABLE customers (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(255) NOT NULL UNIQUE,
            balance NUMERIC(10,2) DEFAULT 0,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            org_id INTEGER NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            CONSTRAINT fk_org FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT chk_balance CHECK (balance >= 0)
        )
    """,
    "tsql": """
        CREATE TABLE customers (
            id INT IDENTITY(1,1) PRIMARY KEY,
            email VARCHAR(255) NOT NULL UNIQUE,
            balance DECIMAL(10,2) DEFAULT 0,
            created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
            org_id INT NOT NULL,
            active BIT NOT NULL DEFAULT 1,
            CONSTRAINT fk_org FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE NO ACTION,
            CONSTRAINT chk_balance CHECK (balance >= 0)
        )
    """,
    "oracle": """
        CREATE TABLE customers (
            id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR2(255) NOT NULL UNIQUE,
            balance NUMBER(10,2) DEFAULT 0,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            org_id NUMBER(10) NOT NULL,
            active NUMBER(1) NOT NULL DEFAULT 1,
            CONSTRAINT fk_org FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
            CONSTRAINT chk_balance CHECK (balance >= 0)
        )
    """,
}


@pytest.mark.parametrize("source,target", ALL_DIRECTION_PAIRS)
def test_realistic_table_translates_and_round_trips_for_every_direction_pair(source: str, target: str) -> None:
    report = translate_ddl(REALISTIC_DDL_BY_SOURCE[source], source, target)
    assert report["status"] == "PASSED", report
    assert report["validation"]["syntaxStatus"] == "PASSED"
    assert report["emitted"] is not None
    # The auto-increment column must never carry another dialect's keyword verbatim --
    # this is exactly the defect reproduced against raw sqlglot.transpile() before this
    # module was written (see dialects.py docstring).
    emitted_upper = report["emitted"].upper()
    if target == "mysql":
        assert "AUTO_INCREMENT" in emitted_upper
        assert "GENERATED BY DEFAULT AS IDENTITY" not in emitted_upper
    elif target == "tsql":
        assert "IDENTITY(1,1)" in emitted_upper or "IDENTITY(1, 1)" in emitted_upper
        assert "AUTO_INCREMENT" not in emitted_upper
    else:  # postgres, oracle
        assert "GENERATED BY DEFAULT AS IDENTITY" in emitted_upper
        assert "AUTO_INCREMENT" not in emitted_upper


def test_source_and_target_must_differ() -> None:
    with pytest.raises(RouteError, match="SOURCE_AND_TARGET_MUST_DIFFER"):
        translate_ddl("CREATE TABLE t (id INT)", "postgres", "postgres")


def test_unsupported_dialect_name_fails_closed_before_parsing() -> None:
    with pytest.raises(RouteError, match="UNSUPPORTED_DIALECT"):
        translate_ddl("CREATE TABLE t (id INT)", "snowflake", "postgres")


@pytest.mark.parametrize(
    "name,ddl",
    [
        ("multiple_statements", "CREATE TABLE t (id INT); CREATE TABLE t2 (id INT);"),
        ("alter_table_not_create_table", "ALTER TABLE t ADD COLUMN x INT"),
        ("unsupported_json_type", "CREATE TABLE t (id INT PRIMARY KEY, payload JSON)"),
        ("generated_column", "CREATE TABLE t (id INT PRIMARY KEY, doubled INT GENERATED ALWAYS AS (id * 2) STORED)"),
        ("qualified_table_name", "CREATE TABLE myschema.t (id INT PRIMARY KEY)"),
        ("quoted_identifier", 'CREATE TABLE "My Table" (id INT PRIMARY KEY)'),
        ("check_with_function_call", "CREATE TABLE t (id INT PRIMARY KEY, name VARCHAR(10) CHECK (LENGTH(name) > 0))"),
        ("check_with_nested_boolean", "CREATE TABLE t (id INT PRIMARY KEY, a INT, b INT, CHECK ((a > 0 AND b > 0) OR a = b))"),
        ("default_expression_not_literal", "CREATE TABLE t (id INT PRIMARY KEY, x INT DEFAULT (1 + 1))"),
        ("no_columns_impossible_but_defensive", "CREATE TABLE t ()"),
    ],
)
def test_out_of_scope_ddl_fails_closed_instead_of_guessing(name: str, ddl: str) -> None:
    report = translate_ddl(ddl, "postgres", "mysql")
    assert report["status"] == "BLOCKED", f"{name} should be BLOCKED but was {report['status']}: {report}"
    assert report["reasonCode"] is not None
    assert report["emitted"] is None


def test_check_constraint_with_string_literal_round_trips_quoted_correctly() -> None:
    ddl = "CREATE TABLE t (id INT PRIMARY KEY, status VARCHAR(20) NOT NULL, CONSTRAINT chk_status CHECK (status = 'active'))"
    report = translate_ddl(ddl, "postgres", "oracle")
    assert report["status"] == "PASSED", report
    assert "CHECK (status = 'active')" in report["emitted"]


def test_check_constraint_with_or_connector() -> None:
    ddl = "CREATE TABLE t (id INT PRIMARY KEY, a INT, CHECK (a = 1 OR a = 2))"
    report = translate_ddl(ddl, "postgres", "mysql")
    assert report["status"] == "PASSED", report
    assert "a = 1 OR a = 2" in report["emitted"]


def test_unnamed_table_level_unique_and_foreign_key_without_constraint_keyword() -> None:
    """sqlglot represents `UNIQUE (...)` / `FOREIGN KEY (...) REFERENCES ...`
    written without a leading `CONSTRAINT <name>` as bare nodes in the table
    body rather than wrapped in exp.Constraint -- a distinct AST shape from
    the named form covered by REALISTIC_DDL_BY_SOURCE, exercised here directly."""
    ddl = "CREATE TABLE line_items (id INT PRIMARY KEY, sku VARCHAR(20), order_id INT, " \
          "UNIQUE (sku), FOREIGN KEY (order_id) REFERENCES orders (id))"
    report = translate_ddl(ddl, "postgres", "oracle")
    assert report["status"] == "PASSED", report
    assert "UNIQUE (sku)" in report["emitted"]
    assert "FOREIGN KEY (order_id) REFERENCES orders (id)" in report["emitted"]


def test_create_index_translates_across_dialects() -> None:
    ddl = "CREATE UNIQUE INDEX idx_customers_email ON customers (email, org_id)"
    for target in ("mysql", "tsql", "oracle"):
        report = translate_ddl(ddl, "postgres", target, statement_kind="INDEX")
        assert report["status"] == "PASSED", (target, report)
        assert "UNIQUE INDEX idx_customers_email ON customers (email, org_id)" in report["emitted"]


def test_varchar_max_maps_to_canonical_text_and_back_to_varchar_max() -> None:
    ddl = "CREATE TABLE t (id INT PRIMARY KEY, notes VARCHAR(MAX))"
    report = translate_ddl(ddl, "tsql", "postgres")
    assert report["status"] == "PASSED", report
    assert "notes TEXT" in report["emitted"]

    back = translate_ddl(report["emitted"], "postgres", "tsql")
    assert back["status"] == "PASSED", back
    assert "VARCHAR(MAX)" in back["emitted"]


def test_execution_validation_reports_not_attempted_without_dsn() -> None:
    report = translate_ddl("CREATE TABLE t (id INT PRIMARY KEY)", "postgres", "mysql")
    assert report["validation"]["executionStatus"] == "EXECUTION_NOT_ATTEMPTED"


def test_execution_validation_reports_not_available_for_oracle_and_tsql_even_with_dsn() -> None:
    for target in ("oracle", "tsql"):
        report = translate_ddl("CREATE TABLE t (id INT PRIMARY KEY)", "postgres", target, dsn="irrelevant")
        assert report["validation"]["executionStatus"] == "EXECUTION_NOT_AVAILABLE", (target, report)
