package io.elmos.skeleton;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import io.elmos.uir.UirModels;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Clock;
import java.util.*;

import static io.elmos.skeleton.SkeletonModels.*;

/** Plans and emits contract-only target repositories. It never translates a business method body. */
public final class SkeletonGenerationService {
    private final Clock clock; private final BaselineRunner baselineRunner;
    private final ObjectMapper json = new ObjectMapper().findAndRegisterModules().enable(SerializationFeature.INDENT_OUTPUT).enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    public SkeletonGenerationService(Clock clock, BaselineRunner baselineRunner) { this.clock=Objects.requireNonNull(clock); this.baselineRunner=Objects.requireNonNull(baselineRunner); }

    public Result generate(Path requestedWorkspace, UirModels.Dataset uir, UirModels.ConformanceReport uirReport, TargetProfile profile) {
        Path workspace=secure(requestedWorkspace), repository=workspace.resolve("target-repository"); Plan plan=new SkeletonPlanner().plan(uir,uirReport,profile);
        try { Files.createDirectories(repository); List<GeneratedFile> files=emit(repository,plan,uir); Coverage coverage=coverage(plan,uir,files);
            String repoId=SkeletonIds.id("target-repo",uir.manifest().snapshotId(),uir.manifest().uirRunId(),profile.targetProfileId());
            Manifest manifest=new Manifest(repoId,uir.manifest().snapshotId(),uir.manifest().uirRunId(),profile.targetProfileId(),plan.generationId(),plan.projects(),files,
                    files.stream().filter(GeneratedFile::provisional).map(GeneratedFile::path).toList(),List.of(),plan.names().stream().filter(name->!name.collisionStatus().equals("none")).map(NamingMapping::targetFile).toList(),plan.placeholders().size(),coverage,clock.instant());
            writePlan(workspace,plan,manifest); BuildBaseline baseline=Objects.requireNonNull(baselineRunner.validate(repository,plan)); ConformanceReport report=validate(plan,manifest,baseline,uir);
            writeJson(workspace.resolve("reports/build-baseline-report.json"),baseline); writeJson(workspace.resolve("reports/skeleton-conformance-report.json"),report); writeJson(workspace.resolve("reports/skeleton-coverage-report.json"),coverage);
            return new Result(plan,manifest,baseline,report);
        } catch(IOException error){throw new IllegalStateException("SKELETON_GENERATION_FAILED",error);}
    }
    private List<GeneratedFile> emit(Path root,Plan plan,UirModels.Dataset uir)throws IOException{List<GeneratedFile> files=new ArrayList<>(); Map<String,UirModels.Declaration> declarations=new HashMap<>();for(UirModels.Declaration value:payloads(uir,UirModels.Declaration.class))declarations.put(value.declarationId(),value);
        emitFile(root,"README.md","# Generated migration skeleton\n\nBusiness method bodies are intentionally pending. Generation: `"+plan.generationId()+"`\n", "metadata",List.of(),false,files);
        emitFile(root,".gitignore","build/\ntarget/\nbin/\nobj/\nnode_modules/\n.venv/\n", "metadata",List.of(),false,files);
        emitBuild(root,plan,files);
        for(NamingMapping name:plan.names()){UirModels.Declaration declaration=declarations.get(name.sourceDeclarationId());if(declaration==null)continue;String content=source(plan.profile(),name,declaration,plan.placeholders().stream().filter(value->value.declarationId().equals(declaration.declarationId())).findFirst().orElse(null));emitFile(root,name.targetFile(),content,"source",List.of(name.targetDeclarationId()),declaration.bodyRegionId()!=null,files);}
        for(TargetProject project:plan.projects())emitFile(root,"tests/"+safe(project.targetProjectId())+"/MIGRATION_TESTS_PENDING.md","# Pending tests\n\nTests must remain pending until translated implementations and obligation assertions exist.\n","test-placeholder",List.of(),true,files);
        return files.stream().sorted(Comparator.comparing(GeneratedFile::path)).toList();}
    private void emitBuild(Path root,Plan plan,List<GeneratedFile> files)throws IOException{TargetProfile p=plan.profile();switch(p.language()){case"java"->emitFile(root,"pom.xml","<project xmlns=\"http://maven.apache.org/POM/4.0.0\"><modelVersion>4.0.0</modelVersion><groupId>generated</groupId><artifactId>migration-skeleton</artifactId><version>0.0.0-SNAPSHOT</version><properties><maven.compiler.release>"+xml(p.resolvedRuntimeVersion())+"</maven.compiler.release></properties></project>\n","build",List.of(),false,files);case"python"->emitFile(root,"pyproject.toml","[project]\nname = \"migration-skeleton\"\nversion = \"0.0.0\"\nrequires-python = \">="+plain(p.resolvedRuntimeVersion())+"\"\n\n[tool.pytest.ini_options]\ntestpaths = [\"tests\"]\n","build",List.of(),false,files);case"csharp"->emitFile(root,"MigrationSkeleton.csproj","<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>"+xml(p.resolvedRuntimeVersion())+"</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup></Project>\n","build",List.of(),false,files);default->{emitFile(root,"package.json","{\n  \"name\": \"migration-skeleton\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\"build\": \"tsc --noEmit\"}\n}\n","build",List.of(),false,files);emitFile(root,"tsconfig.json","{\"compilerOptions\":{\"strict\":true,\"noEmit\":true,\"target\":\"ES"+plain(p.resolvedRuntimeVersion())+"\"},\"include\":[\"src/**/*.ts\"]}\n","build",List.of(),false,files);}}}
    private String source(TargetProfile profile,NamingMapping name,UirModels.Declaration declaration,Placeholder placeholder){String q=name.targetQualifiedName(),simple=q.substring(q.lastIndexOf('.')+1),namespace=q.contains(".")?q.substring(0,q.lastIndexOf('.')):"Generated";boolean pending=placeholder!=null;String marker="MIGRATION_BODY_PENDING: "+declaration.declarationId(),begin="<generated-body id=\""+name.targetDeclarationId()+"\">",end="</generated-body>";return switch(profile.language()){case"java"->"package "+namespace.toLowerCase(Locale.ROOT)+";\n\n// <generated id=\""+name.targetDeclarationId()+"\">\npublic final class "+simple+" {"+(pending?"\n  // "+begin+"\n  public Object contract() { throw new UnsupportedOperationException(\""+marker+"\"); }\n  // "+end+"\n":"")+"}\n// </generated>\n";case"csharp"->"namespace "+namespace+";\n\n// <generated id=\""+name.targetDeclarationId()+"\">\npublic sealed class "+simple+"\n{"+(pending?"\n    // "+begin+"\n    public object Contract() => throw new System.NotImplementedException(\""+marker+"\");\n    // "+end+"\n":"\n")+"}\n// </generated>\n";case"python"->"# <generated id=\""+name.targetDeclarationId()+"\">\nclass "+pascal(simple)+":"+(pending?"\n    # "+begin+"\n    def contract(self) -> object:\n        raise NotImplementedError(\""+marker+"\")\n    # "+end+"\n":"\n    pass\n")+"# </generated>\n";default->"// <generated id=\""+name.targetDeclarationId()+"\">\nexport class "+simple+" {"+(pending?"\n  // "+begin+"\n  contract(): unknown { throw new Error(\""+marker+"\"); }\n  // "+end+"\n":"")+"}\n// </generated>\n";};}
    private void writePlan(Path workspace,Plan plan,Manifest manifest)throws IOException{Files.createDirectories(workspace.resolve("target-plan"));Files.createDirectories(workspace.resolve("mappings"));Files.createDirectories(workspace.resolve("reports"));for(String log:List.of("generation","formatting","build","validation"))Files.createDirectories(workspace.resolve("logs").resolve(log));writeJson(workspace.resolve("target-plan/target-requirement-profile.json"),plan.profile());writeJson(workspace.resolve("target-plan/target-stack-decisions.json"),plan.stackDecisions());writeJson(workspace.resolve("target-plan/migration-mode-plan.json"),plan.modules());writeJson(workspace.resolve("target-plan/module-mapping.json"),plan.modules());writeJson(workspace.resolve("target-plan/naming-map.json"),plan.names());writeJson(workspace.resolve("target-plan/target-skeleton-manifest.json"),manifest);writeJson(workspace.resolve("mappings/source-target-callables.jsonl"),plan.mappings());writeJson(workspace.resolve("mappings/target-placeholders.jsonl"),plan.placeholders());}
    private ConformanceReport validate(Plan plan,Manifest manifest,BuildBaseline baseline,UirModels.Dataset uir){List<String> errors=new ArrayList<>(baseline.errors());if(plan.names().stream().anyMatch(name->!name.collisionStatus().equals("none")))errors.add("blocking-name-collision");if(plan.mappings().size()<plan.names().size())errors.add("source-target-mapping-gap");boolean build=baseline.buildModelLoad()==Status.PASSED&&baseline.syntaxCompile()==Status.PASSED&&baseline.testDiscovery()==Status.PASSED;List<ModuleGate>gates=plan.modules().stream().map(module->new ModuleGate(module.targetModuleId(),build&&errors.isEmpty()?"S-D":manifest.coverage().targetTypeSkeletonRate()>=.98?"S-B":"S-A",build&&errors.isEmpty(),build&&errors.isEmpty(),errors.isEmpty()?List.of():List.copyOf(errors))).toList();boolean eligible=!gates.isEmpty()&&gates.stream().allMatch(ModuleGate::eligibleForBodyGeneration);return new ConformanceReport(4,eligible?"passed":"blocked",manifest.targetRepositoryId(),gates,manifest.coverage(),baseline,payloads(uir,UirModels.Obligation.class).stream().filter(value->!Set.of("verified","waived").contains(value.status())).map(UirModels.Obligation::obligationId).toList(),errors,eligible);}
    private Coverage coverage(Plan plan,UirModels.Dataset uir,List<GeneratedFile>files){long modules=payloads(uir,UirModels.Module.class).size(),declarations=payloads(uir,UirModels.Declaration.class).size(),types=payloads(uir,UirModels.Declaration.class).stream().filter(value->Set.of("type","class","interface","struct","record","enum").contains(value.kind())).count(),publicApi=payloads(uir,UirModels.Declaration.class).stream().filter(value->"public".equals(value.visibility())).count();long mapped=plan.mappings().size(),generated=files.stream().flatMap(value->value.targetDeclarationIds().stream()).distinct().count();return new Coverage(rate(plan.modules().size(),modules),rate(plan.projects().size(),plan.modules().size()),rate(generated,Math.max(1,types)),rate(mapped,declarations),rate(plan.names().stream().filter(name->payloads(uir,UirModels.Declaration.class).stream().anyMatch(d->d.declarationId().equals(name.sourceDeclarationId())&&"public".equals(d.visibility()))).count(),publicApi),rate(plan.names().size(),declarations),1,1,0);}
    private void emitFile(Path root,String relative,String content,String kind,List<String>ids,boolean provisional,List<GeneratedFile>files)throws IOException{Path target=root.resolve(relative).normalize();if(!target.startsWith(root))throw new SecurityException("TARGET_PATH_ESCAPE");byte[]bytes=content.getBytes(StandardCharsets.UTF_8);if(Files.exists(target,LinkOption.NOFOLLOW_LINKS)){if(Files.isSymbolicLink(target)||!Arrays.equals(Files.readAllBytes(target),bytes))throw new IllegalStateException("MANUAL_FILE_CONFLICT:"+relative);}else{Files.createDirectories(target.getParent());Path temp=Files.createTempFile(target.getParent(),target.getFileName().toString(),".tmp");try{Files.write(temp,bytes);Files.move(temp,target,StandardCopyOption.ATOMIC_MOVE);}finally{Files.deleteIfExists(temp);}}files.add(new GeneratedFile(relative,SkeletonIds.hash(bytes),kind,ids,provisional,true));}
    private void writeJson(Path path,Object value)throws IOException{byte[]bytes=json.writeValueAsBytes(value);Files.createDirectories(path.getParent());Path temp=Files.createTempFile(path.getParent(),path.getFileName().toString(),".tmp");try{Files.write(temp,bytes);Files.move(temp,path,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}finally{Files.deleteIfExists(temp);}}
    private static Path secure(Path requested){try{Path path=requested.toAbsolutePath().normalize();if(Files.exists(path,LinkOption.NOFOLLOW_LINKS)&&Files.isSymbolicLink(path))throw new SecurityException("SKELETON_WORKSPACE_SYMLINK");Files.createDirectories(path);return path.toRealPath(LinkOption.NOFOLLOW_LINKS);}catch(IOException e){throw new IllegalArgumentException("SKELETON_WORKSPACE_UNAVAILABLE",e);}}
    private static String safe(String value){return value.replaceAll("[^A-Za-z0-9._-]","-");}private static String plain(String value){if(!value.matches("[A-Za-z0-9._-]+"))throw new IllegalArgumentException("TARGET_VERSION_UNSAFE");return value;}private static String xml(String value){return plain(value);}private static String pascal(String value){return Character.toUpperCase(value.charAt(0))+value.substring(1);}private static double rate(long n,long d){return d==0?1:Math.min(1,Math.round(n*100000d/d)/100000d);}private static<T>List<T>payloads(UirModels.Dataset d,Class<T>t){return d.entities().stream().map(UirModels.Entity::payload).filter(t::isInstance).map(t::cast).toList();}
}
