using Elmos.Dotnet.Application;
using Elmos.Dotnet.AspNet;
using Elmos.Dotnet.Contracts;
using Elmos.Dotnet.Domain;
using Elmos.Dotnet.Ef;
using Elmos.Dotnet.Infrastructure;
using Elmos.Dotnet.MSBuild;
using Elmos.Dotnet.ProjectSystem;
using Elmos.Dotnet.Roslyn;
using Elmos.Dotnet.Validation;
using Elmos.Dotnet.Wcf;
using Xunit;

namespace Elmos.Dotnet.Engine.Tests;

public sealed class Batch11Tests : IDisposable
{
    private readonly string root = Path.Combine(Path.GetTempPath(), "elmos-dotnet-tests", Guid.NewGuid().ToString("N"));
    public Batch11Tests() => Directory.CreateDirectory(root);
    public void Dispose() => Directory.Delete(root, true);

    [Fact]
    public void CapabilitiesDeclareSecondEngineWithoutControlPlaneResponsibilities()
    {
        var capabilities = CapabilityManifest.Current;
        Assert.Equal("ELMOS_DOTNET", capabilities.Engine);
        Assert.Contains("C_SHARP", capabilities.Languages);
        Assert.Contains("VISUAL_BASIC_INVENTORY", capabilities.Languages);
        Assert.Equal(3, capabilities.RunnerProfiles.Count);
    }

    [Fact]
    public void StaticDiscoveryDoesNotChooseAmongMultipleSolutionsOrHideUnsupportedProjects()
    {
        Write("a.sln", "Microsoft Visual Studio Solution File");
        Write("b.slnx", "<Solution />");
        Write("src/App/App.csproj", LegacyProject("v4.8", "<UsingTask TaskName=\"Unsafe\" AssemblyFile=\"unsafe.dll\" />"));
        Write("src/Vb/Vb.vbproj", "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        var inventory = new SafeSolutionDiscovery().Scan(root, "snapshot-1");
        Assert.True(inventory.PrimarySelectionAmbiguous);
        Assert.Contains("MULTIPLE_SOLUTIONS_AMBIGUOUS", inventory.Findings);
        Assert.Contains("CUSTOM_MSBUILD_TASK", inventory.Findings);
        Assert.Contains("src/Vb/Vb.vbproj", inventory.UnsupportedProjects);
    }

    [Fact]
    public void DiscoveryKeepsAllSolutionAndConditionalConfigurationsSeparate()
    {
        Write("App.sln", "Microsoft Visual Studio Solution File\nGlobal\nGlobalSection(SolutionConfigurationPlatforms) = preSolution\nDebug|Any CPU = Debug|Any CPU\nRelease|x64 = Release|x64\nEndGlobalSection\nEndGlobal");
        Write("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><PropertyGroup Condition=\"'$(Configuration)|$(Platform)' == 'Staging|x86'\"><PlatformTarget>x86</PlatformTarget></PropertyGroup></Project>");
        var project = Assert.Single(new SafeSolutionDiscovery().Scan(root, "snapshot-config").Projects);
        Assert.Contains("Staging", project.Configurations);
        Assert.Contains("Release", project.Configurations);
        Assert.DoesNotContain("x64", project.Configurations);
        Assert.Contains("x86", project.Platforms);
        Assert.Contains("x64", project.Platforms);
    }

    [Fact]
    public void FingerprintKeepsWindowsAndDynamicDependenciesVisible()
    {
        Write("App.csproj", LegacyProject("v4.8", ""));
        Write("Service.cs", "using Microsoft.Win32; class S { void X(){ Registry.GetValue(\"a\",\"b\",null); System.Reflection.Assembly.Load(\"plugin\"); } }");
        var inventory = new SafeSolutionDiscovery().Scan(root, "snapshot-2");
        var fingerprint = new TechnologyFingerprinter().Fingerprint(root, inventory);
        Assert.Contains(fingerprint.Findings, finding => finding.Technology == "WINDOWS_REGISTRY" && finding.Portability == Portability.WindowsOnlySupported);
        Assert.True(fingerprint.HasDynamicDependencies);
        Assert.True(fingerprint.Confidence < 0.9m);
    }

    [Fact]
    public async Task RoslynUsesSemanticOperationsAndProtectsGeneratedCode()
    {
        Write("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        Write("A.cs", "namespace Demo; public class A { public void Run(){ B.Call(); } } public static class B { public static void Call(){} }");
        Write("Generated.g.cs", "// <auto-generated />\nnamespace Demo; public class Generated { }");
        var inventory = new SafeSolutionDiscovery().Scan(root, "snapshot-3");
        var graph = await new RoslynGraphBuilder().BuildAsync(root, inventory, CancellationToken.None);
        Assert.Contains(graph.Edges, edge => edge.Kind == "DIRECT_STATIC_CALL");
        Assert.Contains(graph.Symbols, symbol => symbol.GeneratedCode);
        Assert.DoesNotContain(graph.Symbols, symbol => string.IsNullOrWhiteSpace(symbol.SymbolId));
    }

    [Fact]
    public void ProjectSystemMovesToSdkStyleWhileKeepingNet48AndIsIdempotent()
    {
        var modernizer = new SdkProjectModernizer();
        var first = modernizer.Transform(LegacyProject("v4.8", "<Target Name=\"Custom\" />"), "<packages><package id=\"Newtonsoft.Json\" version=\"13.0.3\" /></packages>");
        var second = modernizer.Transform(first.ProjectXml, null);
        Assert.Contains("Sdk=\"Microsoft.NET.Sdk\"", first.ProjectXml);
        Assert.Contains("<TargetFramework>net48</TargetFramework>", first.ProjectXml);
        Assert.Contains("Newtonsoft.Json", first.ProjectXml);
        Assert.Contains("Target:Custom", first.PreservedCustomizations);
        Assert.Equal(first.ProjectXml, second.ProjectXml);
    }

    [Fact]
    public void PlannerDoesNotRecommendLinuxForRegistryAndUsesSideBySideForWebForms()
    {
        var inventory = new SolutionInventory("snapshot", [], false, [new("p", "App.csproj", ProjectLanguageSupport.CSharpFullSupport, ProjectFormat.LegacyNonSdk, ["v4.8"], ["Debug"], ["AnyCPU"], [], [], [], [])], [], []);
        var fingerprint = new TechnologyFingerprint("f", [new("1", "WINDOWS_REGISTRY", Portability.WindowsOnlySupported, 1m, "x", true), new("2", "ASP_NET_WEB_FORMS", Portability.RequiresRedesign, 1m, "x", true)], false, 1m, []);
        var plan = new ConservativeMigrationPlanner().Plan(inventory, fingerprint, new([], [], [], CompilationState.FullCompilation), "STRATEGIC");
        Assert.Equal(TargetStrategy.IncrementalSideBySide, plan.Recommended.Strategy);
        Assert.Equal("WINDOWS", plan.Recommended.OperatingSystem);
        Assert.Contains(plan.Steps, step => step.StepType == "YARP_SYSTEM_WEB_ADAPTER");
    }

    [Fact]
    public void SpecializedAdvisorsKeepManualAndBehaviorGates()
    {
        var asp = new AspNetMigrationAdvisor().Decide(true, true, true);
        var wcf = new WcfMigrationAdvisor().Decide("CustomBinding", true, true, true);
        var ef = new EfMigrationPlanner().Plan(["Sales", "Inventory"], true);
        Assert.True(asp.UiRewriteRequired);
        Assert.Contains("REMOVE_SYSTEM_WEB_ADAPTERS", asp.ExitDecisions);
        Assert.Equal("PARTIAL", wcf.Automation);
        Assert.True(wcf.ArchitectureApproval);
        Assert.True(ef.RegenerateEdmxModel);
        Assert.True(ef.RebuildMigrationBaseline);
        Assert.Equal(2, ef.ContextSteps.Count);
    }

    [Fact]
    public void ValidatorFailsWhenTestsDisappearOrLinuxTargetFails()
    {
        var decision = new DotnetValidationJudge().Judge(new(800, 240, true, true, true, false, []));
        Assert.Equal(EvidenceStatus.Failed, decision.Status);
        Assert.Contains("TEST_INVENTORY", decision.BlockingReasons);
        Assert.Contains("MIGRATED_LINUX", decision.BlockingReasons);
    }

    [Fact]
    public void EngineJobsAreTenantScopedAndIdempotent()
    {
        Write("App.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        Write("A.cs", "public class A { }");
        var engine = new DotnetEngine(root);
        var first = engine.Scan(new("org-a", "snapshot", ".", "STATIC", "c1", "same"));
        var repeated = engine.Scan(new("org-a", "snapshot", ".", "STATIC", "c2", "same"));
        var otherTenant = engine.Scan(new("org-b", "snapshot", ".", "STATIC", "c3", "same"));
        var conflictingReplay = engine.Scan(new("org-a", "different-snapshot", ".", "STATIC", "c4", "same"));
        Assert.Equal(first.JobId, repeated.JobId);
        Assert.NotEqual(first.JobId, otherTenant.JobId);
        Assert.Equal(JobStatus.Failed, engine.GetJob("org-b", first.JobId).Status);
        Assert.Equal(DotnetErrorCode.PolicyBlocked, conflictingReplay.Error?.ErrorCode);
        Assert.Contains("different immutable inputs", conflictingReplay.Error?.Message);
        Assert.Equal(DotnetErrorCode.PolicyBlocked, engine.Cancel("org-a", first.JobId).Error?.ErrorCode);
    }

    [Fact]
    public void ExecuteIdempotencyFingerprintIncludesBudgetWorkspaceAndPolicy()
    {
        var engine = new DotnetEngine(root);
        var step = new StepDefinition("project", ExecutorType.ProjectSystemTransformation,
            new Dictionary<string, object?> { ["projectXml"] = LegacyProject("v4.8", "") });
        var request = new ExecuteStepRequest("org-a", "run", 1, step, ".", "deadbeef",
            new ExecutionBudget(30, 10, 10_000, 0), new Dictionary<string, object?> { ["mode"] = "safe" },
            "corr", "execute-same");
        Assert.Equal(JobStatus.Succeeded, engine.ExecuteStep(request).Status);
        var conflict = engine.ExecuteStep(request with { ExecutionBudget = new ExecutionBudget(60, 10, 10_000, 0) });
        Assert.Equal(JobStatus.Failed, conflict.Status);
        Assert.Contains("different immutable inputs", conflict.Error?.Message);
    }

    [Fact]
    public void DeprecatedUpgradeAssistantCannotOwnPolicyOrMerge()
    {
        var adapter = Assert.Single(ModernizationToolRegistry.All, item => item.Name == "UPGRADE_ASSISTANT");
        Assert.Equal(ToolAuthority.DeprecatedLegacyAdapter, adapter.Authority);
        Assert.False(adapter.CanSelectTarget);
        Assert.False(adapter.CanAcceptRisk);
        Assert.False(adapter.CanMerge);
    }

    private void Write(string relative, string content)
    {
        var path = Path.Combine(root, relative);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    private static string LegacyProject(string framework, string extra) => $"<Project ToolsVersion=\"15.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\"><PropertyGroup><TargetFrameworkVersion>{framework}</TargetFrameworkVersion></PropertyGroup><ItemGroup><Compile Include=\"A.cs\" /></ItemGroup>{extra}<Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" /></Project>";
}
