// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    label: { type: String, value: "" },
    unit: { type: String, value: "" },
    measure: { type: Object, value: {} },
  },
  data: {},
  methods: {},
});
