// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    label: { type: String, value: "" },
    status: { type: String, value: "" },
    passed: { type: Number, value: 0 },
    total: { type: Number, value: 0 },
    counts: { type: Object, value: {} },
  },
  data: {
    segmentOrder: ["PASSED", "FAILED", "BLOCKED", "NOT_RUN", "UNKNOWN", "NOT_APPLICABLE"],
  },
  methods: {},
});
