package io.elmos.domain;

public enum MigrationState {
    CREATED, REPOSITORY_PREPARING, FINGERPRINTING, BASELINING, PLAN_GENERATING,
    AWAITING_PLAN_APPROVAL, MIGRATING, VALIDATING, AWAITING_FINAL_REVIEW, PUBLISHING, DELIVERED,
    BASELINE_BROKEN, MANUAL_INTERVENTION_REQUIRED, VALIDATION_FAILED, POLICY_BLOCKED,
    BUDGET_EXCEEDED, CANCELLED, FAILED;
    public boolean terminal() { return this == DELIVERED || this == CANCELLED || this == FAILED || this == POLICY_BLOCKED || this == BUDGET_EXCEEDED || this == VALIDATION_FAILED || this == BASELINE_BROKEN; }
}

