spring-boot=4.1.1
spring-framework=7.0.8
spring-security=7.1.0
spring-grpc=1.1.0
spring-graphql=2.0.4
spring-hateoas=3.1.0
spring-integration=7.1.0
spring-kafka=4.1.0
spring-amqp=4.1.0
spring-ldap=4.1.0
spring-session=4.1.0
hibernate-orm=7.4.1.Final
tomcat=11.0.22
java=21
maven=3.9.11
gradle=8.14.3
rewrite-spring=6.35.0
rewrite-maven-plugin=6.44.0
