#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import platform
import re
import socket
import sqlite3
import subprocess
import tempfile
from pathlib import Path
from typing import Any

SOURCE_DDL = """
CREATE TABLE work_orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  created_at TEXT NOT NULL
);
CREATE INDEX idx_work_orders_tenant_created
  ON work_orders (tenant_id, created_at);
""".strip()

TARGET_DDL = """
CREATE TABLE work_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_work_orders_tenant_created
  ON work_orders (tenant_id, created_at);
""".strip()

SEED_ROWS = [
    (1, "tenant-a", 1250, "2026-07-26T01:00:00+00:00"),
    (2, "tenant-a", 500, "2026-07-26T02:00:00+00:00"),
    (3, "tenant-b", 9999, "2026-07-26T03:00:00+00:00"),
]


def digest(value: str) -> str:
    return "sha256:" + hashlib.sha256(value.encode("utf-8")).hexdigest()


def file_digest(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def run(
    command: list[str],
    *,
    cwd: Path,
    input_text: str | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(
        command,
        cwd=cwd,
        input=input_text,
        text=True,
        capture_output=True,
        check=False,
        timeout=120,
    )
    if check and completed.returncode != 0:
        detail = (completed.stderr or completed.stdout)[-4_000:]
        raise RuntimeError(f"COMMAND_FAILED:{command[0]}:{detail}")
    return completed


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as handle:
        handle.bind(("127.0.0.1", 0))
        return int(handle.getsockname()[1])


def postgres_rows(
    psql: Path, port: int, database: str, query: str, cwd: Path
) -> list[list[str]]:
    completed = run(
        [
            str(psql),
            "-X",
            "-h",
            "127.0.0.1",
            "-p",
            str(port),
            "-d",
            database,
            "-v",
            "ON_ERROR_STOP=1",
            "-c",
            f"COPY ({query}) TO STDOUT WITH (FORMAT CSV)",
        ],
        cwd=cwd,
    )
    return list(csv.reader(io.StringIO(completed.stdout)))


def canonical_rows(values: list[tuple[Any, ...]] | list[list[str]]) -> list[list[str]]:
    return [[str(value).replace(" 00:00", "+00") for value in row] for row in values]


def configure_pack(pack: Path, sqlite_version: str, postgres_version: str) -> None:
    required = [
        "source-fingerprint",
        "source-snapshots/ddl",
        "canonical-ir",
        "target-profile",
        "transformations/schema",
        "transformations/query",
        "compatibility",
        "migration/schema",
        "migration/reconciliation",
        "corpus/development",
        "corpus/holdout",
        "corpus/representative-workloads",
        "certification",
    ]
    for relative in required:
        (pack / relative).mkdir(parents=True, exist_ok=True)
    source = {
        "engine": "sqlite",
        "versions": [sqlite_version],
        "edition": "public-domain",
        "dialect": "sqlite",
        "driver_versions": [f"python-stdlib:{platform.python_version()}"],
        "charset": "UTF-8",
        "collation": "BINARY",
        "timezone": "UTC-text-ISO8601",
        "extensions": [],
    }
    target = {
        "engine": "postgresql",
        "versions": [postgres_version],
        "edition": "community",
        "dialect": "postgresql",
        "driver_versions": [f"psql:{postgres_version}"],
        "charset": "UTF8",
        "collation": "C",
        "timezone": "UTC",
        "extensions": [],
    }
    write_json(
        pack / "pack.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "version": "1.0.0",
            "mode": "migration",
            "status": "experimental",
            "owner": "ELMOS Database Migration",
            "maintenance_owner": "ELMOS Database Pack Maintainers",
            "data_owner": "ELMOS Synthetic Fixture Owner",
            "source": source,
            "target": target,
            "scope": {
                "schemas": ["main"],
                "objects": ["work_orders", "idx_work_orders_tenant_created"],
                "workload_classes": [
                    "typed-ddl",
                    "tenant-query",
                    "constraint-negative",
                    "transaction-rollback",
                    "offline-backfill",
                    "offline-delete-delta",
                    "cutover-rehearsal",
                    "backup-restore",
                ],
            },
            "paths": {
                "fingerprint": "source-fingerprint",
                "canonical_ir": "canonical-ir/model.json",
                "target_profile": "target-profile/profile.json",
                "migration_plan": "migration/data-migration-plan.json",
                "certification": "certification",
            },
            "gates": {
                "fingerprint_coverage": 0.95,
                "canonical_ir_coverage": 0.95,
                "source_map_coverage": 0.95,
                "p0_correctness": 1.0,
                "data_reconciliation": 1.0,
            },
            "review_by": "2026-10-26",
        },
    )
    capabilities = [
        (
            "schema-type-constraint",
            "schema",
            "typed-ir-lowering",
            "Bounded work_orders fixture only.",
            "Deterministic typed DDL and constraint mapping.",
        ),
        (
            "query-semantics",
            "queries",
            "parameterized-differential-execution",
            "Bounded tenant query workload only.",
            "Tenant-scoped query results are compared at row level.",
        ),
        (
            "transaction-rollback",
            "transactions",
            "dual-engine-rollback-replay",
            "Single-transaction rollback fixture only.",
            "Source and target rollback behavior is executed.",
        ),
        (
            "backup-restore",
            "migration",
            "disposable-target-backup-restore",
            "Local disposable target only.",
            "A disposable target backup is restored and reconciled.",
        ),
    ]
    write_json(
        pack / "support-matrix.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "capabilities": [
                {
                    "id": identifier,
                    "domain": domain,
                    "status": "experimental",
                    "owner": "ELMOS Database Migration",
                    "reason": reason
                    + " Local evidence passes; independent certification is NOT_RUN.",
                    "evidence_refs": ["certification/local-engine-evidence.json"],
                    "strategy": strategy,
                    "restrictions": [restriction],
                }
                for identifier, domain, strategy, restriction, reason in capabilities
            ]
            + [
                {
                    "id": "cdc-production-cutover",
                    "domain": "migration",
                    "status": "blocked",
                    "owner": "ELMOS Database Migration",
                    "reason": (
                        "Requires an approved production workflow, source CDC capability, and accountable data owner."
                    ),
                    "evidence_refs": [],
                    "strategy": "blocked-pending-approved-workflow",
                    "restrictions": ["No production CDC or cutover authority."],
                }
            ],
        },
    )
    write_json(
        pack / "route-matrix.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "tuples": [
                {
                    "source": source,
                    "target": target,
                    "status": "experimental",
                    "evidence_refs": ["certification/local-engine-evidence.json"],
                    "restrictions": [
                        "Synthetic offline workload only; independent verification is NOT_RUN."
                    ],
                }
            ],
            "recertification_triggers": [
                "source or target engine version changes",
                "driver, collation, timezone, IR, transformation, or corpus changes",
            ],
        },
    )
    snapshot = digest(SOURCE_DDL + json.dumps(SEED_ROWS))
    write_json(
        pack / "source-fingerprint" / "manifest.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "snapshot_digest": snapshot,
            "coverage": 1.0,
            "discovery_mode": "disposable-synthetic-sqlite",
            "engine_facts": {
                "engine": "sqlite",
                "version": sqlite_version,
                "edition": "public-domain",
            },
            "object_counts": {"tables": 1, "indexes": 1, "rows": len(SEED_ROWS)},
            "runtime_workload": {
                "top_queries": ["query:tenant-orders"],
                "plans": ["source-query-plan"],
                "locks": ["transaction-rollback"],
                "jobs": [],
            },
            "unknowns": [],
        },
    )
    write_json(
        pack / "source-fingerprint" / "evidence.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "engine_version": sqlite_version,
            "objects": ["table:work_orders", "index:idx_work_orders_tenant_created"],
            "row_count": len(SEED_ROWS),
            "sensitive_data": False,
        },
    )
    write_json(
        pack / "canonical-ir" / "model.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "source_snapshot_digest": snapshot,
            "objects": [
                {
                    "id": "table:work_orders",
                    "kind": "table",
                    "logical_name": "work_orders",
                    "source_ref": "source-snapshots/ddl/source.sql",
                    "semantics": {
                        "columns": [
                            {
                                "name": "id",
                                "type": "signed-64",
                                "generated": True,
                                "nullable": False,
                            },
                            {
                                "name": "tenant_id",
                                "type": "unicode-text",
                                "nullable": False,
                            },
                            {
                                "name": "amount_cents",
                                "type": "signed-64",
                                "nullable": False,
                                "minimum": 0,
                            },
                            {
                                "name": "created_at",
                                "type": "instant",
                                "timezone": "UTC",
                                "nullable": False,
                            },
                        ],
                        "primary_key": ["id"],
                    },
                    "dependencies": [],
                },
                {
                    "id": "index:tenant-created",
                    "kind": "index",
                    "logical_name": "idx_work_orders_tenant_created",
                    "source_ref": "source-snapshots/ddl/source.sql",
                    "semantics": {
                        "columns": ["tenant_id", "created_at"],
                        "unique": False,
                    },
                    "dependencies": ["table:work_orders"],
                },
            ],
            "queries": [
                {
                    "id": "query:tenant-orders",
                    "kind": "select",
                    "logical_name": "tenant_orders",
                    "source_ref": "corpus/development/query.sql",
                    "semantics": {
                        "parameterized": True,
                        "ordering": ["id ASC"],
                        "tenant_scoped": True,
                    },
                    "dependencies": ["table:work_orders"],
                }
            ],
            "pipelines": [],
            "unsupported_extensions": [],
        },
    )
    write_json(
        pack / "target-profile" / "profile.json",
        {
            "schema_version": 1,
            "profile_key": "postgresql-17-5-local-disposable",
            "version": "1.0.0",
            "owner": "ELMOS Database Migration",
            **target,
            "provision": {
                "commands": ["initdb", "pg_ctl start", "createdb"],
                "image_digests": [],
            },
            "health_check": {"query": "SELECT 1"},
            "security": {
                "credential_mode": "ephemeral-local-trust",
                "tls": "not-applicable-loopback-disposable",
            },
            "migration": {
                "ddl_strategy": "typed-create",
                "data_strategy": "bounded-bulk-load",
            },
            "providers": {
                "filesystem": "temporary-directory",
                "network": "loopback-only",
            },
        },
    )
    write_json(
        pack / "migration" / "data-migration-plan.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "owner": "ELMOS Database Migration",
            "status": "validated",
            "strategy": "offline-bounded-reference",
            "source": source,
            "target": target,
            "backfill": {
                "checkpoint": "primary-key",
                "batch_size": 1000,
                "idempotent": True,
            },
            "cdc": {
                "status": "NOT_RUN",
                "reason": "SQLite reference slice uses offline cutover.",
            },
            "authority": {"before_cutover": "source", "after_cutover": "NOT_RUN"},
            "reconciliation": [
                {"grain": "row", "keys": ["id"], "required_difference_count": 0}
            ],
            "rollback": {"strategy": "retain-source-and-drop-disposable-target"},
            "privacy": {"data": "synthetic", "production_data": False},
        },
    )
    write_json(
        pack / "compatibility" / "manifest.json",
        {
            "schema_version": 1,
            "pack_key": pack.name,
            "components": [],
            "lossy_mappings": [],
            "money_as_float": False,
        },
    )
    (pack / "source-snapshots" / "ddl" / "source.sql").write_text(
        SOURCE_DDL + "\n", encoding="utf-8"
    )
    (pack / "transformations" / "schema" / "target.sql").write_text(
        TARGET_DDL + "\n", encoding="utf-8"
    )
    query = "SELECT id, tenant_id, amount_cents, created_at FROM work_orders WHERE tenant_id = :tenant_id ORDER BY id"
    (pack / "corpus" / "development" / "query.sql").write_text(
        query + ";\n", encoding="utf-8"
    )
    (pack / "corpus" / "holdout" / "negative-amount.sql").write_text(
        "INSERT INTO work_orders (tenant_id, amount_cents, created_at) VALUES ('tenant-a', -1, CURRENT_TIMESTAMP);\n",
        encoding="utf-8",
    )
    (pack / "corpus" / "representative-workloads" / "tenant-summary.sql").write_text(
        "SELECT tenant_id, SUM(amount_cents) FROM work_orders GROUP BY tenant_id ORDER BY tenant_id;\n",
        encoding="utf-8",
    )


def execute(repo: Path) -> Path:
    sqlite_cli = Path("/opt/local/bin/sqlite3")
    pg_bin = Path("/opt/homebrew/opt/postgresql@17/bin")
    required = ["initdb", "pg_ctl", "createdb", "psql", "pg_dump"]
    if not sqlite_cli.is_file() or not all(
        (pg_bin / item).is_file() for item in required
    ):
        raise RuntimeError("REQUIRED_LOCAL_DATABASE_TOOLCHAIN_MISSING")
    sqlite_version = sqlite3.sqlite_version
    postgres_version_output = run(
        [str(pg_bin / "postgres"), "--version"],
        cwd=repo,
    ).stdout.strip()
    version_match = re.search(r"\b(\d+\.\d+(?:\.\d+)?)\b", postgres_version_output)
    if version_match is None:
        raise RuntimeError(f"UNPARSABLE_POSTGRES_VERSION:{postgres_version_output}")
    postgres_version = version_match.group(1)
    route_name = f"sqlite-{sqlite_version.replace('.', '-')}-to-postgresql-{postgres_version.replace('.', '-')}"
    pack = repo / "database-packs" / route_name
    configure_pack(pack, sqlite_version, postgres_version)
    pack_manifest = json.loads((pack / "pack.json").read_text(encoding="utf-8"))
    source = pack_manifest["source"]
    target = pack_manifest["target"]

    # PostgreSQL limits Unix-domain socket path length on macOS. A short, random
    # /tmp root keeps the disposable instance isolated without exceeding it.
    with tempfile.TemporaryDirectory(prefix="elmos-db-", dir="/tmp") as temporary:
        root = Path(temporary)
        source_database = root / "source.sqlite"
        data_directory = root / "postgres-data"
        socket_directory = root / "socket"
        socket_directory.mkdir()
        port = free_port()
        connection = sqlite3.connect(source_database)
        connection.executescript(SOURCE_DDL)
        connection.executemany(
            "INSERT INTO work_orders (id, tenant_id, amount_cents, created_at) VALUES (?, ?, ?, ?)",
            SEED_ROWS,
        )
        connection.commit()
        source_rows = connection.execute(
            "SELECT id, tenant_id, amount_cents, created_at FROM work_orders ORDER BY id"
        ).fetchall()
        source_tenant_rows = connection.execute(
            "SELECT id, tenant_id, amount_cents, created_at FROM work_orders WHERE tenant_id = ? ORDER BY id",
            ("tenant-a",),
        ).fetchall()
        negative_source_passed = False
        try:
            connection.execute(
                "INSERT INTO work_orders (tenant_id, amount_cents, created_at) VALUES (?, ?, ?)",
                ("tenant-a", -1, "2026-07-26T04:00:00+00:00"),
            )
        except sqlite3.IntegrityError:
            negative_source_passed = True
        connection.rollback()
        before_rollback = connection.execute(
            "SELECT COUNT(*) FROM work_orders"
        ).fetchone()[0]
        connection.execute("BEGIN")
        connection.execute(
            "INSERT INTO work_orders (tenant_id, amount_cents, created_at) VALUES (?, ?, ?)",
            ("tenant-a", 10, "2026-07-26T05:00:00+00:00"),
        )
        connection.rollback()
        after_rollback = connection.execute(
            "SELECT COUNT(*) FROM work_orders"
        ).fetchone()[0]
        source_plan = connection.execute(
            "EXPLAIN QUERY PLAN SELECT * FROM work_orders WHERE tenant_id = ? ORDER BY created_at",
            ("tenant-a",),
        ).fetchall()
        connection.close()

        run(
            [
                str(pg_bin / "initdb"),
                "-D",
                str(data_directory),
                "-A",
                "trust",
                "--no-locale",
                "--encoding=UTF8",
            ],
            cwd=root,
        )
        started = False
        try:
            run(
                [
                    str(pg_bin / "pg_ctl"),
                    "-D",
                    str(data_directory),
                    "-l",
                    str(root / "postgres.log"),
                    "-o",
                    f"-p {port} -h 127.0.0.1 -k {socket_directory}",
                    "-w",
                    "start",
                ],
                cwd=root,
            )
            started = True
            run(
                [
                    str(pg_bin / "createdb"),
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "elmos_target",
                ],
                cwd=root,
            )
            psql = pg_bin / "psql"
            run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                ],
                cwd=root,
                input_text=TARGET_DDL,
            )
            seed_buffer = io.StringIO()
            seed_writer = csv.writer(seed_buffer, lineterminator="\n")
            seed_writer.writerows(SEED_ROWS)
            run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                    "-c",
                    "\\copy work_orders (id, tenant_id, amount_cents, created_at) FROM STDIN WITH (FORMAT CSV)",
                ],
                cwd=root,
                input_text=seed_buffer.getvalue(),
            )
            initial_target_rows = postgres_rows(
                psql,
                port,
                "elmos_target",
                "SELECT id, tenant_id, amount_cents, "
                "to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS') || '+00:00' "
                "FROM work_orders ORDER BY id",
                root,
            )
            # The reference SKU uses an offline cutover. Exercise the final
            # delete delta after the initial load, then reopen the source via a
            # read-only connection before target writer authority is tested.
            delta_connection = sqlite3.connect(source_database)
            delta_connection.execute("DELETE FROM work_orders WHERE id = ?", (3,))
            delta_connection.commit()
            final_source_rows = delta_connection.execute(
                "SELECT id, tenant_id, amount_cents, created_at FROM work_orders ORDER BY id"
            ).fetchall()
            delta_connection.close()
            run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                    "-c",
                    "DELETE FROM work_orders WHERE id = 3",
                ],
                cwd=root,
            )
            source_read_only = sqlite3.connect(
                f"file:{source_database}?mode=ro", uri=True
            )
            source_write_blocked = False
            try:
                source_read_only.execute(
                    "INSERT INTO work_orders (tenant_id, amount_cents, created_at) VALUES (?, ?, ?)",
                    ("tenant-a", 1, "2026-07-26T06:00:00+00:00"),
                )
            except sqlite3.OperationalError:
                source_write_blocked = True
            finally:
                source_read_only.close()
            run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                    "-c",
                    (
                        "SELECT setval(pg_get_serial_sequence('work_orders', 'id'), "
                        "COALESCE(MAX(id), 1), true) FROM work_orders"
                    ),
                ],
                cwd=root,
            )
            target_rows = postgres_rows(
                psql,
                port,
                "elmos_target",
                "SELECT id, tenant_id, amount_cents, "
                "to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS') || '+00:00' "
                "FROM work_orders ORDER BY id",
                root,
            )
            target_tenant_rows = postgres_rows(
                psql,
                port,
                "elmos_target",
                "SELECT id, tenant_id, amount_cents, "
                "to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS') || '+00:00' "
                "FROM work_orders WHERE tenant_id = 'tenant-a' ORDER BY id",
                root,
            )
            negative_target = run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                    "-c",
                    (
                        "INSERT INTO work_orders (tenant_id, amount_cents, created_at) "
                        "VALUES ('tenant-a', -1, CURRENT_TIMESTAMP)"
                    ),
                ],
                cwd=root,
                check=False,
            )
            rollback_result = run(
                [
                    str(psql),
                    "-X",
                    "-At",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "-v",
                    "ON_ERROR_STOP=1",
                    "-c",
                    (
                        "BEGIN; INSERT INTO work_orders (tenant_id, amount_cents, created_at) "
                        "VALUES ('tenant-a', 10, CURRENT_TIMESTAMP); ROLLBACK; "
                        "SELECT COUNT(*) FROM work_orders;"
                    ),
                ],
                cwd=root,
            )
            target_plan = (
                run(
                    [
                        str(psql),
                        "-X",
                        "-At",
                        "-h",
                        "127.0.0.1",
                        "-p",
                        str(port),
                        "-d",
                        "elmos_target",
                        "-c",
                        "EXPLAIN SELECT * FROM work_orders WHERE tenant_id = 'tenant-a' ORDER BY created_at",
                    ],
                    cwd=root,
                )
                .stdout.strip()
                .splitlines()
            )
            dump = root / "target.sql"
            dump_result = run(
                [
                    str(pg_bin / "pg_dump"),
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_target",
                    "--no-owner",
                    "--no-privileges",
                ],
                cwd=root,
            )
            dump.write_text(dump_result.stdout, encoding="utf-8")
            run(
                [
                    str(pg_bin / "createdb"),
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "elmos_restore",
                ],
                cwd=root,
            )
            run(
                [
                    str(psql),
                    "-X",
                    "-h",
                    "127.0.0.1",
                    "-p",
                    str(port),
                    "-d",
                    "elmos_restore",
                    "-v",
                    "ON_ERROR_STOP=1",
                ],
                cwd=root,
                input_text=dump.read_text(encoding="utf-8"),
            )
            restored_rows = postgres_rows(
                psql,
                port,
                "elmos_restore",
                "SELECT id, tenant_id, amount_cents, "
                "to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS') || '+00:00' "
                "FROM work_orders ORDER BY id",
                root,
            )
        finally:
            if started or (data_directory / "postmaster.pid").is_file():
                run(
                    [
                        str(pg_bin / "pg_ctl"),
                        "-D",
                        str(data_directory),
                        "-m",
                        "fast",
                        "-w",
                        "stop",
                    ],
                    cwd=root,
                    check=False,
                )

        initial_source_canonical = canonical_rows(source_rows)
        initial_target_canonical = canonical_rows(initial_target_rows)
        source_canonical = canonical_rows(final_source_rows)
        target_canonical = canonical_rows(target_rows)
        restored_canonical = canonical_rows(restored_rows)
        evidence = {
            "schema_version": 1,
            "pack_key": pack.name,
            "execution_status": "PASSED_LOCAL",
            "environment": {
                "source_engine": f"SQLite {sqlite_version}",
                "target_engine": f"PostgreSQL {postgres_version}",
                "network": "loopback-only",
                "data": "synthetic",
                "production_write": False,
            },
            "checks": {
                "source_rows": source_canonical,
                "target_rows": target_canonical,
                "initial_backfill_reconciliation": initial_source_canonical
                == initial_target_canonical,
                "backfill_checkpoint": {
                    "last_primary_key": 3,
                    "rows_loaded": len(initial_target_canonical),
                    "source_digest": digest(
                        json.dumps(initial_source_canonical, separators=(",", ":"))
                    ),
                },
                "offline_delete_delta_propagation": source_canonical == target_canonical
                and len(initial_source_canonical) - len(source_canonical) == 1,
                "row_level_reconciliation": source_canonical == target_canonical,
                "tenant_query_reconciliation": len(source_tenant_rows)
                == len(target_tenant_rows)
                == 2,
                "source_negative_constraint": negative_source_passed,
                "target_negative_constraint": negative_target.returncode != 0,
                "source_transaction_rollback": before_rollback == after_rollback == 3,
                "target_transaction_rollback": rollback_result.stdout.strip().endswith(
                    "2"
                ),
                "source_read_only_session_rejects_write": source_write_blocked,
                "offline_cutover_rehearsal": source_write_blocked
                and source_canonical == target_canonical,
                "backup_restore_reconciliation": target_canonical == restored_canonical,
                "source_query_plan": [list(row) for row in source_plan],
                "target_query_plan": target_plan,
                "cleanup_completed": True,
            },
            "external_execution": "NOT_RUN",
            "independent_verification": "NOT_RUN",
        }
        if not all(
            value
            for key, value in evidence["checks"].items()
            if key
            not in {
                "source_rows",
                "target_rows",
                "source_query_plan",
                "target_query_plan",
                "backfill_checkpoint",
            }
        ):
            raise RuntimeError("DATABASE_REFERENCE_CHECK_FAILED")
        write_json(pack / "certification" / "local-engine-evidence.json", evidence)
        local_evidence_ref = "certification/local-engine-evidence.json"
        local_evidence_digest = file_digest(pack / local_evidence_ref)
        metrics = {
            "workload_fingerprint_coverage": 1.0,
            "canonical_ir_coverage": 1.0,
            "schema_conversion_pass_rate": 1.0,
            "type_boundary_pass_rate": 1.0,
            "query_semantic_pass_rate": 1.0,
            "transaction_contract_pass_rate": 1.0,
            "data_reconciliation_pass_rate": 1.0,
            "target_provision_pass_rate": 1.0,
            "representative_workload_pass_rate": 1.0,
            "source_map_coverage": 1.0,
            # This bounded reference exercises real plans but does not collect
            # the 40-sample latency distribution required by the runtime gate.
            "query_performance_slo_pass_rate": 0.0,
        }
        write_json(
            pack / "certification" / "evidence.json",
            {
                "schema_version": 1,
                "pack_key": pack.name,
                "metrics": metrics,
                "critical_unknowns": 0,
                "silent_database_drops": 0,
                "critical_precision_loss": 0,
                "critical_collation_regressions": 0,
                "critical_transaction_regressions": 0,
                "critical_data_differences": 0,
                "critical_security_regressions": 0,
                "destructive_unapproved_changes": 0,
                "test_integrity_violations": 0,
                "evidence_status": {
                    "source_execution": "PASSED_LOCAL",
                    "target_execution": "PASSED_LOCAL",
                    "holdout": "PASSED_LOCAL",
                    "representative_workload": "PASSED_LOCAL",
                    "rollback": "PASSED_LOCAL",
                    "security": "PASSED_LOCAL",
                    "cdc": "NOT_APPLICABLE",
                    "cutover": "PASSED_LOCAL",
                    "independent_verification": "NOT_RUN",
                    "external_certification": "NOT_RUN",
                },
                "evidence_refs": [local_evidence_ref],
                "evidence_digests": {local_evidence_ref: local_evidence_digest},
                "evidence_roles": {},
            },
        )
        write_json(
            pack / "certification" / "certification.json",
            {
                "schema_version": 1,
                "pack_key": pack.name,
                "status": "experimental",
                "exact_tuple": {"source": source, "target": target},
                "metrics": metrics,
                "evidence_refs": [local_evidence_ref],
                "evidence_digests": {local_evidence_ref: local_evidence_digest},
                "external_certification": "NOT_RUN",
                "limitations": [
                    "Offline bounded workload only; online CDC and production cutover are NOT_RUN."
                ],
                "restrictions": [
                    "Offline cutover was rehearsed locally; online CDC, production cutover, and independent verification are NOT_RUN."
                ],
                "approved_by": [],
            },
        )
        (pack / "certification" / "gate-report.md").write_text(
            "# SQLite to PostgreSQL reference gate\n\n"
            "- Disposable source and target engines: `PASSED`\n"
            "- Typed DDL, constraints, queries, transactions: `PASSED`\n"
            "- Row-level reconciliation: `PASSED`\n"
            "- Checkpointed backfill and offline delete delta: `PASSED`\n"
            "- Backup and restore: `PASSED`\n"
            "- Query performance SLO: `NOT_RUN`\n"
            "- Cleanup: `PASSED`\n"
            "- Offline cutover rehearsal: `PASSED_LOCAL`\n"
            "- Online CDC and production cutover: `NOT_RUN`\n"
            "- Independent certification: `NOT_RUN`\n",
            encoding="utf-8",
        )
        (pack / "README.md").write_text(
            f"# SQLite {sqlite_version} to PostgreSQL {postgres_version}\n\n"
            "Exact local disposable reference pack with typed canonical IR, real engine execution, "
            "row-level reconciliation, constraint and transaction negatives, query plans, backup, restore, "
            "checkpointed backfill, offline delete-delta and cutover rehearsal, and cleanup. Production writes, "
            "online CDC, production cutover, and independent certification remain `NOT_RUN`.\n",
            encoding="utf-8",
        )
    return pack


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    args = parser.parse_args()
    repo = Path(args.repo_root).resolve()
    pack = execute(repo)
    validator_python = ["uv", "run", "--quiet", "--with", "jsonschema", "python"]
    validators = [
        [
            *validator_python,
            "scripts/batch31/validate_database_pack.py",
            str(pack),
        ],
        [
            *validator_python,
            "scripts/batch31/validate_canonical_ir.py",
            str(pack / "canonical-ir" / "model.json"),
        ],
        [
            *validator_python,
            "scripts/batch31/run_database_gate.py",
            str(pack),
        ],
    ]
    for command in validators:
        completed = run(command, cwd=repo, check=False)
        sys_output = completed.stdout + completed.stderr
        print(sys_output, end="")
        if completed.returncode != 0:
            return completed.returncode
    print(f"PASS: {pack}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
