import type {
  CloudDeploymentOption,
  DeploymentGuidance,
  GenerationTargetId,
  LocalRuntimeProfile,
} from "./contracts";

const cloudOptions: CloudDeploymentOption[] = [
  {
    id: "google-cloud-run",
    name: "Google Cloud Run",
    status: "RECOMMENDED",
    fit: "无状态 HTTP API、希望按请求伸缩并减少集群运维。",
    tradeoff: "持久化、Secret、连接池、冷启动、恢复与成本仍需独立配置。",
  },
  {
    id: "azure-container-apps",
    name: "Azure Container Apps",
    status: "OPTIONAL",
    fit: "已有 Azure Managed Identity、Key Vault 与 Azure Database 体系。",
    tradeoff: "仍需验证环境、网络、日志、修订流量与身份边界。",
  },
  {
    id: "aws-ecs-fargate",
    name: "AWS ECS on Fargate",
    status: "OPTIONAL",
    fit: "已有 ECR、IAM、VPC、ALB、CloudWatch 与 RDS 运维体系。",
    tradeoff: "任务角色、执行角色、网络和负载均衡配置较多。",
  },
  {
    id: "kubernetes",
    name: "GKE / EKS / AKS",
    status: "CONDITIONAL",
    fit: "已有平台团队、集群准入、镜像策略、观测与升级能力。",
    tradeoff: "运维成本最高，不建议只为一个 Starter 新建集群。",
  },
];

const localProfiles: Record<GenerationTargetId, LocalRuntimeProfile> = {
  java: {
    id: "java",
    label: "Java 21",
    framework: "Spring Boot 3.5.3",
    toolchain: "Java 21 / Maven 3.9.10",
    minimum: { cpu: 2, memoryGb: 4, diskGb: 5 },
    recommended: { cpu: 4, memoryGb: 8, diskGb: 10 },
    scope: "单独构建并运行 Java 目标",
    directory: "java",
    port: 8081,
    healthPath: "/health",
    verifyCommands: ["cd java", "mvn -B -ntp verify"],
    runCommands: ["PORT=8081 mvn spring-boot:run", "curl --fail http://127.0.0.1:8081/health"],
  },
  python: {
    id: "python",
    label: "Python 3.12",
    framework: "FastAPI 0.116.1",
    toolchain: "Python 3.12 / uv 0.11.16",
    minimum: { cpu: 2, memoryGb: 4, diskGb: 4 },
    recommended: { cpu: 4, memoryGb: 8, diskGb: 8 },
    scope: "单独构建并运行 Python 目标",
    directory: "python",
    port: 8082,
    healthPath: "/health",
    verifyCommands: ["cd python", "uv sync --locked --python 3.12", "make test"],
    runCommands: ["make run", "curl --fail http://127.0.0.1:8082/health"],
  },
  csharp: {
    id: "csharp",
    label: "C# / .NET 10",
    framework: "ASP.NET Core 10.0",
    toolchain: ".NET SDK 10.0.301",
    minimum: { cpu: 2, memoryGb: 4, diskGb: 6 },
    recommended: { cpu: 4, memoryGb: 8, diskGb: 12 },
    scope: "单独构建并运行 .NET 目标",
    directory: "dotnet",
    port: 8083,
    healthPath: "/health",
    verifyCommands: ["cd dotnet", "make restore", "make test"],
    runCommands: ["make run", "curl --fail http://127.0.0.1:8083/health"],
  },
  typescript: {
    id: "typescript",
    label: "TypeScript / Node 26",
    framework: "NestJS 11.1.6 + Fastify 5.6.1",
    toolchain: "Node 26.0.0 / pnpm 10.12.4",
    minimum: { cpu: 2, memoryGb: 4, diskGb: 4 },
    recommended: { cpu: 4, memoryGb: 8, diskGb: 8 },
    scope: "单独构建并运行 TypeScript 目标",
    directory: "typescript",
    port: 8084,
    healthPath: "/health",
    verifyCommands: ["cd typescript", "pnpm install --frozen-lockfile", "pnpm check && pnpm test && pnpm build"],
    runCommands: ["PORT=8084 pnpm start", "curl --fail http://127.0.0.1:8084/health"],
  },
  go: {
    id: "go",
    label: "Go 1.25",
    framework: "net/http",
    toolchain: "Go 1.25.0",
    minimum: { cpu: 2, memoryGb: 2, diskGb: 3 },
    recommended: { cpu: 4, memoryGb: 4, diskGb: 6 },
    scope: "单独构建并运行 Go 目标",
    directory: "go",
    port: 8085,
    healthPath: "/health",
    verifyCommands: ["cd go", "go vet ./... && go test -race ./... && go build ./..."],
    runCommands: ["PORT=8085 go run .", "curl --fail http://127.0.0.1:8085/health"],
  },
  kotlin: {
    id: "kotlin",
    label: "Kotlin 2.2 / JVM 21",
    framework: "Ktor 3.2.3",
    toolchain: "Kotlin 2.2.20 / Java 21 / Gradle 8.14.3",
    minimum: { cpu: 4, memoryGb: 8, diskGb: 8 },
    recommended: { cpu: 8, memoryGb: 16, diskGb: 15 },
    scope: "单独构建并运行 Kotlin 目标",
    directory: "kotlin",
    port: 8086,
    healthPath: "/health",
    verifyCommands: ["cd kotlin", "gradle --no-daemon --write-locks test build"],
    runCommands: ["PORT=8086 gradle --no-daemon run", "curl --fail http://127.0.0.1:8086/health"],
  },
  php: {
    id: "php",
    label: "PHP 8.4",
    framework: "原生 HTTP Starter",
    toolchain: "PHP 8.4.12",
    minimum: { cpu: 2, memoryGb: 2, diskGb: 2 },
    recommended: { cpu: 4, memoryGb: 4, diskGb: 5 },
    scope: "单独构建并运行 PHP 目标",
    directory: "php",
    port: 8087,
    healthPath: "/health",
    verifyCommands: ["cd php", "php -l src/Store.php && php tests/run.php"],
    runCommands: ["PORT=8087 php -S 127.0.0.1:8087 public/index.php", "curl --fail http://127.0.0.1:8087/health"],
  },
  rust: {
    id: "rust",
    label: "Rust 1.89",
    framework: "Axum 0.8.4",
    toolchain: "Rust 1.89.0 / Cargo 1.89.0",
    minimum: { cpu: 4, memoryGb: 8, diskGb: 10 },
    recommended: { cpu: 8, memoryGb: 16, diskGb: 20 },
    scope: "单独构建并运行 Rust 目标",
    directory: "rust",
    port: 8088,
    healthPath: "/health",
    verifyCommands: ["cd rust", "cargo fmt --check && cargo clippy --locked --all-targets --all-features -- -D warnings", "cargo test --locked --all-features"],
    runCommands: ["PORT=8088 cargo run --locked", "curl --fail http://127.0.0.1:8088/health"],
  },
};

const recommendation: DeploymentGuidance["recommendation"] = {
  platform: "Google Cloud Run",
  reason: "八类生成目标和 Spring 翻新结果都是容器化 HTTP 服务；Cloud Run 可降低单服务的集群运维，但不会替代数据库、身份、容量和恢复验收。",
  requiredInputs: [
    "已批准的 Cloud 项目、区域、计费与数据驻留负责人",
    "专用最小权限运行时 Service Account",
    "Artifact Registry 仓库与精确镜像摘要 sha256",
    "固定 Secret 版本、ingress、CPU、内存、并发、最小/最大实例",
    "数据库迁移/回滚、告警、预算、DNS 与资源清理负责人",
  ],
  steps: [
    { title: "1. 锁定账号与区域", detail: "登录受控账号，确认项目、区域、计费、数据驻留和变更授权。" },
    {
      title: "2. 启用所需 API",
      detail: "启用 Cloud Run、Artifact Registry、Secret Manager；需要 PostgreSQL 时再启用 Cloud SQL Admin API。",
      commands: ["gcloud services enable run.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com"],
    },
    { title: "3. 创建最小权限身份", detail: "为服务创建专用 Service Account；不使用 Owner/Editor，不复用人工账号。" },
    { title: "4. 构建并锁定镜像", detail: "构建、推送到 Artifact Registry，再读取远端 sha256；部署只接受 image@sha256:...。" },
    { title: "5. 配置 Secret", detail: "通过 Secret Manager 文件挂载传递数据库/JWT/OIDC Secret，固定版本，禁止 latest 和明文环境变量。" },
    {
      title: "6. 私有部署",
      detail: "设置服务身份、端口、CPU、内存、并发、实例上下限；默认 --no-allow-unauthenticated。",
      commands: [
        "gcloud run deploy SERVICE --region=REGION --image=IMAGE@sha256:DIGEST \\",
        "  --service-account=SERVICE_ACCOUNT --port=PORT --cpu=CPU --memory=MEMORY \\",
        "  --concurrency=CONCURRENCY --min=MIN --max=MAX --no-allow-unauthenticated",
      ],
    },
    { title: "7. 接入持久化", detail: "需要 PostgreSQL 时使用同区域 Cloud SQL 或经批准的托管库；限制连接池并先完成迁移和回滚演练。" },
    { title: "8. 执行验收", detail: "从授权调用方执行健康、认证负例、CRUD、并发与重启冒烟，保存修订、摘要、配置与日志证据。" },
  ],
  rollback: [
    "保留上一不可变修订和镜像摘要。",
    "失败时把流量切回上一修订，复跑健康与关键业务旅程。",
    "未知数据库写入结果必须先对账，不自动重试或回滚。",
  ],
  cleanup: [
    "删除失败修订、无引用镜像和未使用 Secret 版本。",
    "项目结束时删除服务、数据库、网络和 DNS 资源。",
    "检查预算告警与最终账单，记录清理证据。",
  ],
  officialDocs: [
    { label: "Cloud Run 部署容器", url: "https://docs.cloud.google.com/run/docs/deploying" },
    { label: "Cloud Run 服务配置", url: "https://docs.cloud.google.com/run/docs/configuring" },
    { label: "Cloud Run Secret", url: "https://docs.cloud.google.com/run/docs/configuring/services/secrets" },
    { label: "Cloud Run 连接 Cloud SQL", url: "https://docs.cloud.google.com/sql/docs/postgres/connect-run" },
  ],
};

export function generationDeploymentGuidance(): DeploymentGuidance {
  return {
    status: "CONFIGURATION_REQUIRED",
    externalEvidence: "NOT_RUN",
    localProfiles: Object.values(localProfiles),
    cloudOptions,
    recommendation,
  };
}

export const springDeploymentGuidance: DeploymentGuidance = {
  status: "CONFIGURATION_REQUIRED",
  externalEvidence: "NOT_RUN",
  localProfiles: [{
    id: "spring-modernization",
    label: "Spring Boot 3.5.3",
    framework: "Boot 2.7.18 / Java 17 → Boot 3.5.3 / Java 21",
    toolchain: "JDK 17 + JDK 21 / Maven 3.9.11 / OpenRewrite 6.35.0",
    minimum: { cpu: 4, memoryGb: 8, diskGb: 20 },
    recommended: { cpu: 8, memoryGb: 16, diskGb: 40 },
    scope: "完整翻新、双工具链构建和独立验证；仅运行目标项目可降至 2 vCPU / 2 GB RAM / 5 GB",
    directory: "迁移后项目根目录",
    port: 8080,
    healthPath: "/actuator/health 或 /health",
    verifyCommands: ["java -version && mvn -version", "mvn -B -ntp verify"],
    runCommands: [
      "SERVER_ADDRESS=127.0.0.1 SERVER_PORT=8080 java -jar target/<verified-app>.jar",
      "curl --fail http://127.0.0.1:8080/actuator/health",
    ],
  }],
  cloudOptions,
  recommendation,
};
