import type { SpringRouteDescriptor } from "./contracts";

/**
 * Mirror of the Java engine's SpringRouteCatalog, used only when the engine
 * proxy is not configured so the console can still show which legacy Spring
 * lines the platform declares. Every entry keeps its declared evidence status;
 * `scripts/operations/validate_spring_route_contract.py` fails the build if
 * this mirror drifts from the engine catalog.
 */
export const springRouteCatalogFallback: SpringRouteDescriptor[] = [
  {
    routeId: "boot-1.5-java-8-maven-to-boot-2.7.18-java-17",
    packKey: "spring-boot-1-5-to-2-7-18",
    label: "Spring Boot 1.5.x / Java 8 / Maven → Boot 2.7.18 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "2.7.18",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5ToBoot2_7_18Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-1.5-java-8-maven-to-boot-3.5.3-java-21",
    packKey: "spring-boot-1-5-to-3-5-3",
    label: "Spring Boot 1.5.x / Java 8 / Maven",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5ToBoot3_5_3Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "1.5.22.RELEASE",
    verifiedSourceJava: "8",
  },
  {
    routeId: "boot-1.5-java-8-maven-to-boot-3.2.12-java-17",
    packKey: "spring-boot-1-5-to-3-2-12",
    label: "Spring Boot 1.5.x / Java 8 / Maven → Boot 3.2.12 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "3.2.12",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5ToBoot3_2_12Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.0-2.6-maven-to-boot-2.7.18-java-17",
    packKey: "spring-boot-2-0-2-6-to-2-7-18",
    label: "Spring Boot 2.0–2.6 / Java 8, 11, 17 / Maven → Boot 2.7.18 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "2.7.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "2.7.18",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot2_0To2_6ToBoot2_7_18Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.0-2.6-maven-to-boot-3.2.12-java-17",
    packKey: "spring-boot-2-0-2-6-to-3-2-12",
    label: "Spring Boot 2.0–2.6 / Java 8, 11, 17 / Maven → Boot 3.2.12 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "2.7.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "3.2.12",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot2_0To2_6ToBoot3_2_12Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.0-2.6-maven-to-boot-3.5.3-java-21",
    packKey: "spring-boot-2-0-2-6-to-3-5-3",
    label: "Spring Boot 2.0–2.6 / Java 8, 11, 17 / Maven",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "2.7.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_0To2_6ToBoot3_5_3Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "2.3.12.RELEASE",
    verifiedSourceJava: "11",
  },
  {
    routeId: "boot-2.7-maven-to-boot-3.2.12-java-17",
    packKey: "spring-boot-2-7-to-3-2-12",
    label: "Spring Boot 2.7.x / Java 8, 11, 17 / Maven → Boot 3.2.12 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.7.0",
    sourceBootMaxExclusive: "2.8.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "3.2.12",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot2_7ToBoot3_2_12Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.7-maven-to-boot-3.5.3-java-21",
    packKey: "spring-boot-2-7-18-to-3-5-3",
    label: "Spring Boot 2.7.x / Java 8, 11, 17 / Maven",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.7.0",
    sourceBootMaxExclusive: "2.8.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_7_18To3_5_3Java21",
    evidenceStatus: "PASSED_LOCAL",
    launchStatus: "DESIGN_PARTNER",
    verifiedSourceSpringBoot: "2.7.18",
    verifiedSourceJava: "17",
  },
  {
    routeId: "boot-3.0-3.1-maven-to-boot-3.2.12-java-17",
    packKey: "spring-boot-3-0-3-1-to-3-2-12",
    label: "Spring Boot 3.0–3.1 / Java 17 / Maven → Boot 3.2.12 / Java 17",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "3.2.0",
    sourceJavaVersions: ["17"],
    targetSpringBoot: "3.2.12",
    targetJava: "17",
    recipeId: "io.elmos.openrewrite.SpringBoot3_0To3_1ToBoot3_2_12Java17",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.0-3.4-maven-to-boot-3.5.3-java-21",
    packKey: "spring-boot-3-0-3-4-to-3-5-3",
    label: "Spring Boot 3.0–3.4 / Java 17, 21 / Maven",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "3.5.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3_0To3_4ToBoot3_5_3Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "3.4.1",
    verifiedSourceJava: "17",
  },
  {
    routeId: "boot-1.5-3.5.15-maven-to-boot-3.5.16-java-21",
    packKey: "spring-boot-1-5-3-5-15-to-3-5-16-inventory-only",
    label: "Spring Boot 1.5–3.5.15 / Java 8, 11, 17, 21 / Maven → Boot 3.5.16 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "3.5.16",
    sourceJavaVersions: ["8", "11", "17", "21"],
    targetSpringBoot: "3.5.16",
    targetJava: "21",
    recipeId: "",
    evidenceStatus: "NOT_IMPLEMENTED",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-1.5-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 1.5.x / Java 8 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5ToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.0-2.6-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 2.0–2.6 / Java 8, 11, 17 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "2.7.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_0To2_6ToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.7-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 2.7.x / Java 8, 11, 17 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.7.0",
    sourceBootMaxExclusive: "3.0.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_7ToBoot4_1_0Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "2.7.18",
    verifiedSourceJava: "17",
  },
  {
    routeId: "boot-3.0-3.4-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 3.0–3.4 / Java 17, 21 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "3.5.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3_0To3_4ToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.5-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 3.5.x / Java 17, 21 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.5.0",
    sourceBootMaxExclusive: "4.0.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3_5ToBoot4_1_0Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "3.5.3",
    verifiedSourceJava: "21",
  },
  {
    routeId: "boot-4.0-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 4.0.x / Java 17, 21 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "4.0.0",
    sourceBootMaxExclusive: "4.1.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot4_0ToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.x-gradle-to-boot-3.5.3-java-21",
    packKey: "spring-boot-2-x-gradle-to-3-5-3",
    label: "Spring Boot 2.x / Gradle",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "3.0.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2xGradleToBoot3_5_3Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-1.5-gradle-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 1.5.x / Java 8 / Gradle → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5GradleToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.x-gradle-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 2.x / Java 8, 11, 17 / Gradle → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "3.0.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2xGradleToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.x-gradle-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 3.x / Java 17, 21 / Gradle → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "4.0.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3xGradleToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-4.0-gradle-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Boot 4.0.x / Java 17, 21 / Gradle → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "4.0.0",
    sourceBootMaxExclusive: "4.1.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot4_0GradleToBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "spring-mvc-3.2-5.2-maven-to-boot-3.5.3-java-21",
    packKey: "spring-framework-3-2-5-2-mvc-to-spring-boot-3-5-3",
    label: "Spring MVC non-Boot 3.2–5.2 / Maven → Boot 3.5.3 / Java 21",
    sourceFrameworkFamily: "spring-mvc",
    buildTool: "maven",
    sourceBootMinInclusive: "3.2.0",
    sourceBootMaxExclusive: "5.3.0",
    sourceJavaVersions: ["11", "17", "8"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "",
    evidenceStatus: "NOT_IMPLEMENTED",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "spring-framework-5.3-mvc-maven-to-boot-3.5.3-java-21",
    packKey: "spring-framework-5-3-mvc-to-spring-boot-3-5-3",
    label: "Spring Framework 5.3.39 MVC / Java 11 / Maven → Boot 3.5.3 / Java 21",
    sourceFrameworkFamily: "spring-mvc",
    buildTool: "maven",
    sourceBootMinInclusive: "5.3.39",
    sourceBootMaxExclusive: "5.3.40",
    exactSourceVersion: "5.3.39",
    sourceConstraint: "exact:5.3.39",
    sourceVersionMatch: "EXACT",
    sourceJavaVersions: ["11"],
    targetSpringBoot: "3.5.3",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringFramework5_3MvcToSpringBoot3_5_3Java21",
    evidenceStatus: "PASSED_LOCAL",
    verifiedSourceSpringBoot: "5.3.39",
    verifiedSourceJava: "11",
  },
  {
    routeId: "spring-mvc-3.2-7.0-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Framework / Spring MVC 3.2–7.0.8 / Java 8, 11, 17, 21 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-mvc",
    buildTool: "maven",
    sourceBootMinInclusive: "3.2.0",
    sourceBootMaxExclusive: "7.0.9",
    sourceJavaVersions: ["8", "11", "17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringFrameworkMvcToSpringBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "spring-framework-3.2-7.0-maven-to-boot-4.1.0-java-21",
    packKey: "spring-to-boot-4-1-0",
    label: "Spring Framework Core / Context 3.2–7.0.8 / Java 8, 11, 17, 21 / Maven → Boot 4.1.0 / Java 21",
    sourceFrameworkFamily: "spring-framework",
    buildTool: "maven",
    sourceBootMinInclusive: "3.2.0",
    sourceBootMaxExclusive: "7.0.9",
    sourceJavaVersions: ["8", "11", "17", "21"],
    targetSpringBoot: "4.1.0",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringFrameworkCoreToSpringBoot4_1_0Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-1.5-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 1.5.x / Java 8 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.0-2.6-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 2.0–2.6 / Java 8, 11, 17 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "2.7.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_0To2_6ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.7-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 2.7.x / Java 8, 11, 17 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "2.7.0",
    sourceBootMaxExclusive: "3.0.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2_7ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.0-3.4-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 3.0–3.4 / Java 17, 21 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "3.5.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3_0To3_4ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.5-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 3.5.x / Java 17, 21 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "3.5.0",
    sourceBootMaxExclusive: "4.0.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3_5ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-4.0-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 4.0–4.1.0 / Java 17, 21 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "maven",
    sourceBootMinInclusive: "4.0.0",
    sourceBootMaxExclusive: "4.1.1",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot4_0ToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-1.5-gradle-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 1.5.x / Java 8 / Gradle → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "1.5.0",
    sourceBootMaxExclusive: "2.0.0",
    sourceJavaVersions: ["8"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot1_5GradleToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-2.x-gradle-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 2.x / Java 8, 11, 17 / Gradle → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "2.0.0",
    sourceBootMaxExclusive: "3.0.0",
    sourceJavaVersions: ["8", "11", "17"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot2xGradleToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-3.x-gradle-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 3.x / Java 17, 21 / Gradle → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "3.0.0",
    sourceBootMaxExclusive: "4.0.0",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot3xGradleToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "boot-4.0-gradle-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Boot 4.0–4.1.0 / Java 17, 21 / Gradle → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-boot",
    buildTool: "gradle",
    sourceBootMinInclusive: "4.0.0",
    sourceBootMaxExclusive: "4.1.1",
    sourceJavaVersions: ["17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringBoot4_0GradleToBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "spring-mvc-3.2-7.0-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Framework / Spring MVC 3.2–7.0.8 / Java 8, 11, 17, 21 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-mvc",
    buildTool: "maven",
    sourceBootMinInclusive: "3.2.0",
    sourceBootMaxExclusive: "7.0.9",
    sourceJavaVersions: ["8", "11", "17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringFrameworkMvcToSpringBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
  {
    routeId: "spring-framework-3.2-7.0-maven-to-boot-4.1.1-java-21",
    packKey: "spring-to-boot-4-1-1",
    label: "Spring Framework Core / Context 3.2–7.0.8 / Java 8, 11, 17, 21 / Maven → Spring Boot 4.1.1 / Java 21",
    sourceFrameworkFamily: "spring-framework",
    buildTool: "maven",
    sourceBootMinInclusive: "3.2.0",
    sourceBootMaxExclusive: "7.0.9",
    sourceJavaVersions: ["8", "11", "17", "21"],
    targetSpringBoot: "4.1.1",
    targetJava: "21",
    recipeId: "io.elmos.openrewrite.SpringFrameworkCoreToSpringBoot4_1_1Java21",
    evidenceStatus: "NOT_RUN",
    verifiedSourceSpringBoot: "",
    verifiedSourceJava: "",
  },
];
