// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    query: { type: String, value: "" },
    items: { type: Array, value: [] },
  },
  data: {},
  methods: {
    handleChangeInput0(event) {
      this.triggerEvent("tQuery", { value: event.detail.value });
    },
    handleClickButton1(event) {
      this.triggerEvent("tQuery", { value: "" });
    },
  },
});
