from __future__ import annotations
from typing import Dict, Any, List
from .base import ProjectGenerator
from ..models import PSIR, GeneratedProject, EntitySpec, EndpointSpec, ServiceSpec, FieldType
from ..type_mapper import TypeMapper, Language

class PythonFastAPIGenerator(ProjectGenerator):
    def __init__(self):
        self.type_mapper = TypeMapper()

    def generate(self, psir: PSIR) -> GeneratedProject:
        app_name = (psir.project_name or "fastapi-app").lower().replace(" ", "_")
        files: Dict[str, str] = {
            "pyproject.toml": self.generate_build_config(psir),
            "database.py": (
                "from sqlalchemy import create_engine\n"
                "from sqlalchemy.orm import declarative_base, sessionmaker\n\n"
                "DATABASE_URL = \"sqlite:///./app.db\"\n\n"
                "engine = create_engine(DATABASE_URL, connect_args={\"check_same_thread\": False})\n"
                "SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\n"
                "Base = declarative_base()\n\n"
                "def get_db():\n"
                "    db = SessionLocal()\n"
                "    try:\n"
                "        yield db\n"
                "    finally:\n"
                "        db.close()\n"
            ),
            "main.py": self._generate_main(psir)
        }

        # Entities -> SQLAlchemy Models, Pydantic Schemas, Services, Routers
        for entity in psir.entities:
            ename_lower = entity.name.lower()
            files[f"models/{ename_lower}.py"] = self.generate_entity(entity)
            files[f"schemas/{ename_lower}.py"] = self._generate_schema(entity)
            files[f"services/{ename_lower}_service.py"] = self._generate_service(entity)
            files[f"routers/{ename_lower}_router.py"] = self._generate_router(entity)

        # Standalone services
        for service in psir.services:
            sname = service.name.lower()
            sfile = f"services/{sname}_service.py"
            if sfile not in files:
                files[sfile] = self.generate_service(service)

        # Standalone endpoints
        for endpoint in psir.endpoints:
            ep_name = endpoint.path.strip("/").replace("/", "_") or "root"
            ep_file = f"routers/{ep_name}_router.py"
            if ep_file not in files:
                files[ep_file] = self.generate_endpoint(endpoint)

        tests = self.generate_tests(psir)
        files.update(tests)

        return GeneratedProject(
            project_root=psir.project_name or "fastapi-app",
            files=files,
            build_command="pip install -e .",
            run_command="uvicorn main:app --host 0.0.0.0 --port 8000 --reload",
            test_command="pytest"
        )

    def _generate_main(self, psir: PSIR) -> str:
        app_name = psir.project_name or "FastAPI Service"
        imports = ["from fastapi import FastAPI", "from database import Base, engine"]
        router_inclusions = []

        for entity in psir.entities:
            ename = entity.name.lower()
            imports.append(f"from routers.{ename}_router import router as {ename}_router")
            router_inclusions.append(f"app.include_router({ename}_router, prefix=\"/api/{ename}s\", tags=[\"{entity.name}\"])")

        for endpoint in psir.endpoints:
            ep_name = endpoint.path.strip("/").replace("/", "_") or "root"
            imports.append(f"from routers.{ep_name}_router import router as {ep_name}_router")
            router_inclusions.append(f"app.include_router({ep_name}_router, tags=[\"Custom\"])")

        imports_block = "\n".join(sorted(set(imports)))
        routers_block = "\n".join(router_inclusions) if router_inclusions else "pass"

        return (
            f"{imports_block}\n\n"
            f"Base.metadata.create_all(bind=engine)\n\n"
            f"app = FastAPI(\n"
            f"    title=\"{app_name}\",\n"
            f"    description=\"Generated by ELMOS Project Synthesis\",\n"
            f"    version=\"0.1.0\"\n"
            f")\n\n"
            f"@app.get(\"/health\")\n"
            f"def health_check():\n"
            f"    return {{\"status\": \"ok\", \"service\": \"{app_name}\"}}\n\n"
            f"{routers_block}\n"
        )

    def generate_entity(self, entity_spec: EntitySpec) -> str:
        ename = entity_spec.name
        table_name = ename.lower() + "s"
        sa_types = {
            FieldType.STRING: "String",
            FieldType.TEXT: "Text",
            FieldType.INT: "Integer",
            FieldType.FLOAT: "Float",
            FieldType.BOOLEAN: "Boolean",
            FieldType.DATE: "Date",
            FieldType.DATETIME: "DateTime",
            FieldType.UUID: "String(36)",
            FieldType.DECIMAL: "Numeric(12, 2)",
            FieldType.BLOB: "LargeBinary"
        }

        col_defs = []
        for f in entity_spec.fields:
            stype = sa_types.get(f.type, "String")
            opts = []
            if not f.required:
                opts.append("nullable=True")
            else:
                opts.append("nullable=False")
            if f.unique:
                opts.append("unique=True")
            opts_str = f", {', '.join(opts)}" if opts else ""
            col_defs.append(f"    {f.name} = Column({stype}{opts_str})")

        cols_str = "\n".join(col_defs) if col_defs else "    # No extra columns"

        return (
            "from sqlalchemy import Column, Integer, String, Text, Float, Boolean, Date, DateTime, Numeric, LargeBinary\n"
            "from database import Base\n\n"
            f"class {ename}(Base):\n"
            f"    __tablename__ = \"{table_name}\"\n\n"
            "    id = Column(Integer, primary_key=True, index=True, autoincrement=True)\n"
            f"{cols_str}\n"
        )

    def _generate_schema(self, entity_spec: EntitySpec) -> str:
        ename = entity_spec.name
        py_types = {
            FieldType.STRING: "str",
            FieldType.TEXT: "str",
            FieldType.INT: "int",
            FieldType.FLOAT: "float",
            FieldType.BOOLEAN: "bool",
            FieldType.DATE: "date",
            FieldType.DATETIME: "datetime",
            FieldType.UUID: "str",
            FieldType.DECIMAL: "float",
            FieldType.BLOB: "bytes"
        }

        base_fields = []
        for f in entity_spec.fields:
            ptype = py_types.get(f.type, "str")
            if not f.required:
                base_fields.append(f"    {f.name}: Optional[{ptype}] = None")
            else:
                base_fields.append(f"    {f.name}: {ptype}")

        fields_block = "\n".join(base_fields) if base_fields else "    pass"

        return (
            "from pydantic import BaseModel, ConfigDict\n"
            "from typing import Optional\n"
            "from datetime import date, datetime\n\n"
            f"class {ename}Base(BaseModel):\n"
            f"{fields_block}\n\n"
            f"class {ename}Create({ename}Base):\n"
            "    pass\n\n"
            f"class {ename}Update({ename}Base):\n"
            "    pass\n\n"
            f"class {ename}Response({ename}Base):\n"
            "    id: int\n"
            "    model_config = ConfigDict(from_attributes=True)\n"
        )

    def _generate_service(self, entity_spec: EntitySpec) -> str:
        ename = entity_spec.name
        elower = ename.lower()
        return (
            f"from sqlalchemy.orm import Session\n"
            f"from models.{elower} import {ename}\n"
            f"from schemas.{elower} import {ename}Create, {ename}Update\n"
            f"from typing import List, Optional\n\n"
            f"class {ename}Service:\n"
            f"    def __init__(self, db: Session):\n"
            f"        self.db = db\n\n"
            f"    def get_all(self, skip: int = 0, limit: int = 100) -> List[{ename}]:\n"
            f"        return self.db.query({ename}).offset(skip).limit(limit).all()\n\n"
            f"    def get_by_id(self, item_id: int) -> Optional[{ename}]:\n"
            f"        return self.db.query({ename}).filter({ename}.id == item_id).first()\n\n"
            f"    def create(self, item_in: {ename}Create) -> {ename}:\n"
            f"        db_item = {ename}(**item_in.model_dump())\n"
            f"        self.db.add(db_item)\n"
            f"        self.db.commit()\n"
            f"        self.db.refresh(db_item)\n"
            f"        return db_item\n\n"
            f"    def update(self, item_id: int, item_in: {ename}Update) -> Optional[{ename}]:\n"
            f"        db_item = self.get_by_id(item_id)\n"
            f"        if not db_item:\n"
            f"            return None\n"
            f"        for key, value in item_in.model_dump(exclude_unset=True).items():\n"
            f"            setattr(db_item, key, value)\n"
            f"        self.db.commit()\n"
            f"        self.db.refresh(db_item)\n"
            f"        return db_item\n\n"
            f"    def delete(self, item_id: int) -> bool:\n"
            f"        db_item = self.get_by_id(item_id)\n"
            f"        if not db_item:\n"
            f"            return False\n"
            f"        self.db.delete(db_item)\n"
            f"        self.db.commit()\n"
            f"        return True\n"
        )

    def _generate_router(self, entity_spec: EntitySpec) -> str:
        ename = entity_spec.name
        elower = ename.lower()
        return (
            f"from fastapi import APIRouter, Depends, HTTPException, status\n"
            f"from sqlalchemy.orm import Session\n"
            f"from typing import List\n"
            f"from database import get_db\n"
            f"from schemas.{elower} import {ename}Create, {ename}Update, {ename}Response\n"
            f"from services.{elower}_service import {ename}Service\n\n"
            f"router = APIRouter()\n\n"
            f"@router.get(\"/\", response_model=List[{ename}Response])\n"
            f"def list_{elower}s(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):\n"
            f"    service = {ename}Service(db)\n"
            f"    return service.get_all(skip=skip, limit=limit)\n\n"
            f"@router.get(\"/{{item_id}}\", response_model={ename}Response)\n"
            f"def get_{elower}(item_id: int, db: Session = Depends(get_db)):\n"
            f"    service = {ename}Service(db)\n"
            f"    item = service.get_by_id(item_id)\n"
            f"    if not item:\n"
            f"        raise HTTPException(status_code=404, detail=\"{ename} not found\")\n"
            f"    return item\n\n"
            f"@router.post(\"/\", response_model={ename}Response, status_code=status.HTTP_201_CREATED)\n"
            f"def create_{elower}(item_in: {ename}Create, db: Session = Depends(get_db)):\n"
            f"    service = {ename}Service(db)\n"
            f"    return service.create(item_in)\n\n"
            f"@router.put(\"/{{item_id}}\", response_model={ename}Response)\n"
            f"def update_{elower}(item_id: int, item_in: {ename}Update, db: Session = Depends(get_db)):\n"
            f"    service = {ename}Service(db)\n"
            f"    item = service.update(item_id, item_in)\n"
            f"    if not item:\n"
            f"        raise HTTPException(status_code=404, detail=\"{ename} not found\")\n"
            f"    return item\n\n"
            f"@router.delete(\"/{{item_id}}\", status_code=status.HTTP_204_NO_CONTENT)\n"
            f"def delete_{elower}(item_id: int, db: Session = Depends(get_db)):\n"
            f"    service = {ename}Service(db)\n"
            f"    success = service.delete(item_id)\n"
            f"    if not success:\n"
            f"        raise HTTPException(status_code=404, detail=\"{ename} not found\")\n"
            f"    return None\n"
        )

    def generate_endpoint(self, endpoint_spec: EndpointSpec) -> str:
        method = endpoint_spec.method.lower()
        path = endpoint_spec.path
        return (
            f"from fastapi import APIRouter\n\n"
            f"router = APIRouter()\n\n"
            f"@router.{method}(\"{path}\")\n"
            f"def handle_custom():\n"
            f"    return {{\"status\": \"ok\", \"path\": \"{path}\"}}\n"
        )

    def generate_service(self, service_spec: ServiceSpec) -> str:
        methods = []
        for m in service_spec.methods:
            methods.append(f"    def {m}(self):\n        pass")
        methods_str = "\n\n".join(methods) if methods else "    pass"
        return (
            f"class {service_spec.name}:\n"
            f"{methods_str}\n"
        )

    def generate_build_config(self, psir: PSIR | None = None) -> str:
        proj_name = (psir.project_name if psir else "app").lower().replace(" ", "-")
        return (
            "[project]\n"
            f"name = \"{proj_name}\"\n"
            "version = \"0.1.0\"\n"
            "description = \"Generated by ELMOS Project Synthesis\"\n"
            "requires-python = \">=3.10\"\n"
            "dependencies = [\n"
            "    \"fastapi>=0.115.0\",\n"
            "    \"uvicorn[standard]>=0.32.0\",\n"
            "    \"pydantic>=2.10.0\",\n"
            "    \"sqlalchemy>=2.0.36\",\n"
            "]\n\n"
            "[project.optional-dependencies]\n"
            "test = [\n"
            "    \"pytest>=8.0.0\",\n"
            "    \"httpx>=0.28.0\",\n"
            "]\n\n"
            "[build-system]\n"
            "requires = [\"setuptools>=61.0\"]\n"
            "build-backend = \"setuptools.build_meta\"\n"
        )

    def generate_config(self, psir: PSIR | None = None) -> str:
        return "# FastAPI Configuration\nHOST = \"0.0.0.0\"\nPORT = 8000\n"

    def generate_tests(self, psir: PSIR | None = None) -> Dict[str, str]:
        return {
            "tests/test_api.py": (
                "from fastapi.testclient import TestClient\n"
                "from main import app\n\n"
                "client = TestClient(app)\n\n"
                "def test_health_check():\n"
                "    response = client.get(\"/health\")\n"
                "    assert response.status_code == 200\n"
                "    data = response.json()\n"
                "    assert data[\"status\"] == \"ok\"\n"
            )
        }
