import type {
  ExactUiTargetProfile,
  UiConversionRoute,
  UiFrameworkId,
} from "./project-types.js";

const profiles: Readonly<Record<UiFrameworkId, ExactUiTargetProfile>> = {
  vue2: {
    id: "vue2",
    label: "Vue 2 compatibility target",
    frameworkVersion: "2.7.16",
    profileVersion: "1.0.0",
    status: "LEGACY_CONDITIONAL",
    platforms: ["WEB"],
    language: "JavaScript",
    languageVersion: "ECMAScript 2022",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Vite",
    buildToolVersion: "7.3.6",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "vue-router 3.6.5",
    state: "Vue.observable",
    rendering: "CSR",
    testTool: "Vitest 4.1.10",
    runnerProfile: "WEB_LEGACY",
    requiredProjectFiles: ["package.json", "vite.config.js", "src/main.js", "src/App.vue"],
  },
  vue3: {
    id: "vue3",
    label: "Vue 3",
    frameworkVersion: "3.5.40",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["WEB"],
    language: "TypeScript",
    languageVersion: "6.0.3",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Vite",
    buildToolVersion: "8.1.5",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "vue-router 4.6.4",
    state: "Pinia 4.0.2",
    rendering: "CSR",
    testTool: "Vitest 4.1.10",
    runnerProfile: "MODERN_WEB",
    requiredProjectFiles: ["package.json", "vite.config.ts", "src/main.ts", "src/App.vue"],
  },
  react: {
    id: "react",
    label: "React",
    frameworkVersion: "19.2.8",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["WEB"],
    language: "TypeScript",
    languageVersion: "7.0.2",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Vite",
    buildToolVersion: "8.1.5",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "react-router-dom 7.18.1",
    state: "React reducer/context",
    rendering: "CSR",
    testTool: "Vitest 4.1.10",
    runnerProfile: "MODERN_WEB",
    requiredProjectFiles: ["package.json", "vite.config.ts", "src/main.tsx", "src/App.tsx"],
  },
  "react-native": {
    id: "react-native",
    label: "React Native with Expo",
    frameworkVersion: "0.86.0",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["ANDROID", "IOS", "WEB"],
    language: "TypeScript",
    languageVersion: "6.0.3",
    runtime: "Expo",
    runtimeVersion: "57.0.8",
    nodeVersion: "26.0.0",
    buildTool: "Expo CLI",
    buildToolVersion: "57.0.10",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "React Navigation 7.3.14",
    state: "React reducer/context",
    rendering: "Native renderer with Hermes",
    testTool: "TypeScript and device E2E profile",
    runnerProfile: "MOBILE_CROSS_PLATFORM",
    requiredProjectFiles: ["package.json", "app.json", "App.tsx", "src/navigation.tsx"],
  },
  jquery: {
    id: "jquery",
    label: "jQuery compatibility target",
    frameworkVersion: "4.0.0",
    profileVersion: "1.0.0",
    status: "LEGACY_CONDITIONAL",
    platforms: ["WEB"],
    language: "TypeScript",
    languageVersion: "7.0.2",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Vite",
    buildToolVersion: "8.1.5",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "History API adapter",
    state: "Explicit immutable store",
    rendering: "CSR with isolated DOM ownership",
    testTool: "Vitest 4.1.10",
    runnerProfile: "WEB_LEGACY",
    requiredProjectFiles: ["package.json", "vite.config.ts", "index.html", "src/main.ts"],
  },
  flutter: {
    id: "flutter",
    label: "Flutter",
    frameworkVersion: "3.44.1",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["ANDROID", "IOS", "WEB"],
    language: "Dart",
    languageVersion: "3.12.1",
    runtime: "Flutter Engine",
    runtimeVersion: "3.44.1",
    buildTool: "flutter",
    buildToolVersion: "3.44.1",
    packageManager: "pub",
    packageManagerVersion: "3.12.1",
    router: "MaterialApp named routes",
    state: "ChangeNotifier-compatible generated boundary",
    rendering: "Flutter widgets",
    testTool: "flutter_test 3.44.1",
    runnerProfile: "MOBILE_CROSS_PLATFORM",
    requiredProjectFiles: ["pubspec.yaml", "analysis_options.yaml", "lib/main.dart", "test/widget_test.dart"],
  },
  "harmony-arkui": {
    id: "harmony-arkui",
    label: "HarmonyOS ArkUI",
    frameworkVersion: "6.0.0(20)",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["HARMONYOS"],
    language: "ArkTS",
    languageVersion: "HarmonyOS 6.0.0 API 20",
    runtime: "HarmonyOS",
    runtimeVersion: "6.0.0(20)",
    buildTool: "Hvigor",
    buildToolVersion: "DevEco Studio 6.0.0 Release bundled",
    packageManager: "ohpm",
    packageManagerVersion: "DevEco Studio 6.0.0 Release bundled",
    router: "ArkUI Navigation",
    state: "ArkUI observed state",
    rendering: "ArkUI declarative rendering",
    testTool: "Hypium profile",
    runnerProfile: "HARMONYOS",
    requiredProjectFiles: [
      "oh-package.json5",
      "hvigor/hvigor-config.json5",
      "build-profile.json5",
      "AppScope/app.json5",
      "entry/src/main/module.json5",
      "entry/src/main/ets/pages/Index.ets",
    ],
  },
  angular: {
    id: "angular",
    label: "Angular",
    frameworkVersion: "22.0.8",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["WEB"],
    language: "TypeScript",
    languageVersion: "6.0.3",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Angular CLI",
    buildToolVersion: "22.0.8",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "Angular Router 22.0.8",
    state: "Angular signals",
    rendering: "CSR",
    testTool: "Angular build and browser E2E profile",
    runnerProfile: "MODERN_WEB",
    requiredProjectFiles: ["package.json", "angular.json", "src/main.ts", "src/app/app.component.ts"],
  },
  svelte: {
    id: "svelte",
    label: "Svelte",
    frameworkVersion: "5.56.8",
    profileVersion: "1.0.0",
    status: "ACTIVE",
    platforms: ["WEB"],
    language: "TypeScript",
    languageVersion: "6.0.3",
    runtime: "Node.js",
    runtimeVersion: "26.0.0",
    nodeVersion: "26.0.0",
    buildTool: "Vite",
    buildToolVersion: "8.1.5",
    packageManager: "npm",
    packageManagerVersion: "11.12.1",
    router: "History API adapter",
    state: "Svelte runes",
    rendering: "CSR",
    testTool: "Vitest 4.1.10",
    runnerProfile: "MODERN_WEB",
    requiredProjectFiles: ["package.json", "svelte.config.js", "vite.config.ts", "src/main.ts", "src/App.svelte"],
  },
};

export const recommendedExtensionProfiles = [
  { id: "nextjs", category: "SSR_FULL_STACK", state: "PLANNED" },
  { id: "nuxt", category: "SSR_FULL_STACK", state: "PLANNED" },
  { id: "jetpack-compose", category: "NATIVE_ANDROID", state: "PLANNED" },
  { id: "swiftui", category: "NATIVE_APPLE", state: "PLANNED" },
  { id: "electron", category: "DESKTOP", state: "DETECTED_ONLY" },
  { id: "tauri", category: "DESKTOP", state: "PLANNED" },
  { id: "ionic-capacitor", category: "HYBRID_MOBILE", state: "DETECTED_ONLY" },
  { id: "uni-app", category: "CHINA_MULTI_END", state: "PLANNED" },
  { id: "wechat-mini-program", category: "MINI_PROGRAM", state: "PLANNED" },
] as const;

export function uiTargetProfiles(): readonly ExactUiTargetProfile[] {
  return Object.values(profiles).sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0);
}

export function uiTargetProfile(id: UiFrameworkId): ExactUiTargetProfile {
  return profiles[id];
}

export function uiConversionRoutes(): readonly UiConversionRoute[] {
  const ids = uiTargetProfiles().map(profile => profile.id);
  return ids.flatMap(source => ids
    .filter(target => target !== source)
    .map(target => {
      const sourceProfile = profiles[source];
      const targetProfile = profiles[target];
      const sourceWebOnly = sourceProfile.platforms.length === 1 && sourceProfile.platforms[0] === "WEB";
      const targetWebOnly = targetProfile.platforms.length === 1 && targetProfile.platforms[0] === "WEB";
      const supportState = targetProfile.status === "LEGACY_CONDITIONAL"
        ? "LEGACY_TARGET_CONDITIONAL" as const
        : sourceWebOnly === targetWebOnly
          ? "PROJECT_GENERATION_READY" as const
          : "ADAPTER_REQUIRED" as const;
      return {
        routeId: `${source}--to--${target}`,
        source,
        target,
        sourceProfileVersion: sourceProfile.frameworkVersion,
        targetProfileVersion: targetProfile.frameworkVersion,
        supportState,
        semanticConversionEvidence: "NOT_RUN" as const,
        runtimeEvidence: "NOT_RUN" as const,
        certification: "NOT_CERTIFIED" as const,
      };
    }));
}

export function uiConversionRoute(source: UiFrameworkId, target: UiFrameworkId): UiConversionRoute {
  const route = uiConversionRoutes().find(candidate => candidate.source === source && candidate.target === target);
  if (!route) throw new Error("source and target frameworks must be different supported profiles");
  return route;
}
