import {
  FullSyntaxComponentIR,
  FullSyntaxEvent,
  FullSyntaxNode,
  FullSyntaxProp,
  FullSyntaxSlot,
  FullSyntaxState,
} from "../types";
import {
  ArkUIComponentAst,
  ArkUIModifier,
  ArkUINode,
} from "./arkui-full-ast-types";

export interface ArkUIEmitOptions {
  isEntry?: boolean;
  isPreview?: boolean;
  useTypescript?: boolean;
}

export class ArkUIFullAstEmitter {
  public emit(irOrAst: FullSyntaxComponentIR | ArkUIComponentAst, options: ArkUIEmitOptions = {}): string {
    if ("structName" in irOrAst) {
      return this.emitAst(irOrAst, options);
    }
    const ir = irOrAst;
    const lines: string[] = [];

    // Header comment
    lines.push(`// Generated by ELMOS ArkUI Full-Syntax Emitter (ArkTS 3.0 Declarative UI)`);
    lines.push(`// Component: ${ir.componentName}`);
    lines.push(``);

    // Decorators
    if (options.isEntry || ir.metadata?.isEntry) {
      lines.push(`@Entry`);
    }
    if (options.isPreview || ir.metadata?.isPreview) {
      lines.push(`@Preview`);
    }
    lines.push(`@Component`);
    lines.push(`export struct ${ir.componentName} {`);

    // State properties (@State)
    for (const state of ir.states) {
      const typeStr = state.typeAnnotation ? `: ${state.typeAnnotation}` : "";
      const initStr = state.initialValueExpr ? ` = ${state.initialValueExpr}` : "";
      lines.push(`  @State ${state.name}${typeStr}${initStr};`);
    }

    // Props (@Prop / @Link)
    for (const prop of ir.props) {
      const isTwoWay = prop.name.startsWith("model") || prop.name.endsWith("Change");
      const dec = isTwoWay ? "@Link" : "@Prop";
      const typeStr = prop.typeAnnotation ? `: ${prop.typeAnnotation}` : ": any";
      const defStr = prop.defaultValue !== undefined ? ` = ${JSON.stringify(prop.defaultValue)}` : "";
      lines.push(`  ${dec} ${prop.name}${typeStr}${defStr};`);
    }

    // Slots (@BuilderParam)
    for (const slot of ir.slots) {
      const slotName = slot.name === "default" ? "defaultSlot" : slot.name;
      lines.push(`  @BuilderParam ${slotName}?: () => void;`);
    }

    // Lifecycle hooks
    const mountEffect = ir.effects.find((e) => e.hookKind === "mount");
    if (mountEffect) {
      lines.push(``);
      lines.push(`  aboutToAppear() {`);
      lines.push(`    ${mountEffect.bodyCode.trim()}`);
      lines.push(`  }`);
    }

    const unmountEffect = ir.effects.find((e) => e.hookKind === "unmount");
    if (unmountEffect) {
      lines.push(``);
      lines.push(`  aboutToDisappear() {`);
      lines.push(`    ${unmountEffect.bodyCode.trim()}`);
      lines.push(`  }`);
    }

    // Custom Methods
    for (const method of ir.methods) {
      lines.push(``);
      const params = method.parameters.map((p) => `${p.name}: ${p.type}`).join(", ");
      const ret = method.returnType ? `: ${method.returnType}` : "";
      const asyncPrefix = method.isAsync ? "async " : "";
      lines.push(`  ${asyncPrefix}${method.name}(${params})${ret} {`);
      lines.push(`    ${method.bodyCode.trim()}`);
      lines.push(`  }`);
    }

    // Build function
    lines.push(``);
    lines.push(`  build() {`);
    if (ir.templateRoot) {
      const buildBody = this.emitNode(ir.templateRoot, "    ");
      lines.push(buildBody);
    } else {
      lines.push(`    Column() {`);
      lines.push(`      Text('${ir.componentName}')`);
      lines.push(`    }`);
    }
    lines.push(`  }`);

    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
  }

  public emitAst(ast: ArkUIComponentAst, options: ArkUIEmitOptions = {}): string {
    const lines: string[] = [];

    // Header comment
    lines.push(`// Generated by ELMOS ArkUI Full-Syntax Emitter (ArkTS 3.0 Declarative UI)`);
    lines.push(`// Component: ${ast.structName}`);
    lines.push(``);

    // Decorators
    if (options.isEntry || ast.isEntry) {
      lines.push(`@Entry`);
    }
    if (options.isPreview || ast.isPreview) {
      lines.push(`@Preview`);
    }
    lines.push(`@Component`);
    lines.push(`export struct ${ast.structName} {`);

    // State properties
    for (const prop of ast.stateProperties) {
      const dec = prop.decorator?.kind || "@State";
      const typeStr = prop.typeAnnotation ? `: ${prop.typeAnnotation}` : "";
      const initStr = prop.initialValueExpr !== undefined ? ` = ${prop.initialValueExpr}` : "";
      lines.push(`  ${dec} ${prop.name}${typeStr}${initStr};`);
    }

    // Builder params
    for (const bp of ast.builderParams) {
      lines.push(`  @BuilderParam ${bp.name}?: ${bp.typeAnnotation || "() => void"};`);
    }

    // Lifecycle methods
    for (const hook of ast.lifecycleMethods) {
      lines.push(``);
      lines.push(`  ${hook.name}() {`);
      lines.push(`    ${hook.bodyCode.trim()}`);
      lines.push(`  }`);
    }

    // Custom methods
    for (const method of ast.customMethods) {
      lines.push(``);
      const params = method.parameters.map((p) => `${p.name}: ${p.type}`).join(", ");
      const ret = method.returnType ? `: ${method.returnType}` : "";
      const asyncPrefix = method.isAsync ? "async " : "";
      lines.push(`  ${asyncPrefix}${method.name}(${params})${ret} {`);
      lines.push(`    ${method.bodyCode.trim()}`);
      lines.push(`  }`);
    }

    // Build function
    lines.push(``);
    lines.push(`  build() {`);
    if (ast.buildRoot) {
      lines.push(this.emitArkUINode(ast.buildRoot, "    "));
    } else {
      lines.push(`    Column() {`);
      lines.push(`      Text('${ast.structName}')`);
      lines.push(`    }`);
    }
    lines.push(`  }`);

    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
  }

  private emitArkUINode(node: ArkUINode, indent: string): string {
    const lines: string[] = [];
    const argsStr = node.constructorArgs && node.constructorArgs.length > 0 ? node.constructorArgs.join(", ") : "";
    const openCall = `${indent}${node.componentName}(${argsStr})`;

    if (!node.children || node.children.length === 0) {
      let nodeStr = openCall;
      for (const mod of node.modifiers || []) {
        const modArgs = mod.args && mod.args.length > 0 ? mod.args.join(", ") : "";
        nodeStr += `\n${indent}  .${mod.name}(${modArgs})`;
      }
      return nodeStr;
    }

    lines.push(`${openCall} {`);
    for (const child of node.children) {
      lines.push(this.emitArkUINode(child, indent + "  "));
    }
    lines.push(`${indent}}`);

    if (node.modifiers && node.modifiers.length > 0) {
      for (const mod of node.modifiers) {
        const modArgs = mod.args && mod.args.length > 0 ? mod.args.join(", ") : "";
        lines.push(`${indent}  .${mod.name}(${modArgs})`);
      }
    }

    return lines.join("\n");
  }

  private emitNode(node: FullSyntaxNode, indent: string): string {
    const lines: string[] = [];

    // Check for conditional
    if (node.condition) {
      lines.push(`${indent}if (${node.condition.test}) {`);
      lines.push(this.emitNode(node.condition.thenNode, indent + "  "));
      if (node.condition.elifBranches) {
        for (const branch of node.condition.elifBranches) {
          lines.push(`${indent}} else if (${branch.test}) {`);
          lines.push(this.emitNode(branch.node, indent + "  "));
        }
      }
      if (node.condition.elseNode) {
        lines.push(`${indent}} else {`);
        lines.push(this.emitNode(node.condition.elseNode, indent + "  "));
      }
      lines.push(`${indent}}`);
      return lines.join("\n");
    }

    // Check for loop
    if (node.loop) {
      const { sourceExpr, itemName, indexName, keyExpr, bodyNode } = node.loop;
      const keyArg = keyExpr ? `, (${itemName}) => ${keyExpr}` : "";
      const idxParam = indexName ? `, ${indexName}: number` : "";
      lines.push(`${indent}ForEach(${sourceExpr}, (${itemName}${idxParam}) => {`);
      lines.push(this.emitNode(bodyNode, indent + "  "));
      lines.push(`${indent}}${keyArg})`);
      return lines.join("\n");
    }

    // Normal component / element mapping
    const arkTag = this.mapTagToArkUI(node.tag || "view");
    const isContainer = this.isContainerComponent(arkTag);

    // Modifiers & attrs
    const modifiers: string[] = [];
    let constructorArg = "";

    // If Text or Button, text can be constructor arg
    if (arkTag === "Text") {
      if (node.text) {
        constructorArg = `'${node.text.replace(/'/g, "\\'")}'`;
      } else if (node.expression) {
        constructorArg = node.expression;
      }
    } else if (arkTag === "Button") {
      if (node.text) {
        constructorArg = `'${node.text.replace(/'/g, "\\'")}'`;
      }
    }

    // Attribute mapping to ArkUI modifiers
    if (node.attrs) {
      for (const attr of node.attrs) {
        if (attr.name === "class" || attr.name === "className") {
          // CSS class / styling
          modifiers.push(`.id('${attr.value}')`);
        } else if (attr.name === "style") {
          this.parseInlineStyleModifiers(attr.value, modifiers);
        } else if (attr.name === "width") {
          modifiers.push(`.width(${this.formatDimension(attr.value)})`);
        } else if (attr.name === "height") {
          modifiers.push(`.height(${this.formatDimension(attr.value)})`);
        } else if (attr.name === "color") {
          modifiers.push(`.fontColor('${attr.value}')`);
        } else if (attr.name === "disabled") {
          modifiers.push(`.enabled(${attr.value !== "true"})`);
        } else if (attr.name === "placeholder") {
          modifiers.push(`.placeholder('${attr.value}')`);
        } else {
          modifiers.push(`.${attr.name}(${attr.isDynamic && attr.expression ? attr.expression : `'${attr.value}'`})`);
        }
      }
    }

    // Events mapping
    if (node.events) {
      for (const ev of node.events) {
        const handlerStr = this.formatEventHandler(ev);
        if (ev.name === "click" || ev.name === "tap") {
          modifiers.push(`.onClick(${handlerStr})`);
        } else if (ev.name === "change" || ev.name === "input") {
          modifiers.push(`.onChange(${handlerStr})`);
        } else if (ev.name === "submit") {
          modifiers.push(`.onSubmit(${handlerStr})`);
        } else {
          modifiers.push(`.on('${ev.name}', ${handlerStr})`);
        }
      }
    }

    if (isContainer) {
      lines.push(`${indent}${arkTag}(${constructorArg}) {`);
      if (node.children && node.children.length > 0) {
        for (const child of node.children) {
          lines.push(this.emitNode(child, indent + "  "));
        }
      }
      lines.push(`${indent}}`);
    } else {
      lines.push(`${indent}${arkTag}(${constructorArg})`);
    }

    // Append chained modifiers
    if (modifiers.length > 0) {
      for (const mod of modifiers) {
        lines[lines.length - 1] += `\n${indent}  ${mod}`;
      }
    }

    return lines.join("\n");
  }

  private mapTagToArkUI(tag: string): string {
    const lower = tag.toLowerCase();
    switch (lower) {
      case "div":
      case "view":
      case "section":
        return "Column";
      case "span":
      case "p":
      case "h1":
      case "h2":
      case "h3":
      case "text":
        return "Text";
      case "button":
        return "Button";
      case "input":
        return "TextInput";
      case "textarea":
        return "TextArea";
      case "img":
      case "image":
        return "Image";
      case "ul":
      case "ol":
        return "List";
      case "li":
        return "ListItem";
      case "switch":
        return "Toggle";
      case "progress":
        return "Progress";
      case "scroll-view":
        return "Scroll";
      default:
        // Already capitalized or custom component
        if (/^[A-Z]/.test(tag)) {
          return tag;
        }
        return "Column";
    }
  }

  private isContainerComponent(tag: string): boolean {
    return [
      "Column",
      "Row",
      "Stack",
      "Flex",
      "Grid",
      "GridItem",
      "List",
      "ListItem",
      "Scroll",
      "Swiper",
      "Tabs",
      "TabContent",
      "RelativeContainer",
      "SideBarContainer",
    ].includes(tag);
  }

  private formatDimension(val: string): string {
    if (/^\d+$/.test(val)) {
      return val;
    }
    if (val.endsWith("px") || val.endsWith("vp")) {
      const num = parseInt(val, 10);
      return isNaN(num) ? `'${val}'` : `${num}`;
    }
    return `'${val}'`;
  }

  private parseInlineStyleModifiers(styleStr: string, modifiers: string[]): void {
    const declarations = styleStr.split(";").map((s) => s.trim()).filter(Boolean);
    for (const decl of declarations) {
      const [prop, rawVal] = decl.split(":").map((s) => s.trim());
      if (!prop || !rawVal) continue;

      if (prop === "background-color" || prop === "backgroundColor") {
        modifiers.push(`.backgroundColor('${rawVal}')`);
      } else if (prop === "font-size" || prop === "fontSize") {
        modifiers.push(`.fontSize(${this.formatDimension(rawVal)})`);
      } else if (prop === "color") {
        modifiers.push(`.fontColor('${rawVal}')`);
      } else if (prop === "padding") {
        modifiers.push(`.padding(${this.formatDimension(rawVal)})`);
      } else if (prop === "margin") {
        modifiers.push(`.margin(${this.formatDimension(rawVal)})`);
      } else if (prop === "border-radius" || prop === "borderRadius") {
        modifiers.push(`.borderRadius(${this.formatDimension(rawVal)})`);
      } else if (prop === "opacity") {
        modifiers.push(`.opacity(${rawVal})`);
      }
    }
  }

  private formatEventHandler(ev: FullSyntaxEvent): string {
    const handler = ev.handlerNameOrExpr.trim();
    if (handler.startsWith("() =>") || handler.startsWith("function")) {
      return handler;
    }
    if (handler.includes("(") && handler.includes(")")) {
      return `() => { ${handler} }`;
    }
    return `() => { this.${handler}() }`;
  }
}
