-- Target DDL for Dameng 8 (DM8)
-- Generated by Elmos SQL Dialect Engine (Batch 31 Profile)

CREATE TABLE orders (
    id BIGINT IDENTITY(1, 1) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    amount_cents BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE INDEX idx_orders_tenant_created ON orders (tenant_id, created_at DESC);
