// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {},
  data: {
    draft: "",
    projectRef: null,
  },
  methods: {
    handleChangeInput0(event) {
      this.setData({ draft: event.detail.value });
    },
    handleClickButton1(event) {
      this.setData({ projectRef: this.data.draft.trim() });
    },
  },
});
