"""ELMOS Polyglot Repository Semantic Compiler Engine v3.0.0."""

from .api_contract_diff import (
    ApiContractDiffer,
    ContractDiffItem,
    ContractDiffReport,
    run_api_contract_diff,
)
from .catalog import CatalogError, CompiledCatalog, load_catalog
from .contracts import (
    AuthorityError,
    ContractError,
    ExecutionAuthority,
    IdempotencyConflict,
    RuntimeRequest,
    canonical_json,
    digest_json,
)
from .models import (
    BatchType,
    BehaviorOracle,
    CapabilityMode,
    CertificationRun,
    CertificationState,
    Counterexample,
    DifferentialResult,
    EvidenceState,
    ExecutionState,
    ObligationStatus,
    ProofObligation,
    RouteCell,
    RouteCertificationPlan,
    SemanticObligation,
    SemanticRisk,
    SkillDefinition,
    TechnologySurface,
    VerdictStatus,
)
from .regression_bisector import (
    BisectResult,
    BisectStep,
    SemanticRegressionBisector,
    run_semantic_bisect,
)
from .runtime import (
    HandlerBinding,
    SkillRuntime,
    SkillRuntimeError,
    build_registry,
    capability_manifest,
    validate_registry,
)
from .service import (
    PolyglotSemanticCompilerService,
    ServiceError,
    certify_language_route,
    check_smt_formula,
    get_compiler_status,
    get_supported_routes,
    run_differential_fuzzing,
    transform_snippet,
)
from .tree_sitter_incremental import (
    AstSpan,
    IncrementalAstNode,
    IncrementalAstTree,
    TreeSitterIncrementalParser,
    parse_incremental_cst,
)

__version__ = "3.0.0"

__all__ = [
    "ApiContractDiffer",
    "AstSpan",
    "AuthorityError",
    "BatchType",
    "BehaviorOracle",
    "BisectResult",
    "BisectStep",
    "CapabilityMode",
    "CatalogError",
    "CertificationRun",
    "CertificationState",
    "CompiledCatalog",
    "ContractDiffItem",
    "ContractDiffReport",
    "ContractError",
    "Counterexample",
    "DifferentialResult",
    "EvidenceState",
    "ExecutionAuthority",
    "ExecutionState",
    "HandlerBinding",
    "IdempotencyConflict",
    "IncrementalAstNode",
    "IncrementalAstTree",
    "ObligationStatus",
    "PolyglotSemanticCompilerService",
    "ProofObligation",
    "RouteCell",
    "RouteCertificationPlan",
    "RuntimeRequest",
    "SemanticObligation",
    "SemanticRegressionBisector",
    "SemanticRisk",
    "ServiceError",
    "SkillDefinition",
    "SkillRuntime",
    "SkillRuntimeError",
    "TechnologySurface",
    "TreeSitterIncrementalParser",
    "VerdictStatus",
    "build_registry",
    "canonical_json",
    "capability_manifest",
    "certify_language_route",
    "check_smt_formula",
    "digest_json",
    "get_compiler_status",
    "get_supported_routes",
    "load_catalog",
    "parse_incremental_cst",
    "run_api_contract_diff",
    "run_differential_fuzzing",
    "run_semantic_bisect",
    "transform_snippet",
    "validate_registry",
]
