package io.elmos.persistence;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class TenantMigrationContractTest {
    @Test void batchNineThroughFortySevenMigrationsEnforceTenantAndAppendOnlyBoundaries() throws Exception {
        Path root = Path.of(System.getProperty("basedir"), "src", "main", "resources", "db", "migration");
        String v9 = Files.readString(root.resolve("V9__enterprise_identity_tenant_and_private_execution.sql"));
        String v10 = Files.readString(root.resolve("V10__commercial_operations_and_asset_reuse.sql"));
        String v11 = Files.readString(root.resolve("V11__dotnet_second_language_engine.sql"));
        String v12 = Files.readString(root.resolve("V12__python_legacy_modernization_engine.sql"));
        String v13 = Files.readString(root.resolve("V13__cross_language_composite_modernization.sql"));
        String v14 = Files.readString(root.resolve("V14__frontend_client_modernization_engine.sql"));
        String v15 = Files.readString(root.resolve("V15__database_and_data_platform_modernization.sql"));
        String v16 = Files.readString(root.resolve("V16__cloud_and_infrastructure_modernization.sql"));
        String v17 = Files.readString(root.resolve("V17__security_and_compliance_modernization.sql"));
        String v18 = Files.readString(root.resolve("V18__test_and_quality_engineering_modernization.sql"));
        String v20 = Files.readString(root.resolve("V20__enterprise_commercial_loop_extensions.sql"));
        String v21 = Files.readString(root.resolve("V21__enterprise_integration_middleware_modernization.sql"));
        String v22 = Files.readString(root.resolve("V22__product_ecosystem_growth_and_regional_replication.sql"));
        String v23 = Files.readString(root.resolve("V23__enterprise_suite_modernization.sql"));
        String v24 = Files.readString(root.resolve("V24__company_operating_and_governance_system.sql"));
        String v25 = Files.readString(root.resolve("V25__ai_native_company_and_agent_workforce.sql"));
        String v26 = Files.readString(root.resolve("V26__vertical_solution_factory.sql"));
        String v27 = Files.readString(root.resolve("V27__group_integration_factory.sql"));
        String v28 = Files.readString(root.resolve("V28__software_delivery_platform_engine.sql"));
        String v29 = Files.readString(root.resolve("V29__ai_ml_generative_ai_platform.sql"));
        String v30 = Files.readString(root.resolve("V30__edge_iot_industrial_systems.sql"));
        String v31 = Files.readString(root.resolve("V31__operations_sre_itsm.sql"));
        String v32 = Files.readString(root.resolve("V32__enterprise_architecture_portfolio.sql"));
        String v33 = Files.readString(root.resolve("V33__technology_business_management.sql"));
        String v34 = Files.readString(root.resolve("V34__organization_workforce_modernization.sql"));
        String v35 = Files.readString(root.resolve("V35__transformation_execution_change_management.sql"));
        String v36 = Files.readString(root.resolve("V36__autonomous_modernization_control_tower.sql"));
        String v37 = Files.readString(root.resolve("V37__reference_mvp_engineering.sql"));
        String v38 = Files.readString(root.resolve("V38__mvp_gap_review_remediation.sql"));
        String v39 = Files.readString(root.resolve("V39__secure_java_vertical_loop.sql"));
        String v40 = Files.readString(root.resolve("V40__enterprise_identity_access_governance.sql"));
        String v41 = Files.readString(root.resolve("V41__migration_pack_certification_admission.sql"));
        String v42 = Files.readString(root.resolve("V42__product_source_control_and_workspace.sql"));
        String v43 = Files.readString(root.resolve("V43__product_secure_execution_plane.sql"));
        String v44 = Files.readString(root.resolve("V44__product_artifact_evidence_fabric.sql"));
        String v45 = Files.readString(root.resolve("V45__product_external_evidence_producers.sql"));
        String v46 = Files.readString(root.resolve("V46__product_assurance_analytics.sql"));
        String v47 = Files.readString(root.resolve("V47__product_continuous_authorization.sql"));
        assertTrue(v9.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v9.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v9.contains("elmos_forbid_append_only_mutation"));
        assertTrue(v9.contains("CREATE TABLE runner_job_leases"));
        assertTrue(v10.contains("CREATE TABLE entitlements"));
        assertTrue(v10.contains("CREATE TABLE support_tickets"));
        assertTrue(v10.contains("commercial_events_append_only"));
        assertTrue(v11.contains("dotnet_solutions"));
        assertTrue(v11.contains("roslyn_symbols"));
        assertTrue(v11.contains("dotnet_compatibility_results"));
        assertTrue(v11.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v11.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v11.contains("dotnet_build_runs_append_only"));
        assertFalse(v11.contains("CREATE TABLE workflow"));
        assertFalse(v11.contains("CREATE TABLE billing"));
        assertTrue(v12.contains("python_environment_snapshots"));
        assertTrue(v12.contains("python_cst_snapshots"));
        assertTrue(v12.contains("numerical_comparisons"));
        assertTrue(v12.contains("ml_evaluation_results"));
        assertTrue(v12.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v12.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v12.contains("python_environment_snapshots_append_only"));
        assertFalse(v12.contains("CREATE TABLE workflow"));
        assertFalse(v12.contains("CREATE TABLE billing"));
        assertFalse(v12.contains("secret_value"));
        assertTrue(v13.contains("system_landscape_versions"));
        assertTrue(v13.contains("contract_consumer_matrix"));
        assertTrue(v13.contains("shadow_differential_results"));
        assertTrue(v13.contains("traffic_shift_decisions"));
        assertTrue(v13.contains("legacy_access_records"));
        assertTrue(v13.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v13.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v13.contains("shadow_differential_results_append_only"));
        assertFalse(v13.contains("CREATE TABLE workflow"));
        assertFalse(v13.contains("CREATE TABLE billing"));
        assertFalse(v13.contains("secret_value"));
        assertTrue(v14.contains("client_applications"));
        assertTrue(v14.contains("frontend_routes"));
        assertTrue(v14.contains("visual_differences"));
        assertTrue(v14.contains("accessibility_findings"));
        assertTrue(v14.contains("client_cutover_decisions"));
        assertTrue(v14.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v14.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v14.contains("visual_differences_append_only"));
        assertFalse(v14.contains("CREATE TABLE workflow"));
        assertFalse(v14.contains("CREATE TABLE billing"));
        assertFalse(v14.contains("secret_value"));
        assertTrue(v15.contains("database_estates"));
        assertTrue(v15.contains("sql_workloads"));
        assertTrue(v15.contains("data_quality_results"));
        assertTrue(v15.contains("lakehouse_protocol_profiles"));
        assertTrue(v15.contains("semantic_metrics"));
        assertTrue(v15.contains("lineage_events"));
        assertTrue(v15.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v15.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v15.contains("data_reconciliation_results_append_only"));
        assertTrue(v15.contains("ALTER TABLE cdc_streams"));
        assertFalse(v15.contains("'cdc_streams','cdc_offsets'"));
        assertFalse(v15.contains("CREATE TABLE workflow"));
        assertFalse(v15.contains("CREATE TABLE billing"));
        assertFalse(v15.contains("secret_value"));
        assertTrue(v16.contains("infrastructure_estates"));
        assertTrue(v16.contains("workload_placement_decisions"));
        assertTrue(v16.contains("container_sboms"));
        assertTrue(v16.contains("kubernetes_network_policies"));
        assertTrue(v16.contains("infrastructure_state_versions"));
        assertTrue(v16.contains("operational_readiness_results"));
        assertTrue(v16.contains("unit_economics_metrics"));
        assertTrue(v16.contains("chaos_experiment_runs"));
        assertTrue(v16.contains("portability_profiles"));
        assertTrue(v16.contains("infrastructure_decommission_plans"));
        assertTrue(v16.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v16.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v16.contains("infrastructure_apply_runs_append_only"));
        assertTrue(v16.contains("ALTER TABLE service_level_objectives"));
        assertFalse(v16.contains("'service_level_objectives','backup_runs','restore_runs','disaster_recovery_tests'"));
        assertFalse(v16.contains("CREATE TABLE workflow"));
        assertFalse(v16.contains("CREATE TABLE billing"));
        assertFalse(v16.contains("secret_value"));
        assertFalse(v9.contains("secret_value"));
        assertTrue(v17.contains("security_estates"));
        assertTrue(v17.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v17.contains("authorization_packages_append_only"));
        assertFalse(v17.contains("secret_value"));
        assertTrue(v18.contains("test_estates"));
        assertTrue(v18.contains("quality_risks"));
        assertTrue(v18.contains("mutation_results"));
        assertTrue(v18.contains("ai_test_promotion_decisions"));
        assertTrue(v18.contains("continuous_validation_runs"));
        assertTrue(v18.contains("ALTER TABLE test_suites"));
        assertFalse(v18.contains("'test_suites','test_case_identities'"));
        assertTrue(v18.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v18.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v18.contains("quality_decisions_append_only"));
        assertFalse(v18.contains("CREATE TABLE workflow"));
        assertFalse(v18.contains("CREATE TABLE billing"));
        assertFalse(v18.contains("secret_value"));
        assertTrue(v20.contains("commercial_leads"));
        assertTrue(v20.contains("commercial_opportunities"));
        assertTrue(v20.contains("commercial_poc_results"));
        assertTrue(v20.contains("commercial_acceptances"));
        assertTrue(v20.contains("commercial_partner_settlements"));
        assertTrue(v20.contains("commercial_value_realizations"));
        assertTrue(v20.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v20.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v20.contains("commercial_acceptances_append_only"));
        assertTrue(v20.contains("V10 remains authoritative"));
        assertFalse(v20.contains("CREATE TABLE billing"));
        assertFalse(v20.contains("secret_value"));
        assertTrue(v22.contains("north_star_metrics"));
        assertTrue(v22.contains("growth_events"));
        assertTrue(v22.contains("experiment_results"));
        assertTrue(v22.contains("developer_profiles"));
        assertTrue(v22.contains("community_spaces"));
        assertTrue(v22.contains("marketplace_assets"));
        assertTrue(v22.contains("publisher_payouts"));
        assertTrue(v22.contains("locales"));
        assertTrue(v22.contains("regional_metrics"));
        assertTrue(v22.contains("growth_economics"));
        assertTrue(v22.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v22.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v22.contains("external_operation_executed = false"));
        assertTrue(v22.contains("batch14_experiment_results_append_only"));
        assertTrue(v22.contains("batch14_publisher_payouts_append_only"));
        assertTrue(v22.contains("batch14_growth_economics_append_only"));
        assertTrue(v22.contains("V10 remains authoritative"));
        assertFalse(v22.contains("CREATE TABLE billing"));
        assertFalse(v22.contains("secret_value"));
        assertTrue(v21.contains("integration_estates"));
        assertTrue(v21.contains("message_topics"));
        assertTrue(v21.contains("partner_agreements"));
        assertTrue(v21.contains("workflow_instances"));
        assertTrue(v21.contains("integration_replay_runs"));
        assertTrue(v21.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v21.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v21.contains("message_delivery_results_append_only"));
        assertTrue(v21.contains("ALTER TABLE message_contracts"));
        assertTrue(v21.contains("Batch 7/13/16 remain authoritative"));
        assertFalse(v21.contains("'message_brokers','message_contracts'"));
        assertFalse(v21.contains("CREATE TABLE workflow"));
        assertFalse(v21.contains("CREATE TABLE billing"));
        assertFalse(v21.contains("secret_value"));
        assertTrue(v23.contains("enterprise_suite_estates"));
        assertTrue(v23.contains("suite_customizations"));
        assertTrue(v23.contains("business_processes"));
        assertTrue(v23.contains("master_data_crosswalks"));
        assertTrue(v23.contains("suite_sod_conflicts"));
        assertTrue(v23.contains("financial_reconciliations"));
        assertTrue(v23.contains("suite_decommission_plans"));
        assertTrue(v23.contains("FORCE ROW LEVEL SECURITY"));
        assertTrue(v23.contains("current_setting(''app.organization_id'', true)"));
        assertTrue(v23.contains("process_equivalence_results_append_only"));
        assertTrue(v23.contains("Batch 13 remains authoritative for business_capabilities"));
        assertTrue(v23.contains("ALTER TABLE business_capabilities"));
        assertFalse(v23.contains("CREATE TABLE workflow"));
        assertFalse(v23.contains("CREATE TABLE billing"));
        assertFalse(v23.contains("secret_value"));
        for (String migration : new String[]{v24, v25, v26, v27}) {
            assertTrue(migration.contains("FORCE ROW LEVEL SECURITY"));
            assertTrue(migration.contains("current_setting(''app.organization_id'', true)"));
            assertTrue(migration.contains("external_operation_executed = false"));
            assertTrue(migration.contains("company_series_append_only"));
            assertFalse(migration.contains("secret_value"));
        }
        assertTrue(v24.contains("CREATE SCHEMA IF NOT EXISTS company_ops"));
        assertTrue(v24.contains("'company_profiles'"));
        assertTrue(v24.contains("'board_actions'"));
        assertTrue(v25.contains("CREATE SCHEMA IF NOT EXISTS agent_workforce"));
        assertTrue(v25.contains("'agent_charters'"));
        assertTrue(v25.contains("'ai_board_reports'"));
        assertTrue(v26.contains("CREATE SCHEMA IF NOT EXISTS vertical_solutions"));
        assertTrue(v26.contains("'vertical_solution_packs'"));
        assertTrue(v26.contains("'vertical_conformance_reports'"));
        assertTrue(v27.contains("CREATE SCHEMA IF NOT EXISTS group_integration"));
        assertTrue(v27.contains("'integration_programs'"));
        assertTrue(v27.contains("'legacy_retirement_evidence'"));
        for (String migration : new String[]{v28, v29, v30, v31, v32}) {
            assertTrue(migration.contains("FORCE ROW LEVEL SECURITY"));
            assertTrue(migration.contains("current_setting(''app.organization_id'', true)"));
            assertTrue(migration.contains("actual_execution_evidence_ref"));
            assertTrue(migration.contains("human_approval_ref"));
            assertTrue(migration.contains("jsonb_array_length(evidence_refs) > 0"));
            assertFalse(migration.contains("secret_value"));
        }
        assertTrue(v28.contains("CREATE SCHEMA IF NOT EXISTS software_delivery"));
        assertTrue(v28.contains("'software_delivery_estates'"));
        assertTrue(v28.contains("'platform_roadmap_items'"));
        assertTrue(v29.contains("CREATE SCHEMA IF NOT EXISTS ai_platform"));
        assertTrue(v29.contains("'ai_estates'"));
        assertTrue(v29.contains("'agent_tool_permissions'"));
        assertTrue(v30.contains("CREATE SCHEMA IF NOT EXISTS edge_industrial"));
        assertTrue(v30.contains("'safety_controllers'"));
        assertTrue(v30.contains("'industrial_decommission_plans'"));
        assertTrue(v31.contains("CREATE SCHEMA IF NOT EXISTS operations_sre"));
        assertTrue(v31.contains("'major_incidents'"));
        assertTrue(v31.contains("'continuity_exercise_results'"));
        assertTrue(v32.contains("CREATE SCHEMA IF NOT EXISTS enterprise_architecture"));
        assertTrue(v32.contains("'business_capabilities'"));
        assertTrue(v32.contains("'architecture_value_observations'"));
        for (String migration : new String[]{v33, v34, v35, v36, v37, v38, v39, v40}) {
            assertTrue(migration.contains("FORCE ROW LEVEL SECURITY"));
            assertTrue(migration.contains("current_setting(''app.organization_id'', true)"));
            assertTrue(migration.contains("external_operation_executed = false"));
            assertTrue(migration.contains("product_governance_append_only"));
            assertTrue(migration.contains("READY_FOR_HUMAN_DECISION"));
            assertFalse(migration.contains("secret_value"));
        }
        assertTrue(v33.contains("CREATE SCHEMA IF NOT EXISTS technology_business_management"));
        assertTrue(v33.contains("'technology_cost_records'"));
        assertTrue(v34.contains("CREATE SCHEMA IF NOT EXISTS organization_workforce"));
        assertTrue(v34.contains("'skill_evidence_consents'"));
        assertTrue(v35.contains("CREATE SCHEMA IF NOT EXISTS transformation_execution"));
        assertTrue(v35.contains("'adoption_observations'"));
        assertTrue(v36.contains("CREATE SCHEMA IF NOT EXISTS autonomous_control_tower"));
        assertTrue(v36.contains("'agent_kill_switches'"));
        assertTrue(v37.contains("CREATE SCHEMA IF NOT EXISTS mvp_engineering"));
        assertTrue(v38.contains("CREATE SCHEMA IF NOT EXISTS mvp_gap_review"));
        assertTrue(v39.contains("CREATE SCHEMA IF NOT EXISTS secure_java_vertical"));
        assertTrue(v40.contains("CREATE SCHEMA IF NOT EXISTS identity_access_governance"));
        assertTrue(v40.contains("'break_glass_post_reviews'"));
        assertTrue(v41.contains("CREATE SCHEMA IF NOT EXISTS migration_pack_certification"));
        assertTrue(v41.contains("READY_FOR_PACK_GATE"));
        assertTrue(v41.contains("NOT certified OR"));
        assertTrue(v41.contains("production_mutation_executed = false"));
        assertTrue(v41.contains("migration_pack_append_only"));
        assertFalse(v41.contains("secret_value"));
        for (String migration : new String[]{v42, v43, v44, v45, v46, v47}) {
            assertTrue(migration.contains("FORCE ROW LEVEL SECURITY"));
            assertTrue(migration.contains("current_setting(''app.organization_id'', true)"));
            assertTrue(migration.contains("external_operation_executed = false"));
            assertTrue(migration.contains("elmos_forbid_append_only_mutation"));
            assertTrue(migration.contains("independent_verifier_id"));
            assertTrue(migration.contains("READY_FOR_HUMAN_DECISION"));
            assertFalse(migration.contains("secret_value"));
        }
        assertTrue(v42.contains("('scm', 'github_providers')"));
        assertTrue(v42.contains("('workspace', 'submodule_authorization_decisions')"));
        assertTrue(v43.contains("('execution', 'runner_attestation_runs')"));
        assertTrue(v43.contains("('sandbox', 'sandbox_profiles')"));
        assertTrue(v44.contains("('attestation', 'attestation_statements')"));
        assertTrue(v45.contains("('evidence', 'external_producer_connections')"));
        assertTrue(v46.contains("('analytics', 'metric_definitions')"));
        assertTrue(v47.contains("('authorization', 'decisions')"));
        assertTrue(v47.contains("('policy', 'policy_exceptions')"));
    }
}
