"""Deterministic repository snapshots and Merkle trees.

Snapshot identity depends only on repository content and declared policy. It
deliberately excludes absolute paths, host names, access times, run IDs and any
UI state, so the same logical repository on macOS, Linux and Windows produces
the same root digest.

Three digests are recorded per file and kept separate on purpose:

``raw_digest``
    the bytes as stored, including line endings and trailing whitespace;
``normalized_digest``
    line endings, BOM and trailing whitespace normalised -- a formatting-only
    edit moves ``raw`` but not ``normalized``;
``semantic_digest``
    supplied by the language front end when available, otherwise ``None`` so
    invalidation stays conservative rather than optimistic.
"""

from __future__ import annotations

import fnmatch
import os
import stat
from collections.abc import Callable, Iterable, Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path, PurePosixPath

from .canonical import digest_of, merkle_node_digest, sha256_bytes, sha256_file
from .errors import UnsafePath

POLICY_VERSION = "elmos.snapshot-policy/1.0.0"

DEFAULT_IGNORES: tuple[str, ...] = (
    ".git/**",
    ".hg/**",
    ".svn/**",
    "**/node_modules/**",
    "**/__pycache__/**",
    "**/.venv/**",
    "**/venv/**",
    "**/target/**",
    "**/build/**",
    "**/dist/**",
    "**/obj/**",
    "**/bin/**",
    "**/.gradle/**",
    "**/.idea/**",
    "**/.vs/**",
    "**/DerivedData/**",
    "**/.mypy_cache/**",
    "**/.pytest_cache/**",
    "**/.ruff_cache/**",
    "**/.elmos/**",
    "**/*.pyc",
    "**/.DS_Store",
)

LOCKFILE_NAMES = frozenset(
    {
        "package-lock.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "poetry.lock",
        "uv.lock",
        "Pipfile.lock",
        "requirements.txt",
        "Cargo.lock",
        "go.sum",
        "go.mod",
        "composer.lock",
        "Gemfile.lock",
        "packages.lock.json",
        "gradle.lockfile",
        "pubspec.lock",
        "Package.resolved",
        "Podfile.lock",
    }
)

VENDOR_DIRECTORIES = frozenset({"vendor", "third_party", "thirdparty", "Pods", "Carthage", "external"})

GENERATED_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "<auto-generated",
    "Code generated by",
)

SECRET_FILENAMES = frozenset({".env", ".env.local", "id_rsa", "id_ed25519", ".npmrc", ".pypirc", ".netrc"})

BINARY_SUFFIXES = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".zip", ".gz", ".bz2", ".xz", ".7z",
        ".jar", ".war", ".class", ".dll", ".so", ".dylib", ".exe", ".o", ".a", ".lib",
        ".wasm", ".pyc", ".woff", ".woff2", ".ttf", ".mp4", ".mov", ".bin", ".dat",
    }
)


class FileKind:
    SOURCE = "SOURCE"
    GENERATED = "GENERATED"
    DEPENDENCY = "DEPENDENCY"
    VENDOR = "VENDOR"
    BINARY = "BINARY"
    SECRET = "SECRET"  # noqa: S105 - a file classification, not a credential
    IGNORED = "IGNORED"


@dataclass(frozen=True)
class FileEntry:
    logical_path: str
    kind: str
    size: int
    raw_digest: str
    normalized_digest: str
    executable: bool
    is_symlink: bool
    symlink_target: str | None = None
    semantic_digest: str | None = None

    @property
    def module(self) -> str:
        parent = PurePosixPath(self.logical_path).parent
        return "" if str(parent) == "." else str(parent)


@dataclass(frozen=True)
class SnapshotPolicy:
    """Everything that can change a digest without the content changing."""

    version: str = POLICY_VERSION
    ignores: tuple[str, ...] = DEFAULT_IGNORES
    follow_symlinks: bool = False
    normalize_line_endings: bool = True
    strip_trailing_whitespace: bool = False
    case_sensitive: bool = True
    record_executable_bit: bool = True
    max_file_bytes: int = 256 * 1024 * 1024

    def digest(self) -> str:
        return digest_of(asdict(self))


@dataclass(frozen=True)
class Snapshot:
    root_digest: str
    manifest_digest: str
    policy_version: str
    policy_digest: str
    entries: tuple[FileEntry, ...]
    directory_digests: dict[str, str] = field(default_factory=dict)
    module_digests: dict[str, str] = field(default_factory=dict)
    lockfile_digests: dict[str, str] = field(default_factory=dict)
    submodule_roots: tuple[str, ...] = ()
    excluded: tuple[str, ...] = ()

    def by_path(self) -> dict[str, FileEntry]:
        return {entry.logical_path: entry for entry in self.entries}

    def to_manifest(self) -> dict[str, object]:
        return {
            "schema_version": "1.0.0",
            "root_digest": self.root_digest,
            "policy_version": self.policy_version,
            "policy_digest": self.policy_digest,
            "entries": [asdict(entry) for entry in self.entries],
            "directory_digests": dict(sorted(self.directory_digests.items())),
            "module_digests": dict(sorted(self.module_digests.items())),
            "lockfile_digests": dict(sorted(self.lockfile_digests.items())),
            "submodule_roots": list(self.submodule_roots),
        }


@dataclass(frozen=True)
class SnapshotDiff:
    added: tuple[str, ...]
    removed: tuple[str, ...]
    modified: tuple[str, ...]
    formatting_only: tuple[str, ...]
    renamed: tuple[tuple[str, str], ...]
    changed_modules: tuple[str, ...]
    lockfiles_changed: bool

    @property
    def unchanged_modules(self) -> bool:
        return not self.changed_modules

    def is_empty(self) -> bool:
        return not (self.added or self.removed or self.modified or self.renamed)


SemanticDigester = Callable[[str, bytes], str | None]


def normalize_text(data: bytes, policy: SnapshotPolicy) -> bytes:
    """Best-effort textual normalisation. Binary payloads are returned as-is."""
    if b"\x00" in data[:8192]:
        return data
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    if text.startswith("﻿"):
        text = text[1:]
    if policy.normalize_line_endings:
        text = text.replace("\r\n", "\n").replace("\r", "\n")
    if policy.strip_trailing_whitespace:
        text = "\n".join(line.rstrip() for line in text.split("\n"))
    return text.encode("utf-8")


def classify(logical_path: str, data: bytes | None) -> str:
    parts = PurePosixPath(logical_path).parts
    name = parts[-1]
    if name in SECRET_FILENAMES or name.endswith(".pem") or name.endswith(".key"):
        return FileKind.SECRET
    if any(part in VENDOR_DIRECTORIES for part in parts[:-1]):
        return FileKind.VENDOR
    if name in LOCKFILE_NAMES:
        return FileKind.DEPENDENCY
    if PurePosixPath(name).suffix.lower() in BINARY_SUFFIXES:
        return FileKind.BINARY
    if data is not None and b"\x00" not in data[:8192]:
        head = data[:4096]
        try:
            text = head.decode("utf-8", errors="ignore")
        except Exception:  # pragma: no cover - decode with errors never raises
            text = ""
        if any(marker in text for marker in GENERATED_MARKERS):
            return FileKind.GENERATED
    return FileKind.SOURCE


def _is_ignored(logical_path: str, policy: SnapshotPolicy) -> bool:
    for pattern in policy.ignores:
        if fnmatch.fnmatch(logical_path, pattern):
            return True
        if fnmatch.fnmatch("/" + logical_path, "/" + pattern):
            return True
    return False


def take_snapshot(
    root: Path,
    policy: SnapshotPolicy | None = None,
    semantic_digester: SemanticDigester | None = None,
) -> Snapshot:
    """Walk ``root`` and build the canonical snapshot.

    Traversal never follows a symlink out of the repository: an escaping link is
    recorded as a symlink entry with its literal target, not as its contents.
    """
    policy = policy or SnapshotPolicy()
    root = Path(root).resolve()
    if not root.is_dir():
        raise UnsafePath("snapshot root is not a directory", root=str(root))

    entries: list[FileEntry] = []
    excluded: list[str] = []
    submodules: list[str] = []
    lockfiles: dict[str, str] = {}

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        current = Path(dirpath)
        relative_dir = current.relative_to(root).as_posix()
        if relative_dir == ".":
            relative_dir = ""
        dirnames.sort()
        filenames.sort()

        kept: list[str] = []
        for name in dirnames:
            logical = f"{relative_dir}/{name}" if relative_dir else name
            if _is_ignored(logical + "/x", policy) or _is_ignored(logical, policy):
                excluded.append(logical + "/")
                continue
            if (current / name / ".git").exists():
                submodules.append(logical)
            kept.append(name)
        dirnames[:] = kept

        for name in filenames:
            logical = f"{relative_dir}/{name}" if relative_dir else name
            absolute = current / name
            if _is_ignored(logical, policy):
                excluded.append(logical)
                continue
            try:
                info = absolute.lstat()
            except OSError:  # pragma: no cover - races during a walk
                continue

            if stat.S_ISLNK(info.st_mode):
                target = os.readlink(absolute)
                digest = sha256_bytes(("symlink:" + target).encode("utf-8"))
                entries.append(
                    FileEntry(
                        logical_path=logical,
                        kind=FileKind.SOURCE,
                        size=len(target),
                        raw_digest=digest,
                        normalized_digest=digest,
                        executable=False,
                        is_symlink=True,
                        symlink_target=target,
                    )
                )
                continue
            if not stat.S_ISREG(info.st_mode):
                excluded.append(logical)
                continue
            if info.st_size > policy.max_file_bytes:
                raw_digest, size = sha256_file(absolute)
                entries.append(
                    FileEntry(
                        logical_path=logical,
                        kind=FileKind.BINARY,
                        size=size,
                        raw_digest=raw_digest,
                        normalized_digest=raw_digest,
                        executable=bool(info.st_mode & stat.S_IXUSR) if policy.record_executable_bit else False,
                        is_symlink=False,
                    )
                )
                continue

            data = absolute.read_bytes()
            raw_digest = sha256_bytes(data)
            kind = classify(logical, data)
            normalized = (
                raw_digest
                if kind in (FileKind.BINARY, FileKind.VENDOR)
                else sha256_bytes(normalize_text(data, policy))
            )
            semantic = semantic_digester(logical, data) if semantic_digester is not None else None
            entries.append(
                FileEntry(
                    logical_path=logical,
                    kind=kind,
                    size=len(data),
                    raw_digest=raw_digest,
                    normalized_digest=normalized,
                    executable=bool(info.st_mode & stat.S_IXUSR) if policy.record_executable_bit else False,
                    is_symlink=False,
                    semantic_digest=semantic,
                )
            )
            if name in LOCKFILE_NAMES:
                lockfiles[logical] = raw_digest

    entries.sort(key=lambda item: item.logical_path)
    directory_digests, module_digests = _build_merkle(entries, policy)
    root_digest = directory_digests.get("", merkle_node_digest("dir", []))

    manifest = {
        "schema_version": "1.0.0",
        "root_digest": root_digest,
        "policy_version": policy.version,
        "policy_digest": policy.digest(),
        "entries": [asdict(entry) for entry in entries],
        "directory_digests": dict(sorted(directory_digests.items())),
        "module_digests": dict(sorted(module_digests.items())),
        "lockfile_digests": dict(sorted(lockfiles.items())),
        "submodule_roots": sorted(submodules),
    }

    return Snapshot(
        root_digest=root_digest,
        manifest_digest=digest_of(manifest),
        policy_version=policy.version,
        policy_digest=policy.digest(),
        entries=tuple(entries),
        directory_digests=directory_digests,
        module_digests=module_digests,
        lockfile_digests=dict(sorted(lockfiles.items())),
        submodule_roots=tuple(sorted(submodules)),
        excluded=tuple(sorted(excluded)),
    )


def _directory_depth(directory: str) -> int:
    return 0 if directory == "" else directory.count("/") + 1


def _ancestors(directory: str) -> list[str]:
    """``"a/b/c"`` -> ``["a/b", "a", ""]`` (nearest first)."""
    chain: list[str] = []
    cursor = directory
    while cursor:
        parent = str(PurePosixPath(cursor).parent)
        parent = "" if parent == "." else parent
        chain.append(parent)
        cursor = parent
    return chain


def _build_merkle(
    entries: Sequence[FileEntry], policy: SnapshotPolicy
) -> tuple[dict[str, str], dict[str, str]]:
    """Bottom-up Merkle so a leaf edit touches only its ancestor chain."""
    file_children: dict[str, list[tuple[str, str]]] = {"": []}
    subdirectories: dict[str, set[str]] = {"": set()}

    def ensure(directory: str) -> None:
        file_children.setdefault(directory, [])
        subdirectories.setdefault(directory, set())

    for entry in entries:
        leaf = digest_of(
            {
                "raw": entry.raw_digest,
                "normalized": entry.normalized_digest,
                "semantic": entry.semantic_digest,
                "kind": entry.kind,
                "executable": entry.executable if policy.record_executable_bit else False,
                "symlink": entry.symlink_target,
            }
        )
        parent = entry.module
        ensure(parent)
        file_children[parent].append((PurePosixPath(entry.logical_path).name, leaf))
        child = parent
        for ancestor in _ancestors(parent):
            ensure(ancestor)
            subdirectories[ancestor].add(child)
            child = ancestor

    ordered = sorted(file_children, key=lambda item: (-_directory_depth(item), item))
    digests: dict[str, str] = {}
    for directory in ordered:
        node_entries = list(file_children[directory])
        for child_dir in sorted(subdirectories[directory]):
            node_entries.append((PurePosixPath(child_dir).name, digests[child_dir]))
        digests[directory] = merkle_node_digest("dir", node_entries)

    modules = dict(digests)
    return digests, modules


def diff_snapshots(before: Snapshot, after: Snapshot) -> SnapshotDiff:
    """Compare two snapshots, detecting renames through content identity."""
    old = before.by_path()
    new = after.by_path()

    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    modified: list[str] = []
    formatting_only: list[str] = []

    for path in sorted(set(old) & set(new)):
        if old[path].raw_digest == new[path].raw_digest:
            continue
        if old[path].normalized_digest == new[path].normalized_digest:
            formatting_only.append(path)
        else:
            modified.append(path)

    renamed: list[tuple[str, str]] = []
    removed_by_digest: dict[str, list[str]] = {}
    for path in removed:
        removed_by_digest.setdefault(old[path].raw_digest, []).append(path)
    still_added: list[str] = []
    for path in added:
        candidates = removed_by_digest.get(new[path].raw_digest)
        if candidates:
            renamed.append((candidates.pop(0), path))
            if not candidates:
                removed_by_digest.pop(new[path].raw_digest, None)
        else:
            still_added.append(path)
    still_removed = sorted(p for paths in removed_by_digest.values() for p in paths)

    changed_modules = sorted(
        {
            module
            for module, digest in after.module_digests.items()
            if before.module_digests.get(module) != digest
        }
        | {module for module in before.module_digests if module not in after.module_digests}
    )

    return SnapshotDiff(
        added=tuple(still_added),
        removed=tuple(still_removed),
        modified=tuple(modified),
        formatting_only=tuple(formatting_only),
        renamed=tuple(renamed),
        changed_modules=tuple(changed_modules),
        lockfiles_changed=before.lockfile_digests != after.lockfile_digests,
    )


def impacted_modules(diff: SnapshotDiff) -> tuple[str, ...]:
    """Modules whose content changed in a way that is not formatting-only."""
    touched: set[str] = set()
    for group in (diff.added, diff.removed, diff.modified):
        for path in group:
            parent = str(PurePosixPath(path).parent)
            touched.add("" if parent == "." else parent)
    for old, new in diff.renamed:
        for path in (old, new):
            parent = str(PurePosixPath(path).parent)
            touched.add("" if parent == "." else parent)
    return tuple(sorted(touched))


def iter_source_files(snapshot: Snapshot, kinds: Iterable[str] = (FileKind.SOURCE,)) -> tuple[FileEntry, ...]:
    wanted = set(kinds)
    return tuple(entry for entry in snapshot.entries if entry.kind in wanted)
