-- Install once by elmos_migration_admin after V77.  This file is intentionally
-- separate from Flyway: role ownership, passwords, and LOGIN assignments are
-- environment-specific and must never be generated by an application migration.
-- No role below has LOGIN or a password.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elmos_scheduler_rw') THEN CREATE ROLE elmos_scheduler_rw NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elmos_billing_rw') THEN CREATE ROLE elmos_billing_rw NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elmos_runtime_worker_limited') THEN CREATE ROLE elmos_runtime_worker_limited NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elmos_projector_limited') THEN CREATE ROLE elmos_projector_limited NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elmos_readonly_analytics') THEN CREATE ROLE elmos_readonly_analytics NOLOGIN; END IF;
END
$$;

GRANT USAGE ON SCHEMA identity, project, orchestration, runtime, artifact, validation, observability TO elmos_scheduler_rw;
GRANT SELECT, INSERT, UPDATE ON identity.tenants, identity.accounts, project.projects,
    project.repository_snapshots, orchestration.jobs, orchestration.job_stages,
    orchestration.work_items, orchestration.work_item_dependencies, runtime.dispatch_intents,
    runtime.workers, runtime.execution_attempts,
    runtime.worker_leases, runtime.checkpoints, runtime.settlement_requests, artifact.artifacts,
    validation.validation_runs, observability.outbox_events TO elmos_scheduler_rw;
GRANT EXECUTE ON FUNCTION runtime.allocate_fence(uuid), runtime.recovery_candidates(integer),
    runtime.select_fair_ready_work_items(integer) TO elmos_scheduler_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA observability TO elmos_scheduler_rw;

GRANT USAGE ON SCHEMA billing, ai_usage, project, orchestration, observability TO elmos_billing_rw;
GRANT SELECT, INSERT, UPDATE ON billing.billing_accounts, billing.wallets, billing.wallet_balances,
    billing.idempotency_records, billing.topups, billing.provider_pricing_versions,
    billing.provider_model_prices, billing.commercial_pricing_versions,
    billing.commercial_model_prices, billing.credit_reservations, billing.usage_meter_events,
    billing.token_usage_events, billing.ledger_entries, billing.billing_journals,
    billing.billing_journal_lines, ai_usage.model_calls, ai_usage.model_call_receipts,
    observability.outbox_events TO elmos_billing_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA billing, observability TO elmos_billing_rw;

GRANT USAGE ON SCHEMA runtime, orchestration, artifact, ai_usage TO elmos_runtime_worker_limited;
GRANT SELECT, UPDATE ON runtime.execution_attempts, runtime.worker_leases, runtime.workers,
    orchestration.work_items TO elmos_runtime_worker_limited;
GRANT SELECT, INSERT, UPDATE ON ai_usage.tool_calls, ai_usage.tool_call_receipts TO elmos_runtime_worker_limited;
GRANT SELECT, INSERT ON runtime.checkpoints, artifact.artifacts TO elmos_runtime_worker_limited;

GRANT USAGE ON SCHEMA observability, project, orchestration, validation TO elmos_projector_limited;
GRANT SELECT ON project.projects, orchestration.jobs, orchestration.job_stages,
    orchestration.work_items, observability.project_events, observability.outbox_events TO elmos_projector_limited;
GRANT INSERT, UPDATE ON observability.project_events, observability.progress_snapshots,
    validation.validation_runs TO elmos_projector_limited;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA observability TO elmos_projector_limited;
GRANT EXECUTE ON FUNCTION observability.claim_outbox(integer, uuid, integer),
    observability.mark_outbox_published(uuid, bigint), observability.mark_outbox_failed(uuid, bigint, text)
    TO elmos_projector_limited;

GRANT USAGE ON SCHEMA project, orchestration, runtime, billing, ai_usage, observability TO elmos_readonly_analytics;
GRANT SELECT ON ALL TABLES IN SCHEMA project, orchestration, runtime, billing, ai_usage, observability TO elmos_readonly_analytics;

-- Explicit negative boundary: these roles are not allowed to write one
-- another's authoritative contexts.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA billing, ai_usage FROM elmos_runtime_worker_limited;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA billing, ai_usage, runtime FROM elmos_projector_limited;
