"""Explicit Skill Registry and Dispatcher for all 178 Functional Assurance Skills."""

from __future__ import annotations

from typing import Any, Callable, Mapping

from .domain import FunctionalAssuranceContext
from .handlers import (
    AccreditationBodyGovernor,
    AIAssuranceCertifier,
    CertificateLifecycleController,
    DataDatabaseCertifier,
    FormalProofCertifier,
    GovernanceComplianceMonitor,
    LabMetrologyGovernor,
    OperationsSRECertifier,
    PolyglotQACertifier,
    SectorProfileCompiler,
    SecurityPrivacyCertifier,
    SupplyChainAttestationCertifier,
)


class FunctionalAssuranceHandlerRegistry:
    """Registry binding all 178 Functional Assurance Skills to concrete domain handlers."""

    _HANDLERS: dict[str, type] = {
        "elmos-accessibility-conformance-certifier": PolyglotQACertifier,
        "elmos-accreditation-evidence-readiness-exporter": AccreditationBodyGovernor,
        "elmos-accreditation-scope-competence-matrix-compiler": AccreditationBodyGovernor,
        "elmos-accredited-once-accepted-everywhere-evidence-packager": PolyglotQACertifier,
        "elmos-agent-skill-mcp-supply-chain-certifier": SecurityPrivacyCertifier,
        "elmos-ai-adversarial-robustness-evasion-poisoning-certifier": AIAssuranceCertifier,
        "elmos-ai-conformal-coverage-certifier": AIAssuranceCertifier,
        "elmos-ai-controllability-override-fail-safe-certifier": AIAssuranceCertifier,
        "elmos-ai-counterfactual-fairness-causal-stability-verifier": AIAssuranceCertifier,
        "elmos-ai-distribution-shift-ood-robustness-certifier": AIAssuranceCertifier,
        "elmos-ai-e0-e5-certifier": CertificateLifecycleController,
        "elmos-ai-evaluation-measurement-model-compiler": LabMetrologyGovernor,
        "elmos-ai-evaluation-power-sample-size-planner": AIAssuranceCertifier,
        "elmos-ai-explainability-fidelity-stability-certifier": AIAssuranceCertifier,
        "elmos-ai-fairness-bias-intersectional-certifier": AIAssuranceCertifier,
        "elmos-ai-golden-route-continuous-agent-certification": CertificateLifecycleController,
        "elmos-ai-human-factors-automation-bias-overreliance-verifier": AIAssuranceCertifier,
        "elmos-ai-impact-harm-benefit-distribution-assessor": AIAssuranceCertifier,
        "elmos-ai-incident-regulatory-reporting-controller": GovernanceComplianceMonitor,
        "elmos-ai-multiple-comparison-sequential-test-controller": AIAssuranceCertifier,
        "elmos-ai-provider-behavior-fingerprint-recertifier": AIAssuranceCertifier,
        "elmos-ai-quality-characteristic-measurement-compiler": AIAssuranceCertifier,
        "elmos-ai-quality-model-evaluation-compiler": AIAssuranceCertifier,
        "elmos-ai-rag-retrieval-grounding-certifier": AIAssuranceCertifier,
        "elmos-ai-rare-event-tail-risk-estimator": AIAssuranceCertifier,
        "elmos-ai-sociotechnical-context-validity-certifier": AIAssuranceCertifier,
        "elmos-ai-supply-chain-performance-resilience-certifier": AIAssuranceCertifier,
        "elmos-ai-test-laboratory-competence-governor": LabMetrologyGovernor,
        "elmos-ai-tevv-athlon-scenario-orchestrator": AIAssuranceCertifier,
        "elmos-ai-tevv-program-architecture-compiler": AIAssuranceCertifier,
        "elmos-ai-uncertainty-calibration-selective-prediction-verifier": AIAssuranceCertifier,
        "elmos-api-sdk-codegen-conformance-certifier": PolyglotQACertifier,
        "elmos-assurance-case-confidence-quantifier": FormalProofCertifier,
        "elmos-audit-duration-sampling-risk-planner": CertificateLifecycleController,
        "elmos-audit-evidence-sufficiency-appropriateness-verifier": CertificateLifecycleController,
        "elmos-auditor-evaluator-competence-authorization-controller": CertificateLifecycleController,
        "elmos-automotive-cybersecurity-update-assurance-profile": SectorProfileCompiler,
        "elmos-automotive-functional-safety-sotif-profile": SectorProfileCompiler,
        "elmos-autonomous-system-safety-case-profile": SectorProfileCompiler,
        "elmos-aviation-software-tool-formal-assurance-profile": SectorProfileCompiler,
        "elmos-benchmark-integrity-large-repository-certifier": CertificateLifecycleController,
        "elmos-browser-computer-use-safety-certifier": PolyglotQACertifier,
        "elmos-capacity-soak-efficiency-certifier": OperationsSRECertifier,
        "elmos-certificate-cross-border-jurisdiction-acceptance-planner": CertificateLifecycleController,
        "elmos-certificate-deployment-admission-controller": CertificateLifecycleController,
        "elmos-certificate-drift-revocation-controller": CertificateLifecycleController,
        "elmos-certificate-maintenance-scope-change-controller": CertificateLifecycleController,
        "elmos-certificate-portability-transfer-controller": CertificateLifecycleController,
        "elmos-certificate-public-directory-transparency-controller": CertificateLifecycleController,
        "elmos-certificate-relying-party-policy-compiler": CertificateLifecycleController,
        "elmos-certificate-status-list-revocation-service": CertificateLifecycleController,
        "elmos-certificate-trust-registry-federation-controller": CertificateLifecycleController,
        "elmos-certification-audit-program-governor": CertificateLifecycleController,
        "elmos-certification-body-financial-liability-risk-governor": CertificateLifecycleController,
        "elmos-certification-confidentiality-information-security-governor": CertificateLifecycleController,
        "elmos-certification-decision-independent-review-controller": CertificateLifecycleController,
        "elmos-certification-ethics-whistleblower-protection-governor": CertificateLifecycleController,
        "elmos-certification-function-separation-controller": CertificateLifecycleController,
        "elmos-certification-key-ceremony-hsm-controller": CertificateLifecycleController,
        "elmos-certification-mark-claim-usage-governor": CertificateLifecycleController,
        "elmos-certification-policy-practice-authority": CertificateLifecycleController,
        "elmos-certification-scheme-ownership-governor": CertificateLifecycleController,
        "elmos-certification-scheme-surveillance-planner": CertificateLifecycleController,
        "elmos-certification-scope-compiler": CertificateLifecycleController,
        "elmos-certification-transfer-suspension-withdrawal-controller": CertificateLifecycleController,
        "elmos-certification-transparency-log-notary": CertificateLifecycleController,
        "elmos-certifier-independence-competence-governor": CertificateLifecycleController,
        "elmos-clean-room-reproducible-builder": CertificateLifecycleController,
        "elmos-common-criteria-evaluation-assurance-level-planner": SecurityPrivacyCertifier,
        "elmos-common-criteria-protection-profile-mapper": SecurityPrivacyCertifier,
        "elmos-common-criteria-security-target-compiler": SecurityPrivacyCertifier,
        "elmos-common-criteria-vulnerability-analysis-controller": SecurityPrivacyCertifier,
        "elmos-compiler-frontend-conformance-certifier": PolyglotQACertifier,
        "elmos-complaint-appeal-dispute-resolution-governor": CertificateLifecycleController,
        "elmos-confidential-ai-inference-receipt-certifier": SecurityPrivacyCertifier,
        "elmos-conformity-assessment-impartiality-risk-governor": CertificateLifecycleController,
        "elmos-conformity-assessment-scheme-architecture-compiler": CertificateLifecycleController,
        "elmos-conformity-decision-guard-band-controller": LabMetrologyGovernor,
        "elmos-critical-infrastructure-ai-resilience-profile": SectorProfileCompiler,
        "elmos-cross-scheme-claim-mapping-equivalence-verifier": PolyglotQACertifier,
        "elmos-cryptographic-algorithm-test-vector-certifier": SecurityPrivacyCertifier,
        "elmos-cryptographic-module-validation-readiness-governor": SecurityPrivacyCertifier,
        "elmos-customer-holdout-acceptance-controller": CertificateLifecycleController,
        "elmos-customer-vpc-runner-attestation-certifier": PolyglotQACertifier,
        "elmos-database-backup-pitr-failover-certifier": DataDatabaseCertifier,
        "elmos-database-cutover-rollback-certifier": DataDatabaseCertifier,
        "elmos-database-performance-plan-certifier": DataDatabaseCertifier,
        "elmos-digital-metrology-measurand-definition-compiler": LabMetrologyGovernor,
        "elmos-disaster-recovery-business-continuity-certifier": OperationsSRECertifier,
        "elmos-document-record-control-certification-governor": CertificateLifecycleController,
        "elmos-enterprise-assurance-dossier-generator": CertificateLifecycleController,
        "elmos-environment-parity-config-drift-certifier": OperationsSRECertifier,
        "elmos-eu-ai-act-post-market-monitoring-controller": GovernanceComplianceMonitor,
        "elmos-event-replay-idempotency-certifier": DataDatabaseCertifier,
        "elmos-evidence-trusted-timestamp-authority-controller": SecurityPrivacyCertifier,
        "elmos-evidence-worm-merkle-sealer": CertificateLifecycleController,
        "elmos-external-audit-oscal-evidence-exporter": CertificateLifecycleController,
        "elmos-ffi-abi-native-boundary-certifier": PolyglotQACertifier,
        "elmos-financial-model-risk-validation-profile": SectorProfileCompiler,
        "elmos-formal-proof-maintenance-drift-recertifier": FormalProofCertifier,
        "elmos-generated-repository-maintainability-evolution-certifier": PolyglotQACertifier,
        "elmos-global-recognition-scope-resolver": AccreditationBodyGovernor,
        "elmos-graphrag-pipeline-certifier": PolyglotQACertifier,
        "elmos-hardware-root-of-trust-measured-boot-verifier": SecurityPrivacyCertifier,
        "elmos-hermetic-build-environment-attestation-controller": SupplyChainAttestationCertifier,
        "elmos-hybrid-signature-certificate-transition-governor": SecurityPrivacyCertifier,
        "elmos-i18n-l10n-conformance-verifier": PolyglotQACertifier,
        "elmos-incident-postmortem-recertification-controller": GovernanceComplianceMonitor,
        "elmos-independent-k8-certificate-signer": CertificateLifecycleController,
        "elmos-industrial-control-security-safety-coassurance-profile": SectorProfileCompiler,
        "elmos-inspection-validation-verification-mode-selector": CertificateLifecycleController,
        "elmos-interlaboratory-comparison-controller": LabMetrologyGovernor,
        "elmos-internal-audit-management-review-compiler": CertificateLifecycleController,
        "elmos-lab-environment-validity-monitor": LabMetrologyGovernor,
        "elmos-lab-reproducibility-repeatability-certifier": LabMetrologyGovernor,
        "elmos-machine-checkable-proof-replay-controller": FormalProofCertifier,
        "elmos-machine-verifiable-certificate-profile-compiler": CertificateLifecycleController,
        "elmos-measurement-uncertainty-budget-engine": LabMetrologyGovernor,
        "elmos-medical-device-ai-software-lifecycle-risk-profile": SectorProfileCompiler,
        "elmos-method-sensitivity-specificity-detection-limit-certifier": LabMetrologyGovernor,
        "elmos-model-checking-state-space-coverage-certifier": FormalProofCertifier,
        "elmos-model-quantization-hardware-compatibility-certifier": PolyglotQACertifier,
        "elmos-model-weight-artifact-provenance-certifier": PolyglotQACertifier,
        "elmos-multi-region-active-active-failover-certifier": OperationsSRECertifier,
        "elmos-multi-verifier-attestation-consensus-governor": SecurityPrivacyCertifier,
        "elmos-mutual-recognition-arrangement-scope-resolver": AccreditationBodyGovernor,
        "elmos-native-conformance-lab-controller": LabMetrologyGovernor,
        "elmos-network-egress-data-exfiltration-certifier": SecurityPrivacyCertifier,
        "elmos-nonconformity-corrective-action-capa-controller": CertificateLifecycleController,
        "elmos-open-source-license-ip-compliance-certifier": SupplyChainAttestationCertifier,
        "elmos-operability-support-readiness-certifier": OperationsSRECertifier,
        "elmos-outsourced-certification-activity-control-governor": CertificateLifecycleController,
        "elmos-peer-assessment-witness-audit-controller": AccreditationBodyGovernor,
        "elmos-polyglot-route-certifier": PolyglotQACertifier,
        "elmos-post-market-surveillance-signal-detection-controller": CertificateLifecycleController,
        "elmos-post-quantum-cryptographic-agility-controller": SecurityPrivacyCertifier,
        "elmos-privacy-impact-consent-purpose-verifier": PolyglotQACertifier,
        "elmos-production-change-control-recertification-gate": CertificateLifecycleController,
        "elmos-production-deployment-certifier": CertificateLifecycleController,
        "elmos-productivity-value-stream-scorecard": PolyglotQACertifier,
        "elmos-proficiency-testing-scheme-generator": LabMetrologyGovernor,
        "elmos-proof-assumption-defeater-ledger": FormalProofCertifier,
        "elmos-proof-carrying-artifact-compiler": FormalProofCertifier,
        "elmos-proof-checker-diversity-cross-validation-governor": FormalProofCertifier,
        "elmos-public-sector-high-impact-ai-assurance-profile": SectorProfileCompiler,
        "elmos-railway-software-safety-case-profile": SectorProfileCompiler,
        "elmos-rats-eat-corim-attestation-appraisal-controller": SecurityPrivacyCertifier,
        "elmos-reference-dataset-material-producer-governor": LabMetrologyGovernor,
        "elmos-regulatory-obligation-effective-date-monitor": GovernanceComplianceMonitor,
        "elmos-risk-acceptance-residual-risk-governor": CertificateLifecycleController,
        "elmos-root-cause-effectiveness-verification-governor": CertificateLifecycleController,
        "elmos-runtime-admission-attestation-controller": PolyglotQACertifier,
        "elmos-runtime-policy-continuous-compliance-monitor": GovernanceComplianceMonitor,
        "elmos-safety-integrity-level-assurance-profile-compiler": SectorProfileCompiler,
        "elmos-sampling-plan-representativeness-certifier": LabMetrologyGovernor,
        "elmos-scitt-evidence-transparency-receipt-publisher": CertificateLifecycleController,
        "elmos-sector-profile-applicability-tailoring-governor": SectorProfileCompiler,
        "elmos-security-evaluation-methodology-work-unit-compiler": SecurityPrivacyCertifier,
        "elmos-security-incident-psirt-disclosure-controller": GovernanceComplianceMonitor,
        "elmos-self-improvement-change-isolation-certifier": PolyglotQACertifier,
        "elmos-sensitive-data-masking-tokenization-certifier": DataDatabaseCertifier,
        "elmos-slo-error-budget-release-governor": OperationsSRECertifier,
        "elmos-structured-assurance-case-compiler": CertificateLifecycleController,
        "elmos-sustainable-ai-energy-carbon-efficiency-certifier": OperationsSRECertifier,
        "elmos-tcb-attack-surface-closure-certifier": FormalProofCertifier,
        "elmos-test-data-privacy-synthetic-generation-certifier": PolyglotQACertifier,
        "elmos-test-equipment-software-calibration-traceability-governor": LabMetrologyGovernor,
        "elmos-test-method-validation-verification-controller": LabMetrologyGovernor,
        "elmos-third-party-mark-conformity-license-governor": CertificateLifecycleController,
        "elmos-trusted-computing-base-minimization-governor": FormalProofCertifier,
        "elmos-ui-visual-regression-journey-certifier": PolyglotQACertifier,
        "elmos-verifiable-credential-assurance-certificate-emitter": CertificateLifecycleController,
        "elmos-verification-tool-validation-corpus-governor": FormalProofCertifier,
        "elmos-verifier-tool-qualification-classifier": FormalProofCertifier,
        "elmos-vulnerability-vex-kev-response-governor": SupplyChainAttestationCertifier,
        "elmos-waiver-expiry-governor": CertificateLifecycleController,
        "elmos-warehouse-lakehouse-migration-certifier": DataDatabaseCertifier,
        "elmos-wasi-sandbox-capability-certifier": SecurityPrivacyCertifier,
    }

    @classmethod
    def get_handler_for_skill(cls, skill_name: str) -> type | None:
        return cls._HANDLERS.get(skill_name)

    @classmethod
    def bound_skills_count(cls) -> int:
        return len(cls._HANDLERS)
