// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    incident: { type: Object, value: {} },
    businessLineLabel: { type: String, value: "" },
    disabled: { type: Boolean, value: false },
  },
  data: {},
  methods: {
    handleClickButton0(event) {
      this.triggerEvent("assign");
    },
    handleClickButton1(event) {
      this.triggerEvent("resolve");
    },
  },
});
