// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    title: { type: String, value: "" },
    detail: { type: String, value: "" },
  },
  data: {},
  methods: {},
});
