"""Elmos Proof-Driven Harness Intelligence v1 foundation."""

from .canonical import (
    canonical_json,
    canonical_json_bytes,
    canonical_json_text,
    digest_bytes,
    digest_object,
    freeze_json,
    require_sha256_digest,
    strict_json_loads,
    utc_now,
)
from .contracts import (
    AgentResultStatus,
    AgentTask,
    AuthorityLevel,
    CertificationBundle,
    CertificationLevel,
    CertificationVerdict,
    DurableJobState,
    DurableJobStatus,
    EvidenceRecord,
    EvidenceStatus,
    ExecutionContext,
    FailureClass,
    GateStatus,
    PatchTransaction,
    PatchTransactionStatus,
    ProofCarryingAgentResult,
    ResourceScope,
    RuleEnforcement,
    RuleIR,
    SkillLifecycleStatus,
    SkillManifest,
    VerificationStatus,
)
from .registry import (
    CAPABILITY_OCCURRENCES,
    CAPABILITY_REGISTRY,
    OPERATION_REGISTRY,
    SKILL_REGISTRY,
    SOURCE_V3_CROSSWALK,
    OperationSpec,
    canonical_capability,
    resolve_capability,
    resolve_operation,
    resolve_skill,
)

__version__ = "1.0.0"

__all__ = [
    "AgentResultStatus",
    "AgentTask",
    "AuthorityLevel",
    "CAPABILITY_OCCURRENCES",
    "CAPABILITY_REGISTRY",
    "CertificationBundle",
    "CertificationLevel",
    "CertificationVerdict",
    "DurableJobState",
    "DurableJobStatus",
    "EvidenceRecord",
    "EvidenceStatus",
    "ExecutionContext",
    "FailureClass",
    "GateStatus",
    "OPERATION_REGISTRY",
    "OperationSpec",
    "PatchTransaction",
    "PatchTransactionStatus",
    "ProofCarryingAgentResult",
    "ResourceScope",
    "RuleEnforcement",
    "RuleIR",
    "SKILL_REGISTRY",
    "SOURCE_V3_CROSSWALK",
    "SkillLifecycleStatus",
    "SkillManifest",
    "VerificationStatus",
    "canonical_capability",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_json_text",
    "digest_bytes",
    "digest_object",
    "freeze_json",
    "require_sha256_digest",
    "resolve_capability",
    "resolve_operation",
    "resolve_skill",
    "strict_json_loads",
    "utc_now",
]
