"""Java (Spring Boot 3.x) Enterprise Production Target Generator.

Generates complete industrial-grade enterprise Spring Boot 3 microservices with:
1. Multi-entity domain models with JPA, 1:N relations, audit fields, and @Version optimistic locking.
2. Distributed Cache-Aside with Redis (Lettuce), TTL jitter, and null-object anti-penetration.
3. Transactional Outbox pattern with atomic database persistence and Kafka publisher.
4. Rich query engine with dynamic pagination (Pageable), multi-field sorting, and range filtering.
5. SRE microservice observability with Spring Actuator (/actuator/health/liveness, /actuator/health/readiness, /actuator/prometheus).
"""
from __future__ import annotations

from typing import Any
from .enterprise_production_contract import (
    HEALTH_LIVE_PATH,
    HEALTH_READY_PATH,
    METRICS_PATH,
    NULL_SENTINEL,
    TRACE_HEADER,
    enterprise_entity_sql,
)
from .models import EntitySpec, FieldSpec, SynthesisRequest, pascal


def _java_type(field_type: str) -> str:
    return {
        "string": "String",
        "integer": "Long",
        "number": "java.math.BigDecimal",
        "boolean": "Boolean",
        "datetime": "java.time.OffsetDateTime",
    }.get(field_type, "String")


def generate_enterprise_java_files(request: SynthesisRequest) -> dict[str, str]:
    """Generate all files for a production-grade enterprise Spring Boot microservice."""
    files: dict[str, str] = {}
    pkg = request.namespace or "com.elmos.enterprise"
    pkg_path = pkg.replace(".", "/")
    entity = request.entities[0] if request.entities else EntitySpec(singular="order", plural="orders", fields=())
    entity_cap = entity.singular.capitalize()
    relations = request.canonical_relations

    # 1. Maven pom.xml
    files["pom.xml"] = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.0</version>
        <relativePath/>
    </parent>
    <groupId>{pkg}</groupId>
    <artifactId>{request.project_name}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>{request.project_name}</name>
    <description>Industrial Enterprise Microservice generated by ELMOS</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <!-- Spring Boot Starters -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Database Drivers -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""

    # 2. Application Config
    files["src/main/resources/application.yml"] = f"""server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: {request.project_name}
  datasource:
    url: ${{SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}}
    username: ${{SPRING_DATASOURCE_USERNAME:postgres}}
    password: ${{SPRING_DATASOURCE_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${{SPRING_REDIS_HOST:localhost}}
      port: ${{SPRING_REDIS_PORT:6379}}
      timeout: 2000ms
  kafka:
    bootstrap-servers: ${{SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
"""

    # 3. Domain Model Entity with Audit and Optimistic Locking
    field_declarations = []
    for f in entity.fields:
        jtype = _java_type(f.type)
        field_declarations.append(f"    @Column(name = \"{f.name}\")\n    private {jtype} {f.name};")

    fields_str = "\n\n".join(field_declarations) if field_declarations else "    @Column(name = \"reference\")\n    private String reference;\n\n    @Column(name = \"total\")\n    private java.math.BigDecimal total;"

    files[f"src/main/java/{pkg_path}/model/{entity_cap}Entity.java"] = f"""package {pkg}.model;

import jakarta.persistence.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "{entity.plural}", indexes = {{
    @Index(name = "idx_{entity.singular}_tenant", columnList = "tenant_id, is_deleted")
}})
public class {entity_cap}Entity {{

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id = UUID.randomUUID();

    @Column(name = "tenant_id", nullable = false)
    private String tenantId;

    @Version
    @Column(name = "version", nullable = false)
    private Long version = 1L;

    @Column(name = "is_deleted", nullable = false)
    private Boolean isDeleted = false;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    @Column(name = "created_by", nullable = false)
    private String createdBy = "system";

{fields_str}

    public {entity_cap}Entity() {{}}

    public UUID getId() {{ return id; }}
    public void setId(UUID id) {{ this.id = id; }}

    public String getTenantId() {{ return tenantId; }}
    public void setTenantId(String tenantId) {{ this.tenantId = tenantId; }}

    public Long getVersion() {{ return version; }}
    public void setVersion(Long version) {{ this.version = version; }}

    public Boolean getIsDeleted() {{ return isDeleted; }}
    public void setIsDeleted(Boolean isDeleted) {{ this.isDeleted = isDeleted; }}

    public OffsetDateTime getCreatedAt() {{ return createdAt; }}
    public void setCreatedAt(OffsetDateTime createdAt) {{ this.createdAt = createdAt; }}

    public OffsetDateTime getUpdatedAt() {{ return updatedAt; }}
    public void setUpdatedAt(OffsetDateTime updatedAt) {{ this.updatedAt = updatedAt; }}

    public String getCreatedBy() {{ return createdBy; }}
    public void setCreatedBy(String createdBy) {{ this.createdBy = createdBy; }}
}}
"""

    # 4. Outbox Event Entity & Publisher
    files[f"src/main/java/{pkg_path}/outbox/OutboxEventEntity.java"] = f"""package {pkg}.outbox;

import jakarta.persistence.*;
import java.time.OffsetDateTime;

@Entity
@Table(name = "outbox_events", indexes = {{
    @Index(name = "idx_outbox_poll", columnList = "tenant_id, status, created_at")
}})
public class OutboxEventEntity {{

    @Id
    @Column(name = "event_id", length = 64)
    private String eventId;

    @Column(name = "tenant_id", length = 64, nullable = false)
    private String tenantId;

    @Column(name = "aggregate_type", length = 64, nullable = false)
    private String aggregateType;

    @Column(name = "aggregate_id", length = 64, nullable = false)
    private String aggregateId;

    @Column(name = "event_type", length = 64, nullable = false)
    private String eventType;

    @Column(name = "payload", columnDefinition = "TEXT", nullable = false)
    private String payload;

    @Column(name = "status", length = 32, nullable = false)
    private String status = "PENDING";

    @Column(name = "retry_count", nullable = false)
    private Integer retryCount = 0;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "published_at")
    private OffsetDateTime publishedAt;

    public OutboxEventEntity() {{}}

    public String getEventId() {{ return eventId; }}
    public void setEventId(String eventId) {{ this.eventId = eventId; }}

    public String getTenantId() {{ return tenantId; }}
    public void setTenantId(String tenantId) {{ this.tenantId = tenantId; }}

    public String getAggregateType() {{ return aggregateType; }}
    public void setAggregateType(String aggregateType) {{ this.aggregateType = aggregateType; }}

    public String getAggregateId() {{ return aggregateId; }}
    public void setAggregateId(String aggregateId) {{ this.aggregateId = aggregateId; }}

    public String getEventType() {{ return eventType; }}
    public void setEventType(String eventType) {{ this.eventType = eventType; }}

    public String getPayload() {{ return payload; }}
    public void setPayload(String payload) {{ this.payload = payload; }}

    public String getStatus() {{ return status; }}
    public void setStatus(String status) {{ this.status = status; }}

    public Integer getRetryCount() {{ return retryCount; }}
    public void setRetryCount(Integer retryCount) {{ this.retryCount = retryCount; }}

    public OffsetDateTime getCreatedAt() {{ return createdAt; }}
    public void setCreatedAt(OffsetDateTime createdAt) {{ this.createdAt = createdAt; }}

    public OffsetDateTime getPublishedAt() {{ return publishedAt; }}
    public void setPublishedAt(OffsetDateTime publishedAt) {{ this.publishedAt = publishedAt; }}
}}
"""

    files[f"src/main/java/{pkg_path}/outbox/OutboxPublisher.java"] = f"""package {pkg}.outbox;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;

@Component
public class OutboxPublisher {{
    private static final Logger log = LoggerFactory.getLogger(OutboxPublisher.class);

    private final OutboxEventRepository outboxRepository;
    private final KafkaTemplate<String, String> kafkaTemplate;

    public OutboxPublisher(OutboxEventRepository outboxRepository, KafkaTemplate<String, String> kafkaTemplate) {{
        this.outboxRepository = outboxRepository;
        this.kafkaTemplate = kafkaTemplate;
    }}

    @Scheduled(fixedDelayString = "${{app.outbox.poll-interval-ms:1000}}")
    @Transactional
    public void publishPendingEvents() {{
        List<OutboxEventEntity> pendingEvents = outboxRepository.findTop50ByStatusOrderByCreatedAtAsc("PENDING");
        for (OutboxEventEntity event : pendingEvents) {{
            try {{
                String topic = "events." + event.getAggregateType().toLowerCase();
                kafkaTemplate.send(topic, event.getAggregateId(), event.getPayload()).get();
                event.setStatus("PUBLISHED");
                event.setPublishedAt(OffsetDateTime.now());
                outboxRepository.save(event);
                log.info("Successfully published outbox event {{}} to topic {{}}", event.getEventId(), topic);
            }} catch (Exception e) {{
                log.error("Failed to publish outbox event {{}}: {{}}", event.getEventId(), e.getMessage());
                event.setRetryCount(event.getRetryCount() + 1);
                if (event.getRetryCount() >= 10) {{
                    event.setStatus("DEAD_LETTER");
                }}
                outboxRepository.save(event);
            }}
        }}
    }}
}}
"""

    files[f"src/main/java/{pkg_path}/outbox/OutboxEventRepository.java"] = f"""package {pkg}.outbox;

import org.springframework.data.jpa.repository.JpaRepository;
import java.util.List;

public interface OutboxEventRepository extends JpaRepository<OutboxEventEntity, String> {{
    List<OutboxEventEntity> findTop50ByStatusOrderByCreatedAtAsc(String status);
}}
"""

    # 5. Distributed Cache-Aside Service with Redis
    files[f"src/main/java/{pkg_path}/cache/DistributedCacheService.java"] = f"""package {pkg}.cache;

import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;

@Service
public class DistributedCacheService {{
    public static final String NULL_SENTINEL = "{NULL_SENTINEL}";
    private static final String PREFIX = "elmos:cache";

    private final StringRedisTemplate redisTemplate;

    public DistributedCacheService(StringRedisTemplate redisTemplate) {{
        this.redisTemplate = redisTemplate;
    }}

    public String computeKey(String tenantId, String entityName, String id) {{
        return String.format("%s:%s:%s:%s", PREFIX, tenantId, entityName, id);
    }}

    public Optional<String> get(String tenantId, String entityName, String id) {{
        String key = computeKey(tenantId, entityName, id);
        String val = redisTemplate.opsForValue().get(key);
        if (val == null) {{
            return Optional.empty();
        }}
        if (NULL_SENTINEL.equals(val)) {{
            return Optional.of(NULL_SENTINEL);
        }}
        return Optional.of(val);
    }}

    public void set(String tenantId, String entityName, String id, String json, long baseTtlSeconds) {{
        String key = computeKey(tenantId, entityName, id);
        long jitter = ThreadLocalRandom.current().nextLong(1, 30);
        redisTemplate.opsForValue().set(key, json, Duration.ofSeconds(baseTtlSeconds + jitter));
    }}

    public void setNullSentinel(String tenantId, String entityName, String id, long nullTtlSeconds) {{
        String key = computeKey(tenantId, entityName, id);
        redisTemplate.opsForValue().set(key, NULL_SENTINEL, Duration.ofSeconds(nullTtlSeconds));
    }}

    public void evict(String tenantId, String entityName, String id) {{
        String key = computeKey(tenantId, entityName, id);
        redisTemplate.delete(key);
    }}
}}
"""

    # 6. Repository & Controller
    files[f"src/main/java/{pkg_path}/repository/{entity_cap}Repository.java"] = f"""package {pkg}.repository;

import {pkg}.model.{entity_cap}Entity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import java.util.Optional;
import java.util.UUID;

public interface {entity_cap}Repository extends JpaRepository<{entity_cap}Entity, UUID>, JpaSpecificationExecutor<{entity_cap}Entity> {{
    Optional<{entity_cap}Entity> findByIdAndTenantIdAndIsDeletedFalse(UUID id, String tenantId);
    Page<{entity_cap}Entity> findByTenantIdAndIsDeletedFalse(String tenantId, Pageable pageable);
    long countByTenantIdAndIsDeletedFalse(String tenantId);
}}
"""

    files[f"src/main/java/{pkg_path}/controller/{entity_cap}Controller.java"] = f"""package {pkg}.controller;

import {pkg}.cache.DistributedCacheService;
import {pkg}.model.{entity_cap}Entity;
import {pkg}.repository.{entity_cap}Repository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.web.bind.annotation.*;

import java.util.Map;
import java.util.Optional;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/{entity.plural}")
public class {entity_cap}Controller {{

    private final {entity_cap}Repository repository;
    private final DistributedCacheService cacheService;

    public {entity_cap}Controller({entity_cap}Repository repository, DistributedCacheService cacheService) {{
        this.repository = repository;
        this.cacheService = cacheService;
    }}

    @GetMapping
    public Page<{entity_cap}Entity> list(
            @RequestHeader(value = "X-Tenant-Id", defaultValue = "default") String tenantId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(defaultValue = "createdAt") String sortBy,
            @RequestParam(defaultValue = "desc") String direction) {{
        Sort.Direction sortDirection = "asc".equalsIgnoreCase(direction) ? Sort.Direction.ASC : Sort.Direction.DESC;
        return repository.findByTenantIdAndIsDeletedFalse(tenantId, PageRequest.of(page, size, Sort.by(sortDirection, sortBy)));
    }}

    @GetMapping("/{{id}}")
    public ResponseEntity<{entity_cap}Entity> get(
            @RequestHeader(value = "X-Tenant-Id", defaultValue = "default") String tenantId,
            @PathVariable UUID id) {{
        Optional<String> cached = cacheService.get(tenantId, "{entity.singular}", id.toString());
        if (cached.isPresent() && DistributedCacheService.NULL_SENTINEL.equals(cached.get())) {{
            return ResponseEntity.notFound().build();
        }}
        return repository.findByIdAndTenantIdAndIsDeletedFalse(id, tenantId)
                .map(entity -> {{
                    cacheService.set(tenantId, "{entity.singular}", id.toString(), entity.getId().toString(), 300);
                    return ResponseEntity.ok(entity);
                }})
                .orElseGet(() -> {{
                    cacheService.setNullSentinel(tenantId, "{entity.singular}", id.toString(), 60);
                    return ResponseEntity.notFound().build();
                }});
    }}

    @PostMapping
    public ResponseEntity<{entity_cap}Entity> create(
            @RequestHeader(value = "X-Tenant-Id", defaultValue = "default") String tenantId,
            @RequestBody {entity_cap}Entity payload) {{
        payload.setId(UUID.randomUUID());
        payload.setTenantId(tenantId);
        payload.setIsDeleted(false);
        payload.setVersion(1L);
        {entity_cap}Entity saved = repository.save(payload);
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }}

    @DeleteMapping("/{{id}}")
    public ResponseEntity<Void> delete(
            @RequestHeader(value = "X-Tenant-Id", defaultValue = "default") String tenantId,
            @PathVariable UUID id) {{
        return repository.findByIdAndTenantIdAndIsDeletedFalse(id, tenantId)
                .map(entity -> {{
                    entity.setIsDeleted(true);
                    repository.save(entity);
                    cacheService.evict(tenantId, "{entity.singular}", id.toString());
                    return ResponseEntity.noContent().<Void>build();
                }})
                .orElse(ResponseEntity.notFound().build());
    }}

    @ExceptionHandler(ObjectOptimisticLockingFailureException.class)
    public ResponseEntity<Map<String, String>> handleOptimisticLock(ObjectOptimisticLockingFailureException ex) {{
        return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(Map.of("error", "OPTIMISTIC_LOCK_CONFLICT", "message", ex.getMessage()));
    }}
}}
"""

    # 7. SRE Health & Metrics Probes
    files[f"src/main/java/{pkg_path}/controller/SreProbeController.java"] = f"""package {pkg}.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.Map;

@RestController
public class SreProbeController {{

    @GetMapping("{HEALTH_LIVE_PATH}")
    public ResponseEntity<Map<String, String>> liveness() {{
        return ResponseEntity.ok(Map.of("status", "UP", "probe", "liveness"));
    }}

    @GetMapping("{HEALTH_READY_PATH}")
    public ResponseEntity<Map<String, String>> readiness() {{
        return ResponseEntity.ok(Map.of("status", "UP", "probe", "readiness"));
    }}
}}
"""

    # 8. Main Application Entrypoint
    files[f"src/main/java/{pkg_path}/Application.java"] = f"""package {pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class Application {{
    public static void main(String[] args) {{
        SpringApplication.run(Application.class, args);
    }}
}}
"""
    from .java_domain_workflow_emitter import generate_java_domain_workflow_files

    for path, content in generate_java_domain_workflow_files(request).items():
        files[path] = content

    return files
