# ruff: noqa: E501
"""Axum production profile: PostgreSQL, forced RLS, JWT or OIDC bearer.

Same shared contract and harness as the Python, Java, Go, TypeScript, C# and
Kotlin profiles. The store speaks tokio-postgres directly so the tenant binding
stays visible rather than hidden behind an ORM session.

Rust source is assembled by ``__TOKEN__`` substitution rather than f-strings:
the generated code is dense with braces, and doubling every one of them to
survive ``str.format`` turns a readable template into a defect factory.

Two mappings are not obvious and are load-bearing:

* ``number`` columns are ``numeric(20,6)``. tokio-postgres has no ``f64``
  conversion for PostgreSQL ``NUMERIC``, so the column is read and written as
  ``rust_decimal::Decimal`` and converted at the JSON boundary. Reading it as
  ``f64`` compiles and then panics at runtime on the first row.
* The integration client is hand-rolled over ``std::net::TcpStream``. A real
  HTTP client crate would add a TLS stack to a build that only ever talks to
  127.0.0.1, and every extra crate is another version to pin and audit.
"""
from __future__ import annotations

import json
from importlib.resources import files

from .container_images import ALPINE_IMAGE, RUST_IMAGE
from .models import FieldSpec, SynthesisRequest
from .production_contract import (
    ENV_AUTH_AUDIENCE,
    ENV_AUTH_ISSUER,
    ENV_DATABASE_URL_FILE,
    ENV_JWT_SECRET_FILE,
    ENV_OIDC_JWKS_FILE,
    ENV_OIDC_PRIVATE_KEY_FILE,
    TENANT_CLAIM,
    TENANT_SETTING,
    all_entity_sql,
    production_contract,
)
from .production_runtime import render_local_runtime
from .rendering import (
    clean,
    dockerignore,
    env_example,
    gitignore,
    kubernetes_yaml,
    openapi_yaml,
    pretty_json,
    target_readme,
)

AXUM_VERSION = "0.8.4"
TOKIO_VERSION = "1.47.1"
TOKIO_POSTGRES_VERSION = "0.7.18"
JSONWEBTOKEN_VERSION = "9.3.1"
RUST_DECIMAL_VERSION = "1.42.1"
SERDE_VERSION = "1.0.219"
SERDE_JSON_VERSION = "1.0.143"
UUID_VERSION = "1.18.0"

_LOCK_PROJECT_MARKER = "__ELMOS_PROJECT_NAME__"


def _production_lock(project_name: str) -> str:
    """Read the pinned dependency lock for the production dependency set.

    The template is generated by ``cargo generate-lockfile`` against the exact
    manifest this emitter writes, then committed. Until it exists the emitter
    cannot produce a reproducible workspace, so it fails with a named reason
    rather than emitting a build that would resolve differently on every run.
    """
    template = files("elmos_project_synthesis").joinpath(
        "templates", "rust", "Cargo.production.lock"
    )
    try:
        lock = template.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError) as error:
        raise ValueError("RUST_PRODUCTION_LOCK_TEMPLATE_MISSING") from error
    for marker in (
        f'name = "tokio-postgres"\nversion = "{TOKIO_POSTGRES_VERSION}"',
        f'name = "jsonwebtoken"\nversion = "{JSONWEBTOKEN_VERSION}"',
        f'name = "rust_decimal"\nversion = "{RUST_DECIMAL_VERSION}"',
        f'name = "axum"\nversion = "{AXUM_VERSION}"',
    ):
        if marker not in lock:
            raise ValueError(
                "RUST_PRODUCTION_LOCK_TEMPLATE_INVALID:" + marker.split('"')[1]
            )
    if lock.count(_LOCK_PROJECT_MARKER) != 1:
        raise ValueError("RUST_PRODUCTION_LOCK_TEMPLATE_INVALID:project-name-marker")
    return lock.replace(_LOCK_PROJECT_MARKER, project_name)


def _crate_name(project_name: str) -> str:
    return project_name.replace("-", "_")


def _rust_type(field: FieldSpec) -> str:
    return {
        "string": "String",
        "integer": "i64",
        "number": "f64",
        "boolean": "bool",
        "datetime": "String",
    }[field.type]


def _row_read(field: FieldSpec, index: int) -> str:
    """Read column ``index`` with the type PostgreSQL actually stores."""
    if field.type == "number":
        return f"decimal_to_f64(row.get::<_, Decimal>({index}))?"
    if field.type == "datetime":
        return f"row.get::<_, String>({index})"
    return f"row.get({index})"


def _bind_expression(field: FieldSpec) -> str:
    if field.type == "number":
        return f"&f64_to_decimal(payload.{field.name})?"
    return f"&payload.{field.name}"


def _sample_json(field: FieldSpec) -> object:
    return {
        "string": f"sample-{field.name}",
        "integer": 1,
        "number": 1.5,
        "boolean": True,
        "datetime": "2026-01-01T00:00:00Z",
    }[field.type]


_SECURITY_JWT = """
fn decoding_key() -> Result<DecodingKey, SecurityError> {
    let path = required_environment("__ENV_JWT_SECRET_FILE__")?;
    let secret = fs::read_to_string(path)?.trim().to_owned();
    if secret.len() < 32 {
        return Err(SecurityError::Configuration("JWT_SECRET_TOO_SHORT"));
    }
    Ok(DecodingKey::from_secret(secret.as_bytes()))
}

fn algorithm() -> Algorithm {
    Algorithm::HS256
}
"""

_SECURITY_OIDC = """
fn decoding_key() -> Result<DecodingKey, SecurityError> {
    let path = required_environment("__ENV_OIDC_JWKS_FILE__")?;
    let document: Value = serde_json::from_str(&fs::read_to_string(path)?)?;
    let keys = document
        .get("keys")
        .and_then(Value::as_array)
        .ok_or(SecurityError::Configuration("OIDC_JWKS_MALFORMED"))?;
    if keys.len() != 1 {
        return Err(SecurityError::Configuration("OIDC_JWKS_MUST_CONTAIN_EXACTLY_ONE_KEY"));
    }
    let modulus = keys[0]
        .get("n")
        .and_then(Value::as_str)
        .ok_or(SecurityError::Configuration("OIDC_JWKS_MISSING_MODULUS"))?;
    let exponent = keys[0]
        .get("e")
        .and_then(Value::as_str)
        .ok_or(SecurityError::Configuration("OIDC_JWKS_MISSING_EXPONENT"))?;
    DecodingKey::from_rsa_components(modulus, exponent).map_err(SecurityError::from)
}

fn algorithm() -> Algorithm {
    Algorithm::RS256
}
"""

_SECURITY_SOURCE = """
use jsonwebtoken::{Algorithm, DecodingKey, Validation, decode};
use serde::Deserialize;
__OIDC_IMPORTS__use std::env;
use std::fs;

/// Failures that mean the process is misconfigured, not that a caller is
/// unauthorized. They are kept distinct so a bad deployment surfaces at
/// startup instead of looking like a wall of rejected requests.
#[derive(Debug)]
pub enum SecurityError {
    Configuration(&'static str),
    MissingEnvironment(String),
    Io(std::io::Error),
    Jwt(jsonwebtoken::errors::Error),
    Json(serde_json::Error),
}

impl std::fmt::Display for SecurityError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Configuration(reason) => write!(formatter, "{reason}"),
            Self::MissingEnvironment(name) => {
                write!(formatter, "REQUIRED_ENVIRONMENT_MISSING:{name}")
            }
            Self::Io(error) => write!(formatter, "{error}"),
            Self::Jwt(error) => write!(formatter, "{error}"),
            Self::Json(error) => write!(formatter, "{error}"),
        }
    }
}

impl std::error::Error for SecurityError {}

impl From<std::io::Error> for SecurityError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

impl From<jsonwebtoken::errors::Error> for SecurityError {
    fn from(error: jsonwebtoken::errors::Error) -> Self {
        Self::Jwt(error)
    }
}

impl From<serde_json::Error> for SecurityError {
    fn from(error: serde_json::Error) -> Self {
        Self::Json(error)
    }
}

pub fn required_environment(name: &str) -> Result<String, SecurityError> {
    match env::var(name) {
        Ok(value) if !value.trim().is_empty() => Ok(value),
        _ => Err(SecurityError::MissingEnvironment(name.to_owned())),
    }
}

#[derive(Debug, Deserialize)]
struct Claims {
    #[serde(rename = "__TENANT_CLAIM__")]
    tenant_id: Option<String>,
}

__KEY_SOURCE__
/// Bearer verification for the production profile.
///
/// A structurally valid signature is not authorization: issuer, audience,
/// expiry and the tenant claim the database policy is keyed on are all
/// mandatory, so a token minted for another service or another tenant is
/// refused here rather than becoming a cross-tenant read.
pub struct TenantAuthenticator {
    key: DecodingKey,
    validation: Validation,
}

impl TenantAuthenticator {
    pub fn from_environment() -> Result<Self, SecurityError> {
        let mut validation = Validation::new(algorithm());
        validation.set_issuer(&[required_environment("__ENV_AUTH_ISSUER__")?]);
        validation.set_audience(&[required_environment("__ENV_AUTH_AUDIENCE__")?]);
        validation.leeway = 0;
        validation.validate_exp = true;
        let required = ["exp", "iss", "aud"].iter().map(|c| (*c).to_owned());
        validation.required_spec_claims = required.collect();
        Ok(Self { key: decoding_key()?, validation })
    }

    /// Returns the tenant a request is entitled to, or `None` for any token
    /// that fails verification for any reason.
    pub fn tenant_from(&self, authorization: Option<&str>) -> Option<String> {
        let token = authorization?.strip_prefix("Bearer ")?;
        let decoded = decode::<Claims>(token, &self.key, &self.validation).ok()?;
        decoded.claims.tenant_id.filter(|tenant| !tenant.trim().is_empty())
    }
}
"""

_STORE_SOURCE = """
use rust_decimal::Decimal;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use serde::{Deserialize, Serialize};
use tokio_postgres::{Client, NoTls, Row};
use uuid::Uuid;

// The statements are hoisted to constants rather than inlined at the call
// sites. Inline, rustfmt's line breaking would depend on how long the entity
// and column names happen to be, so a workspace that passes `cargo fmt
// --check` for one schema would fail it for another.
__SQL_CONSTS__

#[derive(Debug)]
pub enum StoreError {
    Database(tokio_postgres::Error),
    Conversion(&'static str),
}

impl std::fmt::Display for StoreError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Database(error) => write!(formatter, "{error}"),
            Self::Conversion(reason) => write!(formatter, "{reason}"),
        }
    }
}

impl std::error::Error for StoreError {}

impl From<tokio_postgres::Error> for StoreError {
    fn from(error: tokio_postgres::Error) -> Self {
        Self::Database(error)
    }
}

/// PostgreSQL stores `number` fields as `numeric(20,6)`, which tokio-postgres
/// exposes as `Decimal`. The conversion is fallible in both directions and is
/// reported rather than silently rounded.
fn decimal_to_f64(value: Decimal) -> Result<f64, StoreError> {
    value.to_f64().ok_or(StoreError::Conversion("NUMERIC_EXCEEDS_F64_RANGE"))
}

fn f64_to_decimal(value: f64) -> Result<Decimal, StoreError> {
    Decimal::from_f64(value).ok_or(StoreError::Conversion("F64_NOT_REPRESENTABLE_AS_NUMERIC"))
}

#[derive(Debug, Deserialize)]
pub struct __ENTITY__Upsert {
__UPSERT_FIELDS__
}

#[derive(Debug, Serialize)]
pub struct __ENTITY__ {
    pub id: Uuid,
__RECORD_FIELDS__
}

// Signatures below are written against these aliases so that the width of a
// line never depends on how long the caller named their entity. Without them
// a sufficiently long name pushes a signature past rustfmt's limit and the
// emitted workspace fails `cargo fmt --check`.
pub type Record = __ENTITY__;
pub type RecordUpsert = __ENTITY__Upsert;
pub type RecordStore = __ENTITY__Store;

impl __ENTITY__ {
    fn from_row(row: &Row) -> Result<Self, StoreError> {
__FROM_ROW_BODY__
    }
}

pub struct __ENTITY__Store {
    database_url: String,
}

impl __ENTITY__Store {
    pub fn new(database_url: String) -> Self {
        Self { database_url }
    }

    async fn connect(&self) -> Result<Client, StoreError> {
        let (client, connection) = tokio_postgres::connect(&self.database_url, NoTls).await?;
        tokio::spawn(async move {
            if let Err(error) = connection.await {
                eprintln!("connection closed: {error}");
            }
        });
        Ok(client)
    }

    /// Every statement runs inside one tenant-scoped transaction.
    ///
    /// `__TENANT_SETTING__` is applied with `set_config(..., true)` so it is
    /// transaction local and cannot leak to the next borrower of a pooled
    /// connection. Row level security is FORCED on every table, so that
    /// binding -- not the SQL text -- confines a request to its tenant.
    pub async fn list(&self, tenant: &str) -> Result<Vec<Record>, StoreError> {
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let rows = transaction.query(LIST_SQL, &[]).await?;
        let records = rows.iter().map(Record::from_row).collect::<Result<Vec<_>, _>>()?;
        transaction.commit().await?;
        Ok(records)
    }

    pub async fn find(&self, tenant: &str, id: Uuid) -> Result<Option<Record>, StoreError> {
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let rows = transaction.query(GET_SQL, &[&id]).await?;
        let record = rows.first().map(Record::from_row).transpose()?;
        transaction.commit().await?;
        Ok(record)
    }

    pub async fn save(
        &self,
        tenant: &str,
        id: Uuid,
        payload: RecordUpsert,
    ) -> Result<Record, StoreError> {
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
__UPSERT_QUERY__
        let row = rows.first().ok_or(StoreError::Conversion("UPSERT_RETURNED_NO_ROW"))?;
        let record = Record::from_row(row)?;
        transaction.commit().await?;
        Ok(record)
    }

    pub async fn delete(&self, tenant: &str, id: Uuid) -> Result<bool, StoreError> {
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let affected = transaction.execute(DELETE_SQL, &[&id]).await?;
        transaction.commit().await?;
        Ok(affected > 0)
    }
}

async fn bind_tenant(
    transaction: &tokio_postgres::Transaction<'_>,
    tenant: &str,
) -> Result<(), StoreError> {
    transaction.query(BIND_TENANT_SQL, &[&tenant]).await?;
    Ok(())
}
"""

_APPLICATION_SOURCE = """
use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::{Json, Router};
use serde_json::json;
use std::sync::Arc;
use uuid::Uuid;

use crate::security::{TenantAuthenticator, required_environment};
use crate::store::{RecordStore, RecordUpsert};

__PATH_CONSTS__

pub struct AppState {
    pub authenticator: TenantAuthenticator,
    pub store: RecordStore,
}

/// Every rejection carries a stable machine-readable reason and never echoes
/// the offending value back to the caller.
struct ApiError(StatusCode, &'static str);

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.0, Json(json!({ "error": self.1 }))).into_response()
    }
}

fn tenant_of(state: &AppState, headers: &HeaderMap) -> Result<String, ApiError> {
    let authorization = headers.get("authorization").and_then(|value| value.to_str().ok());
    state
        .authenticator
        .tenant_from(authorization)
        .ok_or(ApiError(StatusCode::UNAUTHORIZED, "unauthorized"))
}

const BAD_RECORD_ID: &str = "RECORD_ID_MUST_BE_UUID";

fn record_id(raw: &str) -> Result<Uuid, ApiError> {
    Uuid::parse_str(raw).map_err(|_| ApiError(StatusCode::UNPROCESSABLE_ENTITY, BAD_RECORD_ID))
}

/// Required string fields are rejected when blank. Kept as a helper so each
/// generated call site is one short line: inlining the check would make
/// rustfmt's output depend on how long the field name is.
fn reject_blank(value: &str) -> Result<(), ApiError> {
    if value.trim().is_empty() {
        return Err(ApiError(StatusCode::UNPROCESSABLE_ENTITY, "PAYLOAD_INVALID"));
    }
    Ok(())
}

fn internal(error: impl std::fmt::Display) -> ApiError {
    eprintln!("request failed: {error}");
    ApiError(StatusCode::INTERNAL_SERVER_ERROR, "internal_error")
}

async fn health() -> impl IntoResponse {
    Json(json!({ "status": "UP", "service": SERVICE_NAME }))
}

async fn list_records(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> Result<impl IntoResponse, ApiError> {
    let tenant = tenant_of(&state, &headers)?;
    let records = state.store.list(&tenant).await.map_err(internal)?;
    Ok(Json(records))
}

async fn get_record(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
) -> Result<impl IntoResponse, ApiError> {
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
    match state.store.find(&tenant, id).await.map_err(internal)? {
        Some(record) => Ok(Json(record)),
        None => Err(ApiError(StatusCode::NOT_FOUND, "not_found")),
    }
}

async fn put_record(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
    Json(payload): Json<RecordUpsert>,
) -> Result<impl IntoResponse, ApiError> {
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
__REQUIRED_CHECKS__
    let record = state.store.save(&tenant, id, payload).await.map_err(internal)?;
    Ok(Json(record))
}

async fn delete_record(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
) -> Result<impl IntoResponse, ApiError> {
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
    state.store.delete(&tenant, id).await.map_err(internal)?;
    Ok(StatusCode::NO_CONTENT)
}

pub fn router(state: Arc<AppState>) -> Router {
    Router::new()
        .route("/health", get(health))
        .route(COLLECTION_PATH, get(list_records))
        .route(ITEM_PATH, get(get_record).put(put_record).delete(delete_record))
        .with_state(state)
}

/// The connection string arrives by file reference, never inline, so it never
/// appears in process arguments or configuration dumps.
pub fn build_state() -> Result<AppState, Box<dyn std::error::Error>> {
    let path = required_environment("__ENV_DATABASE_URL_FILE__")?;
    let url = std::fs::read_to_string(path)?.trim().to_owned();
    if !url.starts_with("postgresql://") {
        return Err("DATABASE_URL_SCHEME_UNSUPPORTED".into());
    }
    Ok(AppState {
        authenticator: TenantAuthenticator::from_environment()?,
        store: RecordStore::new(url),
    })
}
"""

_MAIN_SOURCE = """
use std::sync::Arc;

use __CRATE__::{build_state, router};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let port =
        std::env::var("PORT").ok().and_then(|value| value.parse::<u16>().ok()).unwrap_or(__PORT__);
    let host = std::env::var("HOST").unwrap_or_else(|_| "0.0.0.0".to_owned());
    let listener = tokio::net::TcpListener::bind((host.as_str(), port)).await?;
    axum::serve(listener, router(Arc::new(build_state()?))).await?;
    Ok(())
}
"""

_LIB_SOURCE = """
pub mod application;
pub mod security;
pub mod store;

pub use application::{AppState, build_state, router};
"""

_TEST_JWT_SIGNER = """
fn signing(valid: bool) -> (Header, EncodingKey) {
    if valid {
        let path = env::var("__ENV_JWT_SECRET_FILE__").expect("secret path");
        let secret = fs::read_to_string(path).expect("secret file");
        let key = EncodingKey::from_secret(secret.trim().as_bytes());
        (Header::new(Algorithm::HS256), key)
    } else {
        let key = EncodingKey::from_secret(WRONG_SECRET.as_bytes());
        (Header::new(Algorithm::HS256), key)
    }
}
"""

# The harness provisions one OIDC private key and no second one, so the
# "wrong signature" case is signed with a different *algorithm* instead of a
# different RSA key. That still proves the token is refused, and it covers
# algorithm confusion -- an HS256 token offered to an RS256 verifier -- which
# a second RSA key would not have exercised.
_TEST_OIDC_SIGNER = """
fn signing(valid: bool) -> (Header, EncodingKey) {
    if valid {
        let path = env::var("__ENV_OIDC_PRIVATE_KEY_FILE__").expect("private key path");
        let pem = fs::read_to_string(path).expect("private key file");
        let key = EncodingKey::from_rsa_pem(pem.as_bytes()).expect("rsa pem");
        (Header::new(Algorithm::RS256), key)
    } else {
        let key = EncodingKey::from_secret(WRONG_SECRET.as_bytes());
        (Header::new(Algorithm::HS256), key)
    }
}
"""

_TEST_SOURCE = """
use jsonwebtoken::{Algorithm, EncodingKey, Header, encode};
use serde::Serialize;
use std::env;
use std::fs;
use std::io::{Read, Write};
use std::net::TcpStream;
use std::time::{SystemTime, UNIX_EPOCH};

/// Hoisted so the assertion below stays one short line regardless of how many
/// fields the entity declares.
const WRONG_SECRET: &str = "an-entirely-different-secret-value-of-length";
__TEST_CONSTS__

#[derive(Serialize)]
struct Claims {
    iss: String,
    aud: String,
    sub: String,
    iat: u64,
    exp: u64,
    #[serde(rename = "__TENANT_CLAIM__", skip_serializing_if = "Option::is_none")]
    tenant_id: Option<String>,
}

__SIGNER__
fn token(tenant: Option<&str>, issuer: &str, audience: &str, valid: bool) -> String {
    let now = SystemTime::now().duration_since(UNIX_EPOCH).expect("clock").as_secs();
    let claims = Claims {
        iss: issuer.to_owned(),
        aud: audience.to_owned(),
        sub: "integration-subject".to_owned(),
        iat: now,
        exp: now + 300,
        tenant_id: tenant.map(str::to_owned),
    };
    let (header, key) = signing(valid);
    encode(&header, &claims, &key).expect("token")
}

/// A deliberately small HTTP/1.1 client. The scenario only ever talks to
/// 127.0.0.1, so pulling in a full client crate would add a TLS stack and
/// another pinned dependency for no benefit.
fn send(method: &str, path: &str, bearer: Option<&str>, body: Option<&str>) -> (u16, String) {
    let port = env::var("PORT").unwrap_or_else(|_| "__PORT__".to_owned());
    let mut stream = TcpStream::connect(format!("127.0.0.1:{port}")).expect("connect");
    let mut request =
        format!("{method} {path} HTTP/1.1\\r\\nHost: 127.0.0.1\\r\\nConnection: close\\r\\n");
    if let Some(value) = bearer {
        request.push_str(&format!("Authorization: Bearer {value}\\r\\n"));
    }
    match body {
        Some(payload) => request.push_str(&format!(
            "Content-Type: application/json\\r\\nContent-Length: {}\\r\\n\\r\\n{payload}",
            payload.len()
        )),
        None => request.push_str("Content-Length: 0\\r\\n\\r\\n"),
    }
    stream.write_all(request.as_bytes()).expect("write");
    stream.flush().expect("flush");
    let mut raw = String::new();
    stream.read_to_string(&mut raw).expect("read");
    let status = raw
        .split_whitespace()
        .nth(1)
        .and_then(|code| code.parse::<u16>().ok())
        .expect("status line");
    let body = raw.split_once("\\r\\n\\r\\n").map(|(_, rest)| rest).unwrap_or("");
    (status, body.to_owned())
}

/// The ten-step scenario from production-contract.json, executed against the
/// PostgreSQL instance the runtime harness provisioned.
///
/// Marked `#[ignore]` so `cargo test` stays offline and database free; the
/// harness selects it explicitly with `--ignored`.
#[test]
#[ignore]
fn runs_the_shared_production_scenario() {
    let issuer = env::var("__ENV_AUTH_ISSUER__").expect("issuer");
    let audience = env::var("__ENV_AUTH_AUDIENCE__").expect("audience");
    let tenant_a = token(Some("tenant-a"), &issuer, &audience, true);
    let tenant_b = token(Some("tenant-b"), &issuer, &audience, true);

    // health-unauthenticated
    assert_eq!(send("GET", "/health", None, None).0, 200);
    // missing-token-rejected
    assert_eq!(send("GET", COLLECTION_PATH, None, None).0, 401);
    // bad-signature-rejected
    let forged = token(Some("tenant-a"), &issuer, &audience, false);
    assert_eq!(send("GET", COLLECTION_PATH, Some(&forged), None).0, 401);
    // wrong-audience-rejected
    let other_audience = token(Some("tenant-a"), &issuer, "another-service", true);
    assert_eq!(send("GET", COLLECTION_PATH, Some(&other_audience), None).0, 401);
    // wrong-issuer-rejected
    let other_issuer = token(Some("tenant-a"), "https://attacker.invalid/", &audience, true);
    assert_eq!(send("GET", COLLECTION_PATH, Some(&other_issuer), None).0, 401);
    // missing-tenant-claim-rejected
    let no_tenant = token(None, &issuer, &audience, true);
    assert_eq!(send("GET", COLLECTION_PATH, Some(&no_tenant), None).0, 401);

    // upsert-and-read
    let path = format!("{COLLECTION_PATH}/{RECORD_ID}");
    let created = send("PUT", &path, Some(&tenant_a), Some(SAMPLE_BODY));
    assert_eq!(created.0, 200, "{}", created.1);
    let read = send("GET", &path, Some(&tenant_a), None);
    assert_eq!(read.0, 200);
    assert!(read.1.contains(RECORD_ID));

    // list-scoped-to-tenant
    let listed = send("GET", COLLECTION_PATH, Some(&tenant_a), None);
    assert_eq!(listed.0, 200);
    assert!(listed.1.contains(RECORD_ID));

    // cross-tenant-read-blocked
    assert_eq!(send("GET", &path, Some(&tenant_b), None).0, 404);
    let other = send("GET", COLLECTION_PATH, Some(&tenant_b), None);
    assert!(!other.1.contains(RECORD_ID));

    // delete-removes-record
    assert_eq!(send("DELETE", &path, Some(&tenant_a), None).0, 204);
    assert_eq!(send("GET", &path, Some(&tenant_a), None).0, 404);
}
"""


_RUSTFMT_MAX_WIDTH = 100


def _string_const(name: str, literal: str) -> str:
    """Emit a ``&str`` constant already laid out the way rustfmt would.

    rustfmt never reflows a string literal; for a `const` it only chooses
    whether the literal shares the line with the binding or moves to the next
    one, and that choice is a pure function of the line width. Reproducing the
    rule here keeps `cargo fmt --check` clean for schemas whose names are long
    enough to push the declaration over the limit.
    """
    single = f"const {name}: &str = {literal};"
    if len(single) <= _RUSTFMT_MAX_WIDTH:
        return single
    # Wrapping only happens when it actually buys something. A literal that
    # overflows even on its own indented line is left where it is, because
    # rustfmt will not break a string to make it fit.
    if len(literal) + 5 <= _RUSTFMT_MAX_WIDTH:
        return f"const {name}: &str =\n    {literal};"
    return single


def _upsert_query(bind_values: list[str], *, sql_const: str = "UPSERT_SQL") -> str:
    """Lay out the upsert `.query(..)` call the way rustfmt would.

    This is the one call whose width genuinely tracks the schema: it binds one
    parameter per field. Below the limit rustfmt keeps it on a single line;
    above it, the call and the parameter slice are both exploded one entry per
    line. Both forms are reproduced here so the emitted workspace is clean
    whatever the entity turns out to look like.
    """
    values = ["&tenant", "&id", *bind_values]
    parameters = ", ".join(values)
    collapsed = (
        f"        let rows = transaction.query({sql_const}, &[{parameters}]).await?;"
    )
    if len(collapsed) <= _RUSTFMT_MAX_WIDTH:
        return collapsed
    broken = f"            .query({sql_const}, &[{parameters}])"
    if len(broken) <= _RUSTFMT_MAX_WIDTH:
        return f"        let rows = transaction\n{broken}\n            .await?;"
    param_line = f"                &[{parameters}],"
    if len(param_line) <= _RUSTFMT_MAX_WIDTH:
        return (
            "        let rows = transaction\n"
            "            .query(\n"
            f"                {sql_const},\n"
            f"{param_line}\n"
            "            )\n"
            "            .await?;"
        )
    entries = "\n".join(f"                    {value}," for value in values)
    return (
        "        let rows = transaction\n"
        "            .query(\n"
        f"                {sql_const},\n"
        "                &[\n"
        f"{entries}\n"
        "                ],\n"
        "            )\n"
        "            .await?;"
    )


def _from_row_body(assignments: list[str]) -> str:
    """Lay out the `Ok(Self { .. })` literal the way rustfmt would.

    A struct literal collapses onto one line while it fits and explodes one
    field per line once it does not, so a one-field entity and a six-field
    entity need different source text for the same template.
    """
    single = "        Ok(Self { " + ", ".join(assignments) + " })"
    if len(single) <= _RUSTFMT_MAX_WIDTH:
        return single
    entries = "\n".join(f"            {assignment}," for assignment in assignments)
    return f"        Ok(Self {{\n{entries}\n        }})"


def _substitute(template: str, replacements: dict[str, str]) -> str:
    rendered = template.lstrip("\n")
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    if "__" in rendered:
        leftovers = sorted(
            {
                fragment
                for fragment in rendered.split()
                if fragment.startswith("__") and fragment.endswith("__")
            }
        )
        if leftovers:
            raise ValueError("RUST_TEMPLATE_TOKEN_UNRESOLVED:" + ",".join(leftovers))
    return rendered


def _security_source(request: SynthesisRequest) -> str:
    if request.auth_mode == "jwt":
        key_source = _substitute(
            _SECURITY_JWT, {"__ENV_JWT_SECRET_FILE__": ENV_JWT_SECRET_FILE}
        )
        oidc_imports = ""
        # rustfmt sorts a contiguous import block, so the OIDC-only import has
        # to be emitted in its already-sorted position rather than appended.
    else:
        key_source = _substitute(
            _SECURITY_OIDC, {"__ENV_OIDC_JWKS_FILE__": ENV_OIDC_JWKS_FILE}
        )
        oidc_imports = "use serde_json::Value;\n"
    return _substitute(
        _SECURITY_SOURCE,
        {
            "__OIDC_IMPORTS__": oidc_imports,
            "__KEY_SOURCE__": key_source.strip() + "\n",
            "__TENANT_CLAIM__": TENANT_CLAIM,
            "__ENV_AUTH_ISSUER__": ENV_AUTH_ISSUER,
            "__ENV_AUTH_AUDIENCE__": ENV_AUTH_AUDIENCE,
        },
    )


def _store_source(request: SynthesisRequest) -> str:
    from .models import pascal

    statements = {item.entity: item for item in all_entity_sql(request, placeholder="${}")}
    shared = f"""
use rust_decimal::Decimal;
use rust_decimal::prelude::{{FromPrimitive, ToPrimitive}};
use serde::{{Deserialize, Serialize}};
use tokio_postgres::{{Client, NoTls, Row}};
use uuid::Uuid;

{_string_const("BIND_TENANT_SQL", json.dumps(f"SELECT set_config('{TENANT_SETTING}', $1, true)"))}

#[derive(Debug)]
pub enum StoreError {{
    Database(tokio_postgres::Error),
    Conversion(&'static str),
}}

impl std::fmt::Display for StoreError {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        match self {{
            Self::Database(error) => write!(formatter, "{{error}}"),
            Self::Conversion(reason) => write!(formatter, "{{reason}}"),
        }}
    }}
}}

impl std::error::Error for StoreError {{}}

impl From<tokio_postgres::Error> for StoreError {{
    fn from(error: tokio_postgres::Error) -> Self {{
        Self::Database(error)
    }}
}}

fn decimal_to_f64(value: Decimal) -> Result<f64, StoreError> {{
    value.to_f64().ok_or(StoreError::Conversion("NUMERIC_EXCEEDS_F64_RANGE"))
}}

fn f64_to_decimal(value: f64) -> Result<Decimal, StoreError> {{
    Decimal::from_f64(value).ok_or(StoreError::Conversion("F64_NOT_REPRESENTABLE_AS_NUMERIC"))
}}
"""
    blocks: list[str] = [shared]
    for entity in request.entities:
        entity_type = pascal(entity.singular)
        prefix = entity.singular.upper().replace("-", "_")
        sql = statements[entity.singular]
        upsert_fields = "\n".join(
            f"    pub {field.name}: {_rust_type(field)}," for field in entity.fields
        )
        record_fields = upsert_fields
        row_assignments = ["id: row.get(0)"] + [
            f"{field.name}: {_row_read(field, index + 1)}"
            for index, field in enumerate(entity.fields)
        ]
        bind_values = [_bind_expression(field) for field in entity.fields]
        sql_consts = "\n".join(
            _string_const(name, json.dumps(statement))
            for name, statement in (
                (f"{prefix}_LIST_SQL", sql.list_sql),
                (f"{prefix}_GET_SQL", sql.get_sql),
                (f"{prefix}_UPSERT_SQL", sql.upsert_sql),
                (f"{prefix}_DELETE_SQL", sql.delete_sql),
            )
        )
        upsert_query = _upsert_query(bind_values, sql_const=f"{prefix}_UPSERT_SQL")
        list_sig = f"    pub async fn list(&self, tenant: &str) -> Result<Vec<{entity_type}>, StoreError> {{"
        if len(list_sig) > 100:
            list_sig = (
                "    pub async fn list(\n"
                "        &self,\n"
                "        tenant: &str,\n"
                f"    ) -> Result<Vec<{entity_type}>, StoreError> {{"
            )
        list_records = (
            f"        let records = rows.iter().map({entity_type}::from_row).collect::<Result<Vec<_>, _>>()?;"
        )
        if len(list_records) > 92:
            list_records = (
                "        let records =\n"
                f"            rows.iter().map({entity_type}::from_row).collect::<Result<Vec<_>, _>>()?;"
            )
        find_sig = f"    pub async fn find(&self, tenant: &str, id: Uuid) -> Result<Option<{entity_type}>, StoreError> {{"
        if len(find_sig) > 100:
            find_sig = (
                "    pub async fn find(\n"
                "        &self,\n"
                "        tenant: &str,\n"
                "        id: Uuid,\n"
                f"    ) -> Result<Option<{entity_type}>, StoreError> {{"
            )
        blocks.append(
            f"""
{sql_consts}

#[derive(Debug, Deserialize)]
pub struct {entity_type}Upsert {{
{upsert_fields}
}}

#[derive(Debug, Serialize)]
pub struct {entity_type} {{
    pub id: Uuid,
{record_fields}
}}

impl {entity_type} {{
    fn from_row(row: &Row) -> Result<Self, StoreError> {{
{_from_row_body(row_assignments)}
    }}
}}

pub struct {entity_type}Store {{
    database_url: String,
}}

impl {entity_type}Store {{
    pub fn new(database_url: String) -> Self {{
        Self {{ database_url }}
    }}

    async fn connect(&self) -> Result<Client, StoreError> {{
        let (client, connection) = tokio_postgres::connect(&self.database_url, NoTls).await?;
        tokio::spawn(async move {{
            if let Err(error) = connection.await {{
                eprintln!("connection closed: {{error}}");
            }}
        }});
        Ok(client)
    }}

{list_sig}
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let rows = transaction.query({prefix}_LIST_SQL, &[]).await?;
{list_records}
        transaction.commit().await?;
        Ok(records)
    }}

{find_sig}
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let rows = transaction.query({prefix}_GET_SQL, &[&id]).await?;
        let record = rows.first().map({entity_type}::from_row).transpose()?;
        transaction.commit().await?;
        Ok(record)
    }}

    pub async fn save(
        &self,
        tenant: &str,
        id: Uuid,
        payload: {entity_type}Upsert,
    ) -> Result<{entity_type}, StoreError> {{
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
{upsert_query}
        let row = rows.first().ok_or(StoreError::Conversion("UPSERT_RETURNED_NO_ROW"))?;
        let record = {entity_type}::from_row(row)?;
        transaction.commit().await?;
        Ok(record)
    }}

    pub async fn delete(&self, tenant: &str, id: Uuid) -> Result<bool, StoreError> {{
        let mut client = self.connect().await?;
        let transaction = client.transaction().await?;
        bind_tenant(&transaction, tenant).await?;
        let affected = transaction.execute({prefix}_DELETE_SQL, &[&id]).await?;
        transaction.commit().await?;
        Ok(affected > 0)
    }}
}}
"""
        )
    blocks.append(
        """
async fn bind_tenant(
    transaction: &tokio_postgres::Transaction<'_>,
    tenant: &str,
) -> Result<(), StoreError> {
    transaction.query(BIND_TENANT_SQL, &[&tenant]).await?;
    Ok(())
}
"""
    )
    return "\n\n".join(block.strip() for block in blocks) + "\n"


def _entity_type(request: SynthesisRequest) -> str:
    from .models import pascal

    return pascal(request.entities[0].singular)


def _application_source(request: SynthesisRequest) -> str:
    from .models import pascal

    imports = ", ".join(
        f"{pascal(entity.singular)}Store, {pascal(entity.singular)}Upsert"
        for entity in request.entities
    )
    state_fields = "\n    ".join(
        f"pub {entity.singular}_store: {pascal(entity.singular)}Store,"
        for entity in request.entities
    )
    path_consts = [_string_const("SERVICE_NAME", json.dumps(request.project_name))]
    handlers: list[str] = []
    routes = ['.route("/health", get(health))']
    build_fields = ["authenticator: TenantAuthenticator::from_environment()?,"]
    for entity in request.entities:
        entity_type = pascal(entity.singular)
        prefix = entity.singular
        collection = f"/{entity.plural}"
        item = f"/{entity.plural}/{{id}}"
        path_consts.append(_string_const(f"{prefix.upper()}_COLLECTION_PATH", json.dumps(collection)))
        path_consts.append(_string_const(f"{prefix.upper()}_ITEM_PATH", json.dumps(item)))
        checks = "\n    ".join(
            f"    reject_blank(&payload.{field.name})?;"
            for field in entity.fields
            if field.required and field.type == "string"
        ) or "    // no blank-string constraints declared"
        save_line = (
            f"    let record = state.{prefix}_store.save(&tenant, id, payload).await.map_err(internal)?;"
        )
        if len(save_line) > 100:
            save_stmt = (
                "    let record =\n"
                f"        state.{prefix}_store.save(&tenant, id, payload).await.map_err(internal)?;"
            )
        else:
            save_stmt = save_line
        handlers.append(
            f"""
async fn list_{entity.plural}(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
) -> Result<impl IntoResponse, ApiError> {{
    let tenant = tenant_of(&state, &headers)?;
    let records = state.{prefix}_store.list(&tenant).await.map_err(internal)?;
    Ok(Json(records))
}}

async fn get_{entity.singular}(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
) -> Result<impl IntoResponse, ApiError> {{
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
    match state.{prefix}_store.find(&tenant, id).await.map_err(internal)? {{
        Some(record) => Ok(Json(record)),
        None => Err(ApiError(StatusCode::NOT_FOUND, "not_found")),
    }}
}}

async fn put_{entity.singular}(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
    Json(payload): Json<{entity_type}Upsert>,
) -> Result<impl IntoResponse, ApiError> {{
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
{checks}
{save_stmt}
    Ok(Json(record))
}}

async fn delete_{entity.singular}(
    State(state): State<Arc<AppState>>,
    headers: HeaderMap,
    Path(raw_id): Path<String>,
) -> Result<impl IntoResponse, ApiError> {{
    let tenant = tenant_of(&state, &headers)?;
    let id = record_id(&raw_id)?;
    state.{prefix}_store.delete(&tenant, id).await.map_err(internal)?;
    Ok(StatusCode::NO_CONTENT)
}}
"""
        )
        routes.append(
            f".route({prefix.upper()}_COLLECTION_PATH, get(list_{entity.plural}))"
        )
        item_route = (
            f".route({prefix.upper()}_ITEM_PATH, "
            f"get(get_{entity.singular}).put(put_{entity.singular}).delete(delete_{entity.singular}))"
        )
        if 8 + len(item_route) > 100:
            routes.append(
                f".route(\n"
                f"            {prefix.upper()}_ITEM_PATH,\n"
                f"            get(get_{entity.singular})\n"
                f"                .put(put_{entity.singular})\n"
                f"                .delete(delete_{entity.singular}),\n"
                f"        )"
            )
        else:
            routes.append(item_route)
        build_fields.append(f"{prefix}_store: {entity_type}Store::new(url.clone()),")
    route_chain = "\n        ".join(routes)
    handlers_str = "\n\n".join(h.strip() for h in handlers)
    build_fields_str = "\n".join(f"        {field}" for field in build_fields)
    return f"""use axum::extract::{{Path, State}};
use axum::http::{{HeaderMap, StatusCode}};
use axum::response::{{IntoResponse, Response}};
use axum::routing::get;
use axum::{{Json, Router}};
use serde_json::json;
use std::sync::Arc;
use uuid::Uuid;

use crate::security::{{TenantAuthenticator, required_environment}};
use crate::store::{{{imports}}};

{chr(10).join(path_consts)}

pub struct AppState {{
    pub authenticator: TenantAuthenticator,
    {state_fields}
}}

struct ApiError(StatusCode, &'static str);

impl IntoResponse for ApiError {{
    fn into_response(self) -> Response {{
        (self.0, Json(json!({{ "error": self.1 }}))).into_response()
    }}
}}

fn tenant_of(state: &AppState, headers: &HeaderMap) -> Result<String, ApiError> {{
    let authorization = headers.get("authorization").and_then(|value| value.to_str().ok());
    state
        .authenticator
        .tenant_from(authorization)
        .ok_or(ApiError(StatusCode::UNAUTHORIZED, "unauthorized"))
}}

const BAD_RECORD_ID: &str = "RECORD_ID_MUST_BE_UUID";

fn record_id(raw: &str) -> Result<Uuid, ApiError> {{
    Uuid::parse_str(raw).map_err(|_| ApiError(StatusCode::BAD_REQUEST, BAD_RECORD_ID))
}}

fn reject_blank(value: &str) -> Result<(), ApiError> {{
    if value.trim().is_empty() {{
        Err(ApiError(StatusCode::BAD_REQUEST, "string_value_blank"))
    }} else {{
        Ok(())
    }}
}}

fn internal(error: impl std::fmt::Display) -> ApiError {{
    eprintln!("request failed: {{error}}");
    ApiError(StatusCode::INTERNAL_SERVER_ERROR, "internal_error")
}}

async fn health() -> impl IntoResponse {{
    Json(json!({{ "status": "UP", "service": SERVICE_NAME }}))
}}

{handlers_str}

pub fn router(state: Arc<AppState>) -> Router {{
    Router::new()
        {route_chain}
        .with_state(state)
}}

pub fn build_state() -> Result<AppState, Box<dyn std::error::Error>> {{
    let path = required_environment("{ENV_DATABASE_URL_FILE}")?;
    let url = std::fs::read_to_string(path)?.trim().to_owned();
    if !url.starts_with("postgresql://") {{
        return Err("DATABASE_URL_SCHEME_UNSUPPORTED".into());
    }}
    Ok(AppState {{
{build_fields_str}
    }})
}}
"""


def _test_source(request: SynthesisRequest, port: int) -> str:
    entity = request.entities[0]
    body = json.dumps(
        {field.name: _sample_json(field) for field in entity.fields},
        ensure_ascii=False,
    )
    if request.auth_mode == "jwt":
        signer = _substitute(
            _TEST_JWT_SIGNER, {"__ENV_JWT_SECRET_FILE__": ENV_JWT_SECRET_FILE}
        )
    else:
        signer = _substitute(
            _TEST_OIDC_SIGNER,
            {"__ENV_OIDC_PRIVATE_KEY_FILE__": ENV_OIDC_PRIVATE_KEY_FILE},
        )
    return _substitute(
        _TEST_SOURCE,
        {
            "__SIGNER__": signer.strip() + "\n",
            "__TENANT_CLAIM__": TENANT_CLAIM,
            "__TEST_CONSTS__": "\n".join(
                (
                    _string_const("SAMPLE_BODY", json.dumps(body)),
                    _string_const(
                        "RECORD_ID", '"6f1d9c52-4f0a-4c2e-9a58-6f4b2c8d1e70"'
                    ),
                    _string_const("COLLECTION_PATH", json.dumps(f"/{entity.plural}")),
                )
            ),
            "__PORT__": str(port),
            "__ENV_AUTH_ISSUER__": ENV_AUTH_ISSUER,
            "__ENV_AUTH_AUDIENCE__": ENV_AUTH_AUDIENCE,
        },
    )


def render_rust_production(request: SynthesisRequest, port: int) -> dict[str, str]:
    crate = _crate_name(request.project_name)
    return {
        ".gitignore": gitignore(),
        ".dockerignore": dockerignore(),
        ".env.example": env_example(request, port),
        "production-contract.json": pretty_json(production_contract(request)),
        "Cargo.toml": clean(
            f"""
            [package]
            name = "{request.project_name}"
            version = "1.0.0"
            edition = "2024"
            rust-version = "1.89"
            description = {json.dumps(request.description, ensure_ascii=False)}

            [lib]
            path = "src/lib.rs"

            [[bin]]
            name = "{request.project_name}"
            path = "src/main.rs"

            [dependencies]
            axum = "={AXUM_VERSION}"
            jsonwebtoken = "={JSONWEBTOKEN_VERSION}"
            rust_decimal = {{ version = "={RUST_DECIMAL_VERSION}", features = ["db-postgres"] }}
            serde = {{ version = "={SERDE_VERSION}", features = ["derive"] }}
            serde_json = "={SERDE_JSON_VERSION}"
            tokio = {{ version = "={TOKIO_VERSION}", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }}
            tokio-postgres = {{ version = "={TOKIO_POSTGRES_VERSION}", features = ["with-uuid-1"] }}
            uuid = {{ version = "={UUID_VERSION}", features = ["v4", "serde"] }}

            [profile.release]
            strip = true
            lto = "thin"
            codegen-units = 1
            """
        ),
        "Cargo.lock": _production_lock(request.project_name),
        # The workspace pins its own formatting rules. rustfmt's defaults add
        # several sub-width heuristics (fn_call_width and friends) on top of
        # max_width, and whether a generated line trips one of them depends on
        # how long the caller happened to name their entity and fields. With
        # "Max" there is a single rule left, which the emitter can and does
        # model exactly -- so `cargo fmt --check` passes for any schema instead
        # of only the ones the templates were hand-tuned against.
        "rustfmt.toml": clean(
            """
            max_width = 100
            use_small_heuristics = "Max"
            """
        ),
        "rust-toolchain.toml": clean(
            """
            [toolchain]
            channel = "1.89.0"
            components = ["clippy", "rustfmt"]
            """
        ),
        "src/lib.rs": _LIB_SOURCE.lstrip("\n"),
        "src/main.rs": _substitute(
            _MAIN_SOURCE, {"__CRATE__": crate, "__PORT__": str(port)}
        ),
        "src/security.rs": _security_source(request),
        "src/store.rs": _store_source(request),
        "src/application.rs": _application_source(request),
        "tests/production_integration.rs": _test_source(request, port),
        "scripts/local_runtime.py": render_local_runtime(
            auth_mode=request.auth_mode,
            app_command=["cargo", "run", "--locked", "--release"],
            verify_command=[
                "cargo",
                "test",
                "--locked",
                "--release",
                "--test",
                "production_integration",
                "--",
                "--ignored",
            ],
        ),
        "openapi.yaml": openapi_yaml(request, server_port=port),
        "Dockerfile": clean(
            f"""
            FROM {RUST_IMAGE} AS build
            WORKDIR /workspace
            COPY . .
            RUN cargo build --locked --release

            FROM {ALPINE_IMAGE}
            RUN addgroup -S app && adduser -S -G app -u 10001 app
            WORKDIR /app
            COPY --from=build /workspace/target/release/{request.project_name} ./service
            USER 10001:10001
            EXPOSE {port}
            ENTRYPOINT ["./service"]
            """
        ),
        "deploy/kubernetes.yaml": kubernetes_yaml(request, language="rust", port=port),
        ".github/workflows/ci.yml": clean(
            """
            name: rust-production-ci
            on:
              push:
              pull_request:
            permissions:
              contents: read
            jobs:
              test:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
                  - run: cargo fmt --check
                  - run: cargo clippy --locked --all-targets --all-features -- -D warnings
                  - run: cargo test --locked --all-features
                  - run: python3 scripts/local_runtime.py --verify
            """
        ),
        "Makefile": clean(
            """
            .PHONY: test verify run build
            test:
            \tcargo fmt --check && cargo clippy --locked --all-targets -- -D warnings && cargo test --locked
            verify:
            \tpython3 scripts/local_runtime.py --verify
            run:
            \tpython3 scripts/local_runtime.py
            build:
            \tcargo build --locked --release
            """
        ),
        "README.md": target_readme(
            request,
            language="Rust 1.89.0",
            framework=f"Axum {AXUM_VERSION} + tokio-postgres",
            port=port,
            commands=(
                "cargo fmt --check\n"
                "cargo clippy --locked --all-targets -- -D warnings\n"
                "cargo test --locked\n"
                "python3 scripts/local_runtime.py --verify"
            ),
        ),
    }
