"""ELMOS Industrial IoT Protocol Semantic Transformer.

Maps industrial OT protocols (Modbus TCP/RTU registers, Profinet, PLC tags)
to Cloud IT standards: OPC-UA Node IDs, MQTT CloudEvents payloads,
and ROS2 robotic action & sensor topics.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class Endianness(str, Enum):
    BIG_ENDIAN = "ABCD"
    LITTLE_ENDIAN = "DCBA"
    MID_BIG_ENDIAN = "BADC"
    MID_LITTLE_ENDIAN = "CDAB"


@dataclass
class IndustrialTag:
    address: int
    name: str
    data_type: str
    description: str = ""
    engineering_unit: str = ""


@dataclass
class IndustrialMappingResult:
    source_protocol: str
    target_protocol: str
    mapped_tags: List[Dict[str, Any]] = field(default_factory=list)
    cloudevents_schema: Dict[str, Any] = field(default_factory=dict)
    opcua_nodes: List[Dict[str, Any]] = field(default_factory=list)
    ros2_msg_definition: str = ""
    merkle_receipt: str = ""


class IndustrialProtocolMapper:
    """Enterprise Industrial Protocol Semantic Transformer."""

    def __init__(self) -> None:
        pass

    def parse_tags_string(self, raw_tags: str) -> List[IndustrialTag]:
        """Parses tag specification e.g. '40001:FLOAT32:MotorTemp;40003:UINT16:RPM'."""
        tags: List[IndustrialTag] = []
        chunks = [c.strip() for c in raw_tags.split(";") if c.strip()]
        for chunk in chunks:
            parts = chunk.split(":")
            if len(parts) >= 3:
                addr = int(re.sub(r"\D", "", parts[0]) or "0")
                dtype = parts[1].upper()
                name = parts[2]
                unit = parts[3] if len(parts) > 3 else ""
                tags.append(IndustrialTag(address=addr, name=name, data_type=dtype, engineering_unit=unit))
            elif len(parts) == 2:
                addr = int(re.sub(r"\D", "", parts[0]) or "0")
                name = parts[1]
                tags.append(IndustrialTag(address=addr, name=name, data_type="UINT16"))
        return tags

    def map_modbus_to_opcua_and_cloud(
        self, tags_spec: str, namespace_idx: int = 2, device_id: str = "RobotArm_01"
    ) -> IndustrialMappingResult:
        tags = self.parse_tags_string(tags_spec)
        if not tags:
            tags = [
                IndustrialTag(address=40001, name="MotorTemperature", data_type="FLOAT32", engineering_unit="celsius"),
                IndustrialTag(address=40003, name="RotationalSpeed", data_type="UINT16", engineering_unit="rpm"),
                IndustrialTag(address=40004, name="Torque", data_type="FLOAT32", engineering_unit="Nm"),
            ]

        mapped_tags: List[Dict[str, Any]] = []
        opcua_nodes: List[Dict[str, Any]] = []
        cloudevent_props: Dict[str, Any] = {}
        ros2_fields: List[str] = []

        for tag in tags:
            node_id = f"ns={namespace_idx};s={device_id}.{tag.name}"
            mapped_tags.append({
                "modbus_address": tag.address,
                "tag_name": tag.name,
                "data_type": tag.data_type,
                "opcua_node_id": node_id,
                "unit": tag.engineering_unit,
            })

            opcua_nodes.append({
                "nodeId": node_id,
                "browseName": tag.name,
                "dataType": self._to_opcua_type(tag.data_type),
                "accessLevel": "CurrentRead | CurrentWrite",
            })

            cloudevent_props[tag.name] = {
                "type": "number" if "FLOAT" in tag.data_type or "INT" in tag.data_type else "string",
                "modbusRegister": tag.address,
                "unit": tag.engineering_unit,
            }

            ros2_fields.append(f"{self._to_ros2_type(tag.data_type)} {self._snake_case(tag.name)}")

        cloudevent_schema = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "title": f"{device_id}TelemetryEvent",
            "properties": {
                "specversion": {"type": "string", "const": "1.0"},
                "type": {"type": "string", "const": f"com.elmos.industrial.{device_id}.telemetry"},
                "source": {"type": "string", "const": f"/devices/{device_id}"},
                "data": {
                    "type": "object",
                    "properties": cloudevent_props,
                },
            },
            "required": ["specversion", "type", "source", "data"],
        }

        ros2_def = "# Auto-generated by ELMOS Industrial Protocol Mapper\n"
        ros2_def += "std_msgs/Header header\n"
        for rf in ros2_fields:
            ros2_def += f"{rf}\n"

        h = hashlib.sha256(f"{tags_spec}:{json.dumps(cloudevent_schema)}".encode("utf-8")).hexdigest()

        return IndustrialMappingResult(
            source_protocol="Modbus-TCP/RTU",
            target_protocol="OPC-UA / MQTT-CloudEvents / ROS2",
            mapped_tags=mapped_tags,
            cloudevents_schema=cloudevent_schema,
            opcua_nodes=opcua_nodes,
            ros2_msg_definition=ros2_def.strip(),
            merkle_receipt=f"sha256:{h}",
        )

    def _to_opcua_type(self, dtype: str) -> str:
        if "FLOAT" in dtype:
            return "Float" if "32" in dtype else "Double"
        if "INT32" in dtype:
            return "Int32"
        if "INT64" in dtype:
            return "Int64"
        if "UINT" in dtype:
            return "UInt16" if "16" in dtype else "UInt32"
        return "Int16"

    def _to_ros2_type(self, dtype: str) -> str:
        if "FLOAT" in dtype:
            return "float32" if "32" in dtype else "float64"
        if "INT32" in dtype:
            return "int32"
        if "INT64" in dtype:
            return "int64"
        if "UINT" in dtype:
            return "uint16" if "16" in dtype else "uint32"
        return "int16"

    def _snake_case(self, name: str) -> str:
        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()
