import { useEffect, useRef, useState } from "react";
import { Platform, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ELMOS_FRONTEND_INTERACTION, ELMOS_INTERACTION_SCENARIOS } from "./elmos-bounded-interaction";
import { elmosDeclarationJson, elmosNativeObserverDeclarations, type ElmosRuntimeScenario } from "./elmos-interaction-runtime";
interface NativeMeasurement { readonly stateBefore: number; readonly stateAfter: number; readonly saturated: boolean; readonly event: string; readonly action: string; readonly query: string; readonly valid: boolean; readonly apiOutcome: string; readonly nativeOutcome: string; readonly observedBlocks: readonly string[]; } interface RuntimeRow { readonly measurement: NativeMeasurement; readonly sequence: number; }
export interface ElmosNativeAdapter { readonly openDeepLink: (path: string) => Promise<boolean>; }
export function ElmosInteractionPanel({ nativeAdapter }: { readonly nativeAdapter?: ElmosNativeAdapter }) {
  const [query, setQuery] = useState(''); const [rows, setRows] = useState<Readonly<Record<string, RuntimeRow>>>({}); const [sequence, setSequence] = useState(0); const controller = useRef<AbortController | null>(null); const lifecycle = useRef<readonly string[]>(['MOUNT']);
  async function dispatch(scenario: ElmosRuntimeScenario) { const value = query === '' ? scenario.input.query : query; setQuery(value); const rawCounter = Math.max(scenario.input.counterBefore, ELMOS_FRONTEND_INTERACTION.stateManagement.initial) + scenario.input.incrementCount; const stateAfter = Math.max(ELMOS_FRONTEND_INTERACTION.stateManagement.minimum, Math.min(ELMOS_FRONTEND_INTERACTION.stateManagement.maximum, rawCounter)); const submitted = scenario.input.event === 'SUBMIT' || scenario.input.keyboardKey === ELMOS_FRONTEND_INTERACTION.actionEvent.keyboardSubmit; const valid = value.length >= ELMOS_FRONTEND_INTERACTION.formBindingValidation.minimumLength; const apiCalled = submitted && valid; let apiOutcome = 'NOT_CALLED'; if (apiCalled) { controller.current = new AbortController(); try { const response = await fetch(ELMOS_FRONTEND_INTERACTION.apiNetwork.path, { method: ELMOS_FRONTEND_INTERACTION.apiNetwork.method, body: JSON.stringify({ query: value }), signal: controller.current.signal }); apiOutcome = response.ok ? 'SUCCESS' : 'ERROR'; } catch { apiOutcome = 'ERROR'; } finally { controller.current = null; } } let nativeOutcome = 'NOT_RUN'; let nativeObserved = false; if (Platform.OS !== 'web' && scenario.input.event === 'NATIVE_DEEPLINK' && scenario.input.deepLinkPath && nativeAdapter) { nativeObserved = true; nativeOutcome = await nativeAdapter.openDeepLink(scenario.input.deepLinkPath) ? 'OPENED' : 'DENIED_RECOVERABLE'; } const observedBlocks = ['state-management', 'action-event', 'form-binding-validation', 'accessibility-focus', ...(nativeObserved ? ['native-platform'] : [])]; const action = submitted ? valid ? 'SUBMIT_ACCEPTED' : ELMOS_FRONTEND_INTERACTION.actionEvent.deniedAction : scenario.input.event; const measurement: NativeMeasurement = { stateBefore: scenario.input.counterBefore, stateAfter, saturated: rawCounter > ELMOS_FRONTEND_INTERACTION.stateManagement.maximum, event: scenario.input.event, action, query: value, valid, apiOutcome, nativeOutcome, observedBlocks }; const next = sequence + 1; setSequence(next); setRows(previous => ({ ...previous, [scenario.scenarioId]: { measurement, sequence: next } })); }
  useEffect(() => () => { controller.current?.abort(); lifecycle.current = [...lifecycle.current, 'UNMOUNT']; }, []);
  return <ScrollView nativeID="elmos-interaction" testID="elmos-interaction" accessibilityLabel={`ELMOS:bounded-frontend-interaction-v1:protocol:block-specific-runtime-observation-v1:scope:REACT_NATIVE_COMPONENT_ACTUAL_EVENTS:runtime:BLOCK_SPECIFIC_RUNTIME_OBSERVED:state:${sequence > 0 ? "PARTIAL" : "IDLE"}:sequence:${sequence}`}>
    <TextInput testID="elmos-query" accessibilityLabel={ELMOS_FRONTEND_INTERACTION.accessibilityFocus.formLabel} value={query} onChangeText={setQuery} />
    {ELMOS_INTERACTION_SCENARIOS.map(scenario => { const row = rows[scenario.scenarioId]; const value = row?.measurement; const declarations = value ? elmosNativeObserverDeclarations(value.observedBlocks) : []; return <View key={scenario.scenarioId} testID={`scenario:${scenario.scenarioId}`} accessible accessibilityLabel={`scenario:${scenario.scenarioId}:runtime:${row ? 'BLOCK_SPECIFIC_RUNTIME_OBSERVED' : 'NOT_RUN'}:state:${row ? 'PARTIAL' : 'IDLE'}:sequence:${row?.sequence ?? 0}`}><Pressable testID={`action:${scenario.scenarioId}`} accessibilityLabel={`action:${scenario.scenarioId}:event:${scenario.input.event}`} accessibilityRole="button" onPress={() => { void dispatch(scenario); }}><Text>{scenario.scenarioId}</Text></Pressable>{value && <View testID={`measurements:${scenario.scenarioId}`} accessibilityLabel={`state:${value.stateBefore}:${value.stateAfter}:${value.saturated};action:${value.event}:${value.action};form:${value.query}:${value.valid};api:${value.apiOutcome};native:${value.nativeOutcome}`}>{declarations.map(declaration => <Text key={declaration.block_id} testID={`block:${scenario.scenarioId}:${declaration.block_id}`} accessibilityLabel={`declaration:${declaration.block_id}:${declaration.observer_kind}:${declaration.status}:${declaration.measurement_surface}:model-values-used:false`}>{elmosDeclarationJson(declaration)}</Text>)}</View>}</View>; })}
  </ScrollView>;
}
