CREATE TABLE accounts (
    account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL,
    account_code text COLLATE "C" NOT NULL,
    currency character(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    balance numeric(19,4) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    UNIQUE (tenant_id, account_code)
);

CREATE TABLE ledger_entries (
    entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES accounts(account_id),
    amount numeric(19,4) NOT NULL CHECK (amount <> 0),
    idempotency_key uuid NOT NULL UNIQUE,
    description text NOT NULL,
    occurred_at timestamp with time zone NOT NULL
);

CREATE FUNCTION apply_ledger_balance() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE accounts
       SET balance = balance + NEW.amount
     WHERE account_id = NEW.account_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'account % does not exist', NEW.account_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER ledger_balance_after_insert
AFTER INSERT ON ledger_entries
FOR EACH ROW EXECUTE FUNCTION apply_ledger_balance();
