-- ELMOS Product B35: exact evidence projection generated from the commercial specification.
-- This migration records readiness and evidence only; external operations remain NOT_RUN.

DO $$
DECLARE
    target record;
BEGIN
    FOR target IN SELECT * FROM (VALUES
        ('scm', 'github_providers'),
        ('scm', 'github_provider_versions'),
        ('scm', 'github_provider_endpoints'),
        ('scm', 'github_provider_api_versions'),
        ('scm', 'github_provider_capability_snapshots'),
        ('scm', 'github_provider_compatibility_results'),
        ('scm', 'github_provider_readiness'),
        ('scm', 'github_provider_events'),
        ('scm', 'github_apps'),
        ('scm', 'github_app_versions'),
        ('scm', 'github_app_key_references'),
        ('scm', 'github_app_key_rotations'),
        ('scm', 'github_app_permission_profiles'),
        ('scm', 'github_installations'),
        ('scm', 'github_installation_versions'),
        ('scm', 'github_installation_accounts'),
        ('scm', 'github_installation_permissions'),
        ('scm', 'github_installation_events'),
        ('scm', 'github_installation_tombstones'),
        ('scm', 'github_installation_binding_decisions'),
        ('scm', 'github_webhook_deliveries'),
        ('scm', 'github_webhook_payloads'),
        ('scm', 'github_webhook_normalized_events'),
        ('scm', 'github_webhook_processing_attempts'),
        ('scm', 'github_webhook_dead_letters'),
        ('scm', 'github_webhook_redelivery_requests'),
        ('scm', 'github_webhook_schema_versions'),
        ('catalog', 'github_repository_metadata'),
        ('catalog', 'github_repository_permissions'),
        ('catalog', 'github_repository_installations'),
        ('catalog', 'repository_sync_runs'),
        ('catalog', 'repository_sync_pages'),
        ('catalog', 'repository_reconciliation_findings'),
        ('catalog', 'repository_tombstones'),
        ('catalog', 'repository_aliases'),
        ('catalog', 'repository_relationships'),
        ('catalog', 'repository_refs'),
        ('catalog', 'repository_ref_versions'),
        ('catalog', 'repository_branches'),
        ('catalog', 'repository_branch_versions'),
        ('catalog', 'repository_tags'),
        ('catalog', 'repository_tag_versions'),
        ('catalog', 'repository_default_branch_history'),
        ('catalog', 'repository_branch_protections'),
        ('catalog', 'repository_rulesets'),
        ('catalog', 'repository_ruleset_versions'),
        ('catalog', 'repository_effective_branch_rules'),
        ('catalog', 'repository_branch_selection_policies'),
        ('catalog', 'repository_branch_classifications'),
        ('catalog', 'repository_ref_events'),
        ('catalog', 'repository_ref_reconciliation_runs'),
        ('scm', 'github_token_purpose_profiles'),
        ('scm', 'github_token_lease_requests'),
        ('scm', 'github_token_leases'),
        ('scm', 'github_token_scope_decisions'),
        ('scm', 'github_token_cache_entries'),
        ('scm', 'github_token_revocations'),
        ('scm', 'github_git_operations'),
        ('scm', 'github_git_operation_receipts'),
        ('scm', 'github_git_reconciliations'),
        ('scm', 'github_token_security_events'),
        ('scm', 'github_network_profiles'),
        ('scm', 'github_proxy_profiles'),
        ('scm', 'github_ca_trust_profiles'),
        ('scm', 'github_provider_health_checks'),
        ('scm', 'github_rate_limit_snapshots'),
        ('scm', 'github_rate_limit_budgets'),
        ('scm', 'github_rate_limit_events'),
        ('scm', 'github_provider_circuit_breakers'),
        ('scm', 'github_provider_maintenance_events'),
        ('scm', 'github_connectivity_incidents'),
        ('scm', 'github_compatibility_profiles'),
        ('scm', 'github_compatibility_runs'),
        ('scm', 'github_compatibility_capabilities'),
        ('scm', 'github_contract_fixtures'),
        ('scm', 'github_release_gate_results'),
        ('scm', 'scm_providers'),
        ('scm', 'scm_provider_versions'),
        ('scm', 'scm_provider_endpoints'),
        ('scm', 'scm_provider_capabilities'),
        ('scm', 'scm_provider_compatibility_results'),
        ('scm', 'scm_authorization_connections'),
        ('scm', 'scm_authorization_versions'),
        ('scm', 'scm_credential_policies'),
        ('scm', 'scm_credential_leases'),
        ('scm', 'scm_credential_revocations'),
        ('catalog', 'scm_namespaces'),
        ('catalog', 'scm_namespace_versions'),
        ('catalog', 'scm_repositories'),
        ('catalog', 'scm_repository_versions'),
        ('catalog', 'scm_repository_aliases'),
        ('catalog', 'scm_repository_permissions'),
        ('catalog', 'scm_repository_tombstones'),
        ('catalog', 'scm_refs'),
        ('catalog', 'scm_ref_versions'),
        ('catalog', 'scm_branch_policies'),
        ('catalog', 'scm_branch_policy_versions'),
        ('scm', 'scm_webhook_subscriptions'),
        ('scm', 'scm_webhook_delivery_receipts'),
        ('scm', 'scm_webhook_payloads'),
        ('scm', 'scm_normalized_events'),
        ('scm', 'scm_webhook_dead_letters'),
        ('scm', 'scm_webhook_reconciliation_runs'),
        ('delivery', 'scm_review_requests'),
        ('delivery', 'scm_review_request_versions'),
        ('delivery', 'scm_review_request_reconciliations'),
        ('delivery', 'scm_commit_statuses'),
        ('delivery', 'scm_status_publication_runs'),
        ('execution', 'scm_git_operations'),
        ('execution', 'scm_git_operation_receipts'),
        ('execution', 'scm_git_reconciliations'),
        ('scm', 'gitlab_connections'),
        ('scm', 'gitlab_namespaces'),
        ('scm', 'gitlab_project_metadata'),
        ('scm', 'gitlab_webhook_profiles'),
        ('scm', 'azure_devops_connections'),
        ('scm', 'azure_devops_organizations'),
        ('scm', 'azure_devops_projects'),
        ('scm', 'azure_devops_repository_metadata'),
        ('scm', 'azure_devops_service_hook_subscriptions'),
        ('scm', 'bitbucket_cloud_connections'),
        ('scm', 'bitbucket_cloud_workspaces'),
        ('scm', 'bitbucket_cloud_projects'),
        ('scm', 'bitbucket_cloud_repository_metadata'),
        ('scm', 'bitbucket_cloud_webhooks'),
        ('scm', 'bitbucket_dc_connections'),
        ('scm', 'bitbucket_dc_projects'),
        ('scm', 'bitbucket_dc_repository_metadata'),
        ('scm', 'bitbucket_dc_webhooks'),
        ('scm', 'gitee_connections'),
        ('scm', 'gitee_namespaces'),
        ('scm', 'gitee_repository_metadata'),
        ('scm', 'gitee_webhooks'),
        ('scm', 'scm_contract_fixtures'),
        ('scm', 'scm_compatibility_profiles'),
        ('scm', 'scm_compatibility_runs'),
        ('scm', 'scm_release_gate_results'),
        ('workspace', 'repository_workspaces'),
        ('workspace', 'repository_workspace_versions'),
        ('workspace', 'workspace_sources'),
        ('workspace', 'workspace_source_versions'),
        ('workspace', 'workspace_materialization_profiles'),
        ('workspace', 'workspace_materialization_runs'),
        ('workspace', 'workspace_paths'),
        ('workspace', 'workspace_objects'),
        ('workspace', 'workspace_missing_objects'),
        ('workspace', 'workspace_leases'),
        ('workspace', 'workspace_locks'),
        ('workspace', 'workspace_integrity_results'),
        ('workspace', 'workspace_cleanup_runs'),
        ('workspace', 'workspace_manifests'),
        ('workspace', 'workspace_manifest_artifacts'),
        ('workspace', 'workspace_events'),
        ('workspace', 'monorepo_profiles'),
        ('workspace', 'monorepo_detection_runs'),
        ('workspace', 'monorepo_build_roots'),
        ('workspace', 'monorepo_components'),
        ('workspace', 'monorepo_component_versions'),
        ('workspace', 'monorepo_component_paths'),
        ('workspace', 'monorepo_component_dependencies'),
        ('workspace', 'monorepo_component_reverse_dependencies'),
        ('workspace', 'monorepo_shared_files'),
        ('workspace', 'monorepo_generated_source_inputs'),
        ('workspace', 'monorepo_ownership_rules'),
        ('workspace', 'monorepo_slice_profiles'),
        ('workspace', 'monorepo_slice_plans'),
        ('workspace', 'monorepo_slice_paths'),
        ('workspace', 'monorepo_slice_findings'),
        ('workspace', 'monorepo_slice_verifications'),
        ('workspace', 'products'),
        ('workspace', 'product_versions'),
        ('workspace', 'product_repository_sets'),
        ('workspace', 'product_repository_set_versions'),
        ('workspace', 'product_repository_members'),
        ('workspace', 'product_repository_roles'),
        ('workspace', 'product_repository_dependencies'),
        ('workspace', 'product_commit_selection_rules'),
        ('workspace', 'product_snapshot_plans'),
        ('workspace', 'product_snapshots'),
        ('workspace', 'product_snapshot_members'),
        ('workspace', 'product_lock_manifests'),
        ('workspace', 'product_consistency_rules'),
        ('workspace', 'product_consistency_results'),
        ('workspace', 'product_change_sets'),
        ('workspace', 'product_change_set_members'),
        ('workspace', 'product_delivery_dependencies'),
        ('workspace', 'product_evidence_packs'),
        ('workspace', 'submodule_discovery_runs'),
        ('workspace', 'submodule_declarations'),
        ('workspace', 'submodule_declaration_versions'),
        ('workspace', 'submodule_url_resolutions'),
        ('workspace', 'submodule_repository_bindings'),
        ('workspace', 'submodule_authorization_decisions'),
        ('workspace', 'submodule_edges'),
        ('workspace', 'submodule_cycles'),
        ('workspace', 'submodule_fetch_plans'),
        ('workspace', 'submodule_snapshots'),
        ('workspace', 'submodule_snapshot_members'),
        ('workspace', 'submodule_integrity_results'),
        ('workspace', 'submodule_findings'),
        ('workspace', 'lfs_profiles'),
        ('workspace', 'lfs_detection_runs'),
        ('workspace', 'lfs_attribute_rules'),
        ('workspace', 'lfs_pointer_records'),
        ('workspace', 'lfs_endpoint_resolutions'),
        ('workspace', 'lfs_object_plans'),
        ('workspace', 'lfs_object_transfers'),
        ('workspace', 'lfs_object_integrity_results'),
        ('workspace', 'lfs_hydration_runs'),
        ('workspace', 'lfs_lock_snapshots'),
        ('workspace', 'lfs_locks'),
        ('workspace', 'lfs_lock_verifications'),
        ('workspace', 'lfs_bandwidth_budgets'),
        ('workspace', 'lfs_storage_budgets'),
        ('workspace', 'lfs_findings'),
        ('workspace', 'lfs_history_rewrite_plans'),
        ('workspace', 'sparse_profiles'),
        ('workspace', 'sparse_profile_versions'),
        ('workspace', 'sparse_specifications'),
        ('workspace', 'sparse_paths'),
        ('workspace', 'sparse_materialization_runs'),
        ('workspace', 'sparse_drift_findings'),
        ('workspace', 'partial_clone_profiles'),
        ('workspace', 'partial_clone_capability_results'),
        ('workspace', 'promisor_remotes'),
        ('workspace', 'promised_objects'),
        ('workspace', 'object_hydration_plans'),
        ('workspace', 'object_hydration_runs'),
        ('workspace', 'object_hydration_events'),
        ('workspace', 'offline_preparation_runs'),
        ('workspace', 'git_tool_compatibility_profiles'),
        ('workspace', 'sparse_partial_findings'),
        ('workspace', 'branch_families'),
        ('workspace', 'branch_family_versions'),
        ('workspace', 'release_lines'),
        ('workspace', 'release_line_versions'),
        ('workspace', 'branch_memberships'),
        ('workspace', 'branch_selection_runs'),
        ('workspace', 'branch_baselines'),
        ('workspace', 'branch_divergence_results'),
        ('workspace', 'branch_migration_plans'),
        ('workspace', 'branch_worktrees'),
        ('workspace', 'branch_worktree_leases'),
        ('workspace', 'branch_worktree_locks'),
        ('workspace', 'branch_patch_sets'),
        ('workspace', 'cross_branch_consistency_rules'),
        ('workspace', 'branch_delivery_sets'),
        ('workspace', 'worktree_reconciliation_runs'),
        ('workspace', 'git_transport_profiles'),
        ('workspace', 'git_proxy_profiles'),
        ('workspace', 'git_ca_profiles'),
        ('workspace', 'git_mirror_profiles'),
        ('workspace', 'git_mirrors'),
        ('workspace', 'git_mirror_sync_runs'),
        ('workspace', 'git_object_cache_profiles'),
        ('workspace', 'git_object_caches'),
        ('workspace', 'git_cache_namespaces'),
        ('workspace', 'git_cache_write_leases'),
        ('workspace', 'git_cache_objects'),
        ('workspace', 'git_cache_packfiles'),
        ('workspace', 'git_cache_verification_runs'),
        ('workspace', 'git_cache_promotion_runs'),
        ('workspace', 'git_cache_eviction_runs'),
        ('workspace', 'git_offline_packages'),
        ('workspace', 'git_offline_package_members'),
        ('workspace', 'git_offline_import_runs'),
        ('workspace', 'git_cache_findings'),
        ('workspace', 'quota_profiles'),
        ('workspace', 'quota_assignments'),
        ('workspace', 'resource_reservations'),
        ('workspace', 'resource_usage_observations'),
        ('workspace', 'quota_violations'),
        ('workspace', 'workspace_reaper_runs'),
        ('workspace', 'orphan_workspace_findings'),
        ('workspace', 'cleanup_tasks'),
        ('workspace', 'cleanup_attempts'),
        ('workspace', 'recovery_runs'),
        ('workspace', 'security_test_runs'),
        ('workspace', 'release_gate_results')
    ) AS listed(schema_name, table_name)
    LOOP
        EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target.schema_name);
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I.%I (' ||
            'record_id varchar(96) PRIMARY KEY,' ||
            'organization_id varchar(96) NOT NULL REFERENCES public.organizations(organization_id),' ||
            'domain_run_id varchar(160) NOT NULL,' ||
            'subject_digest varchar(64) NOT NULL CHECK (subject_digest ~ ''^[0-9a-f]{64}$''),' ||
            'context_snapshot_digest varchar(64) NOT NULL CHECK (context_snapshot_digest ~ ''^[0-9a-f]{64}$''),' ||
            'policy_version varchar(96) NOT NULL,' ||
            'status varchar(64) NOT NULL DEFAULT ''NOT_RUN'' CHECK (status IN (''OBSERVED'',''VERIFIED'',''FAILED'',''NOT_RUN'',''INCONCLUSIVE'',''UNKNOWN'',''BLOCKED'',''READY_FOR_EXTERNAL_GATE'',''READY_FOR_HUMAN_DECISION'')),' ||
            'independent_verifier_id varchar(160),' ||
            'critical_open_risks integer NOT NULL DEFAULT 0 CHECK (critical_open_risks >= 0),' ||
            'evidence_refs jsonb NOT NULL DEFAULT ''[]''::jsonb CHECK (jsonb_typeof(evidence_refs) = ''array''),' ||
            'payload jsonb NOT NULL DEFAULT ''{}''::jsonb CHECK (jsonb_typeof(payload) = ''object''),' ||
            'external_operation_executed boolean NOT NULL DEFAULT false CHECK (external_operation_executed = false),' ||
            'human_approval_ref varchar(512),' ||
            'idempotency_key varchar(160) NOT NULL,' ||
            'observed_at timestamptz NOT NULL,' ||
            'created_at timestamptz NOT NULL DEFAULT now(),' ||
            'CHECK (status <> ''READY_FOR_HUMAN_DECISION'' OR (independent_verifier_id IS NOT NULL AND critical_open_risks = 0 AND jsonb_array_length(evidence_refs) > 0)),' ||
            'CHECK (human_approval_ref IS NULL OR jsonb_array_length(evidence_refs) > 0),' ||
            'UNIQUE (organization_id, idempotency_key))',
            target.schema_name, target.table_name);
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS %I ON %I.%I (organization_id, domain_run_id, status)',
            'idx_' || left(target.table_name, 32) || '_' || substr(md5(target.schema_name || target.table_name), 1, 8),
            target.schema_name, target.table_name);
        EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', target.schema_name, target.table_name);
        EXECUTE format('ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY', target.schema_name, target.table_name);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE schemaname = target.schema_name AND tablename = target.table_name AND policyname = 'product_b35_tenant_isolation'
        ) THEN
            EXECUTE format(
                'CREATE POLICY product_b35_tenant_isolation ON %I.%I USING (organization_id = current_setting(''app.organization_id'', true)) WITH CHECK (organization_id = current_setting(''app.organization_id'', true))',
                target.schema_name, target.table_name);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM pg_trigger trigger
            JOIN pg_class relation ON relation.oid = trigger.tgrelid
            JOIN pg_namespace namespace ON namespace.oid = relation.relnamespace
            WHERE namespace.nspname = target.schema_name AND relation.relname = target.table_name
              AND trigger.tgname = 'product_b35_append_only' AND NOT trigger.tgisinternal
        ) THEN
            EXECUTE format(
                'CREATE TRIGGER product_b35_append_only BEFORE UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION public.elmos_forbid_append_only_mutation()',
                target.schema_name, target.table_name);
        END IF;
    END LOOP;
END;
$$;
