// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {},
  data: {
    workspaces: [{ eyebrow: "BATCH 30 · SPRING", title: "Spring 老项目翻新", description: "识别经典 Spring、XML 与旧 Boot，显式处理 Java、Jakarta、Security、JPA、配置和真实启动证据。", href: "/spring", icon: "workflow", accent: "blue", meta: "3 种源形态 · 1 个精确实验 Pack" }, { eyebrow: "BATCH 29 · DIRECTED ROUTES", title: "全库跨语言转换", description: "在 Java、C#、Python、TypeScript 的 12 条方向路线中选择精确路径，查看语义风险、阻断项和交接命令。", href: "/translation", icon: "code", accent: "cyan", meta: "4 种语言 · 12 个本地实验 Profile" }, { eyebrow: "PROJECT SYNTHESIS · B46–B80", title: "多语言项目生成", description: "用同一份受审项目意图规划多目标工程、资产图和构建图，区分内置生成器与专用 Runtime Skill 路由。", href: "/generation", icon: "spark", accent: "violet", meta: "草稿 → 批准 → 生成 → 验证" }, { eyebrow: "BATCH 31 · CHINADB SQL", title: "国产数据库 SQL 转换", description: "在 13 个国产数据库目标和 78 条规划路线中做 typed SQL 预评估；缺少精确版本、能力快照或目标适配器时明确阻断。", href: "/migration", icon: "database", accent: "amber", meta: "47 Skills · SPEC_ONLY · 外部证据 NOT_RUN" }, { eyebrow: "GOVERNANCE · M29–M37", title: "迁移能力与验证", description: "检查迁移能力包、开发者工作流、外部控制面和严格门禁；结构就绪不自动升级为运行或认证结论。", href: "/migration", icon: "shield", accent: "green", meta: "Fail closed · External evidence NOT_RUN" }],
    attention: [{ item0: "12 条路线独立验证", item1: "本地三类语料已通过，客户仓库与独立验证仍未运行", item2: "NOT_RUN" }, { item0: "Spring 外部 Runner 证据", item1: "实验 Pack 已闭环，真实客户仓库、holdout 与独立执行未运行", item2: "NOT_RUN" }, { item0: "多语言生成外部工具链", item1: "浏览器只准备受控交接，不执行生成", item2: "NOT_RUN" }],
  },
  methods: {},
});
