import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'elmos_bounded_interaction.dart';
import 'elmos_interaction_runtime.dart';
typedef ElmosApiAdapter = Future<String> Function(String path, String method, String query, bool cancel);
typedef ElmosNativeAdapter = Future<bool> Function(String path);
class ElmosInteractionPanel extends StatefulWidget { const ElmosInteractionPanel({this.apiAdapter, this.nativeAdapter, super.key}); final ElmosApiAdapter? apiAdapter; final ElmosNativeAdapter? nativeAdapter; @override State<ElmosInteractionPanel> createState() => _ElmosInteractionPanelState(); }
class _ElmosInteractionPanelState extends State<ElmosInteractionPanel> {
  final TextEditingController query = TextEditingController(); final FocusNode queryFocus = FocusNode(); final FocusNode resultFocus = FocusNode(); final Map<String, Map<String, Object?>> measurements = <String, Map<String, Object?>>{}; final Map<String, int> sequences = <String, int>{}; int sequence = 0; String get runtimeChannel { if (kIsWeb) return 'browser'; return switch (defaultTargetPlatform) { TargetPlatform.android => 'android', TargetPlatform.iOS => 'ios', _ => 'browser' }; }
  Future<void> dispatch(Object? raw) async { final scenario = elmosMap(raw); final input = elmosMap(scenario['input']); final value = query.text.isEmpty ? input['query']! as String : query.text; query.text = value; final model = elmosFrontendInteraction; final state = elmosMap(model['stateManagement']); final rawCounter = (input['counterBefore']! as num).clamp(state['initial']! as num, double.infinity) + (input['incrementCount']! as num); final stateAfter = rawCounter.clamp(state['minimum']! as num, state['maximum']! as num); final form = elmosMap(model['formBindingValidation']); final actionContract = elmosMap(model['actionEvent']); final submitted = input['event'] == 'SUBMIT' || input['keyboardKey'] == actionContract['keyboardSubmit']; final valid = value.length >= (form['minimumLength']! as num); final api = elmosMap(model['apiNetwork']); final canceled = input['event'] == 'CANCEL' || input['lifecycle'] == 'UNMOUNT'; var apiOutcome = 'NOT_CALLED'; if ((submitted && valid || canceled) && widget.apiAdapter != null) { apiOutcome = await widget.apiAdapter!.call(api['path']! as String, api['method']! as String, value, canceled); } var nativeOutcome = 'NOT_RUN'; var nativeObserved = false; if (runtimeChannel != 'browser' && input['event'] == 'NATIVE_DEEPLINK' && input['deepLinkPath'] is String && widget.nativeAdapter != null) { nativeObserved = true; nativeOutcome = await widget.nativeAdapter!.call(input['deepLinkPath']! as String) ? 'OPENED' : 'DENIED_RECOVERABLE'; } final observed = <String>{'state-management', 'action-event', 'form-binding-validation', 'accessibility-focus', if (nativeObserved) 'native-platform'}; final action = submitted ? valid ? 'SUBMIT_ACCEPTED' : actionContract['deniedAction']! as String : input['event']! as String; final measurement = <String, Object?>{'state_before': input['counterBefore'], 'state_after': stateAfter, 'saturated': rawCounter > (state['maximum']! as num), 'event': input['event'], 'action': action, 'query': value, 'valid': valid, 'api_outcome': apiOutcome, 'native_outcome': nativeOutcome, 'observed_blocks': observed}; if (!mounted) return; final id = scenario['scenarioId']! as String; setState(() { sequence += 1; measurements[id] = measurement; sequences[id] = sequence; }); if (submitted && !valid) { queryFocus.requestFocus(); } else if (submitted) { resultFocus.requestFocus(); } }
  @override void dispose() { query.dispose(); queryFocus.dispose(); resultFocus.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) => Semantics(label: 'ELMOS:bounded-frontend-interaction-v1:block-specific-runtime-observation-v1:${sequence > 0 ? 'PARTIAL' : 'IDLE'}', child: Column(children: [TextField(key: const ValueKey<String>('elmos-query'), controller: query, focusNode: queryFocus, decoration: InputDecoration(labelText: elmosMap(elmosFrontendInteraction['accessibilityFocus'])['formLabel']! as String)), Expanded(child: SingleChildScrollView(key: const ValueKey<String>('elmos-interaction'), child: Column(children: [for (final scenario in elmosInteractionScenarios) Builder(builder: (context) { final id = elmosMap(scenario)['scenarioId']! as String; final measurement = measurements[id]; final observed = measurement == null ? <String>{} : Set<String>.from(measurement['observed_blocks']! as Set<String>); final declarations = measurement == null ? const <Map<String, Object>>[] : elmosNativeObserverDeclarations(observed); return Semantics(container: true, label: 'scenario:$id:${measurement == null ? 'IDLE' : 'PARTIAL'}:sequence:${sequences[id] ?? 0}:runtime:BLOCK_SPECIFIC_RUNTIME_OBSERVED:${measurement == null ? '' : jsonEncode(<String, Object?>{'state_before': measurement['state_before'], 'state_after': measurement['state_after'], 'saturated': measurement['saturated'], 'event': measurement['event'], 'action': measurement['action'], 'query': measurement['query'], 'valid': measurement['valid'], 'api_outcome': measurement['api_outcome'], 'native_outcome': measurement['native_outcome']})}', child: Column(key: ValueKey<String>('scenario:$id'), children: [FilledButton(key: ValueKey<String>('action:$id'), onPressed: () async { await dispatch(scenario); }, child: Text(id)), for (final declaration in declarations) Text(jsonEncode(declaration), key: ValueKey<String>('block:$id:${declaration['block_id']}'), semanticsLabel: 'declaration:${declaration['block_id']}:${declaration['observer_kind']}:${declaration['status']}:${declaration['measurement_surface']}:model-values-used:false')])); })]))), Focus(focusNode: resultFocus, child: const Text('', key: ValueKey<String>('elmos-result')))]));
}
