#!/usr/bin/env bash
set -euo pipefail
INPUT="${1:?usage: uninstall.sh /path/to/elmos-or-v3-package-root}"
resolve_base() {
  if [[ -f "$INPUT/PACKAGE_MANIFEST.yaml" ]]; then printf '%s\n' "$INPUT"; return; fi
  if [[ -f "$INPUT/packages/elmos-v3/PACKAGE_MANIFEST.yaml" ]]; then printf '%s\n' "$INPUT/packages/elmos-v3"; return; fi
  echo "Cannot locate Elmos v3 package" >&2; exit 2
}
BASE="$(resolve_base)"
python3 - "$BASE" <<'PY'
from __future__ import annotations
import hashlib, json, shutil, sys
from pathlib import Path

base=Path(sys.argv[1]).resolve(); package_id='elmos-v3-harness-runtime-assurance-delta-v3.1.0'
record_path=base/'applied-deltas'/package_id/'install-record.json'
if not record_path.exists(): raise SystemExit(f'{package_id} is not installed')
r=json.loads(record_path.read_text()); backup=base/r['backupRoot']; preserved=[]
for rel in sorted(r['installed'], reverse=True):
    p=base/rel
    if not p.exists(): continue
    current=hashlib.sha256(p.read_bytes()).hexdigest(); expected=r['installedHashes'][rel]
    if current == expected:
        p.unlink()
        parent=p.parent
        while parent != base and parent.exists() and not any(parent.iterdir()):
            parent.rmdir(); parent=parent.parent
    else:
        preserved.append(rel)
for rel in r['overwritten']:
    source=backup/'overwritten'/rel; target=base/rel
    target.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(source,target)
for rel in ['PACKAGE_MANIFEST.yaml','PACKAGE_MANIFEST.json','VERSION','FILES.sha256']:
    source=backup/'metadata'/rel; target=base/rel
    if source.exists(): shutil.copy2(source,target)
record_path.unlink()
for parent in [record_path.parent, record_path.parent.parent]:
    try: parent.rmdir()
    except OSError: pass
# Remove only this installation's backup and empty parents; never delete other Delta backups.
shutil.rmtree(backup, ignore_errors=True)
for parent in [backup.parent, backup.parent.parent]:
    try: parent.rmdir()
    except OSError: pass
# Remove generated bytecode for the uninstalled extension only.
for pycache in base.rglob('__pycache__'):
    if 'elmos_v3_delta' in str(pycache) or 'test_runtime_delta' in str(pycache):
        shutil.rmtree(pycache, ignore_errors=True)
if preserved:
    print('Preserved locally modified delta files:')
    for x in preserved: print('  '+x)
print(f'uninstalled {package_id}')
PY
