"""Skill 21 — an organisation-level refactor across many repositories.

A program is not a bigger run.  Its failure modes are different, and three of
them are handled structurally here:

* **A wave must not contain both sides of a break.**  :func:`build_waves`
  places providers and consumers in different waves according to what the
  change breaks, and :func:`check_wave_order` re-derives the ordering from
  the dependency edges and reports any pair that would break — a plan is not
  trusted merely because it was generated by the planner.
* **Pausing one repository must not lose the program.**  :meth:`Program.pause`
  moves a single repository to ``paused`` and leaves every other repository's
  state and the global gate ledger untouched; :meth:`Program.resume` puts it
  back exactly where it was, because a program that has to be restarted to
  unblock one team will be bypassed instead.
* **A consumer that never adopts is the normal outcome, not an exception.**
  :func:`stuck_consumers` names them with how long they have been outstanding
  so the cleanup wave is *blocked* rather than quietly proceeding while a
  fork, a mirror, or an unmaintained service still calls the old path.

Nothing here merges, releases, or notifies; the program tracks state and
adjudicates gates, and the per-repository work is dispatched as ordinary
runs.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from decimal import Decimal
from enum import StrEnum
from typing import Any

from .contracts import ContractError, RiskClass, Status, sha256_payload
from .plan import find_cycle_in_graph


class RepositoryRole(StrEnum):
    #: Owns the contract or the symbol being changed.
    PROVIDER = "provider"
    #: Compiles or calls against it.
    CONSUMER = "consumer"
    #: Generated from the provider; regenerated, never patched.
    GENERATED_CLIENT = "generated-client"
    #: A copy that has diverged, so it needs its own port.
    FORK = "fork"
    #: A read-only mirror; nothing lands here directly.
    MIRROR = "mirror"


class RepositoryState(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    AWAITING_REVIEW = "awaiting-review"
    MERGED = "merged"
    RELEASED = "released"
    ADOPTED = "adopted"
    PAUSED = "paused"
    FAILED = "failed"
    EXEMPTED = "exempted"


#: A repository is only *done* for cleanup purposes when its consumers have
#: adopted, not when its pull request merged.
TERMINAL_STATES = frozenset({RepositoryState.ADOPTED, RepositoryState.EXEMPTED})


@dataclass(frozen=True, slots=True)
class RepositoryEntry:
    repository_id: str
    role: RepositoryRole
    owners: tuple[str, ...]
    #: Repository ids this one depends on, within the portfolio.
    depends_on: tuple[str, ...] = ()
    release_cadence: str = "continuous"
    #: Days after a provider release before this repository can ship.
    compatibility_window_days: int = 0
    external: bool = False

    def to_payload(self) -> dict[str, Any]:
        return {
            "repositoryId": self.repository_id,
            "role": self.role.value,
            "owners": list(self.owners),
            "dependsOn": list(self.depends_on),
            "releaseCadence": self.release_cadence,
            "compatibilityWindowDays": self.compatibility_window_days,
            "external": self.external,
        }


@dataclass(frozen=True, slots=True)
class ProgramWave:
    wave_id: str
    order: int
    title: str
    repositories: tuple[str, ...]
    gate: str
    #: Waves that must be fully adopted before this one may start.
    requires: tuple[str, ...] = ()
    destructive: bool = False

    def to_payload(self) -> dict[str, Any]:
        return {
            "waveId": self.wave_id,
            "order": self.order,
            "title": self.title,
            "repositories": list(self.repositories),
            "gate": self.gate,
            "requires": list(self.requires),
            "destructive": self.destructive,
        }


@dataclass(frozen=True, slots=True)
class RepositoryRun:
    repository_id: str
    wave_id: str
    state: RepositoryState
    run_id: str = ""
    status: Status | None = None
    detail: str = ""
    days_outstanding: int = 0

    def to_payload(self) -> dict[str, Any]:
        return {
            "repositoryId": self.repository_id,
            "waveId": self.wave_id,
            "state": self.state.value,
            "runId": self.run_id,
            "status": "pending" if self.status is None else self.status.value,
            "detail": self.detail,
            "daysOutstanding": self.days_outstanding,
        }


@dataclass(frozen=True, slots=True)
class ProgramPlan:
    program_id: str
    portfolio: tuple[RepositoryEntry, ...]
    waves: tuple[ProgramWave, ...]
    ordering_violations: tuple[str, ...]
    risk_class: RiskClass
    reasons: tuple[str, ...] = ()
    blocked_reason: str = ""

    @property
    def executable(self) -> bool:
        return not self.blocked_reason and not self.ordering_violations

    def to_payload(self) -> dict[str, Any]:
        return {
            "programId": self.program_id,
            "portfolio": [item.to_payload() for item in self.portfolio],
            "waves": [item.to_payload() for item in self.waves],
            "orderingViolations": list(self.ordering_violations),
            "riskClass": self.risk_class.value,
            "reasons": list(self.reasons),
            "executable": self.executable,
            "blockedReason": self.blocked_reason,
        }

    @property
    def digest(self) -> str:
        return sha256_payload(self.to_payload())


def portfolio_from_payload(payload: Sequence[Mapping[str, Any]]) -> tuple[RepositoryEntry, ...]:
    entries: list[RepositoryEntry] = []
    seen: set[str] = set()
    for item in payload:
        repository_id = str(item.get("repositoryId", "")).strip()
        if not repository_id:
            raise ContractError("invalid_portfolio_entry", "every portfolio entry needs a repositoryId")
        if repository_id in seen:
            raise ContractError(
                "duplicate_repository", f"repository '{repository_id}' appears twice in the portfolio"
            )
        seen.add(repository_id)
        try:
            role = RepositoryRole(str(item.get("role", "consumer")))
        except ValueError as error:
            raise ContractError(
                "invalid_repository_role",
                f"unknown role '{item.get('role')}' for '{repository_id}'",
                {"supported": [value.value for value in RepositoryRole]},
            ) from error
        entries.append(
            RepositoryEntry(
                repository_id=repository_id,
                role=role,
                owners=tuple(str(owner) for owner in item.get("owners", ())),
                depends_on=tuple(str(dep) for dep in item.get("dependsOn", ())),
                release_cadence=str(item.get("releaseCadence", "continuous")),
                compatibility_window_days=int(item.get("compatibilityWindowDays", 0)),
                external=bool(item.get("external", False)),
            )
        )
    known = {entry.repository_id for entry in entries}
    for entry in entries:
        unknown = sorted(set(entry.depends_on) - known)
        if unknown:
            raise ContractError(
                "unknown_dependency",
                f"'{entry.repository_id}' depends on repositories outside the portfolio: "
                f"{', '.join(unknown)}; a dependency the program cannot schedule cannot be waved",
                {"missing": unknown},
            )
    return tuple(sorted(entries, key=lambda entry: entry.repository_id))


def build_waves(
    portfolio: Sequence[RepositoryEntry],
    *,
    consumer_first: bool,
    needs_cleanup: bool = True,
) -> tuple[ProgramWave, ...]:
    """Compatibility wave, then the breaking side, then the other, then cleanup."""

    providers = tuple(
        entry.repository_id for entry in portfolio if entry.role is RepositoryRole.PROVIDER
    )
    consumers = tuple(
        entry.repository_id
        for entry in portfolio
        if entry.role in (RepositoryRole.CONSUMER, RepositoryRole.GENERATED_CLIENT)
    )
    forks = tuple(entry.repository_id for entry in portfolio if entry.role is RepositoryRole.FORK)

    waves: list[ProgramWave] = [
        ProgramWave(
            wave_id="wave-0-compatibility",
            order=0,
            title="Publish the new surface alongside the old one",
            repositories=providers,
            gate="api-compatibility",
        )
    ]
    if consumer_first:
        waves.append(
            ProgramWave(
                wave_id="wave-1-consumers",
                order=1,
                title="Consumers accept both shapes",
                repositories=consumers + forks,
                gate="changed-target-tests",
                requires=("wave-0-compatibility",),
            )
        )
        waves.append(
            ProgramWave(
                wave_id="wave-2-providers",
                order=2,
                title="Providers emit the new shape",
                repositories=providers,
                gate="canary-guardrails",
                requires=("wave-1-consumers",),
            )
        )
    else:
        waves.append(
            ProgramWave(
                wave_id="wave-1-providers",
                order=1,
                title="Providers ship the new surface",
                repositories=providers,
                gate="full-tests",
                requires=("wave-0-compatibility",),
            )
        )
        waves.append(
            ProgramWave(
                wave_id="wave-2-consumers",
                order=2,
                title="Consumers migrate to the new surface",
                repositories=consumers + forks,
                gate="changed-target-tests",
                requires=("wave-1-providers",),
            )
        )
    if needs_cleanup:
        waves.append(
            ProgramWave(
                wave_id="wave-3-cleanup",
                order=3,
                title="Remove the compatibility layer",
                repositories=providers,
                gate="old-path-usage-zero",
                requires=(waves[-1].wave_id,),
                destructive=True,
            )
        )
    return tuple(waves)


def check_wave_order(
    portfolio: Sequence[RepositoryEntry],
    waves: Sequence[ProgramWave],
) -> tuple[str, ...]:
    """Re-derive the ordering constraints and report every pair the plan breaks."""

    placement: dict[str, int] = {}
    for wave in waves:
        for repository_id in wave.repositories:
            #: A repository may appear in several waves; the *earliest* is the
            #: one that constrains its dependencies.
            placement.setdefault(repository_id, wave.order)
            placement[repository_id] = min(placement[repository_id], wave.order)

    violations: list[str] = []
    edges: dict[str, tuple[str, ...]] = {}
    for entry in portfolio:
        edges[entry.repository_id] = entry.depends_on
        if entry.repository_id not in placement:
            violations.append(
                f"'{entry.repository_id}' appears in no wave; a repository the program does not "
                "schedule is not therefore unaffected"
            )
            continue
        for dependency in entry.depends_on:
            if dependency not in placement:
                continue
            if placement[dependency] > placement[entry.repository_id]:
                violations.append(
                    f"'{entry.repository_id}' (wave {placement[entry.repository_id]}) depends on "
                    f"'{dependency}' (wave {placement[dependency]}), which lands later"
                )
    cycle = find_cycle_in_graph(edges)
    if cycle:
        violations.append(
            "the portfolio dependency graph has a cycle: " + " -> ".join(cycle) + "; no wave order "
            "satisfies it, so the cycle must be broken with a compatibility shim first"
        )
    destructive = [wave for wave in waves if wave.destructive]
    for wave in destructive:
        earlier = [item for item in waves if item.order < wave.order]
        if not earlier:
            violations.append(f"destructive wave '{wave.wave_id}' has nothing before it")
        elif wave.gate != "old-path-usage-zero":
            violations.append(
                f"destructive wave '{wave.wave_id}' is gated on '{wave.gate}'; removal must be "
                "gated on proven zero usage of the old path"
            )
    return tuple(violations)


def plan_program(
    program_id: str,
    portfolio: Sequence[RepositoryEntry],
    *,
    consumer_first: bool,
    needs_cleanup: bool = True,
) -> ProgramPlan:
    """Build and then independently check the wave plan."""

    if not portfolio:
        raise ContractError("empty_portfolio", "a program needs at least one repository")
    waves = build_waves(portfolio, consumer_first=consumer_first, needs_cleanup=needs_cleanup)
    violations = check_wave_order(portfolio, waves)
    reasons: list[str] = []
    external = [entry for entry in portfolio if entry.external]
    if external:
        reasons.append(
            f"{len(external)} repository/repositories are outside this organisation's control; "
            "their adoption cannot be scheduled, only waited for"
        )
    mirrors = [entry for entry in portfolio if entry.role is RepositoryRole.MIRROR]
    if mirrors:
        reasons.append(
            f"{len(mirrors)} mirror(s) are in the portfolio; nothing lands in a mirror directly, "
            "so they are tracked for divergence rather than scheduled"
        )
    forks = [entry for entry in portfolio if entry.role is RepositoryRole.FORK]
    if forks:
        reasons.append(
            f"{len(forks)} fork(s) have diverged from their source; each needs its own port and "
            "cannot be covered by the provider's patch"
        )
    windows = [entry for entry in portfolio if entry.compatibility_window_days > 0]
    if windows:
        longest = max(entry.compatibility_window_days for entry in windows)
        reasons.append(
            f"the longest compatibility window is {longest} day(s); the cleanup wave cannot start "
            "before it elapses, whatever the merge status says"
        )
    risk = RiskClass.R4 if (external or forks or violations) else RiskClass.R3
    return ProgramPlan(
        program_id=program_id,
        portfolio=tuple(portfolio),
        waves=waves,
        ordering_violations=violations,
        risk_class=risk,
        reasons=tuple(reasons),
    )


# ---------------------------------------------------------------------------
# Execution state
# ---------------------------------------------------------------------------


@dataclass
class Program:
    """Mutable program state: per-repository runs plus a global gate ledger."""

    plan: ProgramPlan
    #: Keyed by (wave_id, repository_id): a provider that appears in the
    #: compatibility wave *and* the cutover wave has two independent states,
    #: and treating them as one is how a program declares a cutover finished
    #: because the compatibility layer shipped.
    runs: dict[tuple[str, str], RepositoryRun] = field(default_factory=dict)
    paused_from: dict[tuple[str, str], RepositoryState] = field(default_factory=dict)
    gates: dict[str, bool] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.runs:
            for wave in self.plan.waves:
                for repository_id in wave.repositories:
                    self.runs[wave.wave_id, repository_id] = RepositoryRun(
                        repository_id=repository_id,
                        wave_id=wave.wave_id,
                        state=RepositoryState.PENDING,
                    )

    def _resolve(self, repository_id: str, wave_id: str) -> tuple[str, str]:
        if wave_id:
            key = (wave_id, repository_id)
            if key not in self.runs:
                raise ContractError(
                    "repository_not_in_wave",
                    f"'{repository_id}' is not scheduled in wave '{wave_id}'",
                )
            return key
        keys = [item for item in self.runs if item[1] == repository_id]
        if not keys:
            raise ContractError(
                "repository_not_in_program",
                f"'{repository_id}' is not scheduled by program '{self.plan.program_id}'",
            )
        if len(keys) > 1:
            raise ContractError(
                "ambiguous_repository_wave",
                f"'{repository_id}' appears in {len(keys)} waves; name the wave explicitly",
                {"waves": sorted(item[0] for item in keys)},
            )
        return keys[0]

    def require(self, repository_id: str, wave_id: str = "") -> RepositoryRun:
        return self.runs[self._resolve(repository_id, wave_id)]

    def advance(
        self,
        repository_id: str,
        state: RepositoryState,
        *,
        wave_id: str = "",
        run_id: str = "",
        status: Status | None = None,
        detail: str = "",
        days_outstanding: int | None = None,
    ) -> RepositoryRun:
        key = self._resolve(repository_id, wave_id)
        current = self.runs[key]
        if current.state is RepositoryState.PAUSED and state is not RepositoryState.PAUSED:
            raise ContractError(
                "repository_paused",
                f"'{repository_id}' is paused; resume it before advancing it",
            )
        updated = RepositoryRun(
            repository_id=repository_id,
            wave_id=current.wave_id,
            state=state,
            run_id=run_id or current.run_id,
            status=status or current.status,
            detail=detail or current.detail,
            days_outstanding=current.days_outstanding if days_outstanding is None else days_outstanding,
        )
        self.runs[key] = updated
        return updated

    def pause(self, repository_id: str, *, reason: str, wave_id: str = "") -> RepositoryRun:
        """Pause one repository in one wave, remembering exactly where it was."""

        key = self._resolve(repository_id, wave_id)
        current = self.runs[key]
        if current.state is RepositoryState.PAUSED:
            return current
        self.paused_from[key] = current.state
        updated = RepositoryRun(
            repository_id=repository_id,
            wave_id=current.wave_id,
            state=RepositoryState.PAUSED,
            run_id=current.run_id,
            status=current.status,
            detail=reason,
            days_outstanding=current.days_outstanding,
        )
        self.runs[key] = updated
        return updated

    def resume(self, repository_id: str, *, wave_id: str = "") -> RepositoryRun:
        key = self._resolve(repository_id, wave_id)
        current = self.runs[key]
        if current.state is not RepositoryState.PAUSED:
            return current
        previous = self.paused_from.pop(key, RepositoryState.PENDING)
        updated = RepositoryRun(
            repository_id=repository_id,
            wave_id=current.wave_id,
            state=previous,
            run_id=current.run_id,
            status=current.status,
            detail="",
            days_outstanding=current.days_outstanding,
        )
        self.runs[key] = updated
        return updated

    # -- adjudication ----------------------------------------------------

    def wave(self, wave_id: str) -> ProgramWave:
        for item in self.plan.waves:
            if item.wave_id == wave_id:
                return item
        raise ContractError("unknown_wave", f"program has no wave '{wave_id}'")

    def wave_complete(self, wave_id: str) -> bool:
        wave = self.wave(wave_id)
        return all(
            self.runs[wave.wave_id, repository_id].state in TERMINAL_STATES
            for repository_id in wave.repositories
        )

    def may_start(self, wave_id: str) -> tuple[bool, tuple[str, ...]]:
        """A wave starts only when every wave it requires is fully adopted."""

        wave = self.wave(wave_id)
        blockers: list[str] = []
        for required in wave.requires:
            if not self.wave_complete(required):
                outstanding = [
                    repository_id
                    for repository_id in self.wave(required).repositories
                    if self.runs[required, repository_id].state not in TERMINAL_STATES
                ]
                blockers.append(
                    f"wave '{required}' is not adopted; outstanding: {', '.join(sorted(outstanding))}"
                )
        if wave.destructive:
            stuck = stuck_consumers(self)
            if stuck:
                blockers.append(
                    f"{len(stuck)} consumer(s) have not adopted: "
                    + ", ".join(item["repositoryId"] for item in stuck[:8])
                    + "; removal while any of them still calls the old path is the breakage, "
                    "not the cleanup"
                )
        return (not blockers, tuple(blockers))

    def adoption_report(self) -> dict[str, Any]:
        by_state: dict[str, int] = {}
        for run in self.runs.values():
            by_state[run.state.value] = by_state.get(run.state.value, 0) + 1
        total = len(self.runs) or 1
        adopted = sum(1 for run in self.runs.values() if run.state in TERMINAL_STATES)
        return {
            "programId": self.plan.program_id,
            "repositoryCount": len({key[1] for key in self.runs}),
            "scheduledSlots": len(self.runs),
            "adopted": adopted,
            "adoptionRate": str((Decimal(adopted) / Decimal(total)).quantize(Decimal("0.0001"))),
            "byState": dict(sorted(by_state.items())),
            "stuckConsumers": list(stuck_consumers(self)),
            "waves": [
                {
                    **wave.to_payload(),
                    "complete": self.wave_complete(wave.wave_id),
                    "mayStart": self.may_start(wave.wave_id)[0],
                    "blockers": list(self.may_start(wave.wave_id)[1]),
                }
                for wave in self.plan.waves
            ],
        }

    def to_payload(self) -> dict[str, Any]:
        return {
            "plan": self.plan.to_payload(),
            "runs": [self.runs[key].to_payload() for key in sorted(self.runs)],
            "gates": dict(sorted(self.gates.items())),
            "adoption": self.adoption_report(),
        }


def stuck_consumers(program: Program, *, threshold_days: int = 30) -> tuple[Mapping[str, Any], ...]:
    """Consumers outstanding past the threshold, or unreachable entirely."""

    by_id = {entry.repository_id: entry for entry in program.plan.portfolio}
    stuck: list[Mapping[str, Any]] = []
    for key in sorted(program.runs):
        wave_id, repository_id = key
        run = program.runs[key]
        entry = by_id.get(repository_id)
        if entry is None or entry.role is RepositoryRole.PROVIDER:
            continue
        if run.state in TERMINAL_STATES:
            continue
        reason = ""
        if run.state is RepositoryState.PAUSED:
            reason = f"paused: {run.detail or 'no reason recorded'}"
        elif entry.external:
            reason = "outside this organisation; adoption cannot be scheduled"
        elif run.days_outstanding >= threshold_days:
            reason = f"outstanding for {run.days_outstanding} day(s)"
        elif run.state is RepositoryState.FAILED:
            reason = f"failed: {run.detail or 'no detail recorded'}"
        if reason:
            stuck.append(
                {
                    "repositoryId": repository_id,
                    "waveId": wave_id,
                    "role": entry.role.value,
                    "state": run.state.value,
                    "owners": list(entry.owners),
                    "reason": reason,
                }
            )
    return tuple(stuck)


__all__ = [
    "TERMINAL_STATES",
    "Program",
    "ProgramPlan",
    "ProgramWave",
    "RepositoryEntry",
    "RepositoryRole",
    "RepositoryRun",
    "RepositoryState",
    "build_waves",
    "check_wave_order",
    "plan_program",
    "portfolio_from_payload",
    "stuck_consumers",
]
