-- DM8 (Dameng 8) Target Initialization for CDC
-- Schema with IDENTITY columns, NUMBER types, and DM8 constraints

-- Schema definition
CREATE SCHEMA IF NOT EXISTS "ECOMMERCE";

-- Table 1: USERS
CREATE TABLE IF NOT EXISTS "ECOMMERCE"."USERS" (
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "USERNAME" VARCHAR(64) NOT NULL,
    "EMAIL" VARCHAR(128) NOT NULL,
    "PHONE" VARCHAR(32),
    "STATUS" VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    "CREATED_AT" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_USERS" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_USERS_USERNAME" UNIQUE ("USERNAME")
);

-- Table 2: ORDERS
CREATE TABLE IF NOT EXISTS "ECOMMERCE"."ORDERS" (
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "ORDER_NO" VARCHAR(64) NOT NULL,
    "AMOUNT" NUMBER(12, 2) NOT NULL,
    "CURRENCY" VARCHAR(3) DEFAULT 'CNY' NOT NULL,
    "STATUS" VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    "CREATED_AT" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATED_AT" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_ORDERS_ORDER_NO" UNIQUE ("ORDER_NO"),
    CONSTRAINT "FK_ORDERS_USER" FOREIGN KEY ("USER_ID") REFERENCES "ECOMMERCE"."USERS"("ID")
);
