package io.elmos.worker.reflect;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Modernizer for eliminating legacy bytecode dependencies (CGLIB) and resolving
 * Java 17/21 JEP 403 (Strongly Encapsulate JDK Internals) illegal reflective access errors.
 *
 * <p>Modernizes:
 * <ol>
 *   <li><b>CGLIB Migration:</b> Replaces unmaintained {@code net.sf.cglib.*} with Spring's repackaged
 *       and shaded {@code org.springframework.cglib.*}. Removes standalone {@code cglib:cglib} from {@code pom.xml}.</li>
 *   <li><b>Reflection Modernization:</b> Converts raw {@code field.setAccessible(true)} to
 *       {@code org.springframework.util.ReflectionUtils.makeAccessible(field)}.</li>
 *   <li><b>JVM Add-Opens Generation:</b> Identifies reflective access to core JDK modules
 *       ({@code java.base/java.lang}, {@code java.base/java.util}, etc.) and generates
 *       {@code META-INF/jvm.argfile} and updates {@code maven-surefire-plugin} with {@code --add-opens}.</li>
 * </ol>
 */
public final class SpringBytecodeReflectModernizer {

    public record BytecodeReflectResult(
            boolean modified,
            int changesCount,
            Set<String> modifiedFiles,
            List<String> rulesApplied,
            List<String> jvmAddOpensFlags
    ) {
        public static BytecodeReflectResult empty() {
            return new BytecodeReflectResult(false, 0, Collections.emptySet(), Collections.emptyList(), Collections.emptyList());
        }
    }

    private SpringBytecodeReflectModernizer() {}

    public static BytecodeReflectResult modernize(Path projectRoot) {
        Objects.requireNonNull(projectRoot, "projectRoot must not be null");
        if (!Files.isDirectory(projectRoot)) {
            return BytecodeReflectResult.empty();
        }

        Set<String> modifiedFiles = new LinkedHashSet<>();
        List<String> rulesApplied = new ArrayList<>();
        Set<String> addOpens = new LinkedHashSet<>();
        int changes = 0;

        // 1. Process Java source files
        try (Stream<Path> stream = Files.walk(projectRoot)) {
            List<Path> javaFiles = stream
                    .filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith(".java"))
                    .toList();

            for (Path javaFile : javaFiles) {
                var fileRes = modernizeJavaFile(projectRoot, javaFile);
                if (fileRes.modified()) {
                    modifiedFiles.addAll(fileRes.modifiedFiles());
                    rulesApplied.addAll(fileRes.rulesApplied());
                    changes += fileRes.changesCount();
                }
                addOpens.addAll(fileRes.jvmAddOpensFlags());
            }
        } catch (IOException ignored) {}

        // 2. Modernize POM dependencies and Surefire plugin argLine
        Path pomPath = projectRoot.resolve("pom.xml");
        if (Files.isRegularFile(pomPath)) {
            var pomRes = modernizePom(projectRoot, pomPath, addOpens);
            if (pomRes.modified()) {
                modifiedFiles.addAll(pomRes.modifiedFiles());
                rulesApplied.addAll(pomRes.rulesApplied());
                changes += pomRes.changesCount();
            }
        }

        // 3. Generate META-INF/jvm.argfile if JDK internal reflection detected
        if (!addOpens.isEmpty()) {
            try {
                Path metaInf = Files.createDirectories(projectRoot.resolve("src/main/resources/META-INF"));
                Path argFile = metaInf.resolve("jvm.argfile");
                StringBuilder sb = new StringBuilder("# Generated by Elmos SpringBytecodeReflectModernizer for Java 17/21 JEP 403\n");
                for (String flag : addOpens) {
                    sb.append(flag).append("\n");
                }
                Files.writeString(argFile, sb.toString(), StandardCharsets.UTF_8);
                modifiedFiles.add(projectRoot.relativize(argFile).toString());
                rulesApplied.add("GENERATED_JVM_ARGFILE");
                changes++;
            } catch (IOException ignored) {}
        }

        return new BytecodeReflectResult(
                !modifiedFiles.isEmpty(),
                changes,
                modifiedFiles,
                rulesApplied,
                new ArrayList<>(addOpens)
        );
    }

    static BytecodeReflectResult modernizeJavaFile(Path projectRoot, Path javaFile) {
        try {
            String content = Files.readString(javaFile, StandardCharsets.UTF_8);
            String original = content;
            List<String> rules = new ArrayList<>();
            Set<String> addOpens = new LinkedHashSet<>();
            int changes = 0;

            // 1. CGLIB import rewrite: net.sf.cglib -> org.springframework.cglib
            if (content.contains("net.sf.cglib.")) {
                content = content.replace("import net.sf.cglib.", "import org.springframework.cglib.");
                rules.add("JAVA_CGLIB_TO_SPRING_CGLIB");
                changes++;
            }

            // 2. SetAccessible inspection and modernization
            if (content.contains("setAccessible(true)")) {
                // If it accesses internal JDK types
                if (content.contains("java.lang.reflect.Field") || content.contains("java.lang.reflect.Method")
                        || content.contains("java.lang.Class") || content.contains("java.lang.ClassLoader")) {
                    addOpens.add("--add-opens java.base/java.lang=ALL-UNNAMED");
                    addOpens.add("--add-opens java.base/java.lang.reflect=ALL-UNNAMED");
                }
                if (content.contains("java.util.") || content.contains("Collections") || content.contains("Map") || content.contains("List")) {
                    addOpens.add("--add-opens java.base/java.util=ALL-UNNAMED");
                }

                // Convert raw field.setAccessible(true) to ReflectionUtils.makeAccessible(field)
                Pattern setAccPattern = Pattern.compile("([a-zA-Z0-9_]+)\\.setAccessible\\(true\\);");
                if (setAccPattern.matcher(content).find()) {
                    content = setAccPattern.matcher(content).replaceAll("ReflectionUtils.makeAccessible($1);");
                    content = ensureImport(content, "org.springframework.util.ReflectionUtils");
                    rules.add("JAVA_REFLECTIONUTILS_MAKE_ACCESSIBLE");
                    changes++;
                }
            }

            if (!content.equals(original)) {
                Files.writeString(javaFile, content, StandardCharsets.UTF_8);
                return new BytecodeReflectResult(true, changes, Set.of(projectRoot.relativize(javaFile).toString()), rules, new ArrayList<>(addOpens));
            } else if (!addOpens.isEmpty()) {
                return new BytecodeReflectResult(false, 0, Collections.emptySet(), Collections.emptyList(), new ArrayList<>(addOpens));
            }
        } catch (IOException ignored) {}
        return BytecodeReflectResult.empty();
    }

    static BytecodeReflectResult modernizePom(Path projectRoot, Path pomPath, Set<String> addOpens) {
        try {
            String content = Files.readString(pomPath, StandardCharsets.UTF_8);
            String original = content;
            List<String> rules = new ArrayList<>();
            int changes = 0;

            // Remove standalone cglib dependency
            if (content.contains("<groupId>cglib</groupId>")) {
                content = content.replaceAll(
                        "(?s)\\s*<dependency>\\s*<groupId>cglib</groupId>\\s*<artifactId>cglib(?:-nodep)?</artifactId>.*?\\s*</dependency>",
                        ""
                );
                rules.add("POM_REMOVE_CGLIB_DEPENDENCY");
                changes++;
            }

            // If add-opens detected and surefire plugin exists or can be updated
            if (!addOpens.isEmpty() && content.contains("<artifactId>maven-surefire-plugin</artifactId>")) {
                String opensArg = String.join(" ", addOpens);
                if (!content.contains("--add-opens")) {
                    if (content.contains("<argLine>")) {
                        content = content.replace("<argLine>", "<argLine>" + opensArg + " ");
                    } else if (content.contains("</configuration>")) {
                        content = content.replace("</configuration>", "    <argLine>" + opensArg + "</argLine>\n            </configuration>");
                    }
                    rules.add("POM_SUREFIRE_ADD_OPENS_INJECTED");
                    changes++;
                }
            }

            if (!content.equals(original)) {
                Files.writeString(pomPath, content, StandardCharsets.UTF_8);
                return new BytecodeReflectResult(true, changes, Set.of(projectRoot.relativize(pomPath).toString()), rules, List.of());
            }
        } catch (IOException ignored) {}
        return BytecodeReflectResult.empty();
    }

    private static String ensureImport(String content, String fqcn) {
        if (content.contains("import " + fqcn + ";")) {
            return content;
        }
        Pattern pkgPattern = Pattern.compile("(?m)^package\\s+[^;]+;");
        Matcher matcher = pkgPattern.matcher(content);
        if (matcher.find()) {
            int end = matcher.end();
            return content.substring(0, end) + "\n\nimport " + fqcn + ";" + content.substring(end);
        }
        return "import " + fqcn + ";\n" + content;
    }
}
