spring.boot.version=4.1.0
spring.framework.version=7.0.8
spring.security.version=7.1.0
hibernate.orm.version=7.4.1.Final
tomcat.version=11.0.22
java.version=21
maven.version=3.9.11
gradle.version=8.14.3
resolution.status=DECLARED_NOT_RUN
