"""Shared fixtures: a small but genuinely multi-language repository."""

from __future__ import annotations

from typing import Any

REVISION = "8a8f31c0d4e5f6a7b8c9d0e1f2a3b4c5d6e7f801"

PYTHON_SERVICE = '''"""Billing service."""

from __future__ import annotations

import os
from decimal import Decimal

from acme.ledger import post_entry

__all__ = ["BillingService", "DEFAULT_CURRENCY"]

DEFAULT_CURRENCY = "USD"


class BillingBase:
    """Shared behaviour."""

    def audit(self, event: str) -> None:
        print(event)


class BillingService(BillingBase):
    """Charge customers."""

    def charge(self, customer_id: str, amount: Decimal, *, currency: str = DEFAULT_CURRENCY) -> str:
        handler = getattr(self, "_gateway_" + currency.lower())
        entry = post_entry(customer_id, amount, currency)
        self.audit(entry)
        return entry

    def _gateway_usd(self, amount: Decimal) -> str:
        return os.environ.get("USD_GATEWAY", "default")
'''

PYTHON_LEDGER = '''"""Ledger primitives."""

from decimal import Decimal


def post_entry(customer_id: str, amount: Decimal, currency: str) -> str:
    return f"{customer_id}:{amount}:{currency}"


def reverse_entry(entry: str) -> str:
    return entry[::-1]
'''

PYTHON_TEST = '''from acme.billing import BillingService


def test_charge_returns_entry() -> None:
    service = BillingService()
    assert service.charge("c1", 1) is not None
'''

JAVA_SOURCE = """package com.acme.users;

import java.util.List;
import com.acme.common.Util;

/** Directory of users. Mentions class NotAClass in prose. */
public final class UserDirectory {
    private static final String MARKER = "class Fake {";

    public List<String> findUser(String id) {
        return Util.wrap(id);
    }

    protected void refresh() {}
}
"""

TYPESCRIPT_SOURCE = """import { formatUser } from "./format";
import * as fs from "node:fs";

export interface UserRecord {
  id: string;
}

export class UserClient {
  private base: string;

  public async fetchUser(id: string): Promise<UserRecord> {
    const key = `user_${id}`;
    return JSON.parse(fs.readFileSync(cache[key], "utf8"));
  }
}

export function formatId(id: string): string {
  return formatUser(id);
}
"""

SQL_SCHEMA = """-- initial schema
CREATE TABLE IF NOT EXISTS public.users (
    id uuid PRIMARY KEY,
    email text NOT NULL,
    legacy_name text
);

CREATE INDEX users_email_idx ON public.users (email);
"""

OPENAPI = """openapi: 3.1.0
info:
  title: Billing
  version: 1.0.0
paths:
  /v1/charges:
    post:
      operationId: createCharge
  /v1/charges/{id}:
    get:
      operationId: getCharge
"""

PROTO = """syntax = "proto3";
package acme.billing.v1;

message ChargeCreated {
  string id = 1;
  string currency = 2;
}

service BillingService {
  rpc CreateCharge(ChargeCreated) returns (ChargeCreated);
}
"""

CODEOWNERS = """# ownership
*                     @acme/platform
/services/billing/    @acme/payments @acme/platform
*.sql                 @acme/data
"""

PACKAGE_JSON = """{
  "name": "@acme/web",
  "version": "1.0.0",
  "scripts": {"test": "vitest run", "build": "tsc -p ."},
  "dependencies": {"react": "18.3.1"}
}
"""

PYPROJECT = """[project]
name = "acme-billing"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = ["httpx>=0.27", "pydantic~=2.7"]

[tool.setuptools]
package-dir = {"" = "src"}
"""

POM = """<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.acme</groupId>
  <artifactId>users</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.acme</groupId>
      <artifactId>common</artifactId>
    </dependency>
  </dependencies>
</project>
"""

GENERATED = """// Code generated by protoc-gen-go. DO NOT EDIT.
package billingpb

type ChargeCreated struct{}
"""


def workspace_files() -> list[dict[str, Any]]:
    return [
        {"path": "CODEOWNERS", "content": CODEOWNERS},
        {"path": "pyproject.toml", "content": PYPROJECT},
        {"path": "src/acme/__init__.py", "content": ""},
        {"path": "src/acme/billing.py", "content": PYTHON_SERVICE},
        {"path": "src/acme/ledger.py", "content": PYTHON_LEDGER},
        {"path": "tests/test_billing.py", "content": PYTHON_TEST},
        {"path": "services/users/pom.xml", "content": POM},
        {
            "path": "services/users/src/main/java/com/acme/users/UserDirectory.java",
            "content": JAVA_SOURCE,
        },
        {"path": "web/package.json", "content": PACKAGE_JSON},
        {"path": "web/src/user-client.ts", "content": TYPESCRIPT_SOURCE},
        {"path": "db/migrations/001_init.sql", "content": SQL_SCHEMA},
        {"path": "contracts/openapi.yaml", "content": OPENAPI},
        {"path": "contracts/billing.proto", "content": PROTO},
        {"path": "gen/billingpb/charge.pb.go", "content": GENERATED},
        {"path": "vendor/left-pad/index.js", "content": "module.exports = () => {};\n"},
        {
            "path": "assets/logo.png",
            "content_digest": "sha256:" + "ab" * 32,
            "size_bytes": 4096,
            "binary": True,
        },
        {
            "path": "docs/broken.bin",
            "content_digest": "sha256:" + "cd" * 32,
            "size_bytes": 12,
            "unreadable_reason": "not-utf8",
            "binary": False,
        },
    ]


def workspace_payload(repository_id: str = "billing", revision: str = REVISION) -> dict[str, Any]:
    return {
        "source": "inline",
        "repository_id": repository_id,
        "revision": revision,
        "files": workspace_files(),
    }


def request_payload(**overrides: Any) -> dict[str, Any]:
    spec: dict[str, Any] = {
        "repositories": [
            {"uri": "git@example.com/acme/billing.git", "revision": REVISION, "role": "primary"}
        ],
        "intent": {
            "type": "structural-refactor",
            "goals": ["extract the payment gateway from the billing service"],
            "nonGoals": ["do not change the public REST contract"],
            "acceptanceCriteria": ["all existing tests pass"],
        },
        "constraints": {
            "behaviorCompatibility": "strict",
            "publicApiCompatibility": "strict",
            "maximumChangedFiles": 200,
        },
        "execution": {"mode": "supervised", "createPullRequest": True, "maxParallelShards": 4},
    }
    for key, value in overrides.items():
        if key in spec and isinstance(spec[key], dict) and isinstance(value, dict):
            spec[key] = {**spec[key], **value}
        else:
            spec[key] = value
    return {
        "apiVersion": "elmos.dev/v1",
        "kind": "RefactorRequest",
        "metadata": {"tenantId": "acme", "projectId": "billing-platform"},
        "spec": spec,
    }
