"""Elmos AI Capability Enhancement Runtime Engine.

Provides concrete runtime handlers, verification models, workflow orchestration,
golden route execution, database migration management, and policy enforcement
for all 296 skills in the AI Capability Enhancement package.
"""

from __future__ import annotations

from .kernel import (
    FeatureRequirement,
    TargetProfile,
    NegotiationResult,
    negotiate,
    compare_traces,
    validate_trace,
    ProofResult,
    CertificationInput,
    CertificationDecision,
    certify,
    validate_skill_ir,
    permission_expansions,
    portability_decision,
    TriggerObservation,
    TriggerMetrics,
    evaluate_trigger,
    trigger_gate,
    McpTaskBridge,
    TaskState,
    Calibration,
    calibrate,
    judge_use_decision,
    compare_fingerprints,
    recertification_decision,
    BudgetLimit,
    RunawayGuard,
    backward_compatibility,
    evolution_decision,
    RetrievalCandidate,
    authorize_candidates,
    deletion_reconciled,
    validate_topology,
    dependency_cycle,
    PackageTrustInput,
    trust_decision,
    IncidentController,
    Control,
    profile_decision,
    CacheContext,
    semantic_key,
    cache_reuse_decision,
    ToolContract,
    compare_tools,
    MemoryRecord,
    authorize_memory,
    isolation_probe,
    QualityResult,
    quality_gate,
    Usage,
    Rates,
    calculate_cost,
    budget_decision,
    ProviderCandidate,
    select_provider,
    PolicyRule,
    validate_rules,
    default_decision,
    ActionPreview,
    ux_gate,
)
from .runtime import AICapabilityRuntime, SkillExecutionResult
from .golden_routes import GoldenRouteEngine, GoldenRouteResult
from .workflows import WorkflowEngine, WorkflowExecutionResult
from .database import MigrationManager, MigrationResult
from .policies import PolicyEngine, PolicyEvaluationResult

__version__ = "4.1.0"
__all__ = [
    "FeatureRequirement",
    "TargetProfile",
    "NegotiationResult",
    "negotiate",
    "compare_traces",
    "validate_trace",
    "ProofResult",
    "CertificationInput",
    "CertificationDecision",
    "certify",
    "validate_skill_ir",
    "permission_expansions",
    "portability_decision",
    "TriggerObservation",
    "TriggerMetrics",
    "evaluate_trigger",
    "trigger_gate",
    "McpTaskBridge",
    "TaskState",
    "Calibration",
    "calibrate",
    "judge_use_decision",
    "compare_fingerprints",
    "recertification_decision",
    "BudgetLimit",
    "RunawayGuard",
    "backward_compatibility",
    "evolution_decision",
    "RetrievalCandidate",
    "authorize_candidates",
    "deletion_reconciled",
    "validate_topology",
    "dependency_cycle",
    "PackageTrustInput",
    "trust_decision",
    "IncidentController",
    "Control",
    "profile_decision",
    "CacheContext",
    "semantic_key",
    "cache_reuse_decision",
    "ToolContract",
    "compare_tools",
    "MemoryRecord",
    "authorize_memory",
    "isolation_probe",
    "QualityResult",
    "quality_gate",
    "Usage",
    "Rates",
    "calculate_cost",
    "budget_decision",
    "ProviderCandidate",
    "select_provider",
    "PolicyRule",
    "validate_rules",
    "default_decision",
    "ActionPreview",
    "ux_gate",
    "AICapabilityRuntime",
    "SkillExecutionResult",
    "GoldenRouteEngine",
    "GoldenRouteResult",
    "WorkflowEngine",
    "WorkflowExecutionResult",
    "MigrationManager",
    "MigrationResult",
    "PolicyEngine",
    "PolicyEvaluationResult",
]
