// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    status: { type: String, value: "" },
    compact: { type: Boolean, value: false },
  },
  data: {},
  methods: {},
});
