-- Target DDL for openGauss 3.0+
-- Generated by Elmos SQL Dialect Engine (Batch 31 Profile)

CREATE TABLE orders (
    id BIGSERIAL NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    amount_cents BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
) WITH (ORIENTATION = ROW)
DISTRIBUTE BY HASH (id);

CREATE INDEX idx_orders_tenant_created ON orders (tenant_id, created_at DESC);
