// Generated by ELMOS component-dialect-engine (certified-component-v1).
Component({
  properties: {
    semanticCoverage: { type: Object, value: {} },
    behaviorCoverage: { type: Object, value: {} },
  },
  data: {},
  methods: {},
});
