apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "proof-harness.serviceAccountName" . }}
  labels:
{{ include "proof-harness.labels" . | indent 4 }}
automountServiceAccountToken: false
