CREATE TABLE work_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_work_orders_tenant_created
  ON work_orders (tenant_id, created_at);
