"""Deterministic static HTML report around rendered diagrams.

C0 chose CLI plus a static HTML report over a web-console page, so this is the
delivery surface for a rendered Diagram Spec.  The report:

* inlines the SVG (no network fetch, no script, no external stylesheet), so the
  file is self-contained and can be mailed or committed as evidence;
* puts every diagram inside an ``overflow-x: auto`` frame with the SVG at its
  natural pixel width, so a wide graph scrolls inside its own box instead of
  stretching the page;
* restates the engine's evidence boundary on the page itself, so a screenshot
  of the report cannot be mistaken for a certified result.

Output is a pure function of its inputs: no clock, no counter, no environment.
"""

from __future__ import annotations

from dataclasses import dataclass

from .diagram_layout import DiagramLayout
from .diagram_svg import escape_xml_text


_STYLE = """
:root { color-scheme: light dark; }
body { margin: 0; font: 14px/1.55 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
       background: #f6f7f9; color: #1d2733; }
main { max-width: 1100px; margin: 0 auto; padding: 32px 20px 64px; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 17px; margin: 32px 0 8px; }
.sub { color: #5a6672; margin: 0 0 20px; }
.boundary { border: 1px solid #c9a227; background: #fdf6e0; color: #5b4708;
            border-radius: 6px; padding: 12px 14px; margin: 0 0 24px; }
.boundary b { display: block; margin-bottom: 4px; }
table { border-collapse: collapse; font-size: 13px; margin: 0 0 12px; }
th, td { text-align: left; padding: 4px 14px 4px 0; vertical-align: top; }
th { color: #5a6672; font-weight: 600; white-space: nowrap; }
td { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; word-break: break-all; }
.frame { overflow-x: auto; overflow-y: hidden; background: #ffffff;
         border: 1px solid #d8dde3; border-radius: 6px; padding: 12px; }
.frame svg { display: block; }
footer { margin-top: 40px; color: #5a6672; font-size: 12px; }
@media (prefers-color-scheme: dark) {
  body { background: #14181d; color: #e6eaef; }
  .sub, th, footer { color: #97a3b0; }
  .boundary { background: #2c2410; border-color: #7d6415; color: #f0dfa4; }
  .frame { background: #ffffff; border-color: #2c333b; }
}
""".strip()


@dataclass(frozen=True)
class ReportSection:
    heading: str
    layout: DiagramLayout
    svg: str
    svg_digest: str


def _rows(pairs: tuple[tuple[str, str], ...]) -> str:
    return "".join(
        f"<tr><th>{escape_xml_text(name)}</th>"
        f"<td>{escape_xml_text(value)}</td></tr>"
        for name, value in pairs
    )


def render_report(
    sections: tuple[ReportSection, ...],
    *,
    title: str,
    project_id: str,
    revision_id: str,
) -> str:
    """Return the full static HTML document."""

    body = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{escape_xml_text(title)}</title>",
        f"<style>{_STYLE}</style></head><body><main>",
        f"<h1>{escape_xml_text(title)}</h1>",
        f'<p class="sub">project {escape_xml_text(project_id)} '
        f"&middot; revision {escape_xml_text(revision_id)}</p>",
        '<div class="boundary"><b>Evidence boundary</b>'
        "Static local analysis only. external_evidence = NOT_RUN, "
        "certification = NOT_CERTIFIED. Diagram geometry is derived from the "
        "compiled Diagram Spec; it is not a runtime observation.</div>",
    ]
    for section in sections:
        layout = section.layout
        body.append(f"<h2>{escape_xml_text(section.heading)}</h2>")
        body.append(
            "<table>"
            + _rows(
                (
                    ("diagram_id", layout.diagram_id),
                    ("type", layout.diagram_type),
                    ("nodes", str(len(layout.nodes))),
                    ("edges", str(len(layout.edges))),
                    ("canvas", f"{layout.width} x {layout.height} px"),
                    ("svg_digest", section.svg_digest),
                    (
                        "labels_normalized",
                        "true" if layout.labels_normalized else "false",
                    ),
                )
            )
            + "</table>"
        )
        inline_svg = section.svg
        if inline_svg.startswith("<?xml"):
            inline_svg = inline_svg.split("\n", 1)[1]
        body.append('<div class="frame">' + inline_svg.strip() + "</div>")
    body.append(
        "<footer>Generated by the bounded ELMOS Project Intelligence engine "
        "offline exporter. No external effects were performed.</footer>"
    )
    body.append("</main></body></html>")
    return "\n".join(body) + "\n"
